/**
 * Emits every consumable artefact from the one token source.
 *
 * CP09 acceptance criterion 1 is "one token source feeds web, mobile and print". This
 * file is where that becomes checkable rather than aspirational: it is the only writer of
 * dist/, everything it writes is derived from ../src/index.ts, and build.test.ts asserts
 * that each output contains the values the source resolves to. A value that appeared in
 * one output and not the others could only get there by being typed twice.
 *
 *   pnpm --filter @dthcms/design-tokens build
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  clinicalStatusNames,
  clinicalStatuses,
  elevation,
  layout,
  motion,
  ramps,
  themes,
  typography,
  type Theme,
} from './index';

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, '..', 'dist');

const BANNER = `/*
 * Generated by @dthcms/design-tokens. Do not edit.
 *
 * Every value here comes from packages/design-tokens/src/tokens/*.json. Editing this file
 * changes one surface and silently desynchronises it from the other two; edit the JSON and
 * run the build.
 */`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Converts px to rem against a 16px root, so OS text scaling works. */
function rem(px: number): string {
  if (px === 0) return '0';
  return `${(px / 16).toFixed(4).replace(/\.?0+$/, '')}rem`;
}

function cssVariablesFor(theme: Theme): string[] {
  const lines: string[] = [];

  for (const [group, roles] of Object.entries(themes[theme])) {
    for (const [role, value] of Object.entries(roles)) {
      lines.push(`  --color-${group}-${kebab(role)}: ${value};`);
    }
  }

  for (const name of clinicalStatusNames) {
    const status = clinicalStatuses[name];
    for (const [role, value] of Object.entries(status.colors[theme])) {
      lines.push(`  --color-status-${name}-${kebab(role)}: ${value};`);
    }
  }

  for (const [level, spec] of Object.entries(elevation.level)) {
    lines.push(`  --elevation-${level}: ${spec[theme]};`);
  }

  return lines;
}

function kebab(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function isMeta(key: string): boolean {
  return key.startsWith('$');
}

// ---------------------------------------------------------------------------
// tokens.css — the web surface
// ---------------------------------------------------------------------------

function buildCss(): string {
  const scaleLines: string[] = [];
  for (const [step, spec] of Object.entries(typography.scale)) {
    if (isMeta(step)) continue;
    const typed = spec as {
      size: number;
      lineHeight: { latin: number; bengali: number };
      tracking: number;
    };
    scaleLines.push(`  --text-${step}: ${rem(typed.size)};`);
    scaleLines.push(`  --leading-${step}-latin: ${typed.lineHeight.latin};`);
    scaleLines.push(`  --leading-${step}-bengali: ${typed.lineHeight.bengali};`);
    scaleLines.push(`  --tracking-${step}: ${typed.tracking}em;`);
  }

  /*
   * The half-steps are `--space-0-5`, not `--space-0.5`.
   *
   * A dot in a custom property name is legal, but it has to be escaped at every single
   * reference — `var(--space-0\\.5)` — and an unescaped one does not error. It silently
   * resolves to nothing and the declaration is dropped, so a gap quietly becomes zero.
   * CP09 shipped eight such references in @dthcms/ui and none of them ever applied;
   * Turbopack's stricter CSS parser is what surfaced it at CP10.
   *
   * Renaming removes the trap rather than documenting it. `assertNoAwkwardNames` in
   * build.test.ts keeps it removed.
   */
  const spaceLines = Object.entries(layout.space)
    .filter(([key]) => !isMeta(key))
    .map(([key, value]) => `  --space-${key.replace('.', '-')}: ${rem(value as number)};`);

  const radiusLines = Object.entries(layout.radius).map(
    ([key, value]) => `  --radius-${key}: ${key === 'full' ? '9999px' : rem(value as number)};`,
  );

  const durationLines = Object.entries(motion.duration).map(
    ([key, value]) => `  --duration-${key}: ${value}ms;`,
  );
  const easingLines = Object.entries(motion.easing)
    .filter(([key]) => !isMeta(key))
    .map(([key, value]) => `  --ease-${key}: ${value};`);

  return `${BANNER}

:root {
  /* Ramps. Available for one-off needs; prefer the semantic roles below. */
${Object.entries(ramps)
  .map(([name, ramp]) =>
    Object.entries(ramp)
      .map(([step, value]) => `  --ramp-${name}-${step}: ${value};`)
      .join('\n'),
  )
  .join('\n')}

  /* Type */
${scaleLines.join('\n')}
  --font-latin: ${typography.family.latin.stack.map(quoteFamily).join(', ')};
  --font-bengali: ${typography.family.bengali.stack.map(quoteFamily).join(', ')};
  --font-mono: ${typography.family.mono.stack.map(quoteFamily).join(', ')};

  /* Space and shape */
${spaceLines.join('\n')}
${radiusLines.join('\n')}
  --touch-target: ${rem(layout.size.touchTarget)};
  --focus-ring: ${rem(layout.size.focusRing)};
  --focus-ring-offset: ${rem(layout.size.focusRingOffset)};

  /* Motion */
${durationLines.join('\n')}
${easingLines.join('\n')}
}

/*
 * The interface language sets the font and the line height together. Setting the family
 * without the line height is the mistake this pairing exists to prevent: Bengali matras
 * collide with the descenders of the line above at Latin leading.
 */
:root,
[lang='en'] {
  --font-ui: var(--font-latin);
  --leading-ui: var(--leading-base-latin);
}

[lang='bn'] {
  --font-ui: var(--font-bengali);
  --leading-ui: var(--leading-base-bengali);
}

/*
 * Light is the default; dark applies by preference or by explicit attribute.
 *
 * \`color-scheme\` travels with the theme blocks, and it is not decoration. The tokens
 * only recolour what the page draws itself; the browser and the operating system draw
 * the rest — the native select dropdown, scrollbars, autofill, the date picker — and
 * they paint those from color-scheme, not from any CSS variable. Without it, a dark
 * interface gets a white dropdown list whose options inherit near-white text:
 * unreadable, and found exactly that way in CP10's review of the role switcher.
 */
:root {
  color-scheme: light;
${cssVariablesFor('light').join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${cssVariablesFor('dark')
  .map((line) => `  ${line}`)
  .join('\n')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${cssVariablesFor('dark').join('\n')}
}

/*
 * Reduced motion collapses durations rather than removing transitions. 1ms keeps
 * transitionend firing, so any state machine built on it still advances instead of
 * stalling silently for exactly the users who asked for less motion.
 */
@media (prefers-reduced-motion: reduce) {
  :root {
${Object.keys(motion.duration)
  .map((key) => `    --duration-${key}: ${motion.reducedMotion.duration}ms;`)
  .join('\n')}
  }
}
`;
}

function quoteFamily(name: string): string {
  return /\s/.test(name) ? `'${name}'` : name;
}

// ---------------------------------------------------------------------------
// tokens.print.css — paper
// ---------------------------------------------------------------------------

function buildPrintCss(): string {
  const statusLabels = clinicalStatusNames
    .map((name) => {
      const status = clinicalStatuses[name];
      return `[data-status='${name}']::after {
  content: ' (${status.label.en})';
}

[lang='bn'] [data-status='${name}']::after {
  content: ' (${status.label.bn})';
}`;
    })
    .join('\n\n');

  return `${BANNER}

/*
 * Print.
 *
 * The printer in a Bangladeshi clinic is a monochrome laser, and a report that carries
 * clinical status in colour arrives carrying nothing. So print does two things: it drops
 * to black on white, and it appends the status label as text to anything marked with
 * data-status.
 *
 * That text is why the greyscale problem is not a problem. It is also why every component
 * that renders a status sets data-status - the attribute is what makes the paper output
 * correct, and it costs nothing on screen.
 */

@media print {
  :root {
    --color-surface-base: #ffffff;
    --color-surface-raised: #ffffff;
    --color-surface-sunken: #ffffff;
    --color-text-primary: #000000;
    --color-text-secondary: #000000;
    --color-text-muted: #333333;
    --color-border-subtle: #999999;
    --color-border-default: #666666;
    --color-border-control: #000000;
    --color-border-strong: #000000;

${Object.keys(elevation.level)
  .map((level) => `    --elevation-${level}: none;`)
  .join('\n')}

${Object.keys(motion.duration)
  .map((key) => `    --duration-${key}: 0ms;`)
  .join('\n')}
  }

  /* Ink is expensive and a tinted background reduces legibility on paper. */
  * {
    background: transparent !important;
    box-shadow: none !important;
    color: #000000 !important;
  }

  /* A clinical value must not be split across a page break. */
  [data-clinical-value],
  [data-status] {
    break-inside: avoid;
    page-break-inside: avoid;
  }

${statusLabels}

  /* A link's destination is invisible on paper unless it is written out. */
  a[href^='http']::after {
    content: ' (' attr(href) ')';
    font-size: ${rem(typography.scale.xs.size)};
  }
}
`;
}

// ---------------------------------------------------------------------------
// Theme objects — Tailwind (web) and NativeWind (mobile)
// ---------------------------------------------------------------------------

function themeObject(): Record<string, unknown> {
  const colors: Record<string, unknown> = { ...ramps };

  for (const theme of ['light', 'dark'] as const) {
    colors[theme] = themes[theme];
  }

  colors.status = Object.fromEntries(
    clinicalStatusNames.map((name) => [name, clinicalStatuses[name].colors]),
  );

  return {
    colors,
    spacing: Object.fromEntries(Object.entries(layout.space).filter(([key]) => !isMeta(key))),
    borderRadius: layout.radius,
    fontSize: Object.fromEntries(
      Object.entries(typography.scale)
        .filter(([key]) => !isMeta(key))
        .map(([step, spec]) => {
          const typed = spec as { size: number };
          return [step, typed.size];
        }),
    ),
    lineHeight: Object.fromEntries(
      Object.entries(typography.scale)
        .filter(([key]) => !isMeta(key))
        .map(([step, spec]) => {
          const typed = spec as { lineHeight: { latin: number; bengali: number } };
          return [step, typed.lineHeight];
        }),
    ),
    fontFamily: {
      latin: typography.family.latin.stack,
      bengali: typography.family.bengali.stack,
      mono: typography.family.mono.stack,
    },
    fontWeight: typography.weight,
    screens: Object.fromEntries(Object.entries(layout.breakpoint).filter(([key]) => !isMeta(key))),
    zIndex: layout.zIndex,
    size: layout.size,
    motion: { duration: motion.duration, easing: motion.easing },
  };
}

function buildThemeModule(target: 'tailwind' | 'nativewind'): string {
  const theme = themeObject();

  const extra =
    target === 'nativewind'
      ? `
/*
 * Android has no box-shadow, so elevation is an integer the platform interprets rather
 * than a shadow string. Same source, different expression of the same intent.
 */
export const androidElevation = ${JSON.stringify(
          Object.fromEntries(
            Object.entries(elevation.level).map(([level, spec]) => [
              level,
              (spec as { androidElevation: number }).androidElevation,
            ]),
          ),
          null,
          2,
        )};
`
      : `
export const elevation = ${JSON.stringify(
          Object.fromEntries(
            Object.entries(elevation.level).map(([level, spec]) => [
              level,
              { light: (spec as { light: string }).light, dark: (spec as { dark: string }).dark },
            ]),
          ),
          null,
          2,
        )};
`;

  return `${BANNER}

export const theme = ${JSON.stringify(theme, null, 2)};
${extra}
export default theme;
`;
}

// ---------------------------------------------------------------------------

/**
 * Writes every artefact into `dist/` and returns the file names it wrote.
 *
 * This module only defines the build; `build.cli.ts` is what runs it. Keeping the two
 * apart means `build.test.ts` can import and call this directly instead of spawning
 * `npx tsx src/build.ts` — which worked on Linux and failed on Windows, where npx is
 * npx.cmd and `execFileSync` without a shell will not resolve a `.cmd`.
 *
 * A main-module check (`process.argv[1] === this file`) would also have worked, but its
 * failure mode on a path-casing difference is a build that silently writes nothing. A
 * separate entry file cannot fail that way.
 *
 * `report` exists so the CLI prints what it wrote and the test does not.
 */
export function build(report: (line: string) => void = () => {}): string[] {
  mkdirSync(dist, { recursive: true });

  const outputs: Array<[string, string]> = [
    ['tokens.css', buildCss()],
    ['tokens.print.css', buildPrintCss()],
    ['tailwind-theme.js', buildThemeModule('tailwind')],
    ['nativewind-theme.js', buildThemeModule('nativewind')],
    [
      'tokens.json',
      `${JSON.stringify({ ramps, themes, clinicalStatuses, layout: layout.size }, null, 2)}\n`,
    ],
  ];

  for (const [name, contents] of outputs) {
    writeFileSync(join(dist, name), contents, 'utf8');
    report(`  ${name}  ${contents.length.toLocaleString()} bytes`);
  }

  return outputs.map(([name]) => name);
}
