/**
 * Station 7's 24-hour dietary recall (CP59, §5.2, §12.1).
 *
 * The public surface is the screen, the five calls, and the pure decisions the tests check. What
 * is deliberately not here is anything that could produce a weight or a calorie: those are the
 * food composition table's, computed by the server, and a helper exported from here that added
 * up a day would be the beginning of a second answer to the question §12.1's analysis asks.
 */

export { NutritionStation } from './NutritionStation';
export {
  getRecall,
  listRecallDays,
  listReference,
  recordDietEntry,
  runSearch,
  searchFoods,
  troubleOf,
  withdrawDietEntry,
} from './api';
export {
  ADVICE,
  ATTEMPTS,
  CODE_ALREADY_WITHDRAWN,
  DAY_RELATIONS,
  DEBOUNCE_MS,
  DIET_ENTRY_NAMESPACE,
  MAX_RESULTS,
  MISSING,
  QUANTITY_STEPS,
  REASON_PRESETS,
  RECALL_REFRESH_MS,
  adviceFor,
  afterEntry,
  alreadyWithdrawn,
  applyAnswer,
  cannotWeigh,
  ceilingFor,
  chooseFood,
  chooseMeal,
  chooseMeasure,
  dayIsEmpty,
  dayRelation,
  emptyDraft,
  emptyReference,
  entryIdFor,
  entryLine,
  foodRows,
  hasEscapeHatch,
  issueSearch,
  mealGroups,
  measureNamed,
  measuresFor,
  missingFrom,
  openPicker,
  openWithdrawal,
  parsedQuantity,
  retrySearch,
  searchDue,
  searching,
  shiftDay,
  toEntry,
  toWithdrawal,
  totalsOf,
  troubleKey,
  typeQuantity,
  typeReason,
  typedQuery,
  unapproved,
  unusualDay,
  visible,
  wordingOf,
  type Advice,
  type Attempt,
  type DayRelation,
  type DietEntry,
  type DietEntryBody,
  type DietRecall,
  type DietTotals,
  type EntryDraft,
  type EntryLine,
  type Food,
  type FoodAnswer,
  type FoodMeasure,
  type FoodPortion,
  type FoodRequest,
  type FoodRow,
  type Locale,
  type Meal,
  type MealCode,
  type MealGroup,
  type MeasureChoice,
  type Missing,
  type PickerState,
  type ReasonPreset,
  type RecallAnswer,
  type RecallDay,
  type Reference,
  type TotalsReading,
  type Trouble,
  type WithdrawalBody,
  type WithdrawalDraft,
  type Wording,
} from './state';
