/**
 * Correction requests, on the device of whoever typed the value (CP62, §4.3, [R-04]).
 *
 * The public surface is deliberately narrow. There is no exported way to flag a value — that
 * is a physician's act and needs a permission a station operator does not hold — and no
 * exported way to answer a request that is not the caller's own. What a screen can reach for
 * is the queue's own panel, the one line that tells an operator there is something waiting,
 * and the pure pieces the tests need.
 */

export { CORRECTIONS_HREF, CorrectionNotice } from './CorrectionNotice';
export { CorrectionInbox } from './CorrectionInbox';

export {
  CORRECTIONS_QUERY_PREFIX,
  CORRECTION_REASONS_QUERY_KEY,
  REASONS_STALE_MS,
  applyCorrection,
  correctionsQueryKey,
  flaggedObservationQueryKey,
  getFlaggedObservation,
  listCorrectionReasons,
  listMyCorrections,
  rejectCorrection,
  troubleOf,
  useCorrectionReasons,
  useFlaggedObservation,
  useMyCorrections,
} from './api';

export {
  ACTS,
  ADVICE,
  ANSWER_KINDS,
  CLINIC_UTC_OFFSET_MINUTES,
  CODE_ALREADY_ANSWERED,
  CORRECTION_REQUESTED,
  KNOWN_ROLE_CODES,
  MEASUREMENTS,
  NOTE_MAX,
  OUTCOMES,
  PROBLEMS,
  REASON_MAX,
  VALUE_SHAPES,
  adviceFor,
  alreadyAnswered,
  answerKindOf,
  applyProblem,
  attemptKey,
  clinicDay,
  clockTime,
  draftFor,
  eventFor,
  flaggedBy,
  flaggedValueOf,
  holdEvent,
  keepsItsEvent,
  measurementFor,
  momentOf,
  myTopic,
  notThisRole,
  notYours,
  notifiesMe,
  outcomeOf,
  queueOf,
  reasonDisplay,
  recomputedOf,
  rejectProblem,
  releaseEvent,
  requestReadingOf,
  roleKeyOf,
  shapeOf,
  toApply,
  toReject,
  unitsFor,
  type Act,
  type Advice,
  type AnswerKind,
  type ApplyRequest,
  type CodeReading,
  type CorrectionReason,
  type CorrectionRequest,
  type Draft,
  type FlaggedObservation,
  type FlaggedValue,
  type HeldEvents,
  type Locale,
  type Measurement,
  type Moment,
  type Observation,
  type Outcome,
  type Problem,
  type Queue,
  type Recomputed,
  type RejectRequest,
  type RequestReading,
  type Trouble,
  type ValueShape,
} from './state';
