// Package ids generates the identifiers DTHCMS uses.
//
// UUIDv7 everywhere, for two reasons. It is time-ordered, so index locality stays good
// as the event ledger grows into millions of rows; and it is opaque, so an identifier
// leaks nothing about the patient or their position in any sequence.
//
// Event identifiers are generated by the *client*, before the event is queued offline.
// That is what makes retrying a sync safe: the same event replayed ten times is inserted
// once, because its identifier came with it rather than being assigned on arrival.
package ids

import (
	"fmt"

	"github.com/google/uuid"
)

// Generator produces identifiers. Injectable so tests can be deterministic.
type Generator interface {
	New() string
}

// UUIDv7 is the production generator.
type UUIDv7 struct{}

// New returns a time-ordered UUIDv7 string.
func (UUIDv7) New() string {
	id, err := uuid.NewV7()
	if err != nil {
		// NewV7 fails only if the system entropy source fails. Continuing with a
		// predictable identifier would be worse than stopping.
		panic(fmt.Sprintf("ids: cannot generate UUIDv7: %v", err))
	}
	return id.String()
}

// Sequential is a test generator producing predictable identifiers.
type Sequential struct {
	Prefix string
	n      int
}

// New returns the next identifier in the sequence.
func (s *Sequential) New() string {
	s.n++
	prefix := s.Prefix
	if prefix == "" {
		prefix = "id"
	}
	return fmt.Sprintf("%s_%08d", prefix, s.n)
}

// Valid reports whether s is a well-formed UUID.
func Valid(s string) bool {
	_, err := uuid.Parse(s)
	return err == nil
}
