package ai_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/AmlanWTK/DTHCMS/backend/internal/ai"
	"github.com/AmlanWTK/DTHCMS/backend/internal/platform/clock"
	"github.com/AmlanWTK/DTHCMS/backend/internal/platform/config"
	"github.com/AmlanWTK/DTHCMS/backend/internal/platform/testsupport"
)

// The AI gateway against a real database (CP70).
//
// Everything here needs one, and the reason is worth stating rather than assuming: the two rules
// this checkpoint exists for are enforced by the database as well as by Go — the tier guard by a
// check constraint and invariant 99, the identifier rule by `ops.carries_identifier` and invariant
// 98 — and a test that stubbed the store would prove the Go half and quietly assert nothing about
// the half that is meant to catch the Go half being wrong.

type harness struct {
	*testsupport.DB
	pool     *pgxpool.Pool
	store    *ai.Store
	registry *ai.Registry
	clock    *clock.Fixed
	logger   *slog.Logger

	facility uuid.UUID
	// realPatient is a patient row nobody has entered in the synthetic register. Everything about
	// it is therefore, by default, unsendable on a free credential — which is the property
	// criterion 1b is about.
	realPatient uuid.UUID
	// fabricated is a subject that *has* been registered, with a reason, as CP13's generator would
	// register one.
	fabricated uuid.UUID

	provider *ai.Mock
	// raised is every budget alert the gateway put in front of an administrator, in order. The
	// table's unique key makes a crossing recorded once; this is the *other* half of criterion 5 —
	// that somebody is told once, rather than on every call for the rest of the day.
	raised []ai.BudgetAlert
}

// RaiseBudgetAlert makes the harness itself the AlertRaiser, standing in for the administrators'
// console that audit's store provides at the composition root.
func (h *harness) RaiseBudgetAlert(_ context.Context, alert ai.BudgetAlert) error {
	h.raised = append(h.raised, alert)
	return nil
}

func newHarness(t *testing.T) *harness {
	t.Helper()
	base := testsupport.Postgres(t)
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	t.Cleanup(cancel)

	pool, err := pgxpool.New(ctx, base.DSN)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(pool.Close)

	registry, err := ai.LoadRegistry()
	if err != nil {
		t.Fatal(err)
	}

	h := &harness{
		DB: base, pool: pool, store: ai.NewStore(pool), registry: registry,
		// Ten in the morning in Faridpur, which is 04:00 UTC. The hour matters to the metering
		// tests: a clock set near midnight UTC would put two calls of one test on either side of
		// the day boundary and the budget arithmetic would be right and the test wrong.
		clock:       clock.NewFixed(time.Date(2026, 9, 14, 4, 0, 0, 0, time.UTC)),
		logger:      slog.New(slog.NewTextHandler(io.Discard, nil)),
		realPatient: uuid.New(),
		fabricated:  uuid.New(),
		provider:    ai.NewMock(),
	}
	if err := base.SQL.QueryRow(`SELECT core.default_facility()`).Scan(&h.facility); err != nil {
		t.Fatal(err)
	}
	if _, err := base.SQL.Exec(`
		INSERT INTO core.patient (id, facility_id, clinical_id, name_en, name_bn, sex, birth_date,
		                          dob_precision, dob_verified_by, phone_primary, status, registered_at)
		VALUES ($1, $2, 'DTHC-FRD-2026-000701', 'Ayesha Rahman', 'আয়েশা রহমান', 'female',
		        DATE '1984-03-11', 'day', 'national_id', '+8801711234567', 'active', now())`,
		h.realPatient, h.facility); err != nil {
		t.Fatal(err)
	}

	if err := registry.Deploy(ctx, h.store, h.clock.Now()); err != nil {
		t.Fatalf("deploying the prompt registry: %v", err)
	}
	return h
}

// registerFabricated does what cmd/synthload will do: enters a subject in the register, with the
// reason the constraint insists on.
func (h *harness) registerFabricated(t *testing.T, subject uuid.UUID) {
	t.Helper()
	if err := h.store.RegisterSynthetic(context.Background(), subject, h.facility,
		"generated by the synthetic caseload loader for development and evaluation", nil,
		h.clock.Now()); err != nil {
		t.Fatal(err)
	}
}

// gateway builds one on this harness's store, at the given tier and environment.
func (h *harness) gateway(t *testing.T, tier config.AITier, env config.Environment) *ai.Gateway {
	t.Helper()
	m, err := ai.NewMinimiser(testPepper)
	if err != nil {
		t.Fatal(err)
	}
	return ai.NewGateway(ai.GatewayConfig{
		Store: h.store, Registry: h.registry, Provider: h.provider, Minimiser: m,
		Breaker: ai.NewBreaker(3, 30*time.Second, h.clock.Now),
		Tier:    tier, Env: env, Facility: h.facility,
		Alerts: h, Clock: h.clock, Logger: h.logger,
		// No jitter, so a retry test's timing is the policy's rather than the dice's.
		Jitter: func() float64 { return 0.5 },
	})
}

func (h *harness) request(subject uuid.UUID, payload map[string]any) ai.Request {
	return ai.Request{
		AgentCode: "gateway.echo",
		Subject: ai.Subject{
			PatientID: subject, AgeMonths: 511, Sex: "female",
			Identifiers: map[string]string{
				"name_en": "Ayesha Rahman", "name_bn": "আয়েশা রহমান",
				"phone": "01711-234567", "nid": "1990123456789",
			},
		},
		Payload: payload,
	}
}

func (h *harness) rows(t *testing.T, where string, args ...any) int {
	t.Helper()
	var n int
	if err := h.SQL.QueryRow(`SELECT count(*) FROM core.ai_interaction WHERE `+where, args...).Scan(&n); err != nil {
		t.Fatal(err)
	}
	return n
}

func (h *harness) latest(t *testing.T) ai.Interaction {
	t.Helper()
	var id uuid.UUID
	if err := h.SQL.QueryRow(
		`SELECT id FROM core.ai_interaction ORDER BY started_at DESC, ctid DESC LIMIT 1`).Scan(&id); err != nil {
		t.Fatalf("no interaction was recorded at all: %v", err)
	}
	interaction, err := h.store.Interaction(context.Background(), h.facility, id)
	if err != nil {
		t.Fatal(err)
	}
	return interaction
}

// verifyInvariants runs the database's own checks, which is where criteria 1 and 1b are re-asserted
// over the whole table rather than row by row.
func (h *harness) verifyInvariants(t *testing.T) {
	t.Helper()
	rows, err := h.SQL.Query(`SELECT function_name FROM ops.invariant WHERE sequence BETWEEN 98 AND 102`)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = rows.Close() }()
	var names []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatal(err)
		}
		names = append(names, name)
	}
	if len(names) != 5 {
		t.Fatalf("expected the five CP70 invariants to be registered, found %d: %v", len(names), names)
	}
	for _, name := range names {
		if _, err := h.SQL.Exec(`SELECT core.` + name + `()`); err != nil {
			t.Errorf("invariant %s failed: %v", name, err)
		}
	}
}

// --- criterion 1b: a real-patient payload cannot go out on a free credential ---

// TestARealPatientPayloadCannotBeSentOnAFreeTierCredential is the checkpoint's sharpest criterion.
//
// Note what the test does *not* do: it never tells the gateway that this patient is real. There is
// nowhere to say it. The patient exists, nobody entered them in the synthetic register, and that is
// the whole of the decision — which is the point, because a caller that had to declare it would one
// day forget.
func TestARealPatientPayloadCannotBeSentOnAFreeTierCredential(t *testing.T) {
	h := newHarness(t)
	var called int
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		called++
		return ai.ProviderResponse{}, nil
	}

	_, err := h.gateway(t, config.TierFree, config.EnvDev).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{"note": "routine review"}))

	if !errors.Is(err, ai.ErrFreeTierRefused) {
		t.Fatalf("the call was not refused: %v", err)
	}
	if called != 0 {
		t.Errorf("the provider was contacted %d times; the guard must fail closed, not after the fact", called)
	}

	// And the refusal is recorded, because a refused call is exactly the one somebody asks about.
	row := h.latest(t)
	if row.Status != "REFUSED_TIER" {
		t.Errorf("status = %q, want REFUSED_TIER", row.Status)
	}
	if row.Provenance != string(ai.ProvenanceRealPatient) {
		t.Errorf("provenance = %q, want REAL_PATIENT", row.Provenance)
	}
	if row.Tier != "free" {
		t.Errorf("tier = %q, want free", row.Tier)
	}
	if !strings.Contains(row.RefusalDetail, "free tier") {
		t.Errorf("the refusal does not say what it objected to: %q", row.RefusalDetail)
	}
	if len(row.Outbound) != 0 {
		t.Error("the payload of a call we decided not to make was kept anyway")
	}
	h.verifyInvariants(t)
}

// TestASubjectNobodyRegisteredIsTreatedAsReal.
//
// The default-deny half. This subject is not in the patient table either — it is a bare uuid, the
// shape a records-extraction job would pass for a document nobody has filed yet — and it is still
// refused, because "we have never heard of this" is not evidence of anything.
func TestASubjectNobodyRegisteredIsTreatedAsReal(t *testing.T) {
	h := newHarness(t)
	_, err := h.gateway(t, config.TierFree, config.EnvDev).Invoke(context.Background(),
		h.request(uuid.New(), map[string]any{"note": "routine"}))
	if !errors.Is(err, ai.ErrFreeTierRefused) {
		t.Fatalf("an unregistered subject was allowed onto the free tier: %v", err)
	}
	if h.latest(t).Provenance != string(ai.ProvenanceRealPatient) {
		t.Error("an unregistered subject was not recorded as a real patient")
	}
}

// TestAPayloadWithNoSubjectAtAllIsTreatedAsReal. An unlinked scanned report is a real patient's
// report; it has just not been filed yet.
func TestAPayloadWithNoSubjectAtAllIsTreatedAsReal(t *testing.T) {
	h := newHarness(t)
	_, err := h.gateway(t, config.TierFree, config.EnvDev).Invoke(context.Background(),
		h.request(uuid.Nil, map[string]any{"note": "routine"}))
	if !errors.Is(err, ai.ErrFreeTierRefused) {
		t.Fatalf("a subjectless payload was allowed onto the free tier: %v", err)
	}
	if got := h.latest(t).Provenance; got != string(ai.ProvenanceUnknown) {
		t.Errorf("provenance = %q, want UNKNOWN — 'we could not tell' and 'we checked and it is real' are different facts", got)
	}
}

// TestAFabricatedSubjectMayUseTheFreeTier is the other side, and without it the guard could be
// "refuse everything" and pass every test above.
func TestAFabricatedSubjectMayUseTheFreeTier(t *testing.T) {
	h := newHarness(t)
	h.registerFabricated(t, h.fabricated)

	result, err := h.gateway(t, config.TierFree, config.EnvDev).Invoke(context.Background(),
		h.request(h.fabricated, map[string]any{"note": "routine"}))
	if err != nil {
		t.Fatalf("a registered synthetic subject was refused: %v", err)
	}
	if !result.AIGenerated {
		t.Error("the result is not marked ai_generated")
	}
	row := h.latest(t)
	if row.Status != "SUCCEEDED" || row.Provenance != string(ai.ProvenanceSynthetic) {
		t.Errorf("row = %s/%s, want SUCCEEDED/SYNTHETIC", row.Status, row.Provenance)
	}
	h.verifyInvariants(t)
}

// TestTheFreeTierIsRefusedOutsideDevelopmentEvenForAFabricatedSubject.
//
// The second, independent condition. The register decides whether *this payload* is fabricated; the
// environment decides whether the deployment is one where that question can be trusted at all. A
// staging system restored from a production backup is one bad INSERT away from having real patients
// registered, and this is what makes that insufficient rather than fatal.
func TestTheFreeTierIsRefusedOutsideDevelopmentEvenForAFabricatedSubject(t *testing.T) {
	h := newHarness(t)
	h.registerFabricated(t, h.fabricated)

	for _, env := range []config.Environment{config.EnvStaging, config.EnvProduction} {
		t.Run(string(env), func(t *testing.T) {
			_, err := h.gateway(t, config.TierFree, env).Invoke(context.Background(),
				h.request(h.fabricated, map[string]any{"note": "routine"}))
			if !errors.Is(err, ai.ErrFreeTierRefused) {
				t.Fatalf("the free tier was usable in %s: %v", env, err)
			}
			if !strings.Contains(h.latest(t).RefusalDetail, string(env)) {
				t.Error("the refusal does not name the environment it objected to")
			}
		})
	}
}

// TestTheDatabaseRefusesToRecordAFreeTierCallOnRealData.
//
// The backstop, tested directly. Everything above goes through the Go guard; this bypasses it
// entirely and writes the row a buggy gateway would write. If this ever passes, the constraint has
// been dropped and only Go stands between a patient and a tier that trains on them.
func TestTheDatabaseRefusesToRecordAFreeTierCallOnRealData(t *testing.T) {
	h := newHarness(t)
	_, err := h.SQL.Exec(`
		INSERT INTO core.ai_interaction
		  (id, facility_id, agent_code, prompt_version, model_version, tier, provenance,
		   status, input_sha256, started_at, finished_at)
		VALUES ($1, $2, 'gateway.echo', '1.0.0', 'mock-000', 'free', 'REAL_PATIENT',
		        'SUCCEEDED', repeat('a', 64), now(), now())`, uuid.New(), h.facility)
	if err == nil {
		t.Fatal("the database recorded a free-tier call carrying real patient data")
	}
	if !strings.Contains(err.Error(), "free_tier_is_synthetic_only") {
		t.Fatalf("refused for the wrong reason: %v", err)
	}
}

// TestTheInvariantCatchesAFreeTierRowThatArrivedSomeOtherWay.
//
// A constraint guards rows written from here on. The invariant is what catches one that was already
// there — a row inserted before the constraint existed, or by a migration, or by somebody with
// psql. It is disabled and re-enabled around the insert precisely because that is the only way to
// get such a row, which is itself the point.
func TestTheInvariantCatchesAFreeTierRowThatArrivedSomeOtherWay(t *testing.T) {
	h := newHarness(t)
	if _, err := h.SQL.Exec(
		`ALTER TABLE core.ai_interaction DROP CONSTRAINT ai_interaction_free_tier_is_synthetic_only`); err != nil {
		t.Fatal(err)
	}
	if _, err := h.SQL.Exec(`
		INSERT INTO core.ai_interaction
		  (id, facility_id, agent_code, prompt_version, model_version, tier, provenance,
		   status, input_sha256, started_at, finished_at)
		VALUES ($1, $2, 'gateway.echo', '1.0.0', 'mock-000', 'free', 'REAL_PATIENT',
		        'SUCCEEDED', repeat('a', 64), now(), now())`, uuid.New(), h.facility); err != nil {
		t.Fatal(err)
	}

	_, err := h.SQL.Exec(`SELECT core.assert_no_free_tier_call_touched_a_real_patient()`)
	if err == nil {
		t.Fatal("the invariant passed with a free-tier call on real patient data in the table")
	}
	if !strings.Contains(err.Error(), "free-tier credential") {
		t.Fatalf("the invariant failed for the wrong reason: %v", err)
	}
}

// --- criterion 1: no identifier reaches a provider ---

// TestWhatWasActuallySentCarriesNoIdentifier is the end-to-end version of the criterion, and the
// one the manual verification step performs by hand: invoke, open the recorded payload, read it.
func TestWhatWasActuallySentCarriesNoIdentifier(t *testing.T) {
	h := newHarness(t)
	var sent string
	h.provider.Respond = func(req ai.ProviderRequest) (ai.ProviderResponse, error) {
		sent = req.System + "\n" + req.User
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":2}`, ModelVersion: ai.MockModelVersion,
			InputTokens: 100, OutputTokens: 20, FinishReason: "STOP",
		}, nil
	}

	if _, err := h.gateway(t, config.TierPaid, config.EnvProduction).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{
			"counselling_note": "Rang her son Md. Rafiqul on 01711-234567; NID 1990123456789 on the form.",
			"diagnosis":        "type 2 diabetes mellitus",
		})); err != nil {
		t.Fatalf("invoking: %v", err)
	}

	// What the provider actually saw.
	//
	// "Rafiqul" is here because the honorific pattern catches "Md. Rafiqul". A *bare* given name —
	// "her son Rafiq", with no honorific — would not be caught by anything in this package, and
	// that is the residual risk stated in the package comment rather than a gap this test hides.
	for _, forbidden := range []string{"Ayesha", "আয়েশা", "01711", "1990123456789", "Rafiqul"} {
		if strings.Contains(sent, forbidden) {
			t.Errorf("%q reached the provider:\n%s", forbidden, sent)
		}
	}
	// The clinical content did reach it, which is the half a scrubber that redacted everything
	// would pass without.
	if !strings.Contains(sent, "type 2 diabetes") {
		t.Errorf("the clinical picture did not reach the model:\n%s", sent)
	}

	// And what is on the record, which is what a reviewer opens.
	row := h.latest(t)
	stored := string(row.Outbound)
	for _, forbidden := range []string{"Ayesha", "আয়েশা", "01711-234567", "1990123456789"} {
		if strings.Contains(stored, forbidden) {
			t.Errorf("%q is in the recorded outbound payload:\n%s", forbidden, stored)
		}
	}
	if !strings.Contains(stored, "removed") {
		t.Error("the record does not say what the scrubber took out; the outbound log is the mitigation")
	}
	h.verifyInvariants(t)
}

// TestTheDatabaseRefusesToRecordAPayloadThatNamesAPerson.
//
// The backstop for criterion 1, tested through the constraint rather than through the function it
// calls. That distinction turned out to matter: the first version of this file exercised
// `ops.carries_identifier` directly, so dropping the constraint from the table changed nothing and
// the suite stayed green — a test that confirmed the check existed rather than that it was
// attached to anything.
//
// Because the gateway writes the record *before* it contacts the provider, a payload that cannot be
// recorded is a payload that is never sent. This is what makes that sentence true.
func TestTheDatabaseRefusesToRecordAPayloadThatNamesAPerson(t *testing.T) {
	h := newHarness(t)
	for name, outbound := range map[string]string{
		"an identifier key":         `{"payload":{"phone":"x"}}`,
		"a suffixed identifier key": `{"payload":{"guardian_phone":"x"}}`,
		"one buried in an array":    `{"payload":{"visits":[{"nid":"x"}]}}`,
		"a phone number in prose":   `{"payload":{"note":"rang her son on 01711-234567"}}`,
		"a national ID in prose":    `{"payload":{"note":"NID 1990123456789 on the form"}}`,
		"an email in prose":         `{"payload":{"note":"bounced from a@b.com"}}`,
	} {
		t.Run(name, func(t *testing.T) {
			_, err := h.SQL.Exec(`
				INSERT INTO core.ai_interaction
				  (id, facility_id, agent_code, prompt_version, model_version, tier, provenance,
				   status, outbound, input_sha256, started_at, finished_at)
				VALUES ($1, $2, 'gateway.echo', '1.0.0', 'mock-000', 'paid', 'REAL_PATIENT',
				        'SUCCEEDED', $3::jsonb, repeat('a', 64), now(), now())`,
				uuid.New(), h.facility, outbound)
			if err == nil {
				t.Fatalf("the database recorded a payload carrying %s", name)
			}
			if !strings.Contains(err.Error(), "outbound_carries_no_identifier") {
				t.Fatalf("refused for the wrong reason: %v", err)
			}
		})
	}

	// And the clinical content it is *supposed* to carry is accepted, or the constraint would be
	// "refuse everything" and every test above would pass while the gateway sent nothing.
	if _, err := h.SQL.Exec(`
		INSERT INTO core.ai_interaction
		  (id, facility_id, agent_code, prompt_version, model_version, tier, provenance,
		   status, outbound, input_sha256, started_at, finished_at)
		VALUES ($1, $2, 'gateway.echo', '1.0.0', 'mock-000', 'paid', 'REAL_PATIENT',
		        'SUCCEEDED', $3::jsonb, repeat('a', 64), now(), now())`,
		uuid.New(), h.facility,
		`{"payload":{"diagnosis":"type 2 diabetes mellitus","hba1c":8.2,"note":"BP 120/80, adherence good"}}`,
	); err != nil {
		t.Fatalf("the constraint refused a legitimate clinical payload: %v", err)
	}
}

// TestTheInvariantCatchesAPayloadThatNamesAPerson. The constraint guards rows written from here on;
// this is what catches one that arrived some other way, which is the check criterion 1 is really
// about.
func TestTheInvariantCatchesAPayloadThatNamesAPerson(t *testing.T) {
	h := newHarness(t)
	if _, err := h.SQL.Exec(
		`ALTER TABLE core.ai_interaction DROP CONSTRAINT ai_interaction_outbound_carries_no_identifier`); err != nil {
		t.Fatal(err)
	}
	if _, err := h.SQL.Exec(`
		INSERT INTO core.ai_interaction
		  (id, facility_id, agent_code, prompt_version, model_version, tier, provenance,
		   status, outbound, input_sha256, started_at, finished_at)
		VALUES ($1, $2, 'gateway.echo', '1.0.0', 'mock-000', 'paid', 'REAL_PATIENT', 'SUCCEEDED',
		        '{"payload":{"note":"call 01711-234567"}}'::jsonb, repeat('a', 64), now(), now())`,
		uuid.New(), h.facility); err != nil {
		t.Fatal(err)
	}
	_, err := h.SQL.Exec(`SELECT core.assert_no_ai_payload_names_a_person()`)
	if err == nil {
		t.Fatal("the invariant passed with an identifier in a recorded payload")
	}
	if !strings.Contains(err.Error(), "names a person") {
		t.Fatalf("the invariant failed for the wrong reason: %v", err)
	}
}

// TestThePayloadCheckAgreesWithTheDatabase.
//
// The Go minimiser refuses first so the message names the key; the constraint is the backstop. A
// backstop narrower than the thing it backs is not one — and one *wider* than it means a payload
// that passes Go arrives as an opaque constraint violation. Both directions matter, so both are
// checked, over payloads shaped like the ones an agent will actually build.
func TestThePayloadCheckAgreesWithTheDatabase(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	m, err := ai.NewMinimiser(testPepper)
	if err != nil {
		t.Fatal(err)
	}

	payloads := map[string]map[string]any{
		"a bare identifier key":     {"phone": "01711234567"},
		"a suffixed identifier key": {"guardian_phone": "01711234567"},
		"a doubly suffixed one":     {"mother_name_bn": "আয়েশা"},
		"one buried two levels in":  {"visit": map[string]any{"patient": map[string]any{"nid": "1990123456789"}}},
		"one inside an array":       {"visits": []any{map[string]any{"address": "House 12"}}},
		"a credential":              {"token": "eyJhbGciOi"},
		"a clinical key, permitted": {"diagnosis": "type 2 diabetes mellitus"},
		"clean structured data":     {"hba1c": 8.2, "unit": "%"},
		"a free-text number":        {"note": "call 01711-234567 tomorrow"},
		"clean prose":               {"note": "BP 120/80, adherence good"},
	}

	for name, payload := range payloads {
		t.Run(name, func(t *testing.T) {
			_, goErr := m.Minimise("gateway.echo", ai.Subject{PatientID: uuid.New()}, payload)
			goRefuses := goErr != nil

			encoded, err := json.Marshal(payload)
			if err != nil {
				t.Fatal(err)
			}
			dbRefuses, err := h.store.PayloadCarriesIdentifier(ctx, encoded)
			if err != nil {
				t.Fatal(err)
			}

			// The one legitimate asymmetry: Go *scrubs* free text rather than refusing it, so a
			// note containing a phone number is refused by the raw database check and accepted by
			// Go — because by the time Go is finished the number is gone. What must agree is the
			// verdict on the payload Go actually produces.
			if goRefuses != dbRefuses {
				if minimised, err := m.Minimise("gateway.echo", ai.Subject{PatientID: uuid.New()}, payload); err == nil {
					after, err := json.Marshal(minimised.Payload)
					if err != nil {
						t.Fatal(err)
					}
					stillBad, err := h.store.PayloadCarriesIdentifier(ctx, after)
					if err != nil {
						t.Fatal(err)
					}
					if stillBad {
						t.Fatalf("Go accepted a payload the database still refuses after minimisation:\n%s", after)
					}
					return
				}
				t.Fatalf("Go refuses = %v, the database refuses = %v", goRefuses, dbRefuses)
			}
		})
	}
}

// TestTheScrubberAgreesWithTheDatabase holds the two copies of the pattern list together.
//
// Both directions on the list itself, and then — the part that actually earns the test — the same
// fixture corpus through both engines. Two regular-expression implementations agreeing about a list
// of patterns is not something to assume: PostgreSQL's ARE and Go's RE2 are different engines, and
// the whole design of patterns.go is that the expressions live in the intersection of the two.
func TestTheScrubberAgreesWithTheDatabase(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()

	stored, err := h.store.PIIPatterns(ctx)
	if err != nil {
		t.Fatal(err)
	}
	byKind := map[string]ai.Pattern{}
	for _, p := range stored {
		byKind[p.Kind] = p
	}
	for _, p := range ai.DefaultPatterns {
		got, ok := byKind[p.Kind]
		if !ok {
			t.Fatalf("%q is in ai.DefaultPatterns and not in ops.pii_pattern", p.Kind)
		}
		if got.Expression != p.Expression {
			t.Fatalf("%q is %q in Go and %q in the database", p.Kind, p.Expression, got.Expression)
		}
		if got.Replacement != p.Replacement {
			t.Fatalf("%q replaces with %q in Go and %q in the database", p.Kind, p.Replacement, got.Replacement)
		}
		delete(byKind, p.Kind)
	}
	for kind := range byKind {
		t.Fatalf("%q is in ops.pii_pattern and not in ai.DefaultPatterns", kind)
	}

	compiled, err := ai.CompilePatterns(ai.DefaultPatterns)
	if err != nil {
		t.Fatal(err)
	}
	corpus := []string{
		"rang her son Rafiq on 01711-234567",
		"+880 1711 234567",
		"01711234567",
		"NID 1990123456789",
		"০১৭১১২৩৪৫৬৭",
		"০১৭১১-২৩৪৫৬৭",
		"ayesha.rahman@example.com",
		"Escorted by Md. Rafiqul Islam",
		"symptoms include polyuria",
		"BP 120/80, pulse 72",
		"HbA1c 8.2 on 2026-03-12, 7.6 on 2026-06-04",
		"Metformin 500 mg twice daily",
		"রক্তচাপ ১২০/৮০, ওজন ৬১.৪ কেজি",
		"12 14 16 18",
		"",
	}
	for _, candidate := range corpus {
		var goSays bool
		for _, p := range compiled {
			if p.Matches(candidate) {
				goSays = true
				break
			}
		}
		dbSays, err := h.store.TextCarriesIdentifier(ctx, candidate)
		if err != nil {
			t.Fatal(err)
		}
		if goSays != dbSays {
			t.Errorf("the engines disagree about %q: Go says %v, PostgreSQL says %v",
				candidate, goSays, dbSays)
		}
	}
}

// TestARefusedPayloadIsRecordedWithoutThePayload.
//
// A REFUSED_PHI row is the one place the record deliberately keeps less. That payload is precisely
// the thing the gateway decided was unsafe; storing it would move the leak from the provider to our
// own audit table, where more people can read it and nobody is watching.
func TestARefusedPayloadIsRecordedWithoutThePayload(t *testing.T) {
	h := newHarness(t)
	var called int
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		called++
		return ai.ProviderResponse{}, nil
	}

	_, err := h.gateway(t, config.TierPaid, config.EnvProduction).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{"patient_name": "Ayesha Rahman"}))
	if !errors.Is(err, ai.ErrPayloadNamesAPerson) {
		t.Fatalf("a payload naming a person was accepted: %v", err)
	}
	if called != 0 {
		t.Error("the provider was contacted with a payload that names a person")
	}

	row := h.latest(t)
	if row.Status != "REFUSED_PHI" {
		t.Fatalf("status = %q, want REFUSED_PHI", row.Status)
	}
	if len(row.Outbound) != 0 {
		t.Errorf("the refused payload was stored anyway: %s", row.Outbound)
	}
	if !strings.Contains(row.RefusalDetail, "patient_name") {
		t.Errorf("the record does not name the offending key: %q", row.RefusalDetail)
	}
	if strings.Contains(row.RefusalDetail, "Ayesha") {
		t.Errorf("the record carries the value it objected to: %q", row.RefusalDetail)
	}
}

// --- criterion 2: every call is recorded ---

// TestEveryCallIsRecordedIncludingTheOnesThatFailed.
//
// The whole point of "every". A call that errored is exactly the one somebody wants to see later,
// and a system that only recorded successes would answer "there is no record of that" to the only
// question anybody asks it.
func TestEveryCallIsRecordedIncludingTheOnesThatFailed(t *testing.T) {
	h := newHarness(t)
	gateway := h.gateway(t, config.TierPaid, config.EnvProduction)
	ctx := context.Background()

	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":1}`, ModelVersion: ai.MockModelVersion,
			InputTokens: 900, OutputTokens: 100,
		}, nil
	}
	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"a": 1})); err != nil {
		t.Fatalf("the good call failed: %v", err)
	}
	good := h.latest(t)

	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		return ai.ProviderResponse{}, fmt.Errorf("%w: connection reset", ai.ErrProviderUnavailable)
	}
	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"b": 2})); err == nil {
		t.Fatal("a provider failure was not reported to the caller")
	}
	bad := h.latest(t)

	for name, row := range map[string]ai.Interaction{"the successful call": good, "the failed call": bad} {
		if row.PromptVersion == "" {
			t.Errorf("%s does not record its prompt version", name)
		}
		if row.InputSHA256 == "" {
			t.Errorf("%s does not record its input hash", name)
		}
		if row.FinishedAt == nil {
			t.Errorf("%s was left in flight", name)
		}
	}
	if good.Status != "SUCCEEDED" {
		t.Errorf("the good call is %s", good.Status)
	}
	if good.ModelVersion == "" {
		t.Error("the successful call does not record which model answered")
	}
	if good.InputTokens != 900 || good.OutputTokens != 100 {
		t.Errorf("tokens = %d/%d, want 900/100", good.InputTokens, good.OutputTokens)
	}
	if bad.Status != "PROVIDER_ERROR" {
		t.Errorf("the failed call is %s, want PROVIDER_ERROR", bad.Status)
	}
	if !strings.Contains(bad.RefusalDetail, "connection reset") {
		t.Errorf("the failed call does not say what went wrong: %q", bad.RefusalDetail)
	}
	if bad.Attempts < 2 {
		t.Errorf("a retryable failure was attempted %d times; the policy says three", bad.Attempts)
	}
	h.verifyInvariants(t)
}

// TestACostIsRecordedAgainstThePinnedModelsPrice. Criterion 2's other half: metering that adds up.
func TestACostIsRecordedAgainstThePinnedModelsPrice(t *testing.T) {
	h := newHarness(t)
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":1}`, ModelVersion: ai.MockModelVersion,
			InputTokens: 1_000_000, OutputTokens: 1_000_000,
		}, nil
	}
	if _, err := h.gateway(t, config.TierPaid, config.EnvProduction).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{"a": 1})); err != nil {
		t.Fatal(err)
	}
	// gateway.echo pins gemini-2.5-flash-001: 300000 in, 2500000 out, per million.
	if got := h.latest(t).CostMicroUSD; got != 2_800_000 {
		t.Errorf("cost = %d micro-dollars, want 2800000 — priced against the model that was asked, "+
			"not the mock that answered", got)
	}
}

// --- criterion 4: invalid output rejected, retried, then failed cleanly ---

func TestAnInvalidAnswerIsRetriedAndThenFailsCleanly(t *testing.T) {
	h := newHarness(t)
	var attempts int
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		attempts++
		return ai.ProviderResponse{
			Text:         `{"summary":"ok"}`, // field_count is required and absent
			ModelVersion: ai.MockModelVersion, InputTokens: 10, OutputTokens: 5,
		}, nil
	}

	result, err := h.gateway(t, config.TierPaid, config.EnvProduction).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{"a": 1}))
	if !errors.Is(err, ai.ErrInvalidOutput) {
		t.Fatalf("an invalid answer was not reported as one: %v", err)
	}
	if result.Output != nil {
		t.Error("a half-valid answer was handed back to the caller")
	}
	if attempts != 3 {
		t.Errorf("the model was asked %d times; gateway.echo's policy is three", attempts)
	}

	row := h.latest(t)
	if row.Status != "INVALID_OUTPUT" {
		t.Errorf("status = %q, want INVALID_OUTPUT", row.Status)
	}
	if row.OutputValid == nil || *row.OutputValid {
		t.Error("the record does not say the answer failed validation")
	}
	if row.Attempts != 3 {
		t.Errorf("attempts recorded = %d, want 3", row.Attempts)
	}
	// Three answers were paid for even though none was usable, and the record has to say so or the
	// monthly total will not reconcile.
	if row.InputTokens != 30 || row.OutputTokens != 15 {
		t.Errorf("tokens = %d/%d; every attempt was billed and all of them must be counted",
			row.InputTokens, row.OutputTokens)
	}
}

// TestARetryAfterAViolationIsToldWhatWasWrong, and the repair instruction is what turns criterion
// 4's retry from a coin toss into a fix.
func TestARetryAfterAViolationIsToldWhatWasWrong(t *testing.T) {
	h := newHarness(t)
	var prompts []string
	h.provider.Respond = func(req ai.ProviderRequest) (ai.ProviderResponse, error) {
		prompts = append(prompts, req.User)
		if len(prompts) == 1 {
			return ai.ProviderResponse{Text: `{"summary":"ok"}`, ModelVersion: ai.MockModelVersion}, nil
		}
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":1}`, ModelVersion: ai.MockModelVersion,
		}, nil
	}

	result, err := h.gateway(t, config.TierPaid, config.EnvProduction).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{"a": 1}))
	if err != nil {
		t.Fatalf("the retry did not recover: %v", err)
	}
	if result.Output["summary"] != "ok" {
		t.Errorf("the recovered answer is wrong: %v", result.Output)
	}
	if len(prompts) != 2 {
		t.Fatalf("the model was asked %d times, want 2", len(prompts))
	}
	if !strings.Contains(prompts[1], "field_count") {
		t.Errorf("the retry was not told which field was missing:\n%s", prompts[1])
	}
	if strings.Contains(prompts[0], "rejected") {
		t.Error("the first attempt carried a repair instruction; there was nothing to repair yet")
	}
	if row := h.latest(t); row.Status != "SUCCEEDED" || row.Attempts != 2 {
		t.Errorf("row = %s after %d attempts, want SUCCEEDED after 2", row.Status, row.Attempts)
	}
}

// --- the cache ---

// TestAnIdenticalInputIsServedFromTheCacheAndNotReBilled is §10.3 step 4, and the cost control
// D-14 leans on.
func TestAnIdenticalInputIsServedFromTheCacheAndNotReBilled(t *testing.T) {
	h := newHarness(t)
	var calls int
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		calls++
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":1}`, ModelVersion: ai.MockModelVersion,
			InputTokens: 1000, OutputTokens: 500,
		}, nil
	}
	gateway := h.gateway(t, config.TierPaid, config.EnvProduction)
	ctx := context.Background()
	payload := map[string]any{"hba1c": 8.2}

	first, err := gateway.Invoke(ctx, h.request(h.realPatient, payload))
	if err != nil {
		t.Fatal(err)
	}
	second, err := gateway.Invoke(ctx, h.request(h.realPatient, payload))
	if err != nil {
		t.Fatal(err)
	}

	if calls != 1 {
		t.Errorf("the model was called %d times for an identical input", calls)
	}
	if !second.Cached {
		t.Error("the second call is not marked as cached")
	}
	if second.CostMicroUSD != 0 {
		t.Errorf("a cached answer cost %d micro-dollars", second.CostMicroUSD)
	}
	if fmt.Sprint(first.Output) != fmt.Sprint(second.Output) {
		t.Errorf("the cached answer differs from the original:\n%v\n%v", first.Output, second.Output)
	}
	// Recorded as its own row, not silently absent: the audit question is "what has this system
	// said about this patient", and an answer served from the cache was still an answer given.
	if n := h.rows(t, `status = 'CACHED'`); n != 1 {
		t.Errorf("%d cached rows recorded, want 1", n)
	}
	if got := h.latest(t).CostMicroUSD; got != 0 {
		t.Errorf("the cached row records a cost of %d", got)
	}

	// A different patient with the same clinical values must *not* hit: the pseudonym is part of
	// the payload, so the hashes differ. This is the failure that would be catastrophic and
	// invisible — one patient's summary served for another.
	h.registerFabricated(t, h.fabricated)
	if _, err := gateway.Invoke(ctx, h.request(h.fabricated, payload)); err != nil {
		t.Fatal(err)
	}
	if calls != 2 {
		t.Error("a different subject with identical clinical values was served another patient's cached answer")
	}
}

// TestAChangedPromptVersionMissesTheCache. The hash covers the prompt version, so an edited prompt
// does not serve answers produced by the old one.
func TestAChangedPromptVersionMissesTheCache(t *testing.T) {
	h := newHarness(t)
	m, err := ai.NewMinimiser(testPepper)
	if err != nil {
		t.Fatal(err)
	}
	minimised, err := m.Minimise("gateway.echo", ai.Subject{PatientID: h.realPatient}, map[string]any{"a": 1})
	if err != nil {
		t.Fatal(err)
	}
	first, err := json.Marshal(map[string]any{
		"payload": minimised.Payload, "removed": minimised.Removed, "prompt_version": "1.0.0",
	})
	if err != nil {
		t.Fatal(err)
	}
	second, err := json.Marshal(map[string]any{
		"payload": minimised.Payload, "removed": minimised.Removed, "prompt_version": "1.1.0",
	})
	if err != nil {
		t.Fatal(err)
	}
	if string(first) == string(second) {
		t.Fatal("the outbound record does not carry the prompt version, so the cache key cannot depend on it")
	}
}

// --- criterion 5: budget alerts ---

// TestABudgetAlertFiresAtEachThresholdOnceADay.
//
// Two properties, and the second is the one that decides whether anybody still reads the alerts in
// six months: every configured threshold fires, and each fires **once**. An alert that fired on
// every call for the rest of the day is one somebody turns off, which is how a clinic ends up with
// no alerting at all on the day it matters.
func TestABudgetAlertFiresAtEachThresholdOnceADay(t *testing.T) {
	h := newHarness(t)
	// A budget small enough that one call crosses 60% and two cross 100%. The seeded ten dollars a
	// day is a proposal for production, not a figure a test should depend on.
	if _, err := h.SQL.Exec(
		`UPDATE core.ai_budget SET daily_micro_usd = 4000000 WHERE facility_id = $1 AND agent_code IS NULL`,
		h.facility); err != nil {
		t.Fatal(err)
	}

	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		// 2.8 US dollars a call, against a four-dollar budget: 70% after one, 140% after two.
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":1}`, ModelVersion: ai.MockModelVersion,
			InputTokens: 1_000_000, OutputTokens: 1_000_000,
		}, nil
	}
	gateway := h.gateway(t, config.TierPaid, config.EnvProduction)
	ctx := context.Background()

	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"n": 1})); err != nil {
		t.Fatal(err)
	}
	alerts, err := h.store.BudgetAlerts(ctx, h.facility, h.clock.Now().AddDate(0, 0, -1), 50)
	if err != nil {
		t.Fatal(err)
	}
	if len(alerts) != 1 || alerts[0].ThresholdPercent != 60 {
		t.Fatalf("after one call the alerts are %v; want exactly the 60%% one", alerts)
	}
	if len(h.raised) != 1 {
		t.Fatalf("%d alerts reached the administrators' console, want 1", len(h.raised))
	}

	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"n": 2})); err != nil {
		t.Fatal(err)
	}
	alerts, err = h.store.BudgetAlerts(ctx, h.facility, h.clock.Now().AddDate(0, 0, -1), 50)
	if err != nil {
		t.Fatal(err)
	}
	crossed := map[int]int{}
	for _, alert := range alerts {
		crossed[alert.ThresholdPercent]++
	}
	if crossed[60] != 1 || crossed[80] != 1 || crossed[100] != 1 {
		t.Errorf("thresholds crossed = %v; want each of 60, 80 and 100 exactly once", crossed)
	}

	// A third call crosses nothing new, and this is the assertion that matters most.
	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"n": 3})); err != nil {
		t.Fatal(err)
	}
	alerts, err = h.store.BudgetAlerts(ctx, h.facility, h.clock.Now().AddDate(0, 0, -1), 50)
	if err != nil {
		t.Fatal(err)
	}
	if len(alerts) != 3 {
		t.Errorf("%d alerts after three calls; each threshold must fire once a day, not once a call", len(alerts))
	}

	// And the console, which is the half a table-only assertion misses. The `ON CONFLICT DO
	// NOTHING` keeps the *record* to one row per threshold per day whatever the Go code does; what
	// this checks is that nobody is *told* twice. An alert that arrives on every call for the rest
	// of the day is one somebody turns off, and then there is no alerting at all on the day it
	// matters.
	told := map[int]int{}
	for _, alert := range h.raised {
		told[alert.ThresholdPercent]++
		if alert.SpendMicroUSD == 0 || alert.BudgetMicroUSD == 0 {
			t.Errorf("an alert reached the console with no figures on it: %+v", alert)
		}
	}
	if len(h.raised) != 3 || told[60] != 1 || told[80] != 1 || told[100] != 1 {
		t.Errorf("the administrators were told %v (%d alerts in total); want each threshold exactly once",
			told, len(h.raised))
	}
}

// TestSpendIsReportedPerAgentAndForTheDeploymentTogether.
func TestSpendIsReportedPerAgentAndForTheDeploymentTogether(t *testing.T) {
	h := newHarness(t)
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		return ai.ProviderResponse{
			Text: `{"summary":"ok","field_count":1}`, ModelVersion: ai.MockModelVersion,
			InputTokens: 1_000_000, OutputTokens: 0,
		}, nil
	}
	ctx := context.Background()
	if _, err := h.gateway(t, config.TierPaid, config.EnvProduction).
		Invoke(ctx, h.request(h.realPatient, map[string]any{"n": 1})); err != nil {
		t.Fatal(err)
	}

	dayStart := h.clock.Now().UTC().Truncate(24 * time.Hour)
	spend, err := h.store.DailySpend(ctx, h.facility, dayStart, dayStart.Add(24*time.Hour))
	if err != nil {
		t.Fatal(err)
	}
	byAgent := map[string]int64{}
	percentSet := map[string]bool{}
	for _, line := range spend {
		byAgent[line.AgentCode] = line.SpendMicroUSD
		percentSet[line.AgentCode] = line.PercentOfBudget != nil
	}
	if byAgent[""] != 300_000 {
		t.Errorf("the deployment total is %d micro-dollars, want 300000", byAgent[""])
	}
	if byAgent["gateway.echo"] != 300_000 {
		t.Errorf("gateway.echo spent %d, want 300000", byAgent["gateway.echo"])
	}
	if !percentSet[""] {
		t.Error("the deployment row has no percentage, though a deployment-wide budget is seeded")
	}
	if percentSet["gateway.echo"] {
		t.Error("gateway.echo reports a percentage though no per-agent budget is configured; " +
			"'nothing configured' and 'nothing spent' are different states")
	}
}

// --- criterion 3: the provider is swappable by configuration ---

// TestTheSamePipelineRunsAgainstTheRealAdapter.
//
// The mock proves the gateway; this proves the *seam*. The Gemini adapter is pointed at an httptest
// server speaking generateContent — which is what `tools/mockai` is in the compose stack, and what
// `DTHCMS_AI_BASE_URL` pointed at Vertex would be in production. Nothing in the gateway changes.
func TestTheSamePipelineRunsAgainstTheRealAdapter(t *testing.T) {
	h := newHarness(t)

	var seen string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		seen = string(body)
		if key := r.Header.Get("x-goog-api-key"); key != "test-key" {
			t.Errorf("the adapter sent the key as %q", key)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, `{
			"candidates":[{"content":{"role":"model","parts":[{"text":"{\"summary\":\"ok\",\"field_count\":1}"}]},"finishReason":"STOP"}],
			"usageMetadata":{"promptTokenCount":120,"candidatesTokenCount":30},
			"modelVersion":"gemini-2.5-flash-001"}`)
	}))
	defer server.Close()

	m, err := ai.NewMinimiser(testPepper)
	if err != nil {
		t.Fatal(err)
	}
	gateway := ai.NewGateway(ai.GatewayConfig{
		Store: h.store, Registry: h.registry,
		Provider:  ai.NewGemini(server.URL, "test-key", 5*time.Second),
		Minimiser: m, Breaker: ai.NewBreaker(3, 30*time.Second, h.clock.Now),
		Tier: config.TierPaid, Env: config.EnvProduction, Facility: h.facility,
		Clock: h.clock, Logger: h.logger, Jitter: func() float64 { return 0.5 },
	})

	result, err := gateway.Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{
			"note": "Rang her son on 01711-234567 about adherence.",
		}))
	if err != nil {
		t.Fatalf("the real adapter failed: %v", err)
	}
	if result.Output["summary"] != "ok" {
		t.Errorf("the answer was not parsed: %v", result.Output)
	}
	if result.ModelVersion != "gemini-2.5-flash-001" {
		t.Errorf("model version = %q; the record must say what actually answered", result.ModelVersion)
	}
	// And the same minimisation applies: nothing about the adapter can turn it off.
	for _, forbidden := range []string{"Ayesha", "01711", "1990123456789"} {
		if strings.Contains(seen, forbidden) {
			t.Errorf("%q reached the wire:\n%s", forbidden, seen)
		}
	}
	if row := h.latest(t); row.Status != "SUCCEEDED" || row.InputTokens != 120 {
		t.Errorf("the record is %s with %d input tokens, want SUCCEEDED with 120",
			row.Status, row.InputTokens)
	}
}

// TestTheAdapterClassifiesTheProvidersFailures.
//
// This is the one thing the adapter does that looks like policy, and it is not: only the adapter
// knows that this provider says 429 with a Retry-After and puts a refusal in `finishReason` rather
// than in a status code. Translating that into the sentinel errors is what lets the gateway have
// one retry policy rather than one per provider.
func TestTheAdapterClassifiesTheProvidersFailures(t *testing.T) {
	for name, tc := range map[string]struct {
		status    int
		headers   map[string]string
		body      string
		want      error
		retryable bool
		after     time.Duration
	}{
		"a rate limit": {
			status: http.StatusTooManyRequests, headers: map[string]string{"Retry-After": "17"},
			body: `{"error":{"code":429}}`, want: ai.ErrProviderRateLimited, retryable: true,
			after: 17 * time.Second,
		},
		"a server fault": {
			status: http.StatusInternalServerError, body: `{"error":{"code":500}}`,
			want: ai.ErrProviderUnavailable, retryable: true,
		},
		"a retired model version": {
			status: http.StatusNotFound, body: `{"error":{"code":404,"message":"model not found"}}`,
			want: ai.ErrProviderRejected, retryable: false,
		},
		"a safety refusal": {
			status: http.StatusOK,
			body:   `{"candidates":[{"finishReason":"SAFETY"}],"usageMetadata":{}}`,
			want:   ai.ErrProviderRefused, retryable: false,
		},
		"a truncated body": {
			status: http.StatusOK, body: `{"candidates":[{"content":{"parts":[{"text":"unter`,
			want: ai.ErrProviderUnavailable, retryable: true,
		},
	} {
		t.Run(name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				for k, v := range tc.headers {
					w.Header().Set(k, v)
				}
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(tc.status)
				_, _ = io.WriteString(w, tc.body)
			}))
			defer server.Close()

			_, err := ai.NewGemini(server.URL, "k", time.Second).Generate(context.Background(),
				ai.ProviderRequest{ModelVersion: "gemini-2.5-flash-001", User: "x"})
			if !errors.Is(err, tc.want) {
				t.Fatalf("got %v, want %v", err, tc.want)
			}
			if ai.Retryable(err) != tc.retryable {
				t.Errorf("retryable = %v, want %v", ai.Retryable(err), tc.retryable)
			}
			if tc.after > 0 {
				advice, ok := ai.RetryAfter(err)
				if !ok || advice != tc.after {
					t.Errorf("Retry-After = %v (%v), want %v — answering a 429 with our own curve "+
						"instead of the provider's advice is a second 429", advice, ok, tc.after)
				}
			}
		})
	}
}

// TestASafetyRefusalIsNotRetried. Asking the same question again is the one thing guaranteed not to
// change the answer, and three attempts is three times the cost for the same silence.
func TestASafetyRefusalIsNotRetried(t *testing.T) {
	h := newHarness(t)
	var calls int
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		calls++
		return ai.ProviderResponse{}, fmt.Errorf("%w: finish reason SAFETY", ai.ErrProviderRefused)
	}
	if _, err := h.gateway(t, config.TierPaid, config.EnvProduction).Invoke(context.Background(),
		h.request(h.realPatient, map[string]any{"a": 1})); err == nil {
		t.Fatal("a refusal was reported as a success")
	}
	if calls != 1 {
		t.Errorf("a safety refusal was retried %d times", calls)
	}
}

// --- the prompt registry ---

// TestAPromptEditedUnderTheSameVersionIsRefused.
//
// The single change that would make every stored interaction unreproducible: the record names a
// version whose text no longer exists anywhere. A process that will not start is a bad morning; a
// clinical audit trail that quietly stopped meaning anything is a worse year.
func TestAPromptEditedUnderTheSameVersionIsRefused(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()

	// Deploying the same build twice is start-up succeeding.
	if err := h.registry.Deploy(ctx, h.store, h.clock.Now()); err != nil {
		t.Fatalf("re-deploying an unchanged build failed: %v", err)
	}

	// Now the same version with different text, which is what an edit-without-a-bump looks like
	// from the database's side.
	if _, err := h.SQL.Exec(
		`UPDATE core.ai_prompt_version SET content_sha256 = repeat('b', 64) WHERE version = '1.0.0'`); err != nil {
		t.Fatal(err)
	}
	err := h.registry.Deploy(ctx, h.store, h.clock.Now())
	if err == nil {
		t.Fatal("a prompt edited under an unchanged version number was accepted")
	}
	if !strings.Contains(err.Error(), "Bump the version") {
		t.Errorf("the refusal does not say what to do instead: %v", err)
	}
}

// TestTheRegistryIsMirroredInTheDatabase.
func TestTheRegistryIsMirroredInTheDatabase(t *testing.T) {
	h := newHarness(t)
	deployed, err := h.store.DeployedPrompts(context.Background(), true)
	if err != nil {
		t.Fatal(err)
	}
	stored := map[string]string{}
	for _, p := range deployed {
		stored[p.AgentCode+"@"+p.Version] = p.ContentSHA256
		if p.Content == "" {
			t.Errorf("%s %s stored no content; a hash says a prompt changed and not what it said",
				p.AgentCode, p.Version)
		}
	}
	for _, p := range h.registry.All() {
		key := p.AgentCode + "@" + p.Version
		got, ok := stored[key]
		if !ok {
			t.Errorf("%s is in the build and not in the database", key)
			continue
		}
		if got != p.SHA256 {
			t.Errorf("%s hashes to %s in the build and %s in the database", key, p.SHA256, got)
		}
		delete(stored, key)
	}
	for key := range stored {
		t.Errorf("%s is in the database and not in the build", key)
	}
}

// TestTheApplicationRoleCannotRewriteAPromptOrDeleteARecord.
//
// The grants, tested as the role the deployment actually connects as — which is the gap migration
// 00051 was written about: every other database test in this repository connects as the schema
// owner, so a privilege defect can survive the whole suite.
func TestTheApplicationRoleCannotRewriteAPromptOrDeleteARecord(t *testing.T) {
	h := newHarness(t)
	app := h.OpenAs(t, "dthcms_app_local", "dthcms_local_only")

	for name, statement := range map[string]string{
		"rewrite a deployed prompt":       `UPDATE core.ai_prompt_version SET content = 'x'`,
		"delete a deployed prompt":        `DELETE FROM core.ai_prompt_version`,
		"delete an interaction":           `DELETE FROM core.ai_interaction`,
		"delete a synthetic register row": `DELETE FROM core.ai_synthetic_subject`,
		"rewrite a budget alert":          `UPDATE core.ai_budget_alert SET threshold_percent = 1`,
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := app.Exec(statement); err == nil {
				t.Errorf("the application was allowed to %s", name)
			}
		})
	}
}

// --- the circuit breaker and the fallback, end to end ---

func TestAnOpenCircuitIsRecordedRatherThanRetriedForever(t *testing.T) {
	h := newHarness(t)
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		return ai.ProviderResponse{}, fmt.Errorf("%w: down", ai.ErrProviderUnavailable)
	}
	gateway := h.gateway(t, config.TierPaid, config.EnvProduction)
	ctx := context.Background()

	// gateway.echo allows three attempts, so the first invocation alone trips a three-failure
	// breaker. The second invocation must not reach the provider at all.
	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"n": 1})); err == nil {
		t.Fatal("a provider outage was reported as success")
	}
	var calls int
	h.provider.Respond = func(ai.ProviderRequest) (ai.ProviderResponse, error) {
		calls++
		return ai.ProviderResponse{}, fmt.Errorf("%w: down", ai.ErrProviderUnavailable)
	}
	if _, err := gateway.Invoke(ctx, h.request(h.realPatient, map[string]any{"n": 2})); err == nil {
		t.Fatal("the second call was reported as success")
	}
	if calls != 0 {
		t.Errorf("the provider was contacted %d times through an open circuit", calls)
	}
	if row := h.latest(t); row.Status != "CIRCUIT_OPEN" {
		t.Errorf("status = %q, want CIRCUIT_OPEN — the fast failure is what lets D-15's degraded "+
			"mode appear before the consultation rather than five minutes into it", row.Status)
	}
}
