// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: alert.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const alertByID = `-- name: AlertByID :one
SELECT a.id, a.facility_id, a.patient_id, a.visit_id, a.observation_id, a.code, a.value_num, a.unit, a.rule_id, a.breached, a.threshold, a.action_en, a.action_bn, a.raised_at, a.raised_by, a.raised_role, a.station_code, a.status, a.acknowledged_by, a.acknowledged_at, a.acknowledgement, a.escalation_step, a.escalated_at, a.notified_at, a.recipients, a.delivery_error, a.event_id, a.global_seq, c.display_en, c.display_bn FROM read.critical_alert a
  JOIN core.observation_code c ON c.code = a.code
 WHERE a.id = $1 AND a.facility_id = $2
`

type AlertByIDParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type AlertByIDRow struct {
	ReadCriticalAlert ReadCriticalAlert
	DisplayEn         string
	DisplayBn         string
}

func (q *Queries) AlertByID(ctx context.Context, arg AlertByIDParams) (AlertByIDRow, error) {
	row := q.db.QueryRow(ctx, alertByID, arg.ID, arg.FacilityID)
	var i AlertByIDRow
	err := row.Scan(
		&i.ReadCriticalAlert.ID,
		&i.ReadCriticalAlert.FacilityID,
		&i.ReadCriticalAlert.PatientID,
		&i.ReadCriticalAlert.VisitID,
		&i.ReadCriticalAlert.ObservationID,
		&i.ReadCriticalAlert.Code,
		&i.ReadCriticalAlert.ValueNum,
		&i.ReadCriticalAlert.Unit,
		&i.ReadCriticalAlert.RuleID,
		&i.ReadCriticalAlert.Breached,
		&i.ReadCriticalAlert.Threshold,
		&i.ReadCriticalAlert.ActionEn,
		&i.ReadCriticalAlert.ActionBn,
		&i.ReadCriticalAlert.RaisedAt,
		&i.ReadCriticalAlert.RaisedBy,
		&i.ReadCriticalAlert.RaisedRole,
		&i.ReadCriticalAlert.StationCode,
		&i.ReadCriticalAlert.Status,
		&i.ReadCriticalAlert.AcknowledgedBy,
		&i.ReadCriticalAlert.AcknowledgedAt,
		&i.ReadCriticalAlert.Acknowledgement,
		&i.ReadCriticalAlert.EscalationStep,
		&i.ReadCriticalAlert.EscalatedAt,
		&i.ReadCriticalAlert.NotifiedAt,
		&i.ReadCriticalAlert.Recipients,
		&i.ReadCriticalAlert.DeliveryError,
		&i.ReadCriticalAlert.EventID,
		&i.ReadCriticalAlert.GlobalSeq,
		&i.DisplayEn,
		&i.DisplayBn,
	)
	return i, err
}

const alertsDueForEscalation = `-- name: AlertsDueForEscalation :many
SELECT a.id, a.facility_id, a.patient_id, a.visit_id, a.observation_id, a.code, a.value_num, a.unit, a.rule_id, a.breached, a.threshold, a.action_en, a.action_bn, a.raised_at, a.raised_by, a.raised_role, a.station_code, a.status, a.acknowledged_by, a.acknowledged_at, a.acknowledgement, a.escalation_step, a.escalated_at, a.notified_at, a.recipients, a.delivery_error, a.event_id, a.global_seq, c.display_en, c.display_bn,
       s.step_number AS next_step, s.notify_role AS next_role,
       s.note_en AS next_note_en, s.note_bn AS next_note_bn
  FROM read.critical_alert a
  JOIN core.observation_code c ON c.code = a.code
  JOIN core.escalation_step s ON s.step_number = a.escalation_step + 1
 WHERE a.status = 'OPEN'
   AND a.raised_at + make_interval(secs => s.after_seconds) <= $1::timestamptz
 ORDER BY a.raised_at
 LIMIT $2::int
`

type AlertsDueForEscalationParams struct {
	Now       time.Time
	MaxAlerts int32
}

type AlertsDueForEscalationRow struct {
	ReadCriticalAlert ReadCriticalAlert
	DisplayEn         string
	DisplayBn         string
	NextStep          int32
	NextRole          *string
	NextNoteEn        string
	NextNoteBn        string
}

// Open alerts whose current step has been standing longer than the next step's window.
//
// The whole sweep in one statement, and deliberately so: the alternative is the worker
// reading every open alert and doing the arithmetic in Go, which is the same arithmetic in
// a second place, running against a clock that is not the database's.
func (q *Queries) AlertsDueForEscalation(ctx context.Context, arg AlertsDueForEscalationParams) ([]AlertsDueForEscalationRow, error) {
	rows, err := q.db.Query(ctx, alertsDueForEscalation, arg.Now, arg.MaxAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertsDueForEscalationRow{}
	for rows.Next() {
		var i AlertsDueForEscalationRow
		if err := rows.Scan(
			&i.ReadCriticalAlert.ID,
			&i.ReadCriticalAlert.FacilityID,
			&i.ReadCriticalAlert.PatientID,
			&i.ReadCriticalAlert.VisitID,
			&i.ReadCriticalAlert.ObservationID,
			&i.ReadCriticalAlert.Code,
			&i.ReadCriticalAlert.ValueNum,
			&i.ReadCriticalAlert.Unit,
			&i.ReadCriticalAlert.RuleID,
			&i.ReadCriticalAlert.Breached,
			&i.ReadCriticalAlert.Threshold,
			&i.ReadCriticalAlert.ActionEn,
			&i.ReadCriticalAlert.ActionBn,
			&i.ReadCriticalAlert.RaisedAt,
			&i.ReadCriticalAlert.RaisedBy,
			&i.ReadCriticalAlert.RaisedRole,
			&i.ReadCriticalAlert.StationCode,
			&i.ReadCriticalAlert.Status,
			&i.ReadCriticalAlert.AcknowledgedBy,
			&i.ReadCriticalAlert.AcknowledgedAt,
			&i.ReadCriticalAlert.Acknowledgement,
			&i.ReadCriticalAlert.EscalationStep,
			&i.ReadCriticalAlert.EscalatedAt,
			&i.ReadCriticalAlert.NotifiedAt,
			&i.ReadCriticalAlert.Recipients,
			&i.ReadCriticalAlert.DeliveryError,
			&i.ReadCriticalAlert.EventID,
			&i.ReadCriticalAlert.GlobalSeq,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.NextStep,
			&i.NextRole,
			&i.NextNoteEn,
			&i.NextNoteBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const alertsForObservation = `-- name: AlertsForObservation :many
SELECT a.id, a.facility_id, a.patient_id, a.visit_id, a.observation_id, a.code, a.value_num, a.unit, a.rule_id, a.breached, a.threshold, a.action_en, a.action_bn, a.raised_at, a.raised_by, a.raised_role, a.station_code, a.status, a.acknowledged_by, a.acknowledged_at, a.acknowledgement, a.escalation_step, a.escalated_at, a.notified_at, a.recipients, a.delivery_error, a.event_id, a.global_seq, c.display_en, c.display_bn FROM read.critical_alert a
  JOIN core.observation_code c ON c.code = a.code
 WHERE a.observation_id = $1 AND a.facility_id = $2
 ORDER BY a.raised_at
`

type AlertsForObservationParams struct {
	ObservationID uuid.UUID
	FacilityID    uuid.UUID
}

type AlertsForObservationRow struct {
	ReadCriticalAlert ReadCriticalAlert
	DisplayEn         string
	DisplayBn         string
}

// Every alert raised by one recorded value. Normally one; more than one when a value was
// entered, corrected and entered again.
func (q *Queries) AlertsForObservation(ctx context.Context, arg AlertsForObservationParams) ([]AlertsForObservationRow, error) {
	rows, err := q.db.Query(ctx, alertsForObservation, arg.ObservationID, arg.FacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertsForObservationRow{}
	for rows.Next() {
		var i AlertsForObservationRow
		if err := rows.Scan(
			&i.ReadCriticalAlert.ID,
			&i.ReadCriticalAlert.FacilityID,
			&i.ReadCriticalAlert.PatientID,
			&i.ReadCriticalAlert.VisitID,
			&i.ReadCriticalAlert.ObservationID,
			&i.ReadCriticalAlert.Code,
			&i.ReadCriticalAlert.ValueNum,
			&i.ReadCriticalAlert.Unit,
			&i.ReadCriticalAlert.RuleID,
			&i.ReadCriticalAlert.Breached,
			&i.ReadCriticalAlert.Threshold,
			&i.ReadCriticalAlert.ActionEn,
			&i.ReadCriticalAlert.ActionBn,
			&i.ReadCriticalAlert.RaisedAt,
			&i.ReadCriticalAlert.RaisedBy,
			&i.ReadCriticalAlert.RaisedRole,
			&i.ReadCriticalAlert.StationCode,
			&i.ReadCriticalAlert.Status,
			&i.ReadCriticalAlert.AcknowledgedBy,
			&i.ReadCriticalAlert.AcknowledgedAt,
			&i.ReadCriticalAlert.Acknowledgement,
			&i.ReadCriticalAlert.EscalationStep,
			&i.ReadCriticalAlert.EscalatedAt,
			&i.ReadCriticalAlert.NotifiedAt,
			&i.ReadCriticalAlert.Recipients,
			&i.ReadCriticalAlert.DeliveryError,
			&i.ReadCriticalAlert.EventID,
			&i.ReadCriticalAlert.GlobalSeq,
			&i.DisplayEn,
			&i.DisplayBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const alertsForPatient = `-- name: AlertsForPatient :many
SELECT a.id, a.facility_id, a.patient_id, a.visit_id, a.observation_id, a.code, a.value_num, a.unit, a.rule_id, a.breached, a.threshold, a.action_en, a.action_bn, a.raised_at, a.raised_by, a.raised_role, a.station_code, a.status, a.acknowledged_by, a.acknowledged_at, a.acknowledgement, a.escalation_step, a.escalated_at, a.notified_at, a.recipients, a.delivery_error, a.event_id, a.global_seq, c.display_en, c.display_bn FROM read.critical_alert a
  JOIN core.observation_code c ON c.code = a.code
 WHERE a.patient_id = $1 AND a.facility_id = $2
 ORDER BY a.raised_at DESC
 LIMIT $3
`

type AlertsForPatientParams struct {
	PatientID  uuid.UUID
	FacilityID uuid.UUID
	Limit      int32
}

type AlertsForPatientRow struct {
	ReadCriticalAlert ReadCriticalAlert
	DisplayEn         string
	DisplayBn         string
}

// One patient's alert history, acknowledged ones included. What a physician reads before
// deciding whether today's reading is the first of its kind.
func (q *Queries) AlertsForPatient(ctx context.Context, arg AlertsForPatientParams) ([]AlertsForPatientRow, error) {
	rows, err := q.db.Query(ctx, alertsForPatient, arg.PatientID, arg.FacilityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertsForPatientRow{}
	for rows.Next() {
		var i AlertsForPatientRow
		if err := rows.Scan(
			&i.ReadCriticalAlert.ID,
			&i.ReadCriticalAlert.FacilityID,
			&i.ReadCriticalAlert.PatientID,
			&i.ReadCriticalAlert.VisitID,
			&i.ReadCriticalAlert.ObservationID,
			&i.ReadCriticalAlert.Code,
			&i.ReadCriticalAlert.ValueNum,
			&i.ReadCriticalAlert.Unit,
			&i.ReadCriticalAlert.RuleID,
			&i.ReadCriticalAlert.Breached,
			&i.ReadCriticalAlert.Threshold,
			&i.ReadCriticalAlert.ActionEn,
			&i.ReadCriticalAlert.ActionBn,
			&i.ReadCriticalAlert.RaisedAt,
			&i.ReadCriticalAlert.RaisedBy,
			&i.ReadCriticalAlert.RaisedRole,
			&i.ReadCriticalAlert.StationCode,
			&i.ReadCriticalAlert.Status,
			&i.ReadCriticalAlert.AcknowledgedBy,
			&i.ReadCriticalAlert.AcknowledgedAt,
			&i.ReadCriticalAlert.Acknowledgement,
			&i.ReadCriticalAlert.EscalationStep,
			&i.ReadCriticalAlert.EscalatedAt,
			&i.ReadCriticalAlert.NotifiedAt,
			&i.ReadCriticalAlert.Recipients,
			&i.ReadCriticalAlert.DeliveryError,
			&i.ReadCriticalAlert.EventID,
			&i.ReadCriticalAlert.GlobalSeq,
			&i.DisplayEn,
			&i.DisplayBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criticalValueRuleFor = `-- name: CriticalValueRuleFor :one
SELECT id, code, sex, min_age_years, max_age_years, low, high, action_en, action_bn, approved_by, approved_at, updated_at FROM core.critical_value_for($1::text, $2::text, $3::numeric)
`

type CriticalValueRuleForParams struct {
	PCode     string
	PSex      string
	PAgeYears pgtype.Numeric
}

// The rule that applies to one patient and one code, resolved by the database.
func (q *Queries) CriticalValueRuleFor(ctx context.Context, arg CriticalValueRuleForParams) (CoreCriticalValueRule, error) {
	row := q.db.QueryRow(ctx, criticalValueRuleFor, arg.PCode, arg.PSex, arg.PAgeYears)
	var i CoreCriticalValueRule
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Sex,
		&i.MinAgeYears,
		&i.MaxAgeYears,
		&i.Low,
		&i.High,
		&i.ActionEn,
		&i.ActionBn,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const criticalValueRules = `-- name: CriticalValueRules :many

SELECT id, code, sex, min_age_years, max_age_years, low, high, action_en, action_bn, approved_by, approved_at, updated_at FROM core.critical_value_rule
 ORDER BY code,
          num_nonnulls(sex, min_age_years, max_age_years) DESC,
          coalesce(max_age_years, 200) - coalesce(min_age_years, 0),
          updated_at
`

// Critical values and their escalation (CP50).
// Every rule, for a station app to evaluate locally so the alarm sounds in the operator's
// hand at the instant they type, not after a round trip they may not have signal for.
//
// **Ordered most specific first, in exactly the order core.critical_value_for resolves.**
// The same trick as the plausibility rules and the reference ranges: the client's rule is
// "the first entry whose predicate matches", and it never ranks anything itself. A phone
// that ranked them could sound an alarm the server did not raise — or, far worse, stay
// quiet when the server did.
func (q *Queries) CriticalValueRules(ctx context.Context) ([]CoreCriticalValueRule, error) {
	rows, err := q.db.Query(ctx, criticalValueRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreCriticalValueRule{}
	for rows.Next() {
		var i CoreCriticalValueRule
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Sex,
			&i.MinAgeYears,
			&i.MaxAgeYears,
			&i.Low,
			&i.High,
			&i.ActionEn,
			&i.ActionBn,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const escalationChain = `-- name: EscalationChain :many
SELECT step_number, after_seconds, notify_role, note_en, note_bn, approved_by, approved_at, updated_at FROM core.escalation_step ORDER BY step_number
`

// The chain, in order. Read by the worker on every sweep rather than cached: an escalation
// window edited at nine o'clock should apply to the alert raised at nine-oh-one.
func (q *Queries) EscalationChain(ctx context.Context) ([]CoreEscalationStep, error) {
	rows, err := q.db.Query(ctx, escalationChain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreEscalationStep{}
	for rows.Next() {
		var i CoreEscalationStep
		if err := rows.Scan(
			&i.StepNumber,
			&i.AfterSeconds,
			&i.NotifyRole,
			&i.NoteEn,
			&i.NoteBn,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationAnswers = `-- name: ObservationAnswers :many
SELECT code, value_code, display_en, display_bn, ordering, is_normal, retired_at FROM core.observation_answer
 WHERE retired_at IS NULL
 ORDER BY code, ordering
`

// Every vocabulary, in clinical order. Whole rather than per code: the examination screen
// needs eleven of these the moment the patient sits down, and eleven round trips on a clinic
// connection is the difference between a two-minute examination and a five-minute one.
func (q *Queries) ObservationAnswers(ctx context.Context) ([]CoreObservationAnswer, error) {
	rows, err := q.db.Query(ctx, observationAnswers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreObservationAnswer{}
	for rows.Next() {
		var i CoreObservationAnswer
		if err := rows.Scan(
			&i.Code,
			&i.ValueCode,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.Ordering,
			&i.IsNormal,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAlerts = `-- name: OpenAlerts :many
SELECT a.id, a.facility_id, a.patient_id, a.visit_id, a.observation_id, a.code, a.value_num, a.unit, a.rule_id, a.breached, a.threshold, a.action_en, a.action_bn, a.raised_at, a.raised_by, a.raised_role, a.station_code, a.status, a.acknowledged_by, a.acknowledged_at, a.acknowledgement, a.escalation_step, a.escalated_at, a.notified_at, a.recipients, a.delivery_error, a.event_id, a.global_seq, c.display_en, c.display_bn FROM read.critical_alert a
  JOIN core.observation_code c ON c.code = a.code
 WHERE a.facility_id = $1 AND a.status = 'OPEN'
 ORDER BY a.raised_at DESC
 LIMIT $2
`

type OpenAlertsParams struct {
	FacilityID uuid.UUID
	Limit      int32
}

type OpenAlertsRow struct {
	ReadCriticalAlert ReadCriticalAlert
	DisplayEn         string
	DisplayBn         string
}

// The consultant's priority surface: everything unacknowledged in this facility, newest
// first. Small by construction — an alert list long enough to need paging is a clinic in
// trouble, and the answer to that is not pagination.
//
// The display names are joined rather than left to the client. An alert is a message, and a
// message that says "SPO2 88" makes whoever reads it look the code up; one that says "Oxygen
// saturation" does not. The registry is the only place those names live (CP42), so this is a
// join rather than a copy.
func (q *Queries) OpenAlerts(ctx context.Context, arg OpenAlertsParams) ([]OpenAlertsRow, error) {
	rows, err := q.db.Query(ctx, openAlerts, arg.FacilityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenAlertsRow{}
	for rows.Next() {
		var i OpenAlertsRow
		if err := rows.Scan(
			&i.ReadCriticalAlert.ID,
			&i.ReadCriticalAlert.FacilityID,
			&i.ReadCriticalAlert.PatientID,
			&i.ReadCriticalAlert.VisitID,
			&i.ReadCriticalAlert.ObservationID,
			&i.ReadCriticalAlert.Code,
			&i.ReadCriticalAlert.ValueNum,
			&i.ReadCriticalAlert.Unit,
			&i.ReadCriticalAlert.RuleID,
			&i.ReadCriticalAlert.Breached,
			&i.ReadCriticalAlert.Threshold,
			&i.ReadCriticalAlert.ActionEn,
			&i.ReadCriticalAlert.ActionBn,
			&i.ReadCriticalAlert.RaisedAt,
			&i.ReadCriticalAlert.RaisedBy,
			&i.ReadCriticalAlert.RaisedRole,
			&i.ReadCriticalAlert.StationCode,
			&i.ReadCriticalAlert.Status,
			&i.ReadCriticalAlert.AcknowledgedBy,
			&i.ReadCriticalAlert.AcknowledgedAt,
			&i.ReadCriticalAlert.Acknowledgement,
			&i.ReadCriticalAlert.EscalationStep,
			&i.ReadCriticalAlert.EscalatedAt,
			&i.ReadCriticalAlert.NotifiedAt,
			&i.ReadCriticalAlert.Recipients,
			&i.ReadCriticalAlert.DeliveryError,
			&i.ReadCriticalAlert.EventID,
			&i.ReadCriticalAlert.GlobalSeq,
			&i.DisplayEn,
			&i.DisplayBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
