// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acknowledgeAdminAlert = `-- name: AcknowledgeAdminAlert :one
UPDATE core.admin_alert
   SET acknowledged_by = $2, acknowledged_at = $3
 WHERE id = $1 AND facility_id = $4 AND acknowledged_at IS NULL
RETURNING id, facility_id, kind, severity, message_en, message_bn, reference, audit_seq, created_at, acknowledged_by, acknowledged_at
`

type AcknowledgeAdminAlertParams struct {
	ID             uuid.UUID
	AcknowledgedBy uuid.NullUUID
	AcknowledgedAt *time.Time
	FacilityID     uuid.UUID
}

func (q *Queries) AcknowledgeAdminAlert(ctx context.Context, arg AcknowledgeAdminAlertParams) (CoreAdminAlert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAdminAlert,
		arg.ID,
		arg.AcknowledgedBy,
		arg.AcknowledgedAt,
		arg.FacilityID,
	)
	var i CoreAdminAlert
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Kind,
		&i.Severity,
		&i.MessageEn,
		&i.MessageBn,
		&i.Reference,
		&i.AuditSeq,
		&i.CreatedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
	)
	return i, err
}

const acknowledgeBreakGlass = `-- name: AcknowledgeBreakGlass :one
UPDATE core.break_glass_access
   SET acknowledged_by = $2, acknowledged_at = $3
 WHERE id = $1 AND acknowledged_at IS NULL
RETURNING id, facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at, ended_at, ended_by, end_reason, acknowledged_by, acknowledged_at, audit_seq
`

type AcknowledgeBreakGlassParams struct {
	ID             uuid.UUID
	AcknowledgedBy uuid.NullUUID
	AcknowledgedAt *time.Time
}

func (q *Queries) AcknowledgeBreakGlass(ctx context.Context, arg AcknowledgeBreakGlassParams) (CoreBreakGlassAccess, error) {
	row := q.db.QueryRow(ctx, acknowledgeBreakGlass, arg.ID, arg.AcknowledgedBy, arg.AcknowledgedAt)
	var i CoreBreakGlassAccess
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.UserID,
		&i.ActiveRole,
		&i.ScopeKind,
		&i.ScopeRef,
		&i.Justification,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AuditSeq,
	)
	return i, err
}

const activeBreakGlass = `-- name: ActiveBreakGlass :many
SELECT id, facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at, ended_at, ended_by, end_reason, acknowledged_by, acknowledged_at, audit_seq FROM core.break_glass_access
 WHERE facility_id = $1 AND ended_at IS NULL AND expires_at > $2
 ORDER BY granted_at DESC
`

type ActiveBreakGlassParams struct {
	FacilityID uuid.UUID
	ExpiresAt  time.Time
}

func (q *Queries) ActiveBreakGlass(ctx context.Context, arg ActiveBreakGlassParams) ([]CoreBreakGlassAccess, error) {
	rows, err := q.db.Query(ctx, activeBreakGlass, arg.FacilityID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreBreakGlassAccess{}
	for rows.Next() {
		var i CoreBreakGlassAccess
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.UserID,
			&i.ActiveRole,
			&i.ScopeKind,
			&i.ScopeRef,
			&i.Justification,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.EndReason,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.AuditSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO ledger.audit_event (
  seq, facility_id, kind, actor_user_id, actor_code, actor_role,
  target_user_id, target_code, patient_id, device_id, session_id,
  reason, details, client_digest, recorded_at, prev_hash, hash
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING seq, facility_id, kind, actor_user_id, actor_code, actor_role, target_user_id, target_code, patient_id, device_id, session_id, reason, details, client_digest, recorded_at, prev_hash, hash
`

type AppendAuditEventParams struct {
	Seq          int64
	FacilityID   uuid.UUID
	Kind         string
	ActorUserID  uuid.NullUUID
	ActorCode    string
	ActorRole    string
	TargetUserID uuid.NullUUID
	TargetCode   string
	PatientID    uuid.NullUUID
	DeviceID     uuid.NullUUID
	SessionID    uuid.NullUUID
	Reason       string
	Details      []byte
	ClientDigest []byte
	RecordedAt   time.Time
	PrevHash     []byte
	Hash         []byte
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (LedgerAuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.Seq,
		arg.FacilityID,
		arg.Kind,
		arg.ActorUserID,
		arg.ActorCode,
		arg.ActorRole,
		arg.TargetUserID,
		arg.TargetCode,
		arg.PatientID,
		arg.DeviceID,
		arg.SessionID,
		arg.Reason,
		arg.Details,
		arg.ClientDigest,
		arg.RecordedAt,
		arg.PrevHash,
		arg.Hash,
	)
	var i LedgerAuditEvent
	err := row.Scan(
		&i.Seq,
		&i.FacilityID,
		&i.Kind,
		&i.ActorUserID,
		&i.ActorCode,
		&i.ActorRole,
		&i.TargetUserID,
		&i.TargetCode,
		&i.PatientID,
		&i.DeviceID,
		&i.SessionID,
		&i.Reason,
		&i.Details,
		&i.ClientDigest,
		&i.RecordedAt,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const auditDefaultPartitionCount = `-- name: AuditDefaultPartitionCount :one
SELECT count(*) FROM ledger.audit_event_default
`

// Rows that landed in the safety-net partition: zero unless somebody forgot the monthly
// partitions. The verifier reports it.
func (q *Queries) AuditDefaultPartitionCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, auditDefaultPartitionCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditEventCount = `-- name: AuditEventCount :one
SELECT count(*) FROM ledger.audit_event
`

func (q *Queries) AuditEventCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, auditEventCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditEventsFrom = `-- name: AuditEventsFrom :many
SELECT seq, facility_id, kind, actor_user_id, actor_code, actor_role, target_user_id, target_code, patient_id, device_id, session_id, reason, details, client_digest, recorded_at, prev_hash, hash FROM ledger.audit_event WHERE seq >= $1 ORDER BY seq ASC LIMIT $2
`

type AuditEventsFromParams struct {
	Seq   int64
	Limit int32
}

// The verifier walks the chain forwards in slices.
func (q *Queries) AuditEventsFrom(ctx context.Context, arg AuditEventsFromParams) ([]LedgerAuditEvent, error) {
	rows, err := q.db.Query(ctx, auditEventsFrom, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAuditEvent{}
	for rows.Next() {
		var i LedgerAuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.FacilityID,
			&i.Kind,
			&i.ActorUserID,
			&i.ActorCode,
			&i.ActorRole,
			&i.TargetUserID,
			&i.TargetCode,
			&i.PatientID,
			&i.DeviceID,
			&i.SessionID,
			&i.Reason,
			&i.Details,
			&i.ClientDigest,
			&i.RecordedAt,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditEventsPage = `-- name: AuditEventsPage :many
SELECT seq, facility_id, kind, actor_user_id, actor_code, actor_role, target_user_id, target_code, patient_id, device_id, session_id, reason, details, client_digest, recorded_at, prev_hash, hash FROM ledger.audit_event
 WHERE facility_id = $1
   AND ($3::bigint IS NULL OR seq < $3)
   AND ($4::text IS NULL OR kind = $4)
   AND ($5::text IS NULL OR actor_code = $5)
   AND ($6::text IS NULL
        OR actor_code = $6 OR target_code = $6)
   AND ($7::uuid IS NULL OR patient_id = $7)
   AND ($8::timestamptz IS NULL OR recorded_at >= $8)
   AND ($9::timestamptz IS NULL OR recorded_at < $9)
 ORDER BY seq DESC
 LIMIT $2
`

type AuditEventsPageParams struct {
	FacilityID  uuid.UUID
	Limit       int32
	Before      *int64
	Kind        *string
	ActorCode   *string
	SubjectCode *string
	PatientID   uuid.NullUUID
	Since       *time.Time
	Until       *time.Time
}

// The viewer's query: newest first, filtered by whatever the person narrowed to. A NULL
// filter means "any". `before` is the seq cursor for the next page.
func (q *Queries) AuditEventsPage(ctx context.Context, arg AuditEventsPageParams) ([]LedgerAuditEvent, error) {
	rows, err := q.db.Query(ctx, auditEventsPage,
		arg.FacilityID,
		arg.Limit,
		arg.Before,
		arg.Kind,
		arg.ActorCode,
		arg.SubjectCode,
		arg.PatientID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAuditEvent{}
	for rows.Next() {
		var i LedgerAuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.FacilityID,
			&i.Kind,
			&i.ActorUserID,
			&i.ActorCode,
			&i.ActorRole,
			&i.TargetUserID,
			&i.TargetCode,
			&i.PatientID,
			&i.DeviceID,
			&i.SessionID,
			&i.Reason,
			&i.Details,
			&i.ClientDigest,
			&i.RecordedAt,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditHead = `-- name: AuditHead :one

SELECT seq, hash FROM ledger.audit_event ORDER BY seq DESC LIMIT 1
`

type AuditHeadRow struct {
	Seq  int64
	Hash []byte
}

// The audit chain (CP22). Append and read; the schema forbids anything else.
// The last link, for the recorder to chain onto. Called under the advisory lock.
func (q *Queries) AuditHead(ctx context.Context) (AuditHeadRow, error) {
	row := q.db.QueryRow(ctx, auditHead)
	var i AuditHeadRow
	err := row.Scan(&i.Seq, &i.Hash)
	return i, err
}

const breakGlassByID = `-- name: BreakGlassByID :one
SELECT id, facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at, ended_at, ended_by, end_reason, acknowledged_by, acknowledged_at, audit_seq FROM core.break_glass_access WHERE id = $1
`

func (q *Queries) BreakGlassByID(ctx context.Context, id uuid.UUID) (CoreBreakGlassAccess, error) {
	row := q.db.QueryRow(ctx, breakGlassByID, id)
	var i CoreBreakGlassAccess
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.UserID,
		&i.ActiveRole,
		&i.ScopeKind,
		&i.ScopeRef,
		&i.Justification,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AuditSeq,
	)
	return i, err
}

const breakGlassForUser = `-- name: BreakGlassForUser :many
SELECT id, facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at, ended_at, ended_by, end_reason, acknowledged_by, acknowledged_at, audit_seq FROM core.break_glass_access
 WHERE user_id = $1 AND ended_at IS NULL AND expires_at > $2
 ORDER BY granted_at DESC
`

type BreakGlassForUserParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

// What a person currently holds through the glass: the clinical checkpoints ask this.
func (q *Queries) BreakGlassForUser(ctx context.Context, arg BreakGlassForUserParams) ([]CoreBreakGlassAccess, error) {
	rows, err := q.db.Query(ctx, breakGlassForUser, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreBreakGlassAccess{}
	for rows.Next() {
		var i CoreBreakGlassAccess
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.UserID,
			&i.ActiveRole,
			&i.ScopeKind,
			&i.ScopeRef,
			&i.Justification,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.EndReason,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.AuditSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endBreakGlass = `-- name: EndBreakGlass :one
UPDATE core.break_glass_access
   SET ended_at = $2, ended_by = $3, end_reason = $4
 WHERE id = $1 AND ended_at IS NULL
RETURNING id, facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at, ended_at, ended_by, end_reason, acknowledged_by, acknowledged_at, audit_seq
`

type EndBreakGlassParams struct {
	ID        uuid.UUID
	EndedAt   *time.Time
	EndedBy   uuid.NullUUID
	EndReason string
}

func (q *Queries) EndBreakGlass(ctx context.Context, arg EndBreakGlassParams) (CoreBreakGlassAccess, error) {
	row := q.db.QueryRow(ctx, endBreakGlass,
		arg.ID,
		arg.EndedAt,
		arg.EndedBy,
		arg.EndReason,
	)
	var i CoreBreakGlassAccess
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.UserID,
		&i.ActiveRole,
		&i.ScopeKind,
		&i.ScopeRef,
		&i.Justification,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AuditSeq,
	)
	return i, err
}

const linkBreakGlassAudit = `-- name: LinkBreakGlassAudit :exec
UPDATE core.break_glass_access SET audit_seq = $2 WHERE id = $1
`

type LinkBreakGlassAuditParams struct {
	ID       uuid.UUID
	AuditSeq *int64
}

func (q *Queries) LinkBreakGlassAudit(ctx context.Context, arg LinkBreakGlassAuditParams) error {
	_, err := q.db.Exec(ctx, linkBreakGlassAudit, arg.ID, arg.AuditSeq)
	return err
}

const openAdminAlerts = `-- name: OpenAdminAlerts :many
SELECT id, facility_id, kind, severity, message_en, message_bn, reference, audit_seq, created_at, acknowledged_by, acknowledged_at FROM core.admin_alert
 WHERE facility_id = $1 AND acknowledged_at IS NULL
 ORDER BY created_at DESC
 LIMIT $2
`

type OpenAdminAlertsParams struct {
	FacilityID uuid.UUID
	Limit      int32
}

func (q *Queries) OpenAdminAlerts(ctx context.Context, arg OpenAdminAlertsParams) ([]CoreAdminAlert, error) {
	rows, err := q.db.Query(ctx, openAdminAlerts, arg.FacilityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreAdminAlert{}
	for rows.Next() {
		var i CoreAdminAlert
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Kind,
			&i.Severity,
			&i.MessageEn,
			&i.MessageBn,
			&i.Reference,
			&i.AuditSeq,
			&i.CreatedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openBreakGlass = `-- name: OpenBreakGlass :one
INSERT INTO core.break_glass_access (
  facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, facility_id, user_id, active_role, scope_kind, scope_ref, justification, granted_at, expires_at, ended_at, ended_by, end_reason, acknowledged_by, acknowledged_at, audit_seq
`

type OpenBreakGlassParams struct {
	FacilityID    uuid.UUID
	UserID        uuid.UUID
	ActiveRole    string
	ScopeKind     string
	ScopeRef      string
	Justification string
	GrantedAt     time.Time
	ExpiresAt     time.Time
}

func (q *Queries) OpenBreakGlass(ctx context.Context, arg OpenBreakGlassParams) (CoreBreakGlassAccess, error) {
	row := q.db.QueryRow(ctx, openBreakGlass,
		arg.FacilityID,
		arg.UserID,
		arg.ActiveRole,
		arg.ScopeKind,
		arg.ScopeRef,
		arg.Justification,
		arg.GrantedAt,
		arg.ExpiresAt,
	)
	var i CoreBreakGlassAccess
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.UserID,
		&i.ActiveRole,
		&i.ScopeKind,
		&i.ScopeRef,
		&i.Justification,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AuditSeq,
	)
	return i, err
}

const raiseAdminAlert = `-- name: RaiseAdminAlert :one
INSERT INTO core.admin_alert (facility_id, kind, severity, message_en, message_bn, reference, audit_seq, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, facility_id, kind, severity, message_en, message_bn, reference, audit_seq, created_at, acknowledged_by, acknowledged_at
`

type RaiseAdminAlertParams struct {
	FacilityID uuid.UUID
	Kind       string
	Severity   string
	MessageEn  string
	MessageBn  string
	Reference  []byte
	AuditSeq   *int64
	CreatedAt  time.Time
}

func (q *Queries) RaiseAdminAlert(ctx context.Context, arg RaiseAdminAlertParams) (CoreAdminAlert, error) {
	row := q.db.QueryRow(ctx, raiseAdminAlert,
		arg.FacilityID,
		arg.Kind,
		arg.Severity,
		arg.MessageEn,
		arg.MessageBn,
		arg.Reference,
		arg.AuditSeq,
		arg.CreatedAt,
	)
	var i CoreAdminAlert
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Kind,
		&i.Severity,
		&i.MessageEn,
		&i.MessageBn,
		&i.Reference,
		&i.AuditSeq,
		&i.CreatedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
	)
	return i, err
}
