// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: correction.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const correctionReasons = `-- name: CorrectionReasons :many

SELECT code, display_en, display_bn, is_transcription, ordering
  FROM core.correction_reason
 WHERE retired_at IS NULL
 ORDER BY ordering
`

type CorrectionReasonsRow struct {
	Code            string
	DisplayEn       string
	DisplayBn       string
	IsTranscription bool
	Ordering        int32
}

// The correction workflow (CP62).
func (q *Queries) CorrectionReasons(ctx context.Context) ([]CorrectionReasonsRow, error) {
	rows, err := q.db.Query(ctx, correctionReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionReasonsRow{}
	for rows.Next() {
		var i CorrectionReasonsRow
		if err := rows.Scan(
			&i.Code,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.IsTranscription,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctionRequestByID = `-- name: CorrectionRequestByID :one
SELECT r.id, r.facility_id, r.patient_id, r.visit_id, r.observation_id, r.code,
       r.requested_at, r.requested_by, r.requested_role,
       r.reason_code, r.note, r.assigned_to, r.status,
       r.resolved_at, r.resolved_by, r.resolved_role, r.resolution_note, r.replacement_id,
       r.recomputed,
       coalesce(q.employee_code, '') AS requested_by_code,
       coalesce(q.name_en, '')       AS requested_by_name_en,
       coalesce(q.name_bn, '')       AS requested_by_name_bn,
       coalesce(a.employee_code, '') AS assigned_to_code,
       coalesce(a.name_en, '')       AS assigned_to_name_en,
       coalesce(a.name_bn, '')       AS assigned_to_name_bn
  FROM read.correction_request r
  LEFT JOIN core.app_user q ON q.id = r.requested_by
  LEFT JOIN core.app_user a ON a.id = r.assigned_to
 WHERE r.id = $1 AND r.facility_id = $2
`

type CorrectionRequestByIDParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type CorrectionRequestByIDRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	PatientID         uuid.UUID
	VisitID           uuid.NullUUID
	ObservationID     uuid.UUID
	Code              string
	RequestedAt       time.Time
	RequestedBy       uuid.UUID
	RequestedRole     string
	ReasonCode        string
	Note              string
	AssignedTo        uuid.UUID
	Status            string
	ResolvedAt        *time.Time
	ResolvedBy        uuid.NullUUID
	ResolvedRole      string
	ResolutionNote    string
	ReplacementID     uuid.NullUUID
	Recomputed        []string
	RequestedByCode   string
	RequestedByNameEn string
	RequestedByNameBn string
	AssignedToCode    string
	AssignedToNameEn  string
	AssignedToNameBn  string
}

func (q *Queries) CorrectionRequestByID(ctx context.Context, arg CorrectionRequestByIDParams) (CorrectionRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, correctionRequestByID, arg.ID, arg.FacilityID)
	var i CorrectionRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.PatientID,
		&i.VisitID,
		&i.ObservationID,
		&i.Code,
		&i.RequestedAt,
		&i.RequestedBy,
		&i.RequestedRole,
		&i.ReasonCode,
		&i.Note,
		&i.AssignedTo,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.ResolvedRole,
		&i.ResolutionNote,
		&i.ReplacementID,
		&i.Recomputed,
		&i.RequestedByCode,
		&i.RequestedByNameEn,
		&i.RequestedByNameBn,
		&i.AssignedToCode,
		&i.AssignedToNameEn,
		&i.AssignedToNameBn,
	)
	return i, err
}

const correctionRequestsForOperator = `-- name: CorrectionRequestsForOperator :many
SELECT r.id, r.facility_id, r.patient_id, r.visit_id, r.observation_id, r.code,
       r.requested_at, r.requested_by, r.requested_role,
       r.reason_code, r.note, r.assigned_to, r.status,
       r.resolved_at, r.resolved_by, r.resolved_role, r.resolution_note, r.replacement_id,
       r.recomputed,
       coalesce(q.employee_code, '') AS requested_by_code,
       coalesce(q.name_en, '')       AS requested_by_name_en,
       coalesce(q.name_bn, '')       AS requested_by_name_bn,
       coalesce(a.employee_code, '') AS assigned_to_code,
       coalesce(a.name_en, '')       AS assigned_to_name_en,
       coalesce(a.name_bn, '')       AS assigned_to_name_bn
  FROM read.correction_request r
  LEFT JOIN core.app_user q ON q.id = r.requested_by
  LEFT JOIN core.app_user a ON a.id = r.assigned_to
 WHERE r.facility_id = $1 AND r.assigned_to = $2
   AND ($3::bool IS FALSE OR r.status = 'OPEN')
 ORDER BY r.requested_at
 LIMIT $4
`

type CorrectionRequestsForOperatorParams struct {
	FacilityID uuid.UUID
	AssignedTo uuid.UUID
	Column3    bool
	Limit      int32
}

type CorrectionRequestsForOperatorRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	PatientID         uuid.UUID
	VisitID           uuid.NullUUID
	ObservationID     uuid.UUID
	Code              string
	RequestedAt       time.Time
	RequestedBy       uuid.UUID
	RequestedRole     string
	ReasonCode        string
	Note              string
	AssignedTo        uuid.UUID
	Status            string
	ResolvedAt        *time.Time
	ResolvedBy        uuid.NullUUID
	ResolvedRole      string
	ResolutionNote    string
	ReplacementID     uuid.NullUUID
	Recomputed        []string
	RequestedByCode   string
	RequestedByNameEn string
	RequestedByNameBn string
	AssignedToCode    string
	AssignedToNameEn  string
	AssignedToNameBn  string
}

// What an operator's own device asks: "what am I being asked to fix". Open ones only, oldest
// first — a queue answered newest-first is a queue where the oldest request is never answered.
func (q *Queries) CorrectionRequestsForOperator(ctx context.Context, arg CorrectionRequestsForOperatorParams) ([]CorrectionRequestsForOperatorRow, error) {
	rows, err := q.db.Query(ctx, correctionRequestsForOperator,
		arg.FacilityID,
		arg.AssignedTo,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionRequestsForOperatorRow{}
	for rows.Next() {
		var i CorrectionRequestsForOperatorRow
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.PatientID,
			&i.VisitID,
			&i.ObservationID,
			&i.Code,
			&i.RequestedAt,
			&i.RequestedBy,
			&i.RequestedRole,
			&i.ReasonCode,
			&i.Note,
			&i.AssignedTo,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolvedRole,
			&i.ResolutionNote,
			&i.ReplacementID,
			&i.Recomputed,
			&i.RequestedByCode,
			&i.RequestedByNameEn,
			&i.RequestedByNameBn,
			&i.AssignedToCode,
			&i.AssignedToNameEn,
			&i.AssignedToNameBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctionRequestsForPatient = `-- name: CorrectionRequestsForPatient :many
SELECT r.id, r.facility_id, r.patient_id, r.visit_id, r.observation_id, r.code,
       r.requested_at, r.requested_by, r.requested_role,
       r.reason_code, r.note, r.assigned_to, r.status,
       r.resolved_at, r.resolved_by, r.resolved_role, r.resolution_note, r.replacement_id,
       r.recomputed,
       coalesce(q.employee_code, '') AS requested_by_code,
       coalesce(q.name_en, '')       AS requested_by_name_en,
       coalesce(q.name_bn, '')       AS requested_by_name_bn,
       coalesce(a.employee_code, '') AS assigned_to_code,
       coalesce(a.name_en, '')       AS assigned_to_name_en,
       coalesce(a.name_bn, '')       AS assigned_to_name_bn
  FROM read.correction_request r
  LEFT JOIN core.app_user q ON q.id = r.requested_by
  LEFT JOIN core.app_user a ON a.id = r.assigned_to
 WHERE r.patient_id = $1 AND r.facility_id = $2
 ORDER BY r.requested_at DESC
 LIMIT $3
`

type CorrectionRequestsForPatientParams struct {
	PatientID  uuid.UUID
	FacilityID uuid.UUID
	Limit      int32
}

type CorrectionRequestsForPatientRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	PatientID         uuid.UUID
	VisitID           uuid.NullUUID
	ObservationID     uuid.UUID
	Code              string
	RequestedAt       time.Time
	RequestedBy       uuid.UUID
	RequestedRole     string
	ReasonCode        string
	Note              string
	AssignedTo        uuid.UUID
	Status            string
	ResolvedAt        *time.Time
	ResolvedBy        uuid.NullUUID
	ResolvedRole      string
	ResolutionNote    string
	ReplacementID     uuid.NullUUID
	Recomputed        []string
	RequestedByCode   string
	RequestedByNameEn string
	RequestedByNameBn string
	AssignedToCode    string
	AssignedToNameEn  string
	AssignedToNameBn  string
}

// Every flag ever raised on this patient's values, newest first. What the value-history screen
// reads beside the observation chain.
func (q *Queries) CorrectionRequestsForPatient(ctx context.Context, arg CorrectionRequestsForPatientParams) ([]CorrectionRequestsForPatientRow, error) {
	rows, err := q.db.Query(ctx, correctionRequestsForPatient, arg.PatientID, arg.FacilityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionRequestsForPatientRow{}
	for rows.Next() {
		var i CorrectionRequestsForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.PatientID,
			&i.VisitID,
			&i.ObservationID,
			&i.Code,
			&i.RequestedAt,
			&i.RequestedBy,
			&i.RequestedRole,
			&i.ReasonCode,
			&i.Note,
			&i.AssignedTo,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolvedRole,
			&i.ResolutionNote,
			&i.ReplacementID,
			&i.Recomputed,
			&i.RequestedByCode,
			&i.RequestedByNameEn,
			&i.RequestedByNameBn,
			&i.AssignedToCode,
			&i.AssignedToNameEn,
			&i.AssignedToNameBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveDerivedValue = `-- name: LiveDerivedValue :one
SELECT id, code, formula, formula_version, effective_at
  FROM read.observation
 WHERE patient_id = $1 AND facility_id = $2 AND code = $3
   AND status = 'ACTIVE' AND formula <> ''
 ORDER BY effective_at DESC, global_seq DESC
 LIMIT 1
`

type LiveDerivedValueParams struct {
	PatientID  uuid.UUID
	FacilityID uuid.UUID
	Code       string
}

type LiveDerivedValueRow struct {
	ID             uuid.UUID
	Code           string
	Formula        string
	FormulaVersion string
	EffectiveAt    time.Time
}

// The live derived value of one code on one patient, if there is one.
//
// The cascade asks this per derivation rather than asking the database which derived values read a
// given code, and the reason is a small trap: `inputs` stores the names the formula's own paper
// uses — `height_cm`, not `BODY_HEIGHT` — so a query matching the corrected code against the keys
// of `inputs` matches nothing and recomputes nothing, silently. Which derivation reads which code
// is stated in Go, beside the formula that reads it.
func (q *Queries) LiveDerivedValue(ctx context.Context, arg LiveDerivedValueParams) (LiveDerivedValueRow, error) {
	row := q.db.QueryRow(ctx, liveDerivedValue, arg.PatientID, arg.FacilityID, arg.Code)
	var i LiveDerivedValueRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Formula,
		&i.FormulaVersion,
		&i.EffectiveAt,
	)
	return i, err
}

const openCorrectionRequestFor = `-- name: OpenCorrectionRequestFor :one
SELECT id FROM read.correction_request
 WHERE observation_id = $1 AND status = 'OPEN'
`

// The open request on one value, if there is one. A second flag on the same value is the same
// conversation, and two would route two corrections at one number.
func (q *Queries) OpenCorrectionRequestFor(ctx context.Context, observationID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, openCorrectionRequestFor, observationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
