// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: counseling.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCounselingItem = `-- name: AddCounselingItem :exec
INSERT INTO core.counseling_item
  (template_id, version, item_code, ordering, text_en, text_bn,
   guidance_en, guidance_bn, is_mandatory, room)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type AddCounselingItemParams struct {
	TemplateID  uuid.UUID
	Version     int32
	ItemCode    string
	Ordering    int32
	TextEn      string
	TextBn      string
	GuidanceEn  string
	GuidanceBn  string
	IsMandatory bool
	Room        string
}

func (q *Queries) AddCounselingItem(ctx context.Context, arg AddCounselingItemParams) error {
	_, err := q.db.Exec(ctx, addCounselingItem,
		arg.TemplateID,
		arg.Version,
		arg.ItemCode,
		arg.Ordering,
		arg.TextEn,
		arg.TextBn,
		arg.GuidanceEn,
		arg.GuidanceBn,
		arg.IsMandatory,
		arg.Room,
	)
	return err
}

const counselingAssignments = `-- name: CounselingAssignments :many
SELECT a.id, a.template_id, t.code AS template_code, t.title_en, t.title_bn,
       a.code_system, a.code_version, a.code_prefix, a.priority
  FROM core.counseling_assignment a
  JOIN core.counseling_template t ON t.id = a.template_id
 WHERE a.retired_at IS NULL
 ORDER BY a.priority DESC, a.code_prefix
`

type CounselingAssignmentsRow struct {
	ID           uuid.UUID
	TemplateID   uuid.UUID
	TemplateCode string
	TitleEn      string
	TitleBn      string
	CodeSystem   string
	CodeVersion  string
	CodePrefix   string
	Priority     int32
}

func (q *Queries) CounselingAssignments(ctx context.Context) ([]CounselingAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, counselingAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CounselingAssignmentsRow{}
	for rows.Next() {
		var i CounselingAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TemplateCode,
			&i.TitleEn,
			&i.TitleBn,
			&i.CodeSystem,
			&i.CodeVersion,
			&i.CodePrefix,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const counselingItems = `-- name: CounselingItems :many
SELECT i.template_id, i.version, i.item_code, i.ordering,
       i.text_en, i.text_bn, i.guidance_en, i.guidance_bn,
       i.is_mandatory, i.room,
       r.display_en AS room_en, r.display_bn AS room_bn,
       r.ordering AS room_ordering, r.station_code
  FROM core.counseling_item i
  JOIN core.counseling_room r ON r.room = i.room
 WHERE i.template_id = $1 AND i.version = $2
 ORDER BY i.ordering
`

type CounselingItemsParams struct {
	TemplateID uuid.UUID
	Version    int32
}

type CounselingItemsRow struct {
	TemplateID   uuid.UUID
	Version      int32
	ItemCode     string
	Ordering     int32
	TextEn       string
	TextBn       string
	GuidanceEn   string
	GuidanceBn   string
	IsMandatory  bool
	Room         string
	RoomEn       string
	RoomBn       string
	RoomOrdering int32
	StationCode  string
}

// One version's items, in the order the counsellor works through them. Joined to the room so a
// screen can group by it without a second round trip -- the grouping is the flow (section 5.2).
func (q *Queries) CounselingItems(ctx context.Context, arg CounselingItemsParams) ([]CounselingItemsRow, error) {
	rows, err := q.db.Query(ctx, counselingItems, arg.TemplateID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CounselingItemsRow{}
	for rows.Next() {
		var i CounselingItemsRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.Version,
			&i.ItemCode,
			&i.Ordering,
			&i.TextEn,
			&i.TextBn,
			&i.GuidanceEn,
			&i.GuidanceBn,
			&i.IsMandatory,
			&i.Room,
			&i.RoomEn,
			&i.RoomBn,
			&i.RoomOrdering,
			&i.StationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const counselingRooms = `-- name: CounselingRooms :many

SELECT room, display_en, display_bn, station_code, ordering
  FROM core.counseling_room ORDER BY ordering
`

// Counselling templates (CP55).
// The rooms counselling walks through, in the configured sequence (section 5.2).
func (q *Queries) CounselingRooms(ctx context.Context) ([]CoreCounselingRoom, error) {
	rows, err := q.db.Query(ctx, counselingRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreCounselingRoom{}
	for rows.Next() {
		var i CoreCounselingRoom
		if err := rows.Scan(
			&i.Room,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.StationCode,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const counselingTemplateByCode = `-- name: CounselingTemplateByCode :one
SELECT id, code, title_en, title_bn, retired_at FROM core.counseling_template WHERE code = $1
`

type CounselingTemplateByCodeRow struct {
	ID        uuid.UUID
	Code      string
	TitleEn   string
	TitleBn   string
	RetiredAt *time.Time
}

func (q *Queries) CounselingTemplateByCode(ctx context.Context, code string) (CounselingTemplateByCodeRow, error) {
	row := q.db.QueryRow(ctx, counselingTemplateByCode, code)
	var i CounselingTemplateByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TitleEn,
		&i.TitleBn,
		&i.RetiredAt,
	)
	return i, err
}

const counselingTemplateByID = `-- name: CounselingTemplateByID :one
SELECT id, code, title_en, title_bn, retired_at FROM core.counseling_template WHERE id = $1
`

type CounselingTemplateByIDRow struct {
	ID        uuid.UUID
	Code      string
	TitleEn   string
	TitleBn   string
	RetiredAt *time.Time
}

func (q *Queries) CounselingTemplateByID(ctx context.Context, id uuid.UUID) (CounselingTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, counselingTemplateByID, id)
	var i CounselingTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TitleEn,
		&i.TitleBn,
		&i.RetiredAt,
	)
	return i, err
}

const counselingTemplates = `-- name: CounselingTemplates :many
SELECT t.id, t.code, t.title_en, t.title_bn, t.retired_at,
       p.version AS published_version, p.published_at, p.approved_at,
       (SELECT max(version) FROM core.counseling_template_version v WHERE v.template_id = t.id)
         AS latest_version,
       (SELECT count(*) FROM core.counseling_template_version v
         WHERE v.template_id = t.id AND v.status = 'DRAFT') AS draft_count
  FROM core.counseling_template t
  LEFT JOIN core.counseling_template_version p
    ON p.template_id = t.id AND p.status = 'PUBLISHED'
 ORDER BY t.title_en
`

type CounselingTemplatesRow struct {
	ID               uuid.UUID
	Code             string
	TitleEn          string
	TitleBn          string
	RetiredAt        *time.Time
	PublishedVersion *int32
	PublishedAt      *time.Time
	ApprovedAt       *time.Time
	LatestVersion    interface{}
	DraftCount       int64
}

// Every template with the version a new session would get, if it has one. A template with no
// published version is a draft in progress and is listed anyway: an author who cannot see their
// own unpublished work has no way back to it.
func (q *Queries) CounselingTemplates(ctx context.Context) ([]CounselingTemplatesRow, error) {
	rows, err := q.db.Query(ctx, counselingTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CounselingTemplatesRow{}
	for rows.Next() {
		var i CounselingTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TitleEn,
			&i.TitleBn,
			&i.RetiredAt,
			&i.PublishedVersion,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.LatestVersion,
			&i.DraftCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const counselingVersion = `-- name: CounselingVersion :one
SELECT template_id, version, status, notes,
       created_at, created_by, published_at, published_by, published_source,
       retired_at, approved_at, approved_by
  FROM core.counseling_template_version
 WHERE template_id = $1 AND version = $2
`

type CounselingVersionParams struct {
	TemplateID uuid.UUID
	Version    int32
}

func (q *Queries) CounselingVersion(ctx context.Context, arg CounselingVersionParams) (CoreCounselingTemplateVersion, error) {
	row := q.db.QueryRow(ctx, counselingVersion, arg.TemplateID, arg.Version)
	var i CoreCounselingTemplateVersion
	err := row.Scan(
		&i.TemplateID,
		&i.Version,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.PublishedSource,
		&i.RetiredAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
	)
	return i, err
}

const counselingVersions = `-- name: CounselingVersions :many
SELECT template_id, version, status, notes,
       created_at, created_by, published_at, published_by, published_source,
       retired_at, approved_at, approved_by
  FROM core.counseling_template_version
 WHERE template_id = $1 ORDER BY version DESC
`

func (q *Queries) CounselingVersions(ctx context.Context, templateID uuid.UUID) ([]CoreCounselingTemplateVersion, error) {
	rows, err := q.db.Query(ctx, counselingVersions, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreCounselingTemplateVersion{}
	for rows.Next() {
		var i CoreCounselingTemplateVersion
		if err := rows.Scan(
			&i.TemplateID,
			&i.Version,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.PublishedSource,
			&i.RetiredAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCounselingTemplate = `-- name: CreateCounselingTemplate :one
INSERT INTO core.counseling_template (code, title_en, title_bn, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, code, title_en, title_bn, retired_at
`

type CreateCounselingTemplateParams struct {
	Code      string
	TitleEn   string
	TitleBn   string
	CreatedBy uuid.NullUUID
}

type CreateCounselingTemplateRow struct {
	ID        uuid.UUID
	Code      string
	TitleEn   string
	TitleBn   string
	RetiredAt *time.Time
}

func (q *Queries) CreateCounselingTemplate(ctx context.Context, arg CreateCounselingTemplateParams) (CreateCounselingTemplateRow, error) {
	row := q.db.QueryRow(ctx, createCounselingTemplate,
		arg.Code,
		arg.TitleEn,
		arg.TitleBn,
		arg.CreatedBy,
	)
	var i CreateCounselingTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TitleEn,
		&i.TitleBn,
		&i.RetiredAt,
	)
	return i, err
}

const createCounselingVersion = `-- name: CreateCounselingVersion :exec
INSERT INTO core.counseling_template_version (template_id, version, status, notes, created_by)
VALUES ($1, $2, 'DRAFT', $3, $4)
`

type CreateCounselingVersionParams struct {
	TemplateID uuid.UUID
	Version    int32
	Notes      string
	CreatedBy  uuid.NullUUID
}

func (q *Queries) CreateCounselingVersion(ctx context.Context, arg CreateCounselingVersionParams) error {
	_, err := q.db.Exec(ctx, createCounselingVersion,
		arg.TemplateID,
		arg.Version,
		arg.Notes,
		arg.CreatedBy,
	)
	return err
}

const nextCounselingVersion = `-- name: NextCounselingVersion :one
SELECT coalesce(max(version), 0) + 1 AS next FROM core.counseling_template_version
 WHERE template_id = $1
`

func (q *Queries) NextCounselingVersion(ctx context.Context, templateID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCounselingVersion, templateID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const publishCounselingVersion = `-- name: PublishCounselingVersion :exec
UPDATE core.counseling_template_version
   SET status = 'PUBLISHED', published_at = now(), published_by = $3,
       published_source = 'USER'
 WHERE template_id = $1 AND version = $2 AND status = 'DRAFT'
`

type PublishCounselingVersionParams struct {
	TemplateID  uuid.UUID
	Version     int32
	PublishedBy uuid.NullUUID
}

func (q *Queries) PublishCounselingVersion(ctx context.Context, arg PublishCounselingVersionParams) error {
	_, err := q.db.Exec(ctx, publishCounselingVersion, arg.TemplateID, arg.Version, arg.PublishedBy)
	return err
}

const publishedCounselingVersion = `-- name: PublishedCounselingVersion :one
SELECT template_id, version, status, notes,
       created_at, created_by, published_at, published_by, published_source,
       retired_at, approved_at, approved_by
  FROM core.counseling_template_version
 WHERE template_id = $1 AND status = 'PUBLISHED'
`

// What a new session gets. At most one exists -- a unique index says so -- because two would
// make "which checklist" a question with two answers.
func (q *Queries) PublishedCounselingVersion(ctx context.Context, templateID uuid.UUID) (CoreCounselingTemplateVersion, error) {
	row := q.db.QueryRow(ctx, publishedCounselingVersion, templateID)
	var i CoreCounselingTemplateVersion
	err := row.Scan(
		&i.TemplateID,
		&i.Version,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.PublishedSource,
		&i.RetiredAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
	)
	return i, err
}

const replaceCounselingItems = `-- name: ReplaceCounselingItems :exec
DELETE FROM core.counseling_item WHERE template_id = $1 AND version = $2
`

type ReplaceCounselingItemsParams struct {
	TemplateID uuid.UUID
	Version    int32
}

// A draft's items are replaced wholesale rather than patched. An authoring UI sends the list it
// is showing, and a partial update would leave the stored version disagreeing with the screen
// the author is looking at -- which is how somebody publishes an item they thought they deleted.
func (q *Queries) ReplaceCounselingItems(ctx context.Context, arg ReplaceCounselingItemsParams) error {
	_, err := q.db.Exec(ctx, replaceCounselingItems, arg.TemplateID, arg.Version)
	return err
}

const retirePublishedCounselingVersion = `-- name: RetirePublishedCounselingVersion :exec
UPDATE core.counseling_template_version
   SET status = 'RETIRED', retired_at = now()
 WHERE template_id = $1 AND status = 'PUBLISHED'
`

// Two statements rather than one, and the reason is a real bug rather than taste.
//
// As a single statement with a data-modifying CTE, the retire and the publish run against the
// same snapshot: the unique index that allows one published version per template still sees the
// old row as PUBLISHED when the new one is set, and the publish fails. The transaction is what
// makes the pair atomic; the statement boundary is what makes them sequential.
func (q *Queries) RetirePublishedCounselingVersion(ctx context.Context, templateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, retirePublishedCounselingVersion, templateID)
	return err
}

const templatesForCoding = `-- name: TemplatesForCoding :many
SELECT DISTINCT ON (t.id)
       t.id, t.code, t.title_en, t.title_bn, v.version, a.priority
  FROM core.counseling_assignment a
  JOIN core.counseling_template t ON t.id = a.template_id
  JOIN core.counseling_template_version v
    ON v.template_id = t.id AND v.status = 'PUBLISHED'
 WHERE a.retired_at IS NULL AND t.retired_at IS NULL
   AND a.code_system = $1 AND a.code_version = $2
   AND $3::text LIKE a.code_prefix || '%'
 ORDER BY t.id, a.priority DESC
`

type TemplatesForCodingParams struct {
	CodeSystem  string
	CodeVersion string
	Column3     string
}

type TemplatesForCodingRow struct {
	ID       uuid.UUID
	Code     string
	TitleEn  string
	TitleBn  string
	Version  int32
	Priority int32
}

// Which checklists a recorded diagnosis calls for, best first.
//
// Prefix matching rather than equality: ICD-10 groups a family under E11, and a rule per member
// would be sixteen rows that drift apart. Only published versions come back, because a draft is
// not something to hand a counsellor.
func (q *Queries) TemplatesForCoding(ctx context.Context, arg TemplatesForCodingParams) ([]TemplatesForCodingRow, error) {
	rows, err := q.db.Query(ctx, templatesForCoding, arg.CodeSystem, arg.CodeVersion, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplatesForCodingRow{}
	for rows.Next() {
		var i TemplatesForCodingRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TitleEn,
			&i.TitleBn,
			&i.Version,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
