// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateDevice = `-- name: ActivateDevice :one
UPDATE core.device
   SET status = 'active', enrolled_by = COALESCE(enrolled_by, $2), enrolled_at = COALESCE(enrolled_at, $3),
       model = $4, os_version = $5, app_version = $6, last_seen_at = $3,
       status_changed_at = $3, status_changed_by = $2, status_reason = ''
 WHERE id = $1 AND status IN ('pending', 'active', 'suspended')
RETURNING id, facility_id, name, kind, status, enrolled_by, enrolled_at, model, os_version, app_version, last_seen_at, status_changed_at, status_changed_by, status_reason, created_at, updated_at
`

type ActivateDeviceParams struct {
	ID              uuid.UUID
	StatusChangedBy uuid.NullUUID
	LastSeenAt      *time.Time
	Model           string
	OsVersion       string
	AppVersion      string
}

// ActivateDevice moves a device to active on enrolment, in the same statement that records
// what it said about itself. A pending device becomes active; an active or suspended one
// being re-enrolled (reinstalled app, new key) stays or becomes active and keeps its
// original enrolled_at. A revoked or lost device cannot be brought back this way — that is
// what terminal means — and the WHERE returns no row for it.
func (q *Queries) ActivateDevice(ctx context.Context, arg ActivateDeviceParams) (CoreDevice, error) {
	row := q.db.QueryRow(ctx, activateDevice,
		arg.ID,
		arg.StatusChangedBy,
		arg.LastSeenAt,
		arg.Model,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i CoreDevice
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.EnrolledBy,
		&i.EnrolledAt,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const changeDeviceStatus = `-- name: ChangeDeviceStatus :one
UPDATE core.device
   SET status = $2, status_changed_at = $5, status_changed_by = $3, status_reason = $4
 WHERE id = $1
RETURNING id, facility_id, name, kind, status, enrolled_by, enrolled_at, model, os_version, app_version, last_seen_at, status_changed_at, status_changed_by, status_reason, created_at, updated_at
`

type ChangeDeviceStatusParams struct {
	ID              uuid.UUID
	Status          string
	StatusChangedBy uuid.NullUUID
	StatusReason    string
	StatusChangedAt time.Time
}

func (q *Queries) ChangeDeviceStatus(ctx context.Context, arg ChangeDeviceStatusParams) (CoreDevice, error) {
	row := q.db.QueryRow(ctx, changeDeviceStatus,
		arg.ID,
		arg.Status,
		arg.StatusChangedBy,
		arg.StatusReason,
		arg.StatusChangedAt,
	)
	var i CoreDevice
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.EnrolledBy,
		&i.EnrolledAt,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeDeviceEnrolment = `-- name: ConsumeDeviceEnrolment :execrows
UPDATE core.device_enrolment
   SET consumed_at = $2
 WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeDeviceEnrolmentParams struct {
	ID         uuid.UUID
	ConsumedAt *time.Time
}

func (q *Queries) ConsumeDeviceEnrolment(ctx context.Context, arg ConsumeDeviceEnrolmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeDeviceEnrolment, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO core.device (facility_id, name, kind, status_changed_by)
VALUES ($1, $2, $3, $4)
RETURNING id, facility_id, name, kind, status, enrolled_by, enrolled_at, model, os_version, app_version, last_seen_at, status_changed_at, status_changed_by, status_reason, created_at, updated_at
`

type CreateDeviceParams struct {
	FacilityID      uuid.UUID
	Name            string
	Kind            string
	StatusChangedBy uuid.NullUUID
}

// Device queries (CP18).
//
// Nothing here deletes. A device is revoked, a key retired, a code consumed.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CoreDevice, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.FacilityID,
		arg.Name,
		arg.Kind,
		arg.StatusChangedBy,
	)
	var i CoreDevice
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.EnrolledBy,
		&i.EnrolledAt,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeviceEnrolment = `-- name: CreateDeviceEnrolment :one

INSERT INTO core.device_enrolment (device_id, facility_id, issued_by, code_digest, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_id, facility_id, issued_by, code_digest, issued_at, expires_at, consumed_at
`

type CreateDeviceEnrolmentParams struct {
	DeviceID   uuid.UUID
	FacilityID uuid.UUID
	IssuedBy   uuid.UUID
	CodeDigest []byte
	IssuedAt   time.Time
	ExpiresAt  time.Time
}

// --- enrolment codes ---
func (q *Queries) CreateDeviceEnrolment(ctx context.Context, arg CreateDeviceEnrolmentParams) (CoreDeviceEnrolment, error) {
	row := q.db.QueryRow(ctx, createDeviceEnrolment,
		arg.DeviceID,
		arg.FacilityID,
		arg.IssuedBy,
		arg.CodeDigest,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i CoreDeviceEnrolment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FacilityID,
		&i.IssuedBy,
		&i.CodeDigest,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deviceByID = `-- name: DeviceByID :one
SELECT id, facility_id, name, kind, status, enrolled_by, enrolled_at, model, os_version, app_version, last_seen_at, status_changed_at, status_changed_by, status_reason, created_at, updated_at FROM core.device WHERE id = $1
`

func (q *Queries) DeviceByID(ctx context.Context, id uuid.UUID) (CoreDevice, error) {
	row := q.db.QueryRow(ctx, deviceByID, id)
	var i CoreDevice
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.EnrolledBy,
		&i.EnrolledAt,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deviceEnrolmentByDigest = `-- name: DeviceEnrolmentByDigest :one
SELECT id, device_id, facility_id, issued_by, code_digest, issued_at, expires_at, consumed_at FROM core.device_enrolment WHERE code_digest = $1
`

func (q *Queries) DeviceEnrolmentByDigest(ctx context.Context, codeDigest []byte) (CoreDeviceEnrolment, error) {
	row := q.db.QueryRow(ctx, deviceEnrolmentByDigest, codeDigest)
	var i CoreDeviceEnrolment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FacilityID,
		&i.IssuedBy,
		&i.CodeDigest,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deviceEventsForDevice = `-- name: DeviceEventsForDevice :many
SELECT id, device_id, facility_id, actor_id, kind, detail, at FROM core.device_event WHERE device_id = $1 ORDER BY at DESC, id DESC LIMIT $2
`

type DeviceEventsForDeviceParams struct {
	DeviceID uuid.UUID
	Limit    int32
}

func (q *Queries) DeviceEventsForDevice(ctx context.Context, arg DeviceEventsForDeviceParams) ([]CoreDeviceEvent, error) {
	rows, err := q.db.Query(ctx, deviceEventsForDevice, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDeviceEvent{}
	for rows.Next() {
		var i CoreDeviceEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.FacilityID,
			&i.ActorID,
			&i.Kind,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const devicesForFacility = `-- name: DevicesForFacility :many
SELECT id, facility_id, name, kind, status, enrolled_by, enrolled_at, model, os_version, app_version, last_seen_at, status_changed_at, status_changed_by, status_reason, created_at, updated_at FROM core.device WHERE facility_id = $1 ORDER BY lower(name)
`

func (q *Queries) DevicesForFacility(ctx context.Context, facilityID uuid.UUID) ([]CoreDevice, error) {
	rows, err := q.db.Query(ctx, devicesForFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDevice{}
	for rows.Next() {
		var i CoreDevice
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.EnrolledBy,
			&i.EnrolledAt,
			&i.Model,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastSeenAt,
			&i.StatusChangedAt,
			&i.StatusChangedBy,
			&i.StatusReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expirePendingEnrolments = `-- name: ExpirePendingEnrolments :execrows
UPDATE core.device_enrolment
   SET consumed_at = $2
 WHERE device_id = $1 AND consumed_at IS NULL
`

type ExpirePendingEnrolmentsParams struct {
	DeviceID   uuid.UUID
	ConsumedAt *time.Time
}

// ExpirePendingEnrolments consumes every open code for a device, so that issuing a new one
// leaves exactly one that works.
func (q *Queries) ExpirePendingEnrolments(ctx context.Context, arg ExpirePendingEnrolmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingEnrolments, arg.DeviceID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDeviceEvent = `-- name: InsertDeviceEvent :exec

INSERT INTO core.device_event (device_id, facility_id, actor_id, kind, detail, at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDeviceEventParams struct {
	DeviceID   uuid.UUID
	FacilityID uuid.UUID
	ActorID    uuid.NullUUID
	Kind       string
	Detail     []byte
	At         time.Time
}

// --- events ---
func (q *Queries) InsertDeviceEvent(ctx context.Context, arg InsertDeviceEventParams) error {
	_, err := q.db.Exec(ctx, insertDeviceEvent,
		arg.DeviceID,
		arg.FacilityID,
		arg.ActorID,
		arg.Kind,
		arg.Detail,
		arg.At,
	)
	return err
}

const insertDeviceKey = `-- name: InsertDeviceKey :one

INSERT INTO core.device_key (device_id, facility_id, public_key)
VALUES ($1, $2, $3)
RETURNING id, device_id, facility_id, algorithm, public_key, created_at, retired_at, retire_reason
`

type InsertDeviceKeyParams struct {
	DeviceID   uuid.UUID
	FacilityID uuid.UUID
	PublicKey  []byte
}

// --- keys ---
func (q *Queries) InsertDeviceKey(ctx context.Context, arg InsertDeviceKeyParams) (CoreDeviceKey, error) {
	row := q.db.QueryRow(ctx, insertDeviceKey, arg.DeviceID, arg.FacilityID, arg.PublicKey)
	var i CoreDeviceKey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FacilityID,
		&i.Algorithm,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.RetireReason,
	)
	return i, err
}

const liveDeviceKey = `-- name: LiveDeviceKey :one
SELECT id, device_id, facility_id, algorithm, public_key, created_at, retired_at, retire_reason FROM core.device_key WHERE device_id = $1 AND retired_at IS NULL
`

func (q *Queries) LiveDeviceKey(ctx context.Context, deviceID uuid.UUID) (CoreDeviceKey, error) {
	row := q.db.QueryRow(ctx, liveDeviceKey, deviceID)
	var i CoreDeviceKey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FacilityID,
		&i.Algorithm,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.RetireReason,
	)
	return i, err
}

const retireDeviceKeys = `-- name: RetireDeviceKeys :execrows
UPDATE core.device_key
   SET retired_at = $2, retire_reason = $3
 WHERE device_id = $1 AND retired_at IS NULL
`

type RetireDeviceKeysParams struct {
	DeviceID     uuid.UUID
	RetiredAt    *time.Time
	RetireReason string
}

func (q *Queries) RetireDeviceKeys(ctx context.Context, arg RetireDeviceKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireDeviceKeys, arg.DeviceID, arg.RetiredAt, arg.RetireReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForDevice = `-- name: RevokeSessionsForDevice :execrows
UPDATE core.session
   SET revoked_at = $2, revoked_by = $3, revoke_reason = $4
 WHERE device_id = $1 AND revoked_at IS NULL
`

type RevokeSessionsForDeviceParams struct {
	DeviceID     uuid.NullUUID
	RevokedAt    *time.Time
	RevokedBy    uuid.NullUUID
	RevokeReason string
}

// RevokeSessionsForDevice ends every live session on a device the moment it is revoked, so
// that revocation is effective on the next request rather than at the next refresh.
func (q *Queries) RevokeSessionsForDevice(ctx context.Context, arg RevokeSessionsForDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForDevice,
		arg.DeviceID,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevokeReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionsForDevice = `-- name: SessionsForDevice :many

SELECT id, facility_id, user_id, device_id, token_digest, issued_at, expires_at, last_seen_at, stepped_up_at, revoked_at, revoked_by, revoke_reason, user_agent, created_at, updated_at FROM core.session
 WHERE device_id = $1 AND revoked_at IS NULL AND expires_at > $2
 ORDER BY issued_at DESC
`

type SessionsForDeviceParams struct {
	DeviceID  uuid.NullUUID
	ExpiresAt time.Time
}

// --- sessions ---
func (q *Queries) SessionsForDevice(ctx context.Context, arg SessionsForDeviceParams) ([]CoreSession, error) {
	rows, err := q.db.Query(ctx, sessionsForDevice, arg.DeviceID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreSession{}
	for rows.Next() {
		var i CoreSession
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.UserID,
			&i.DeviceID,
			&i.TokenDigest,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.SteppedUpAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE core.device
   SET last_seen_at = $2,
       app_version = CASE WHEN $3::text = '' THEN app_version ELSE $3::text END
 WHERE id = $1
`

type TouchDeviceParams struct {
	ID         uuid.UUID
	LastSeenAt *time.Time
	Column3    string
}

// TouchDevice records the request just verified: when, and what version of the app made
// it. The version travels with every signed request so the admin screen is current
// without an update endpoint.
func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice, arg.ID, arg.LastSeenAt, arg.Column3)
	return err
}
