// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: history.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const familyRelations = `-- name: FamilyRelations :many
SELECT relation, display_en, display_bn, degree, ordering
  FROM core.family_relation
 ORDER BY ordering
`

// Who a family history is about, with the degree. First-degree family history is a risk
// factor with a number attached; second-degree is context, and a query that had to enumerate
// which is which would be a clinical rule living in a WHERE clause somebody copies wrong.
func (q *Queries) FamilyRelations(ctx context.Context) ([]CoreFamilyRelation, error) {
	rows, err := q.db.Query(ctx, familyRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreFamilyRelation{}
	for rows.Next() {
		var i CoreFamilyRelation
		if err := rows.Scan(
			&i.Relation,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.Degree,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyForPatient = `-- name: HistoryForPatient :many
SELECT i.id, i.patient_id, i.kind,
       i.code_system, i.code_version, i.code,
       coalesce(c.display_en, '') AS display_en,
       coalesce(c.display_bn, '') AS display_bn,
       coalesce(c.heading, '')    AS heading,
       coalesce(c.heading_bn, '') AS heading_bn,
       i.said,
       i.relation, i.duration_days, i.severity, i.onset_on, i.onset_precision,
       i.dose, i.frequency, i.formulary_product_id, i.reconciliation,
       i.status,
       i.recorded_at, i.recorded_by, i.recorded_role, i.recorded_visit,
       i.confirmed_at, i.confirmed_by, i.confirmed_visit,
       i.amended_at, i.amended_by
  FROM read.history_item i
  LEFT JOIN core.terminology_concept c
    ON c.system = i.code_system AND c.version = i.code_version AND c.code = i.code
  JOIN core.history_kind k ON k.kind = i.kind
 WHERE i.patient_id = $1 AND i.removed_at IS NULL
 ORDER BY k.ordering, i.recorded_at, i.id
`

type HistoryForPatientRow struct {
	ID                 uuid.UUID
	PatientID          uuid.UUID
	Kind               string
	CodeSystem         *string
	CodeVersion        *string
	Code               *string
	DisplayEn          string
	DisplayBn          string
	Heading            string
	HeadingBn          string
	Said               string
	Relation           *string
	DurationDays       *int32
	Severity           *string
	OnsetOn            pgtype.Date
	OnsetPrecision     *string
	Dose               string
	Frequency          string
	FormularyProductID uuid.NullUUID
	Reconciliation     *string
	Status             string
	RecordedAt         time.Time
	RecordedBy         uuid.UUID
	RecordedRole       string
	RecordedVisit      uuid.NullUUID
	ConfirmedAt        *time.Time
	ConfirmedBy        uuid.NullUUID
	ConfirmedVisit     uuid.NullUUID
	AmendedAt          *time.Time
	AmendedBy          uuid.NullUUID
}

// Everything currently believed about this patient, in the order station 4 asks it.
//
// Removed items are absent: an item somebody removed is one somebody said should not have
// been recorded, and it belongs in the ledger rather than on the screen. RESOLVED items are
// present, because "she had this and no longer does" is a clinical fact and a list that hid
// it would make every follow-up look like a first visit.
//
// The concept's displays are joined rather than copied onto the item. A catalogue title that
// was corrected — a spelling, a better Bangla term — should read correctly on every item
// coded with it, and a copy would leave the old words on every row recorded before the fix.
// What is *not* joined is `said`: that is what the patient told this officer on this day, and
// it is the item's own.
func (q *Queries) HistoryForPatient(ctx context.Context, patientID uuid.UUID) ([]HistoryForPatientRow, error) {
	rows, err := q.db.Query(ctx, historyForPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryForPatientRow{}
	for rows.Next() {
		var i HistoryForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Kind,
			&i.CodeSystem,
			&i.CodeVersion,
			&i.Code,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.Heading,
			&i.HeadingBn,
			&i.Said,
			&i.Relation,
			&i.DurationDays,
			&i.Severity,
			&i.OnsetOn,
			&i.OnsetPrecision,
			&i.Dose,
			&i.Frequency,
			&i.FormularyProductID,
			&i.Reconciliation,
			&i.Status,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.RecordedRole,
			&i.RecordedVisit,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.ConfirmedVisit,
			&i.AmendedAt,
			&i.AmendedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyItem = `-- name: HistoryItem :one
SELECT i.id, i.patient_id, i.facility_id, i.kind,
       i.code_system, i.code_version, i.code,
       coalesce(c.display_en, '') AS display_en,
       coalesce(c.display_bn, '') AS display_bn,
       coalesce(c.heading, '')    AS heading,
       coalesce(c.heading_bn, '') AS heading_bn,
       i.said,
       i.relation, i.duration_days, i.severity, i.onset_on, i.onset_precision,
       i.dose, i.frequency, i.formulary_product_id, i.reconciliation,
       i.status,
       i.recorded_at, i.recorded_by, i.recorded_role, i.recorded_visit,
       i.confirmed_at, i.confirmed_by, i.confirmed_visit,
       i.amended_at, i.amended_by,
       i.removed_at, i.removed_by, i.removed_reason
  FROM read.history_item i
  LEFT JOIN core.terminology_concept c
    ON c.system = i.code_system AND c.version = i.code_version AND c.code = i.code
 WHERE i.id = $1
`

type HistoryItemRow struct {
	ID                 uuid.UUID
	PatientID          uuid.UUID
	FacilityID         uuid.UUID
	Kind               string
	CodeSystem         *string
	CodeVersion        *string
	Code               *string
	DisplayEn          string
	DisplayBn          string
	Heading            string
	HeadingBn          string
	Said               string
	Relation           *string
	DurationDays       *int32
	Severity           *string
	OnsetOn            pgtype.Date
	OnsetPrecision     *string
	Dose               string
	Frequency          string
	FormularyProductID uuid.NullUUID
	Reconciliation     *string
	Status             string
	RecordedAt         time.Time
	RecordedBy         uuid.UUID
	RecordedRole       string
	RecordedVisit      uuid.NullUUID
	ConfirmedAt        *time.Time
	ConfirmedBy        uuid.NullUUID
	ConfirmedVisit     uuid.NullUUID
	AmendedAt          *time.Time
	AmendedBy          uuid.NullUUID
	RemovedAt          *time.Time
	RemovedBy          uuid.NullUUID
	RemovedReason      string
}

func (q *Queries) HistoryItem(ctx context.Context, id uuid.UUID) (HistoryItemRow, error) {
	row := q.db.QueryRow(ctx, historyItem, id)
	var i HistoryItemRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FacilityID,
		&i.Kind,
		&i.CodeSystem,
		&i.CodeVersion,
		&i.Code,
		&i.DisplayEn,
		&i.DisplayBn,
		&i.Heading,
		&i.HeadingBn,
		&i.Said,
		&i.Relation,
		&i.DurationDays,
		&i.Severity,
		&i.OnsetOn,
		&i.OnsetPrecision,
		&i.Dose,
		&i.Frequency,
		&i.FormularyProductID,
		&i.Reconciliation,
		&i.Status,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.RecordedRole,
		&i.RecordedVisit,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.ConfirmedVisit,
		&i.AmendedAt,
		&i.AmendedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.RemovedReason,
	)
	return i, err
}

const historyKind = `-- name: HistoryKind :one
SELECT kind, display_en, display_bn, code_system,
       requires_relation, requires_duration, allows_severity, allows_onset,
       is_medication, ordering
  FROM core.history_kind WHERE kind = $1
`

func (q *Queries) HistoryKind(ctx context.Context, kind string) (CoreHistoryKind, error) {
	row := q.db.QueryRow(ctx, historyKind, kind)
	var i CoreHistoryKind
	err := row.Scan(
		&i.Kind,
		&i.DisplayEn,
		&i.DisplayBn,
		&i.CodeSystem,
		&i.RequiresRelation,
		&i.RequiresDuration,
		&i.AllowsSeverity,
		&i.AllowsOnset,
		&i.IsMedication,
		&i.Ordering,
	)
	return i, err
}

const historyKinds = `-- name: HistoryKinds :many

SELECT kind, display_en, display_bn, code_system,
       requires_relation, requires_duration, allows_severity, allows_onset,
       is_medication, ordering
  FROM core.history_kind
 ORDER BY ordering
`

// Medical history (CP53).
// The six kinds and what each one needs. Reference data a station app fetches once and then
// renders the right fields from — which is what stops a screen asking for a family relation on
// a complaint, or forgetting to ask for one on a family history.
func (q *Queries) HistoryKinds(ctx context.Context) ([]CoreHistoryKind, error) {
	rows, err := q.db.Query(ctx, historyKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreHistoryKind{}
	for rows.Next() {
		var i CoreHistoryKind
		if err := rows.Scan(
			&i.Kind,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.CodeSystem,
			&i.RequiresRelation,
			&i.RequiresDuration,
			&i.AllowsSeverity,
			&i.AllowsOnset,
			&i.IsMedication,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncodedHistoryCount = `-- name: UncodedHistoryCount :many
SELECT kind, count(*) AS uncoded
  FROM read.history_item
 WHERE facility_id = $1 AND removed_at IS NULL AND code IS NULL
 GROUP BY kind
 ORDER BY kind
`

type UncodedHistoryCountRow struct {
	Kind    string
	Uncoded int64
}

// How much of the history has no code, by kind.
//
// Criterion 1 says complaints and comorbidities are coded rather than free text, and the
// escape hatch for a concept the catalogue lacks is what keeps that rule from being one people
// work around. This is the number that keeps the hatch honest: it is the list of concepts
// somebody should add, and if it grows the catalogue is wrong rather than the officers.
func (q *Queries) UncodedHistoryCount(ctx context.Context, facilityID uuid.UUID) ([]UncodedHistoryCountRow, error) {
	rows, err := q.db.Query(ctx, uncodedHistoryCount, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UncodedHistoryCountRow{}
	for rows.Next() {
		var i UncodedHistoryCountRow
		if err := rows.Scan(&i.Kind, &i.Uncoded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
