// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attemptsFor = `-- name: AttemptsFor :many
SELECT job_id, attempt, worker, failed_at, ran_for_ms, error
  FROM ops.job_attempt
 WHERE job_id = $1
 ORDER BY attempt
`

func (q *Queries) AttemptsFor(ctx context.Context, jobID uuid.UUID) ([]OpsJobAttempt, error) {
	rows, err := q.db.Query(ctx, attemptsFor, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsJobAttempt{}
	for rows.Next() {
		var i OpsJobAttempt
		if err := rows.Scan(
			&i.JobID,
			&i.Attempt,
			&i.Worker,
			&i.FailedAt,
			&i.RanForMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelJob = `-- name: CancelJob :one
UPDATE ops.job
   SET status = 'CANCELLED', finished_at = $1::timestamptz,
       last_error = $2::text
 WHERE id = $3::uuid AND status = 'AVAILABLE'
RETURNING id
`

type CancelJobParams struct {
	Now    time.Time
	Reason string
	ID     uuid.UUID
}

// Stop a job that has not started. A RUNNING job is not cancellable from here: the worker holding
// it would carry on regardless, and a status saying otherwise would be a lie on a screen.
func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.Now, arg.Reason, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const claimJobs = `-- name: ClaimJobs :many
WITH claimable AS (
  SELECT j.id
    FROM ops.job j
    JOIN ops.job_kind k ON k.kind = j.kind
   WHERE j.status = 'AVAILABLE'
     AND j.run_at <= $2::timestamptz
     AND j.queue = ANY($4::text[])
     AND k.paused_at IS NULL
   ORDER BY j.priority DESC, j.run_at, j.enqueued_at
   LIMIT $5::integer
   FOR UPDATE OF j SKIP LOCKED
)
UPDATE ops.job j
   SET status = 'RUNNING',
       attempt = j.attempt + 1,
       leased_by = $1::text,
       leased_until = $2::timestamptz + make_interval(secs => $3::integer),
       started_at = coalesce(j.started_at, $2::timestamptz)
  FROM claimable c
 WHERE j.id = c.id
RETURNING j.id, j.kind, j.args, j.attempt, j.max_attempts, j.enqueued_at, j.sla_deadline
`

type ClaimJobsParams struct {
	Worker       string
	Now          time.Time
	LeaseSeconds int32
	Queues       []string
	RowLimit     int32
}

type ClaimJobsRow struct {
	ID          uuid.UUID
	Kind        string
	Args        []byte
	Attempt     int32
	MaxAttempts int32
	EnqueuedAt  time.Time
	SlaDeadline *time.Time
}

// Take up to `row_limit` jobs, best first, and hold them for the lease.
//
// `FOR UPDATE ... SKIP LOCKED` is the whole concurrency story: two workers running this at the same
// moment take disjoint sets rather than blocking on each other, and a third arriving mid-statement
// takes whatever neither has locked.
//
// A paused kind is skipped rather than claimed-and-requeued, so a pause takes effect on the next
// poll rather than after one more run of everything already in flight.
func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]ClaimJobsRow, error) {
	rows, err := q.db.Query(ctx, claimJobs,
		arg.Worker,
		arg.Now,
		arg.LeaseSeconds,
		arg.Queues,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimJobsRow{}
	for rows.Next() {
		var i ClaimJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Args,
			&i.Attempt,
			&i.MaxAttempts,
			&i.EnqueuedAt,
			&i.SlaDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :exec
UPDATE ops.job
   SET status = 'SUCCEEDED',
       finished_at = $1::timestamptz,
       leased_by = NULL, leased_until = NULL,
       met_sla = CASE WHEN sla_deadline IS NULL THEN NULL
                      ELSE $1::timestamptz <= sla_deadline END
 WHERE id = $2::uuid AND status = 'RUNNING' AND leased_by = $3::text
`

type CompleteJobParams struct {
	Now    time.Time
	ID     uuid.UUID
	Worker string
}

// Done. `met_sla` is resolved here rather than computed on read, so that changing a kind's budget
// does not retroactively rewrite whether last week was met.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.Exec(ctx, completeJob, arg.Now, arg.ID, arg.Worker)
	return err
}

const dueSchedules = `-- name: DueSchedules :many
UPDATE ops.job_schedule s
   SET last_run_at = $1::timestamptz,
       next_run_at = $1::timestamptz + make_interval(secs => s.every_seconds)
 WHERE s.kind IN (
   SELECT d.kind FROM ops.job_schedule d
    WHERE d.paused_at IS NULL AND d.next_run_at <= $1::timestamptz
    FOR UPDATE SKIP LOCKED)
RETURNING s.kind, s.args, s.next_run_at
`

type DueSchedulesRow struct {
	Kind      string
	Args      []byte
	NextRunAt time.Time
}

// Periodic jobs whose time has come, claimed so that two workers produce one enqueue.
//
// `FOR UPDATE SKIP LOCKED` is the leader election. It matters more here than for ordinary jobs: a
// periodic job has no natural dedupe key, and "run the nightly audit twice" is a real cost rather
// than an absorbed duplicate.
func (q *Queries) DueSchedules(ctx context.Context, now time.Time) ([]DueSchedulesRow, error) {
	rows, err := q.db.Query(ctx, dueSchedules, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueSchedulesRow{}
	for rows.Next() {
		var i DueSchedulesRow
		if err := rows.Scan(&i.Kind, &i.Args, &i.NextRunAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO ops.job (id, kind, queue, priority, args, dedupe_key, max_attempts, run_at,
                     enqueued_at, sla_deadline)
SELECT $1::uuid, k.kind, k.queue, k.priority,
       $2::jsonb, $3::text, k.max_attempts,
       $4::timestamptz,
       -- ` + "`" + `enqueued_at` + "`" + ` comes from the caller's clock rather than from the column's ` + "`" + `now()` + "`" + `
       -- default, for a reason that only shows up on the dashboard: ` + "`" + `oldest_available_seconds` + "`" + ` is
       -- the number an alert fires on, and it is computed as ` + "`" + `now - enqueued_at` + "`" + `. If one of those
       -- comes from the application and the other from the database, clock skew between the two
       -- becomes queue age, and an alert threshold measured in minutes is sensitive to a skew of
       -- minutes. One clock decides both.
       $5::timestamptz,
       CASE WHEN k.sla_seconds IS NULL THEN NULL
            ELSE $5::timestamptz + make_interval(secs => k.sla_seconds) END
  FROM ops.job_kind k
 WHERE k.kind = $6::text
ON CONFLICT DO NOTHING
RETURNING id, kind, queue, priority, status, attempt, max_attempts, run_at, enqueued_at, sla_deadline
`

type EnqueueJobParams struct {
	ID        uuid.UUID
	Args      []byte
	DedupeKey *string
	RunAt     time.Time
	Now       time.Time
	Kind      string
}

type EnqueueJobRow struct {
	ID          uuid.UUID
	Kind        string
	Queue       string
	Priority    int32
	Status      string
	Attempt     int32
	MaxAttempts int32
	RunAt       time.Time
	EnqueuedAt  time.Time
	SlaDeadline *time.Time
}

// The job queue (CP69).
//
// # The one query that is not here
//
// There is no `InsertJob` that opens its own transaction. `EnqueueTx` takes the caller's `pgx.Tx`,
// because acceptance criterion 1 — *"a job enqueued in a rolled-back transaction never runs"* — is
// a property of where the insert happens, and a convenience helper that opened its own connection
// would be the one call site that quietly broke it.
// The enqueue. Everything the row needs that is not the caller's business — priority, attempts,
// backoff, the SLA deadline — comes from the kind's own row, so a caller cannot enqueue a job with
// a retry policy nobody agreed.
//
// `ON CONFLICT DO NOTHING` against the live-dedupe index makes enqueue-once free: a caller that
// retries its own transaction, or two stations that both notice the same visit is ready, produce
// one job. The `:one` returns nothing when it was absorbed, which the Go side reads as "already
// queued" rather than as an error.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.ID,
		arg.Args,
		arg.DedupeKey,
		arg.RunAt,
		arg.Now,
		arg.Kind,
	)
	var i EnqueueJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Priority,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAt,
		&i.EnqueuedAt,
		&i.SlaDeadline,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE ops.job j
   SET status = CASE WHEN j.attempt >= j.max_attempts THEN 'DISCARDED' ELSE 'AVAILABLE' END,
       run_at = CASE WHEN j.attempt >= j.max_attempts THEN j.run_at
                     ELSE $1::timestamptz + make_interval(secs => $2::integer) END,
       finished_at = CASE WHEN j.attempt >= j.max_attempts THEN $1::timestamptz ELSE NULL END,
       met_sla = CASE WHEN j.attempt >= j.max_attempts AND j.sla_deadline IS NOT NULL
                      THEN false ELSE j.met_sla END,
       leased_by = NULL, leased_until = NULL,
       last_error = $3::text
 WHERE j.id = $4::uuid AND j.status = 'RUNNING' AND j.leased_by = $5::text
RETURNING j.id, j.kind, j.attempt, j.max_attempts, j.status, j.run_at
`

type FailJobParams struct {
	Now            time.Time
	BackoffSeconds int32
	Error          string
	ID             uuid.UUID
	Worker         string
}

type FailJobRow struct {
	ID          uuid.UUID
	Kind        string
	Attempt     int32
	MaxAttempts int32
	Status      string
	RunAt       time.Time
}

// A failure: back to the queue with a backoff, or dead-lettered if the attempts are spent.
//
// The decision is made here, in one statement, rather than by the worker reading the row and
// writing it back. Two workers cannot both decide, and a worker that dies between the read and the
// write cannot leave a job in a state neither branch produced.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (FailJobRow, error) {
	row := q.db.QueryRow(ctx, failJob,
		arg.Now,
		arg.BackoffSeconds,
		arg.Error,
		arg.ID,
		arg.Worker,
	)
	var i FailJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Status,
		&i.RunAt,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :exec
UPDATE ops.job
   SET leased_until = $1::timestamptz + make_interval(secs => $2::integer)
 WHERE id = $3::uuid AND status = 'RUNNING' AND leased_by = $4::text
`

type HeartbeatJobParams struct {
	Now          time.Time
	LeaseSeconds int32
	ID           uuid.UUID
	Worker       string
}

// Extend a lease while the work is still running.
//
// Without this a job legitimately taking longer than one lease would be reaped out from under a
// healthy worker and run twice — which is the difference between "at-least-once because a worker
// died" and "at-least-once because we were impatient".
func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) error {
	_, err := q.db.Exec(ctx, heartbeatJob,
		arg.Now,
		arg.LeaseSeconds,
		arg.ID,
		arg.Worker,
	)
	return err
}

const jobByID = `-- name: JobByID :one
SELECT j.id, j.kind, j.queue, j.priority, j.args, j.dedupe_key, j.status,
       j.attempt, j.max_attempts, j.run_at, j.enqueued_at, j.started_at, j.finished_at,
       j.leased_by, j.leased_until, j.sla_deadline, j.met_sla, j.last_error,
       coalesce(k.description_en, j.kind) AS description_en,
       coalesce(k.description_bn, j.kind) AS description_bn
  FROM ops.job j
  LEFT JOIN ops.job_kind k ON k.kind = j.kind
 WHERE j.id = $1
`

type JobByIDRow struct {
	ID            uuid.UUID
	Kind          string
	Queue         string
	Priority      int32
	Args          []byte
	DedupeKey     *string
	Status        string
	Attempt       int32
	MaxAttempts   int32
	RunAt         time.Time
	EnqueuedAt    time.Time
	StartedAt     *time.Time
	FinishedAt    *time.Time
	LeasedBy      *string
	LeasedUntil   *time.Time
	SlaDeadline   *time.Time
	MetSla        *bool
	LastError     string
	DescriptionEn string
	DescriptionBn string
}

func (q *Queries) JobByID(ctx context.Context, id uuid.UUID) (JobByIDRow, error) {
	row := q.db.QueryRow(ctx, jobByID, id)
	var i JobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Priority,
		&i.Args,
		&i.DedupeKey,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeasedBy,
		&i.LeasedUntil,
		&i.SlaDeadline,
		&i.MetSla,
		&i.LastError,
		&i.DescriptionEn,
		&i.DescriptionBn,
	)
	return i, err
}

const jobHealth = `-- name: JobHealth :many
SELECT k.kind, k.job_class, k.queue, (k.paused_at IS NOT NULL)::boolean AS paused,
       k.paused_at, coalesce(u.name_en, '') AS paused_by_name_en,
       coalesce(u.name_bn, '') AS paused_by_name_bn,
       k.sla_seconds,
       count(*) FILTER (WHERE j.status = 'AVAILABLE')::bigint AS available,
       count(*) FILTER (WHERE j.status = 'RUNNING')::bigint AS running,
       -- Seconds, so an alert threshold is a number a person writes without converting.
       -- Coalesced to zero, and unambiguous because ` + "`" + `available` + "`" + ` says whether anything is
       -- waiting at all: zero with an empty queue means nothing waiting, zero with a queue means
       -- something arrived this instant.
       coalesce(max(CASE WHEN j.status = 'AVAILABLE'
                         THEN extract(epoch FROM ($1::timestamptz - j.enqueued_at))::integer
                    END), 0)::integer AS oldest_available_seconds,
       -- **The number to alert on**, and different from the one above in a way that matters.
       --
       -- ` + "`" + `oldest_available_seconds` + "`" + ` is total age from enqueue, which counts a job that is sitting
       -- out an exponential backoff as "waiting" — so one failing SMS on a kind with a half-hour
       -- cap lights the row up while the retry policy behaves exactly as designed. This one
       -- measures from ` + "`" + `run_at` + "`" + `, over jobs that are actually **due**, so it answers the question an
       -- alert is really asking: is there work nobody is doing right now.
       coalesce(max(CASE WHEN j.status = 'AVAILABLE' AND j.run_at <= $1::timestamptz
                         THEN extract(epoch FROM ($1::timestamptz - j.run_at))::integer
                    END), 0)::integer AS oldest_due_seconds,
       count(*) FILTER (WHERE j.status = 'SUCCEEDED' AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))::bigint AS succeeded,
       count(*) FILTER (WHERE j.status = 'DISCARDED' AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))::bigint AS discarded,
       count(*) FILTER (WHERE j.status = 'CANCELLED' AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))::bigint AS cancelled,
       -- **Not windowed**, and deliberately beside the windowed counts rather than instead of
       -- them. A kind can read "0% given up on, 0 of 40 finished" while forty dead letters from
       -- last night are still sitting there waiting for somebody — both true, and a reader who
       -- assumed one set would conclude the screen was lying.
       count(*) FILTER (WHERE j.status = 'DISCARDED')::bigint AS dead_letters,
       CASE
         WHEN count(*) FILTER (WHERE j.status IN ('SUCCEEDED', 'DISCARDED')
                                 AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer)) = 0
         THEN NULL
         ELSE round(100.0
              * count(*) FILTER (WHERE j.status = 'DISCARDED' AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))
              / count(*) FILTER (WHERE j.status IN ('SUCCEEDED', 'DISCARDED')
                                   AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer)), 1)
       END::numeric AS failure_rate,
       count(*) FILTER (WHERE j.met_sla IS NOT NULL AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))::bigint AS sla_measured,
       count(*) FILTER (WHERE j.met_sla AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))::bigint AS sla_met,
       CASE
         WHEN count(*) FILTER (WHERE j.met_sla IS NOT NULL AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer)) = 0
         THEN NULL
         ELSE round(100.0
              * count(*) FILTER (WHERE j.met_sla AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer))
              / count(*) FILTER (WHERE j.met_sla IS NOT NULL AND j.finished_at >= $1::timestamptz - make_interval(secs => $2::integer)), 1)
       END::numeric AS sla_attainment,
       -- Seconds since this kind last finished anything, and **-1 for "never"** rather than a
       -- null timestamp. A sentinel is usually the wrong answer; here it is the right one twice
       -- over: the generator will not infer nullability through an aggregate, and the number a
       -- dashboard actually renders is an age rather than a wall-clock time — "nothing for four
       -- hours" is the sentence, and a kind that has never run is the single most interesting
       -- thing this row can say.
       coalesce(
         extract(epoch FROM ($1::timestamptz - max(j.finished_at)))::integer,
         -1)::integer AS seconds_since_last_finish
  FROM ops.job_kind k
  LEFT JOIN core.app_user u ON u.id = k.paused_by
  LEFT JOIN ops.job j ON j.kind = k.kind
 GROUP BY k.kind, k.job_class, k.queue, k.paused_at, u.name_en, u.name_bn, k.sla_seconds, k.priority
 ORDER BY k.priority DESC, k.kind
`

type JobHealthParams struct {
	Now           time.Time
	WindowSeconds int32
}

type JobHealthRow struct {
	Kind                   string
	JobClass               string
	Queue                  string
	Paused                 bool
	PausedAt               *time.Time
	PausedByNameEn         string
	PausedByNameBn         string
	SlaSeconds             *int32
	Available              int64
	Running                int64
	OldestAvailableSeconds int32
	OldestDueSeconds       int32
	Succeeded              int64
	Discarded              int64
	Cancelled              int64
	DeadLetters            int64
	FailureRate            pgtype.Numeric
	SlaMeasured            int64
	SlaMet                 int64
	SlaAttainment          pgtype.Numeric
	SecondsSinceLastFinish int32
}

// Criterion 3, as one query.
//
// **Every registered kind is a row**, whether or not anything is queued — the left join is the
// point. A dashboard assembled from what is in the queue cannot report the failure it exists to
// catch: a job type that has stopped being enqueued at all.
//
// `oldest_available_seconds` is the number to alert on. Depth says how much there is; age says how
// long the oldest thing has been ignored, and a queue of two that has not moved in an hour is a
// worse state than a queue of four hundred that is draining.
//
// The rates are **null rather than zero when nothing finished in the window**. "No failures" and
// "nothing ran" are different states, and a dashboard showing 0% for both hides a stopped queue
// behind the healthiest-looking number on the page.
func (q *Queries) JobHealth(ctx context.Context, arg JobHealthParams) ([]JobHealthRow, error) {
	rows, err := q.db.Query(ctx, jobHealth, arg.Now, arg.WindowSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHealthRow{}
	for rows.Next() {
		var i JobHealthRow
		if err := rows.Scan(
			&i.Kind,
			&i.JobClass,
			&i.Queue,
			&i.Paused,
			&i.PausedAt,
			&i.PausedByNameEn,
			&i.PausedByNameBn,
			&i.SlaSeconds,
			&i.Available,
			&i.Running,
			&i.OldestAvailableSeconds,
			&i.OldestDueSeconds,
			&i.Succeeded,
			&i.Discarded,
			&i.Cancelled,
			&i.DeadLetters,
			&i.FailureRate,
			&i.SlaMeasured,
			&i.SlaMet,
			&i.SlaAttainment,
			&i.SecondsSinceLastFinish,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobKinds = `-- name: JobKinds :many
SELECT k.kind, k.job_class, k.queue, k.priority, k.max_attempts, k.backoff_seconds,
       k.backoff_cap_seconds, k.sla_seconds, k.description_en, k.description_bn,
       k.paused_at, k.paused_by,
       coalesce(u.employee_code, '') AS paused_by_code,
       coalesce(u.name_en, '')       AS paused_by_name_en,
       coalesce(u.name_bn, '')       AS paused_by_name_bn
  FROM ops.job_kind k
  LEFT JOIN core.app_user u ON u.id = k.paused_by
 ORDER BY k.priority DESC, k.kind
`

type JobKindsRow struct {
	Kind              string
	JobClass          string
	Queue             string
	Priority          int32
	MaxAttempts       int32
	BackoffSeconds    int32
	BackoffCapSeconds int32
	SlaSeconds        *int32
	DescriptionEn     string
	DescriptionBn     string
	PausedAt          *time.Time
	PausedBy          uuid.NullUUID
	PausedByCode      string
	PausedByNameEn    string
	PausedByNameBn    string
}

// The registered catalogue. Read at boot to check that every kind has a handler and every handler
// has a kind, which is the same fail-at-startup treatment the route registry gets.
//
// The pause is **attributed on the way out as well as on the way in**. `paused_by` was being
// recorded and never shown, so the one screen an operator opens during an incident could say a
// kind was stopped and not who stopped it — leaving the log as the only place that person was
// findable, which is not what "findable afterwards" means.
func (q *Queries) JobKinds(ctx context.Context) ([]JobKindsRow, error) {
	rows, err := q.db.Query(ctx, jobKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobKindsRow{}
	for rows.Next() {
		var i JobKindsRow
		if err := rows.Scan(
			&i.Kind,
			&i.JobClass,
			&i.Queue,
			&i.Priority,
			&i.MaxAttempts,
			&i.BackoffSeconds,
			&i.BackoffCapSeconds,
			&i.SlaSeconds,
			&i.DescriptionEn,
			&i.DescriptionBn,
			&i.PausedAt,
			&i.PausedBy,
			&i.PausedByCode,
			&i.PausedByNameEn,
			&i.PausedByNameBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobsByStatus = `-- name: JobsByStatus :many
SELECT j.id, j.kind, j.queue, j.priority, j.args, j.dedupe_key, j.status,
       j.attempt, j.max_attempts, j.run_at, j.enqueued_at, j.started_at, j.finished_at,
       j.leased_by, j.leased_until, j.sla_deadline, j.met_sla, j.last_error,
       coalesce(k.description_en, j.kind) AS description_en,
       coalesce(k.description_bn, j.kind) AS description_bn
  FROM ops.job j
  LEFT JOIN ops.job_kind k ON k.kind = j.kind
 WHERE ($1::text IS NULL OR j.status = $1::text)
   AND ($2::text IS NULL OR j.kind = $2::text)
   -- The jobs behind the attainment figure. Without this, a page could report "63.6% on time,
   -- 14 of 22 met it" and offer no way to reach the eight that missed: they succeeded, so they
   -- are not dead letters, and they are finished, so they are not waiting. A number nobody can
   -- drill into is asserted to the reader however carefully it was measured.
   AND ($3::boolean IS NULL OR j.met_sla = $3::boolean)
 ORDER BY j.enqueued_at DESC
 LIMIT $4
`

type JobsByStatusParams struct {
	Status   *string
	Kind     *string
	MetSla   *bool
	RowLimit int32
}

type JobsByStatusRow struct {
	ID            uuid.UUID
	Kind          string
	Queue         string
	Priority      int32
	Args          []byte
	DedupeKey     *string
	Status        string
	Attempt       int32
	MaxAttempts   int32
	RunAt         time.Time
	EnqueuedAt    time.Time
	StartedAt     *time.Time
	FinishedAt    *time.Time
	LeasedBy      *string
	LeasedUntil   *time.Time
	SlaDeadline   *time.Time
	MetSla        *bool
	LastError     string
	DescriptionEn string
	DescriptionBn string
}

// The operator's list. Ordered newest-relevant-first: what is waiting, then what has failed.
func (q *Queries) JobsByStatus(ctx context.Context, arg JobsByStatusParams) ([]JobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, jobsByStatus,
		arg.Status,
		arg.Kind,
		arg.MetSla,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobsByStatusRow{}
	for rows.Next() {
		var i JobsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Priority,
			&i.Args,
			&i.DedupeKey,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAt,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LeasedBy,
			&i.LeasedUntil,
			&i.SlaDeadline,
			&i.MetSla,
			&i.LastError,
			&i.DescriptionEn,
			&i.DescriptionBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pHIKeys = `-- name: PHIKeys :many
SELECT key, guidance FROM ops.phi_key ORDER BY key
`

// The database's copy of the list, so a Go test can compare it against logging.PHIKeys in both
// directions. Two representations of one list is a thing that drifts, and the drift is silent.
func (q *Queries) PHIKeys(ctx context.Context) ([]OpsPhiKey, error) {
	rows, err := q.db.Query(ctx, pHIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsPhiKey{}
	for rows.Next() {
		var i OpsPhiKey
		if err := rows.Scan(&i.Key, &i.Guidance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseKind = `-- name: PauseKind :one
UPDATE ops.job_kind
   SET paused_at = $1::timestamptz, paused_by = $2::uuid
 WHERE kind = $3::text AND paused_at IS NULL
RETURNING kind, paused_at
`

type PauseKindParams struct {
	Now      time.Time
	PausedBy uuid.UUID
	Kind     string
}

type PauseKindRow struct {
	Kind     string
	PausedAt *time.Time
}

func (q *Queries) PauseKind(ctx context.Context, arg PauseKindParams) (PauseKindRow, error) {
	row := q.db.QueryRow(ctx, pauseKind, arg.Now, arg.PausedBy, arg.Kind)
	var i PauseKindRow
	err := row.Scan(&i.Kind, &i.PausedAt)
	return i, err
}

const reapExpiredLeases = `-- name: ReapExpiredLeases :many
UPDATE ops.job j
   SET status = CASE WHEN j.attempt >= j.max_attempts THEN 'DISCARDED' ELSE 'AVAILABLE' END,
       leased_by = NULL,
       leased_until = NULL,
       run_at = CASE WHEN j.attempt >= j.max_attempts THEN j.run_at ELSE $1::timestamptz END,
       finished_at = CASE WHEN j.attempt >= j.max_attempts THEN $1::timestamptz ELSE NULL END,
       met_sla = CASE
                   WHEN j.attempt >= j.max_attempts AND j.sla_deadline IS NOT NULL
                   THEN false ELSE j.met_sla
                 END,
       last_error = CASE
                      WHEN btrim(j.last_error) <> '' THEN j.last_error
                      ELSE 'the worker holding this job stopped answering'
                    END
 WHERE j.status = 'RUNNING' AND j.leased_until < $1::timestamptz
RETURNING j.id, j.kind, j.attempt, (j.attempt >= j.max_attempts)::boolean AS discarded
`

type ReapExpiredLeasesRow struct {
	ID        uuid.UUID
	Kind      string
	Attempt   int32
	Discarded bool
}

// Return abandoned work to the queue. This is what criterion 5 rests on, and what it buys is
// **at-least-once** delivery: a worker that finished the work and died before marking the row runs
// that job again when its lease expires. No queue that is not writing its completion inside the
// work's own transaction can do better, which is why §8.5 requires every job to be idempotent.
//
// A job whose attempts are spent is discarded rather than requeued, or one poisonous job would take
// the queue down with it, over and over, forever.
func (q *Queries) ReapExpiredLeases(ctx context.Context, now time.Time) ([]ReapExpiredLeasesRow, error) {
	rows, err := q.db.Query(ctx, reapExpiredLeases, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReapExpiredLeasesRow{}
	for rows.Next() {
		var i ReapExpiredLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Attempt,
			&i.Discarded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :exec
INSERT INTO ops.job_attempt (job_id, attempt, worker, failed_at, ran_for_ms, error)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (job_id, attempt) DO NOTHING
`

type RecordAttemptParams struct {
	JobID    uuid.UUID
	Attempt  int32
	Worker   string
	FailedAt time.Time
	RanForMs int64
	Error    string
}

// Every failure, kept with what it said. "It failed five times" and "here is what it said each
// time" are different questions, and the second is the one asked at the point of fixing it.
func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAttempt,
		arg.JobID,
		arg.Attempt,
		arg.Worker,
		arg.FailedAt,
		arg.RanForMs,
		arg.Error,
	)
	return err
}

const resumeKind = `-- name: ResumeKind :one
UPDATE ops.job_kind
   SET paused_at = NULL, paused_by = NULL
 WHERE kind = $1::text AND paused_at IS NOT NULL
RETURNING kind, paused_at
`

type ResumeKindRow struct {
	Kind     string
	PausedAt *time.Time
}

func (q *Queries) ResumeKind(ctx context.Context, kind string) (ResumeKindRow, error) {
	row := q.db.QueryRow(ctx, resumeKind, kind)
	var i ResumeKindRow
	err := row.Scan(&i.Kind, &i.PausedAt)
	return i, err
}

const retryJob = `-- name: RetryJob :one
UPDATE ops.job
   SET status = 'AVAILABLE', attempt = 0, finished_at = NULL, met_sla = NULL,
       run_at = $1::timestamptz, last_error = ''
 WHERE id = $2::uuid AND status = 'DISCARDED'
RETURNING id
`

type RetryJobParams struct {
	Now time.Time
	ID  uuid.UUID
}

// Put a dead-lettered job back, with its attempt count reset so the policy applies again from the
// start. An operator retrying a job that failed five times means "try again", not "try once more".
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, retryJob, arg.Now, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
