// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Things an administrator must see now: break-glass access, chain verification failures. Acknowledged, never deleted.
type CoreAdminAlert struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	Kind           string
	Severity       string
	MessageEn      string
	MessageBn      string
	Reference      []byte
	AuditSeq       *int64
	CreatedAt      time.Time
	AcknowledgedBy uuid.NullUUID
	AcknowledgedAt *time.Time
}

type CoreAiAgent struct {
	AgentCode     string
	Technology    string
	DescriptionEn string
	DescriptionBn string
	// Whether §10.2 step 4 applies to this agent's answers. Defaults to true; an exemption must name its reason. Never taken from a request (ADR-0032, ADR-0034).
	GroundingRequired     bool
	GroundingExemptReason string
}

type CoreAiBudget struct {
	FacilityID    uuid.UUID
	AgentCode     *string
	DailyMicroUsd int64
	Thresholds    []int32
}

type CoreAiBudgetAlert struct {
	FacilityID       uuid.UUID
	AgentCode        string
	Day              time.Time
	ThresholdPercent int32
	SpendMicroUsd    int64
	BudgetMicroUsd   int64
	RaisedAt         time.Time
}

// One grounding violation: what the model said, which arm of the check caught it, and a human's verdict on whether the check was right (CP72). Never retried, never deleted.
type CoreAiGroundingDefect struct {
	ID               uuid.UUID
	FacilityID       uuid.UUID
	AiInteractionID  uuid.UUID
	AgentCode        string
	PromptVersion    string
	ModelVersion     string
	SubjectPatientID uuid.NullUUID
	SubjectPseudonym string
	Arm              string
	Path             string
	Token            string
	Excerpt          string
	Reason           string
	DetectedAt       time.Time
	Status           string
	Classification   *string
	ReviewedBy       uuid.NullUUID
	ReviewedAt       *time.Time
	ReviewNote       string
}

type CoreAiInteraction struct {
	ID                    uuid.UUID
	FacilityID            uuid.UUID
	AgentCode             string
	PromptVersion         *string
	ModelVersion          *string
	RequestedModelVersion *string
	Tier                  string
	Provenance            string
	SubjectPatientID      uuid.NullUUID
	SubjectPseudonym      string
	Status                string
	Outbound              []byte
	Response              []byte
	RefusalDetail         string
	InputSha256           string
	InputTokens           int32
	OutputTokens          int32
	CostMicroUsd          int64
	LatencyMs             int32
	Attempts              int32
	OutputValid           *bool
	UsedFallback          bool
	StartedAt             time.Time
	FinishedAt            *time.Time
	// The §10.2 step 4 verdict on this answer. NOT_CHECKED means the call predates CP72 or never produced an answer; NOT_REQUIRED means core.ai_agent exempts this agent.
	GroundingState    string
	GroundingFindings int32
}

type CoreAiModel struct {
	Model                    string
	ModelVersion             string
	Provider                 string
	InputMicroUsdPerMillion  int64
	OutputMicroUsdPerMillion int64
	DescriptionEn            string
	DescriptionBn            string
	RetiredAt                *time.Time
}

type CoreAiPromptVersion struct {
	AgentCode            string
	Version              string
	Major                int32
	Minor                int32
	Patch                int32
	ModelVersion         string
	FallbackModelVersion *string
	ContentSha256        string
	Content              string
	Changelog            string
	DeployedAt           time.Time
}

// One run of the pre-consultation synthesis agent against one visit: the assembled context, the model's draft, and whether §7.1's five minutes were kept (CP71).
type CoreAiSynthesis struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
	VisitID    uuid.UUID
	PatientID  uuid.UUID
	Generation int32
	State      string
	Trigger    string
	// What the deterministic assembler produced. Every number and date in `output` must be traceable to something in here — that is what CP72 will check.
	Context []byte
	// Hash over the material subset of the context. Two runs with the same hash would produce the same summary, so the second one does not call a model.
	MaterialSha256  string
	Output          []byte
	AiInteractionID uuid.NullUUID
	PromptVersion   *string
	ModelVersion    *string
	JobID           uuid.NullUUID
	RequestedAt     time.Time
	RequestedBy     uuid.NullUUID
	StartedAt       *time.Time
	FinishedAt      *time.Time
	SlaDeadline     *time.Time
	MetSla          *bool
	FailureKind     *string
	FailureDetail   string
	SupersededAt    *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	// The §10.2 step 4 verdict. A READY row must be PASSED — see ai_synthesis_ready_is_grounded. NOT_CHECKED belongs to runs that predate CP72 or never reached a model.
	GroundingState    string
	GroundingFindings int32
}

// Record ids known to be fabricated. The AI gateway resolves provenance by looking a subject up here; absent means real, and a failed lookup means real. Never a flag on the request.
type CoreAiSyntheticSubject struct {
	SubjectID    uuid.UUID
	FacilityID   uuid.UUID
	Reason       string
	RegisteredBy uuid.NullUUID
	RegisteredAt time.Time
}

type CoreAllergenCrossReaction struct {
	ID             uuid.UUID
	FromGroup      string
	ToGroup        string
	Risk           string
	NoteEn         string
	NoteBn         string
	SourceCitation string
	Origin         string
	ApprovedBy     uuid.NullUUID
	ApprovedAt     *time.Time
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type CoreAllergenGroup struct {
	Code           string
	NameEn         string
	NameBn         string
	NotesEn        string
	NotesBn        string
	SourceCitation string
	Origin         string
	ApprovedBy     uuid.NullUUID
	ApprovedAt     *time.Time
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type CoreAllergenGroupMember struct {
	ID             uuid.UUID
	GroupCode      string
	MatchKind      string
	MatchValue     string
	SourceCitation string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type CoreAllergyReaction struct {
	Reaction    string
	DisplayEn   string
	DisplayBn   string
	IsEmergency bool
	Ordering    int32
}

// A member of staff. Never deleted — deactivated, so that attribution [R-03] survives.
type CoreAppUser struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
	// Short human identifier, unique per facility. Appears in attribution chips and audit lines.
	EmployeeCode string
	NameEn       string
	NameBn       string
	Phone        string
	Email        string
	// Argon2id, set at CP16. Null means the invitation has not been accepted.
	PasswordHash    *string
	PasswordSetAt   *time.Time
	Status          string
	StatusReason    string
	StatusChangedAt time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

// The only rows the wall board may read. An explicit allowlist of columns safe to project in a public waiting area (CP40).
type CoreBoardRow struct {
	EntryID        uuid.UUID
	FacilityID     uuid.UUID
	ClinicDay      time.Time
	StationCode    string
	Position       int32
	Status         string
	Priority       int32
	EnteredAt      time.Time
	CalledAt       *time.Time
	StartedAt      *time.Time
	VisitID        uuid.UUID
	VisitCode      string
	VisitType      string
	ClinicalID     string
	Initials       string
	CounselingDone bool
}

// How the wall board names patients and when it goes amber and red. Data, not code: both are decisions the clinic owns (CP40).
type CoreBoardSetting struct {
	FacilityID uuid.UUID
	// Patient identification convention on a screen patients can read. Defaults to the visit code alone.
	IdentifyBy            string
	BusyWaitSeconds       int32
	BusyDepth             int32
	BottleneckWaitSeconds int32
	BottleneckDepth       int32
	UpdatedAt             time.Time
}

// Emergency access grants: who, what, the typed justification, for how long, and who acknowledged it. Never deleted.
type CoreBreakGlassAccess struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	UserID         uuid.UUID
	ActiveRole     string
	ScopeKind      string
	ScopeRef       string
	Justification  string
	GrantedAt      time.Time
	ExpiresAt      time.Time
	EndedAt        *time.Time
	EndedBy        uuid.NullUUID
	EndReason      string
	AcknowledgedBy uuid.NullUUID
	AcknowledgedAt *time.Time
	AuditSeq       *int64
}

// The next clinical id per facility per year. Locked per row, so ids are gapless (CP28).
type CoreClinicalIDCounter struct {
	FacilityID uuid.UUID
	Year       int16
	NextValue  int32
	UpdatedAt  time.Time
}

type CoreCodeSystem struct {
	Code        string
	TitleEn     string
	TitleBn     string
	Publisher   string
	LicenceNote string
	Usable      bool
}

type CoreCodeSystemVersion struct {
	System     string
	Version    string
	ReleasedOn *time.Time
	IsDefault  bool
}

// The bilingual, versioned wording a consent is taken against. Immutable once active (CP36, D-02).
type CoreConsentTemplate struct {
	ID          uuid.UUID
	ConsentType string
	Version     int32
	Language    string
	Title       string
	Body        string
	// SHA-256 of the body. Travels into CONSENT_GRANTED so a later edit of this row is detectable.
	BodyDigest    string
	Status        string
	EffectiveFrom *time.Time
	RetiredAt     *time.Time
	CreatedAt     time.Time
	CreatedBy     uuid.NullUUID
}

type CoreContraindication struct {
	Code            string
	NameEn          string
	NameBn          string
	QuestionEn      string
	QuestionBn      string
	FromObservation *string
	Ordering        int32
	RetiredAt       *time.Time
}

type CoreCorrectionReason struct {
	Code            string
	DisplayEn       string
	DisplayBn       string
	IsTranscription bool
	Ordering        int32
	RetiredAt       *time.Time
}

type CoreCounselingAssignment struct {
	ID          uuid.UUID
	TemplateID  uuid.UUID
	CodeSystem  string
	CodeVersion string
	CodePrefix  string
	Priority    int32
	RetiredAt   *time.Time
}

type CoreCounselingItem struct {
	TemplateID  uuid.UUID
	Version     int32
	ItemCode    string
	Ordering    int32
	TextEn      string
	TextBn      string
	GuidanceEn  string
	GuidanceBn  string
	IsMandatory bool
	Room        string
}

type CoreCounselingRoom struct {
	Room        string
	DisplayEn   string
	DisplayBn   string
	StationCode string
	Ordering    int32
}

type CoreCounselingTemplate struct {
	ID        uuid.UUID
	Code      string
	TitleEn   string
	TitleBn   string
	RetiredAt *time.Time
	CreatedAt time.Time
	CreatedBy uuid.NullUUID
}

type CoreCounselingTemplateVersion struct {
	TemplateID      uuid.UUID
	Version         int32
	Status          string
	Notes           string
	CreatedAt       time.Time
	CreatedBy       uuid.NullUUID
	PublishedAt     *time.Time
	PublishedBy     uuid.NullUUID
	PublishedSource string
	RetiredAt       *time.Time
	ApprovedAt      *time.Time
	ApprovedBy      uuid.NullUUID
}

// Values that require immediate action (CP50). Not plausibility (CP46), not a normal range (CP49). Every row is proposed until D-27 approves it.
type CoreCriticalValueRule struct {
	ID          uuid.UUID
	Code        string
	Sex         *string
	MinAgeYears pgtype.Numeric
	MaxAgeYears pgtype.Numeric
	Low         pgtype.Numeric
	High        pgtype.Numeric
	ActionEn    string
	ActionBn    string
	ApprovedBy  uuid.NullUUID
	ApprovedAt  *time.Time
	UpdatedAt   time.Time
}

// An enrolled clinic device. Never deleted: revoked or lost, the row stays for attribution.
type CoreDevice struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
	Name       string
	Kind       string
	// pending → active → (suspended ↔ active) → revoked | lost. revoked and lost are terminal.
	Status          string
	EnrolledBy      uuid.NullUUID
	EnrolledAt      *time.Time
	Model           string
	OsVersion       string
	AppVersion      string
	LastSeenAt      *time.Time
	StatusChangedAt time.Time
	StatusChangedBy uuid.NullUUID
	StatusReason    string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// One-time enrolment codes, digest only, minutes-long, consumed once.
type CoreDeviceEnrolment struct {
	ID         uuid.UUID
	DeviceID   uuid.UUID
	FacilityID uuid.UUID
	IssuedBy   uuid.UUID
	CodeDigest []byte
	IssuedAt   time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

// Append-only record of what happened to a device. Nothing rewrites it.
type CoreDeviceEvent struct {
	ID         int64
	DeviceID   uuid.UUID
	FacilityID uuid.UUID
	ActorID    uuid.NullUUID
	Kind       string
	Detail     []byte
	At         time.Time
}

// Ed25519 public keys. The private key is generated on the device and never leaves it.
type CoreDeviceKey struct {
	ID           uuid.UUID
	DeviceID     uuid.UUID
	FacilityID   uuid.UUID
	Algorithm    string
	PublicKey    []byte
	CreatedAt    time.Time
	RetiredAt    *time.Time
	RetireReason string
}

type CoreDispenseUnit struct {
	Code      string
	NameEn    string
	NameBn    string
	RetiredAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

// One station touch, with start, end and attribution. What makes §14.2 bottleneck analysis a query (CP38).
type CoreEncounter struct {
	ID          uuid.UUID
	FacilityID  uuid.UUID
	VisitID     uuid.UUID
	PatientID   uuid.UUID
	StationCode string
	Status      string
	StartedAt   time.Time
	StartedBy   uuid.UUID
	EndedAt     *time.Time
	EndedBy     uuid.NullUUID
	StartedRole string
	DeviceID    uuid.NullUUID
	Outcome     string
	Notes       string
	CreatedAt   time.Time
}

// Acknowledge-or-escalate: who is told after how long (CP50). Proposed until D-27 approves it.
type CoreEscalationStep struct {
	StepNumber   int32
	AfterSeconds int32
	NotifyRole   *string
	NoteEn       string
	NoteBn       string
	ApprovedBy   uuid.NullUUID
	ApprovedAt   *time.Time
	UpdatedAt    time.Time
}

type CoreExercise struct {
	Code           string
	NameEn         string
	NameBn         string
	HowEn          string
	HowBn          string
	Kind           string
	Intensity      string
	Impact         string
	NeedsEquipment bool
	CanDoAtHome    bool
	ApprovedAt     *time.Time
	ApprovedBy     uuid.NullUUID
	Ordering       int32
	RetiredAt      *time.Time
}

type CoreExerciseContraindication struct {
	ExerciseCode         string
	ContraindicationCode string
	ReasonEn             string
	ReasonBn             string
}

// A physical clinic. Every facility-scoped table references this (D-61).
type CoreFacility struct {
	ID uuid.UUID
	// Short human-readable identifier, printed on reports. Immutable in practice.
	Code         string
	NameEn       string
	NameBn       string
	FacilityType string
	AddressEn    string
	AddressBn    string
	District     string
	Division     string
	Country      string
	Phone        string
	Email        string
	// IANA zone. Clinical timestamps are stored UTC and rendered in this zone.
	Timezone  string
	IsActive  bool
	OpenedOn  *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	// core.app_user.id. The foreign key is added in CP15, when that table exists.
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

// How old an eGFR may be and still count as current renal function, per facility (CP79). Six months is the plan's proposal and nobody has approved it yet.
type CoreFacilityRenalPolicy struct {
	FacilityID        uuid.UUID
	EgfrRecencyMonths int32
	SourceCitation    string
	Origin            string
	ApprovedBy        uuid.NullUUID
	ApprovedAt        *time.Time
	NotesEn           string
	NotesBn           string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	UpdatedBy         uuid.NullUUID
}

// Tables deliberately not facility-scoped. A row here is a decision on the record, not an oversight.
type CoreFacilityScopeExemption struct {
	SchemaName string
	TableName  string
	Reason     string
	ExemptedAt time.Time
}

type CoreFamilyRelation struct {
	Relation  string
	DisplayEn string
	DisplayBn string
	Degree    int32
	Ordering  int32
}

type CoreFood struct {
	Code           string
	NameEn         string
	NameBn         string
	Synonyms       []string
	GroupCode      string
	KcalPer100g    pgtype.Numeric
	ProteinPer100g pgtype.Numeric
	CarbPer100g    pgtype.Numeric
	FatPer100g     pgtype.Numeric
	Source         string
	ApprovedAt     *time.Time
	ApprovedBy     uuid.NullUUID
	RetiredAt      *time.Time
	Searchable     string
	// Where this food sits in the list before anybody types. Null sorts last. A proposal until the clinic has recorded a month of recalls (CP59).
	StapleRank *int32
}

type CoreFoodMeasure struct {
	Code      string
	NameEn    string
	NameBn    string
	Universal bool
	Ordering  int32
	// The most of this measure one entry may carry. A hundred cups is nobody's lunch; two hundred grams is an ordinary plate of rice (CP59).
	MaxQuantity int32
}

type CoreFoodPortion struct {
	FoodCode    string
	MeasureCode string
	Grams       pgtype.Numeric
	NoteEn      string
	NoteBn      string
	Ordering    int32
}

type CoreFormularyImport struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	Filename        string
	Mode            string
	RowsTotal       int32
	RowsAccepted    int32
	RowsRejected    int32
	ProductsCreated int32
	ProductsUpdated int32
	PricesRecorded  int32
	ImportedAt      time.Time
	ImportedBy      uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type CoreFormularyImportRow struct {
	ID         uuid.UUID
	ImportID   uuid.UUID
	FacilityID uuid.UUID
	LineNumber int32
	Outcome    string
	Field      *string
	MessageEn  *string
	MessageBn  *string
	RawLine    *string
	ProductID  uuid.NullUUID
	CreatedAt  time.Time
}

type CoreFormularyPriceReview struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	PeriodMonth       time.Time
	OwnerRole         string
	OwnerUserID       uuid.NullUUID
	Status            string
	OpenedAt          time.Time
	DueOn             time.Time
	RemindedAt        *time.Time
	AlertID           uuid.NullUUID
	ProductsAtOpen    int32
	ProvisionalAtOpen int32
	CompletedAt       *time.Time
	CompletedBy       uuid.NullUUID
	CompletionNote    *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type CoreFormularyReviewOwner struct {
	FacilityID    uuid.UUID
	OwnerRole     string
	OwnerUserID   uuid.NullUUID
	DueDayOfMonth int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
}

type CoreFormularySeedRow struct {
	ID               uuid.UUID
	GenericName      string
	ClassCode        string
	TradeName        string
	Strength         string
	FormCode         string
	Manufacturer     string
	UnitPricePoisha  int64
	DispenseUnit     string
	DgdaRegistration *string
	IsActive         bool
	Notes            *string
	SourceUrl        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CreatedBy        uuid.NullUUID
	UpdatedBy        uuid.NullUUID
}

type CoreGeneric struct {
	ID        uuid.UUID
	Name      string
	ClassCode string
	AtcCode   *string
	Notes     *string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
	// DETERMINED means somebody has written out which molecules this medicine contains. UNDETERMINED is the default and makes CP78 duplicate detection answer "cannot verify" rather than "no duplicate".
	ComponentsStatus       string
	ComponentsSource       string
	ComponentsDeterminedAt *time.Time
}

type CoreGenericComponent struct {
	ID             uuid.UUID
	GenericID      uuid.UUID
	Ordinal        int32
	Molecule       string
	SourceCitation string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

// Whether prescribing this molecule depends on knowing the kidney function (CP79). Absence of a row means unclassified, which the engine reports and never reads as safe.
type CoreGenericRenalDependence struct {
	GenericID      uuid.UUID
	Dependence     string
	ReasonEn       string
	ReasonBn       string
	SourceCitation string
	Origin         string
	ApprovedBy     uuid.NullUUID
	ApprovedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      uuid.NullUUID
}

type CoreGrowthBand struct {
	Indicator    string
	MinAgeMonths pgtype.Numeric
	MaxAgeMonths pgtype.Numeric
	StandardCode string
}

type CoreGrowthLm struct {
	StandardCode string
	Indicator    string
	Sex          string
	AgeMonths    pgtype.Numeric
	L            pgtype.Numeric
	M            pgtype.Numeric
	S            pgtype.Numeric
}

type CoreGrowthStandard struct {
	Code         string
	Version      string
	NameEn       string
	NameBn       string
	Source       string
	MinAgeMonths pgtype.Numeric
	MaxAgeMonths pgtype.Numeric
}

type CoreHistoryKind struct {
	Kind             string
	DisplayEn        string
	DisplayBn        string
	CodeSystem       string
	RequiresRelation bool
	RequiresDuration bool
	AllowsSeverity   bool
	AllowsOnset      bool
	IsMedication     bool
	Ordering         int32
}

// The questionnaires station 3 may run, and the ones it may not (CP58, D-26).
type CoreInstrument struct {
	Code            string
	NameEn          string
	NameBn          string
	PurposeEn       string
	PurposeBn       string
	CopyrightHolder string
	LicenceNote     string
	Usable          bool
	Domain          string
	Ordering        int32
	RetiredAt       *time.Time
	LicenceNoteBn   string
	Provenance      string
}

type CoreInstrumentItem struct {
	InstrumentCode string
	Version        int32
	ItemCode       string
	Ordering       int32
	PromptEn       string
	PromptBn       string
	AnswerType     string
	Unit           *string
	MinValue       pgtype.Numeric
	MaxValue       pgtype.Numeric
	Required       bool
}

type CoreInstrumentOption struct {
	InstrumentCode string
	Version        int32
	ItemCode       string
	OptionCode     string
	Ordering       int32
	LabelEn        string
	LabelBn        string
	Score          int32
}

type CoreInstrumentVersion struct {
	InstrumentCode string
	Version        int32
	Scoring        string
	PublishedAt    *time.Time
	Note           string
}

// Every login attempt, whether or not the account exists. Pruned by the retention job at CP23.
type CoreLoginAttempt struct {
	ID           int64
	FacilityID   uuid.UUID
	EmployeeCode string
	UserID       uuid.NullUUID
	Succeeded    bool
	FailureKind  string
	// SHA-256 of the client address and a server pepper. Throttling without keeping addresses.
	ClientDigest []byte
	AttemptedAt  time.Time
}

type CoreMeal struct {
	Code     string
	NameEn   string
	NameBn   string
	Ordering int32
}

type CoreMedicationClass struct {
	Code      string
	NameEn    string
	NameBn    string
	AtcCode   *string
	Ordering  int32
	RetiredAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

type CoreMedicationForm struct {
	Code      string
	NameEn    string
	NameBn    string
	RetiredAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

type CoreMedicationPrice struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	ProductID       uuid.UUID
	UnitPricePoisha int64
	EffectiveFrom   time.Time
	EffectiveTo     *time.Time
	Verification    string
	Origin          string
	SourceNote      *string
	SourceUrl       *string
	RecordedAt      time.Time
	RecordedBy      uuid.NullUUID
	CreatedAt       time.Time
}

type CoreMedicationProduct struct {
	ID               uuid.UUID
	FacilityID       uuid.UUID
	GenericID        uuid.UUID
	TradeName        string
	Strength         string
	FormCode         string
	Manufacturer     string
	DispenseUnit     string
	DgdaRegistration *string
	Notes            *string
	SourceUrl        *string
	IsActive         bool
	WithdrawnAt      *time.Time
	WithdrawnReason  *string
	WithdrawnBy      uuid.NullUUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CreatedBy        uuid.NullUUID
	UpdatedBy        uuid.NullUUID
}

type CoreMedicationRule struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	Code            string
	RuleType        string
	IsActive        bool
	WithdrawnAt     *time.Time
	WithdrawnReason *string
	WithdrawnBy     uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type CoreMedicationRuleVersion struct {
	ID             uuid.UUID
	RuleID         uuid.UUID
	Version        int32
	Severity       string
	NameEn         string
	NameBn         string
	MessageEn      string
	MessageBn      string
	AdviceEn       string
	AdviceBn       string
	Condition      []byte
	SourceCitation string
	Origin         string
	Status         string
	AuthoredBy     uuid.NullUUID
	AuthoredAt     time.Time
	ApprovedBy     uuid.NullUUID
	ApprovedAt     *time.Time
	EffectiveFrom  *time.Time
	EffectiveTo    *time.Time
	Notes          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      uuid.NullUUID
}

// Which answers a coded observation may take, in clinical order and in both languages (CP51).
type CoreObservationAnswer struct {
	Code      string
	ValueCode string
	DisplayEn string
	DisplayBn string
	Ordering  int32
	IsNormal  bool
	RetiredAt *time.Time
}

// What each kind of measured value is: its category, its shape, its unit dimension, its plausibility band and who may write it (CP42).
type CoreObservationCode struct {
	Code      string
	Category  string
	ValueType string
	Dimension *string
	// Empty where the LOINC code is not known. An empty code is honest; a guessed one is a mapping error that surfaces years later in somebody else's system.
	Loinc           string
	DisplayEn       string
	DisplayBn       string
	MinCanonical    pgtype.Numeric
	MaxCanonical    pgtype.Numeric
	WritePermission string
	RetiredAt       *time.Time
}

// A person the clinic knows. Demographics, contact, the socio-economic baseline, and the date of birth pediatric percentiles depend on (CP28).
type CorePatient struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
	ClinicalID string
	NameEn     string
	NameBn     string
	Sex        string
	BirthDate  time.Time
	// day | month | year. Below "day", the rest of birth_date is a placeholder and any age derived from it carries that uncertainty.
	DobPrecision       string
	DobVerifiedBy      string
	DobVerifiedAt      *time.Time
	DobVerifiedUserID  uuid.NullUUID
	PhonePrimary       string
	PhoneSecondary     string
	Division           string
	District           string
	Upazila            string
	AddressLine        string
	Postcode           string
	EmergencyName      string
	EmergencyRelation  string
	EmergencyPhone     string
	EducationLevel     *string
	OccupationCategory *string
	// Monthly household income in BDT. NULL means not captured; 'unknown' means asked and not known.
	IncomeBand     *string
	HouseholdSize  *int16
	ResidenceType  *string
	MedicinePayer  *string
	PhotoObjectKey string
	Status         string
	MergedIntoID   uuid.NullUUID
	StatusReason   string
	RegisteredBy   uuid.NullUUID
	RegisteredAt   time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// A patient's official numbers: a peppered digest for matching, a sealed value for retrieval, a mask for display (CP28, D-47).
type CorePatientIdentifier struct {
	ID            uuid.UUID
	FacilityID    uuid.UUID
	PatientID     uuid.UUID
	Kind          string
	Digest        []byte
	Sealed        []byte
	KeyID         string
	Masked        string
	VerifiedAt    *time.Time
	VerifiedBy    uuid.NullUUID
	CaptureMethod string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// One row per merge: who, when, on what score, with what justification, and the candidate list that was on screen (CP30).
type CorePatientMerge struct {
	ID            uuid.UUID
	FacilityID    uuid.UUID
	SurvivorID    uuid.UUID
	MergedID      uuid.UUID
	Score         pgtype.Numeric
	Decision      string
	Justification string
	Candidates    []byte
	MergedBy      uuid.UUID
	MergedAt      time.Time
	EventID       uuid.UUID
}

// The reference to a patient's photograph in object storage, and its provenance. The bytes are never in the database (CP34).
type CorePatientPhoto struct {
	ID          uuid.UUID
	FacilityID  uuid.UUID
	PatientID   uuid.UUID
	ObjectClass string
	// Derived by the server, never chosen by a client: a key a client picks is a key that can be pointed at somebody else's photograph.
	ObjectKey   string
	ContentType string
	ByteSize    int32
	Sha256      []byte
	Width       *int32
	Height      *int32
	CapturedBy  uuid.UUID
	CapturedAt  time.Time
	DeviceID    uuid.NullUUID
	EventID     uuid.UUID
	ReplacesID  uuid.NullUUID
	ReplacedAt  *time.Time
	CreatedAt   time.Time
}

// The permission catalogue. resource.action.scope triples covering every station and administrative action.
type CorePermission struct {
	Code        string
	Description string
	Resource    string
	Action      string
	Scope       string
	// Seeing this means seeing identifiable clinical detail. Blueprint §4.4 blinding rules are checked against it.
	IsSensitive bool
	CreatedAt   time.Time
}

// Per-code plausibility bands and delta limits (CP46). Data, so a clinic can retune them.
type CorePlausibilityRule struct {
	ID                uuid.UUID
	Code              string
	Sex               *string
	MinAgeYears       pgtype.Numeric
	MaxAgeYears       pgtype.Numeric
	AbsoluteMin       pgtype.Numeric
	AbsoluteMax       pgtype.Numeric
	PlausibleMin      pgtype.Numeric
	PlausibleMax      pgtype.Numeric
	MaxIncrease       pgtype.Numeric
	MaxDecrease       pgtype.Numeric
	MaxIncreasePerDay pgtype.Numeric
	MaxDecreasePerDay pgtype.Numeric
	NoteEn            string
	NoteBn            string
	ApprovedBy        uuid.NullUUID
	ApprovedAt        *time.Time
	UpdatedAt         time.Time
}

// The seven states a prescription can be in (CP80). Rows rather than an enum so the machine is readable with a SELECT.
type CorePrescriptionStatus struct {
	Status     string
	NameEn     string
	NameBn     string
	MeaningEn  string
	MeaningBn  string
	IsFrozen   bool
	IsTerminal bool
	Ordering   int32
}

// Every legal status change for a prescription (CP80). Anything not in this table is refused by a trigger.
type CorePrescriptionTransition struct {
	FromStatus string
	ToStatus   string
	EventType  string
	NoteEn     string
	NoteBn     string
	OwnedBy    string
}

// A pattern of corrections worth a conversation (CP63). Acknowledged, never deleted, and never naming a patient.
type CoreQualityFlag struct {
	ID            uuid.UUID
	FacilityID    uuid.UUID
	OperatorID    uuid.UUID
	ThresholdCode string
	RaisedAt      time.Time
	WindowFrom    time.Time
	WindowTo      time.Time
	ObservedCount int32
	EntriesCount  int32
	Evidence      []byte
	Status        string
	ResolvedAt    *time.Time
	ResolvedBy    uuid.NullUUID
	Resolution    string
	AuditSeq      *int64
}

// When a pattern of corrections is worth somebody looking at (CP63). Proposals until approved.
type CoreQualityThreshold struct {
	Code       string
	Pattern    string
	WindowDays int32
	MinCount   int32
	MinEntries int32
	AfterHour  *int32
	DisplayEn  string
	DisplayBn  string
	ActionEn   string
	ActionBn   string
	ApprovedAt *time.Time
	ApprovedBy uuid.NullUUID
	Active     bool
	Ordering   int32
}

// Where every patient is and what is next. The traffic board, the counselling gate and throughput all read this (CP39).
type CoreQueueEntry struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	VisitID        uuid.UUID
	PatientID      uuid.UUID
	StationCode    string
	Position       int32
	Status         string
	Priority       int32
	PriorityReason string
	// When the patient joined *this* queue. A waiting time is measured from here, not from when the visit opened.
	EnteredAt     time.Time
	CalledAt      *time.Time
	CalledBy      uuid.NullUUID
	StartedAt     *time.Time
	EndedAt       *time.Time
	Outcome       string
	OutcomeReason string
	ReroutedTo    string
	EncounterID   uuid.NullUUID
	ClinicDay     time.Time
	CreatedAt     time.Time
}

// Single-use recovery codes, stored as digests. A used row stays; that is the proof it was used once.
type CoreRecoveryCode struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	FacilityID     uuid.UUID
	BatchID        uuid.UUID
	CodeDigest     []byte
	UsedAt         *time.Time
	UsedFromClient []byte
	RevokedAt      *time.Time
	CreatedAt      time.Time
}

// What is normal for a patient, per code and age band (CP49). Not plausibility (CP46) and not a critical value (CP50).
type CoreReferenceRange struct {
	ID          uuid.UUID
	Code        string
	Sex         *string
	MinAgeYears pgtype.Numeric
	MaxAgeYears pgtype.Numeric
	Low         pgtype.Numeric
	High        pgtype.Numeric
	NoteEn      string
	NoteBn      string
	ApprovedBy  uuid.NullUUID
	ApprovedAt  *time.Time
	UpdatedAt   time.Time
}

// Rotating refresh tokens with lineage. Reuse of a used token revokes the whole family.
type CoreRefreshToken struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
	SessionID  uuid.UUID
	// The lineage descended from one login. Revoked as a unit when reuse is detected.
	FamilyID     uuid.UUID
	TokenDigest  []byte
	IssuedAt     time.Time
	ExpiresAt    time.Time
	UsedAt       *time.Time
	ReplacedBy   uuid.NullUUID
	RevokedAt    *time.Time
	RevokeReason string
}

type CoreRole struct {
	ID          uuid.UUID
	Code        string
	NameEn      string
	NameBn      string
	Description string
	IsClinical  bool
	StationCode *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Which permissions a role carries. ON DELETE CASCADE is safe here: roles and permissions are catalogue, not history.
type CoreRolePermission struct {
	RoleID         uuid.UUID
	PermissionCode string
	GrantedAt      time.Time
}

// Append-only record of second-factor and step-up events. CP22 renders it; nothing rewrites it.
type CoreSecurityEvent struct {
	ID           int64
	FacilityID   uuid.UUID
	UserID       uuid.NullUUID
	SessionID    uuid.NullUUID
	ActorID      uuid.NullUUID
	Kind         string
	Outcome      string
	Detail       []byte
	ClientDigest []byte
	At           time.Time
}

// A live login. The access token is opaque and stored only as a digest (ADR-0011).
type CoreSession struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
	UserID     uuid.UUID
	// The device holding this session. Constrained at CP18, when devices exist.
	DeviceID    uuid.NullUUID
	TokenDigest []byte
	IssuedAt    time.Time
	ExpiresAt   time.Time
	LastSeenAt  time.Time
	// When a second factor was last completed for this session. Set at CP17.
	SteppedUpAt  *time.Time
	RevokedAt    *time.Time
	RevokedBy    uuid.NullUUID
	RevokeReason string
	UserAgent    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Minutes-long tokens for a login challenge or a step-up. Digest only; consumed once; never deleted by the app.
type CoreShortToken struct {
	ID           uuid.UUID
	FacilityID   uuid.UUID
	UserID       uuid.UUID
	SessionID    uuid.NullUUID
	Kind         string
	Purpose      string
	TokenDigest  []byte
	ClientDigest []byte
	IssuedAt     time.Time
	ExpiresAt    time.Time
	ConsumedAt   *time.Time
	Failures     int32
}

// A physical point of care in the patient journey (blueprint §3). Order is configurable (§5.2).
type CoreStation struct {
	ID           uuid.UUID
	FacilityID   uuid.UUID
	Code         string
	NameEn       string
	NameBn       string
	Room         string
	SequenceHint int32
	// False means the station exists in the design but nobody works it yet. The queue must not route to it.
	IsStaffed bool
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

// The planned journey per visit type. Data, not code: the sequences are an operational decision (CP39).
type CoreStationSequence struct {
	FacilityID  uuid.UUID
	VisitType   string
	Position    int32
	StationCode string
	Required    bool
}

// Coded diagnoses and complaints, per system and version (CP52). A coding stores both.
type CoreTerminologyConcept struct {
	System        string
	Version       string
	Code          string
	DisplayEn     string
	DisplayBn     string
	Heading       string
	HeadingBn     string
	FavouriteRank *int32
	RetiredAt     *time.Time
}

// Between two terminologies. Empty until D-24 answers whether SNOMED may be used here (CP52).
type CoreTerminologyMap struct {
	FromSystem  string
	FromVersion string
	FromCode    string
	ToSystem    string
	ToVersion   string
	ToCode      string
	Equivalence string
}

type CoreTerminologySynonym struct {
	System   string
	Version  string
	Code     string
	Term     string
	Language string
}

// Units and their conversion to their dimension's canonical unit. Two units convert if and only if they share a dimension (CP42).
type CoreUnit struct {
	Code string
	// Analyte-specific where the chemistry demands it: glucose and cholesterol concentrations are separate dimensions because the mmol/L↔mg/dL factor is a molar mass.
	Dimension   string
	IsCanonical bool
	Factor      pgtype.Numeric
	Offset      pgtype.Numeric
	DisplayEn   string
	DisplayBn   string
	Decimals    int32
}

// Role grants with their history. Revocation sets revoked_at; rows are never deleted [R-02].
type CoreUserRole struct {
	ID     uuid.UUID
	UserID uuid.UUID
	RoleID uuid.UUID
	// Where the role applies. Equals the user's facility today; separate so a multi-site user needs no second account.
	FacilityID   uuid.UUID
	GrantedBy    uuid.NullUUID
	GrantedAt    time.Time
	RevokedBy    uuid.NullUUID
	RevokedAt    *time.Time
	RevokeReason string
}

// One TOTP enrolment per user. The seed is a secretbox ciphertext, never plaintext.
type CoreUserTotp struct {
	UserID       uuid.UUID
	FacilityID   uuid.UUID
	SecretSealed []byte
	KeyID        string
	ConfirmedAt  *time.Time
	// Replay guard: the last 30-second step a code was accepted for. Earlier or equal steps are refused.
	LastUsedStep  *int64
	DisabledAt    *time.Time
	DisabledBy    uuid.NullUUID
	DisableReason string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// One journey through the clinic. §11.1's visit memory and §14.2's throughput both read this (CP38).
type CoreVisit struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	PatientID      uuid.UUID
	VisitCode      string
	VisitType      string
	ChiefComplaint string
	Status         string
	StatusReason   string
	// Asia/Dhaka. Separate from opened_at because a visit spanning midnight belongs to one day.
	ClinicDay      time.Time
	OpenedAt       time.Time
	OpenedBy       uuid.UUID
	ClosedAt       *time.Time
	ClosedBy       uuid.NullUUID
	Diagnoses      string
	Plan           string
	NextReviewDays *int32
	NextReviewOn   *time.Time
	ReopenedCount  int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CoreVisitCounter struct {
	FacilityID uuid.UUID
	ClinicDay  time.Time
	NextValue  int32
}

// patient_id ↔ research_id. Written once at registration; read only by the owner, under governance.
type IdentityLinkResearchSubject struct {
	PatientID  uuid.UUID
	ResearchID string
	FacilityID uuid.UUID
	LinkedAt   time.Time
}

// Aggregate state as of a sequence, for replay to resume from. Created at CP23 and unused until a measured need appears (§7.9).
type LedgerAggregateSnapshot struct {
	AggregateType string
	AggregateID   uuid.UUID
	Sequence      int64
	FacilityID    uuid.UUID
	State         []byte
	TakenAt       time.Time
}

// Security audit log: sign-ins, role changes, credential resets, exports, break-glass. Append-only, hash-chained, partitioned by month.
type LedgerAuditEvent struct {
	Seq          int64
	FacilityID   uuid.UUID
	Kind         string
	ActorUserID  uuid.NullUUID
	ActorCode    string
	ActorRole    string
	TargetUserID uuid.NullUUID
	TargetCode   string
	PatientID    uuid.NullUUID
	DeviceID     uuid.NullUUID
	SessionID    uuid.NullUUID
	Reason       string
	Details      []byte
	ClientDigest []byte
	RecordedAt   time.Time
	PrevHash     []byte
	Hash         []byte
}

type LedgerAuditEventDefault struct {
	Seq          int64
	FacilityID   uuid.UUID
	Kind         string
	ActorUserID  uuid.NullUUID
	ActorCode    string
	ActorRole    string
	TargetUserID uuid.NullUUID
	TargetCode   string
	PatientID    uuid.NullUUID
	DeviceID     uuid.NullUUID
	SessionID    uuid.NullUUID
	Reason       string
	Details      []byte
	ClientDigest []byte
	RecordedAt   time.Time
	PrevHash     []byte
	Hash         []byte
}

// Daily global anchor over the event ledger: SHA-256 fold of the day's event hashes, chained to the previous day.
type LedgerChainAnchor struct {
	Day            time.Time
	FacilityID     uuid.UUID
	EventCount     int64
	FirstGlobalSeq *int64
	LastGlobalSeq  *int64
	PrevAnchor     []byte
	Anchor         []byte
	ComputedAt     time.Time
}

// The clinical event ledger: the source of truth. Append-only by grant, rule and trigger; hash-chained per aggregate; partitioned by month.
type LedgerEvent struct {
	GlobalSeq     int64
	EventID       uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	Sequence      int64
	PatientID     uuid.NullUUID
	VisitID       uuid.NullUUID
	EventType     string
	EventVersion  int16
	OccurredAt    time.Time
	RecordedAt    time.Time
	ActorUserID   uuid.UUID
	ActorDeviceID uuid.UUID
	ActorRole     string
	ActorStation  *string
	FacilityID    uuid.UUID
	Source        string
	Payload       []byte
	Previous      []byte
	Correction    []byte
	Metadata      []byte
	PrevHash      []byte
	Hash          []byte
}

type LedgerEventDefault struct {
	GlobalSeq     int64
	EventID       uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	Sequence      int64
	PatientID     uuid.NullUUID
	VisitID       uuid.NullUUID
	EventType     string
	EventVersion  int16
	OccurredAt    time.Time
	RecordedAt    time.Time
	ActorUserID   uuid.UUID
	ActorDeviceID uuid.UUID
	ActorRole     string
	ActorStation  *string
	FacilityID    uuid.UUID
	Source        string
	Payload       []byte
	Previous      []byte
	Correction    []byte
	Metadata      []byte
	PrevHash      []byte
	Hash          []byte
}

// One row per event: enforces event_id and (aggregate, sequence) uniqueness across partitions and holds each aggregate's chain head.
type LedgerEventKey struct {
	EventID       uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	Sequence      int64
	GlobalSeq     int64
	RecordedAt    time.Time
	Hash          []byte
	FacilityID    uuid.UUID
}

// What happened to each case in one evaluation run. The run row carries the totals; this is where the case that regressed is named.
type OpsAiEvaluationCase struct {
	RunID       uuid.UUID
	CaseID      string
	Expectation string
	Outcome     string
	Findings    []byte
	LatencyMs   *int32
}

// One run of the frozen evaluation set against one prompt version and model version (CP72, §10.5). Append-only: a trend somebody can edit is not a trend.
type OpsAiEvaluationRun struct {
	ID               uuid.UUID
	AgentCode        string
	PromptVersion    string
	PromptSha256     string
	ModelVersion     string
	CaseSet          string
	CaseSetSha256    string
	GitSha           string
	Mode             string
	Cases            int32
	Injected         int32
	Detected         int32
	Correct          int32
	Blocked          int32
	SchemaFailures   int32
	LatencyP50Ms     *int32
	LatencyP95Ms     *int32
	CostMicroUsd     *int64
	Verdict          string
	RegressionDetail string
	StartedAt        time.Time
	FinishedAt       time.Time
}

// Which derived values depend on which demographic fields, so a correction knows what it invalidates (CP35).
type OpsDerivedDependency struct {
	DerivedName string
	DependsOn   string
	Action      string
	Description string
	AddedAt     time.Time
}

type OpsDeviceSyncState struct {
	DeviceID         uuid.UUID
	LastPulledSeq    int64
	LastPulledAt     *time.Time
	LastPushedAt     *time.Time
	LastSkewMs       *int64
	PushedTotal      int64
	QuarantinedTotal int64
}

// Cached responses for retried mutating requests, keyed per user (CP24, §7.5 layer 2). Operational, with a TTL — not a fact of history.
type OpsIdempotencyRecord struct {
	FacilityID  uuid.UUID
	UserID      uuid.UUID
	Key         string
	Fingerprint []byte
	State       string
	Status      *int32
	Headers     []byte
	Body        []byte
	ClaimedAt   time.Time
	CompletedAt *time.Time
	ExpiresAt   time.Time
}

// Every structural guarantee DTHCMS makes about its database. core.assert_invariants() runs exactly this list.
type OpsInvariant struct {
	SchemaName   string
	FunctionName string
	Description  string
	Sequence     int32
	AddedAt      time.Time
}

type OpsJob struct {
	ID          uuid.UUID
	Kind        string
	Queue       string
	Priority    int32
	Args        []byte
	DedupeKey   *string
	Status      string
	Attempt     int32
	MaxAttempts int32
	RunAt       time.Time
	EnqueuedAt  time.Time
	LeasedBy    *string
	LeasedUntil *time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
	SlaDeadline *time.Time
	MetSla      *bool
	LastError   string
}

type OpsJobAttempt struct {
	JobID    uuid.UUID
	Attempt  int32
	Worker   string
	FailedAt time.Time
	RanForMs int64
	Error    string
}

type OpsJobKind struct {
	Kind              string
	JobClass          string
	Queue             string
	Priority          int32
	MaxAttempts       int32
	BackoffSeconds    int32
	BackoffCapSeconds int32
	SlaSeconds        *int32
	DescriptionEn     string
	DescriptionBn     string
	PausedAt          *time.Time
	PausedBy          uuid.NullUUID
}

type OpsJobSchedule struct {
	Kind         string
	EverySeconds int32
	Args         []byte
	NextRunAt    time.Time
	LastRunAt    *time.Time
	PausedAt     *time.Time
}

// SHA-256 of each migration file as applied. Drift means a migration was edited after it ran.
type OpsMigrationChecksum struct {
	Version   int64
	Filename  string
	Sha256    string
	AppliedAt time.Time
	// The database role that applied it. Grants from ALTER DEFAULT PRIVILEGES depend on this being stable.
	AppliedBy string
}

type OpsPhiKey struct {
	Key      string
	Guidance string
	// IDENTIFIER: says which person this is; never leaves the boundary. CLINICAL: what is wrong with them; banned from logs and job arguments, permitted in a minimised AI payload because summarising it is what the model is for. CREDENTIAL: grants access; belongs nowhere.
	Class string
}

type OpsPiiPattern struct {
	Kind          string
	Pattern       string
	Replacement   string
	DescriptionEn string
	DescriptionBn string
}

type OpsSyncBatch struct {
	ID          uuid.UUID
	DeviceID    uuid.UUID
	UserID      uuid.UUID
	FacilityID  uuid.UUID
	ReceivedAt  time.Time
	ClientClock *time.Time
	SkewMs      *int64
	ClosedAt    *time.Time
	Events      int32
	Accepted    int32
	Duplicated  int32
	Rejected    int32
	Quarantined int32
	Blocked     int32
}

type OpsSyncQuarantine struct {
	ID              uuid.UUID
	BatchID         uuid.UUID
	EventID         uuid.UUID
	DeviceID        uuid.UUID
	UserID          uuid.UUID
	FacilityID      uuid.UUID
	ReasonCode      string
	Reason          string
	Envelope        []byte
	EventType       string
	OccurredAt      time.Time
	PatientID       uuid.NullUUID
	HeldAt          time.Time
	Status          string
	ResolvedAt      *time.Time
	ResolvedBy      uuid.NullUUID
	ResolutionNote  string
	ReleasedEventID uuid.NullUUID
}

type OpsSyncResult struct {
	BatchID    uuid.UUID
	EventID    uuid.UUID
	Outcome    string
	ReasonCode string
	Reason     string
	GlobalSeq  *int64
}

// One recorded allergy. Never deleted; withdrawn ones keep their reason (CP54).
type ReadAllergy struct {
	ID            uuid.UUID
	FacilityID    uuid.UUID
	PatientID     uuid.UUID
	CodeSystem    *string
	CodeVersion   *string
	Code          *string
	Said          string
	Reaction      string
	Severity      string
	Certainty     string
	Note          string
	RecordedAt    time.Time
	RecordedBy    uuid.UUID
	RecordedRole  string
	RecordedVisit uuid.NullUUID
	RemovedAt     *time.Time
	RemovedBy     uuid.NullUUID
	RemovedReason string
	EventID       uuid.UUID
	GlobalSeq     int64
	DeviceID      uuid.NullUUID
	StationCode   string
	Source        string
}

// An explicit, attributed statement about allergy status. Criterion 2 (CP54).
type ReadAllergyAssertion struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	PatientID       uuid.UUID
	Kind            string
	Reason          string
	AssertedAt      time.Time
	AssertedBy      uuid.UUID
	AssertedRole    string
	AssertedVisit   uuid.NullUUID
	WithdrawnAt     *time.Time
	WithdrawnBy     uuid.NullUUID
	WithdrawnReason string
	EventID         uuid.UUID
	GlobalSeq       int64
	DeviceID        uuid.NullUUID
	StationCode     string
	Source          string
}

// One value somebody said was wrong, routed to whoever typed it (CP62, §4.3).
type ReadCorrectionRequest struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	PatientID      uuid.UUID
	VisitID        uuid.NullUUID
	ObservationID  uuid.UUID
	Code           string
	RequestedAt    time.Time
	RequestedBy    uuid.UUID
	RequestedRole  string
	ReasonCode     string
	Note           string
	AssignedTo     uuid.UUID
	Status         string
	ResolvedAt     *time.Time
	ResolvedBy     uuid.NullUUID
	ResolvedRole   string
	ResolutionNote string
	ReplacementID  uuid.NullUUID
	Recomputed     []string
	EventID        uuid.UUID
	GlobalSeq      int64
}

// A patient let past the counselling gate, by a named person, with a reason (CP57).
type ReadCounselingGateOverride struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	VisitID        uuid.UUID
	PatientID      uuid.UUID
	GrantedAt      time.Time
	GrantedBy      uuid.UUID
	GrantedRole    string
	Reason         string
	MissingAtGrant []string
	EventID        uuid.UUID
	GlobalSeq      int64
}

// One walk through one checklist, for one visit (CP56). Holds the template version it used.
type ReadCounselingSession struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	PatientID       uuid.UUID
	VisitID         uuid.UUID
	TemplateID      uuid.UUID
	TemplateVersion int32
	StartedAt       time.Time
	StartedBy       uuid.UUID
	StartedRole     string
	CompletedAt     *time.Time
	CompletedBy     uuid.NullUUID
	EventID         uuid.UUID
	GlobalSeq       int64
}

// One item covered, by one person, at one time (CP56 criterion 1). Un-ticks keep the row.
type ReadCounselingTick struct {
	SessionID    uuid.UUID
	ItemCode     string
	FacilityID   uuid.UUID
	PatientID    uuid.UUID
	TickedAt     time.Time
	TickedBy     uuid.UUID
	TickedRole   string
	Note         string
	UndoneAt     *time.Time
	UndoneBy     uuid.NullUUID
	UndoneReason string
	UndoCount    int32
	EventID      uuid.UUID
	GlobalSeq    int64
	DeviceID     uuid.NullUUID
	StationCode  string
}

// One row per critical value raised (CP50). Written only by the projector; the ledger is the record.
type ReadCriticalAlert struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	PatientID       uuid.UUID
	VisitID         uuid.NullUUID
	ObservationID   uuid.UUID
	Code            string
	ValueNum        pgtype.Numeric
	Unit            *string
	RuleID          uuid.NullUUID
	Breached        string
	Threshold       pgtype.Numeric
	ActionEn        string
	ActionBn        string
	RaisedAt        time.Time
	RaisedBy        uuid.UUID
	RaisedRole      string
	StationCode     string
	Status          string
	AcknowledgedBy  uuid.NullUUID
	AcknowledgedAt  *time.Time
	Acknowledgement string
	EscalationStep  int32
	EscalatedAt     *time.Time
	NotifiedAt      *time.Time
	Recipients      int32
	DeliveryError   string
	EventID         uuid.UUID
	GlobalSeq       int64
}

// One thing a patient said they ate (CP59). Never edited or merged: two operators cannot collide because they never write the same row.
type ReadDietEntry struct {
	ID              uuid.UUID
	FacilityID      uuid.UUID
	PatientID       uuid.UUID
	VisitID         uuid.NullUUID
	RecallDate      time.Time
	Meal            string
	EatenAtHour     *int32
	FoodCode        string
	MeasureCode     string
	Quantity        pgtype.Numeric
	Grams           pgtype.Numeric
	Kcal            pgtype.Numeric
	Protein         pgtype.Numeric
	Carb            pgtype.Numeric
	Fat             pgtype.Numeric
	Note            string
	RecordedAt      time.Time
	RecordedBy      uuid.UUID
	RecordedRole    string
	StationCode     string
	DeviceID        uuid.NullUUID
	Source          string
	WithdrawnAt     *time.Time
	WithdrawnBy     uuid.NullUUID
	WithdrawnReason string
	EventID         uuid.UUID
	GlobalSeq       int64
}

type ReadExerciseAssessment struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	PatientID         uuid.UUID
	VisitID           uuid.NullUUID
	WalksUnaided      *bool
	WalkMinutes       *int32
	JointPain         string
	Contraindications []string
	Asked             []string
	Note              string
	Status            string
	RecordedAt        time.Time
	RecordedBy        uuid.UUID
	RecordedRole      string
	StationCode       string
	DeviceID          uuid.NullUUID
	Source            string
	EventID           uuid.UUID
	GlobalSeq         int64
}

type ReadExercisePlan struct {
	ID           uuid.UUID
	FacilityID   uuid.UUID
	PatientID    uuid.UUID
	VisitID      uuid.NullUUID
	AssessmentID uuid.UUID
	Status       string
	IssuedAt     time.Time
	IssuedBy     uuid.UUID
	IssuedRole   string
	StationCode  string
	DeviceID     uuid.NullUUID
	Source       string
	Note         string
	EventID      uuid.UUID
	GlobalSeq    int64
}

type ReadExercisePlanItem struct {
	PlanID            uuid.UUID
	ExerciseCode      string
	TimesPerWeek      int32
	MinutesPerSession int32
	Ordering          int32
	Note              string
}

// One thing the patient brings with them, with an identity that outlives the visit (CP53).
type ReadHistoryItem struct {
	ID                 uuid.UUID
	FacilityID         uuid.UUID
	PatientID          uuid.UUID
	Kind               string
	CodeSystem         *string
	CodeVersion        *string
	Code               *string
	Said               string
	Relation           *string
	DurationDays       *int32
	Severity           *string
	OnsetOn            *time.Time
	OnsetPrecision     *string
	Dose               string
	Frequency          string
	FormularyProductID uuid.NullUUID
	Reconciliation     *string
	Status             string
	RecordedAt         time.Time
	RecordedBy         uuid.UUID
	RecordedRole       string
	RecordedVisit      uuid.NullUUID
	ConfirmedAt        *time.Time
	ConfirmedBy        uuid.NullUUID
	ConfirmedVisit     uuid.NullUUID
	AmendedAt          *time.Time
	AmendedBy          uuid.NullUUID
	RemovedAt          *time.Time
	RemovedBy          uuid.NullUUID
	RemovedReason      string
	EventID            uuid.UUID
	GlobalSeq          int64
	DeviceID           uuid.NullUUID
	StationCode        string
	Source             string
}

// One row per item answered. Raw responses, not totals (CP58 criterion 1) — a total cannot be re-scored.
type ReadInstrumentAnswer struct {
	ResponseID uuid.UUID
	ItemCode   string
	OptionCode *string
	ValueNum   pgtype.Numeric
	ValueBool  *bool
	Score      int32
}

type ReadInstrumentResponse struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	PatientID         uuid.UUID
	VisitID           uuid.NullUUID
	InstrumentCode    string
	InstrumentVersion int32
	RecordedAt        time.Time
	RecordedBy        uuid.UUID
	RecordedRole      string
	StationCode       string
	DeviceID          uuid.NullUUID
	Source            string
	Status            string
	ReplacedBy        uuid.NullUUID
	EventID           uuid.UUID
	GlobalSeq         int64
}

// Every measured clinical value, in one shape: canonical value for arithmetic, entered value for display, unit metadata for both (CP42).
type ReadObservation struct {
	ID          uuid.UUID
	FacilityID  uuid.UUID
	PatientID   uuid.UUID
	VisitID     uuid.NullUUID
	EncounterID uuid.NullUUID
	Code        string
	Category    string
	ValueType   string
	ValueNum    pgtype.Numeric
	Unit        *string
	// As typed. Showing a value back in the unit it was entered in is a read, not a round trip.
	EnteredNum   pgtype.Numeric
	EnteredUnit  *string
	ValueText    string
	ValueBool    *bool
	ValueCode    string
	ValueJson    []byte
	EffectiveAt  time.Time
	RecordedAt   time.Time
	Source       string
	Status       string
	ReplacedBy   uuid.NullUUID
	RecordedBy   uuid.UUID
	RecordedRole string
	StationCode  string
	DeviceID     uuid.NullUUID
	EventID      uuid.UUID
	GlobalSeq    int64
	Note         string
	// For a DERIVED value: which equation produced it. Empty for a measurement (CP43).
	Formula string
	// The equation's version at computation time. CKD-EPI has already changed once; a value without this cannot be interpreted later (CP43).
	FormulaVersion string
	// What the formula was given, in canonical units. What it *actually saw* — a later correction to an input does not change what this value was computed from (CP43).
	Inputs []byte
	// The operator was warned this value was outside the plausible band and confirmed it (CP46).
	ImplausibleConfirmed bool
	ImplausibleReason    string
}

// The patient as a screen shows them, derived from PATIENT_REGISTERED. Synchronous projection (CP29).
type ReadPatient struct {
	PatientID          uuid.UUID
	FacilityID         uuid.UUID
	ClinicalID         string
	NameEn             string
	NameBn             string
	Sex                string
	BirthDate          time.Time
	DobPrecision       string
	DobSource          string
	PhonePrimary       string
	PhoneSecondary     string
	Division           string
	District           string
	Upazila            string
	AddressLine        string
	Postcode           string
	EmergencyName      string
	EmergencyRelation  string
	EmergencyPhone     string
	EducationLevel     *string
	OccupationCategory *string
	IncomeBand         *string
	HouseholdSize      *int16
	ResidenceType      *string
	MedicinePayer      *string
	// Which official numbers are on file. Never the numbers themselves — those are sealed in core.patient_identifier (D-47).
	IdentifierKinds   []string
	ConsentReference  string
	Status            string
	RegisteredAt      time.Time
	RegisteredBy      uuid.UUID
	RegisteredRole    string
	RegisteredStation string
	EventID           uuid.UUID
	GlobalSeq         int64
	// The phonetic key of name_en, for blocking candidates. Computed in Go; see internal/platform/textmatch (CP30).
	NameKeyEn    string
	MergedIntoID uuid.NullUUID
}

// What is true now, per patient per consent type. Derived from CONSENT_GRANTED/CONSENT_REVOKED (CP36).
type ReadPatientConsent struct {
	PatientID          uuid.UUID
	FacilityID         uuid.UUID
	ConsentType        string
	Status             string
	TemplateVersion    int32
	Language           string
	TemplateDigest     string
	CaptureMethod      string
	EvidenceKey        string
	EvidenceSha256     string
	PaperReference     string
	WitnessedBy        uuid.NullUUID
	WitnessedByCode    string
	GrantedForRelation string
	GrantedForName     string
	GrantedAt          time.Time
	GrantedBy          uuid.UUID
	GrantedByCode      string
	RevokedAt          *time.Time
	RevokedBy          uuid.NullUUID
	RevokedByCode      string
	RevokeReason       string
	RevokeRequestedBy  string
	EventID            uuid.UUID
	GlobalSeq          int64
}

// Every grant and revocation in order, so "was this lawful at the time" is answerable (CP36).
type ReadPatientConsentEvent struct {
	ID              int64
	PatientID       uuid.UUID
	FacilityID      uuid.UUID
	ConsentType     string
	Action          string
	TemplateVersion *int32
	Language        string
	CaptureMethod   string
	Reason          string
	RequestedBy     string
	ActorID         uuid.UUID
	ActorCode       string
	OccurredAt      time.Time
	EventID         uuid.UUID
	GlobalSeq       int64
}

// The demographic change history, derived from PATIENT_DEMOGRAPHICS_CORRECTED. The originals are in the ledger (CP35).
type ReadPatientCorrection struct {
	ID              int64
	PatientID       uuid.UUID
	FacilityID      uuid.UUID
	Field           string
	Previous        string
	Current         string
	Reason          string
	HighImpact      bool
	CorrectedBy     uuid.UUID
	CorrectedByCode string
	CorrectedAt     time.Time
	EventID         uuid.UUID
	GlobalSeq       int64
}

// Everything known about a patient, in one chronological shape, attributed per row (CP37, §8).
type ReadPatientTimeline struct {
	ID           int64
	PatientID    uuid.UUID
	FacilityID   uuid.UUID
	OccurredAt   time.Time
	RecordedAt   time.Time
	Category     string
	Kind         string
	LabelEn      string
	LabelBn      string
	Value        string
	Unit         string
	ValueNum     pgtype.Numeric
	ActorID      uuid.NullUUID
	ActorCode    string
	ActorRole    string
	ActorStation string
	DeviceID     uuid.NullUUID
	Source       string
	Flags        []string
	EventID      uuid.UUID
	EventType    string
	GlobalSeq    int64
	Item         string
	// The permission a reader needs. Filtering happens in SQL so a hidden row cannot skew a count or a cursor.
	NeedsPermission string
	SupersededBy    uuid.NullUUID
}

// One prescription, projected from the ledger (CP80). The ledger is the truth; this is its current shape.
type ReadPrescription struct {
	ID                        uuid.UUID
	FacilityID                uuid.UUID
	PatientID                 uuid.UUID
	VisitID                   uuid.UUID
	Status                    string
	CreatedAt                 time.Time
	CreatedBy                 uuid.UUID
	CreatedRole               string
	SubmittedAt               *time.Time
	SubmittedBy               uuid.NullUUID
	BouncedAt                 *time.Time
	BouncedBy                 uuid.NullUUID
	SignedAt                  *time.Time
	SignedBy                  uuid.NullUUID
	PrintedAt                 *time.Time
	PrintedBy                 uuid.NullUUID
	DispensedAt               *time.Time
	DispensedBy               uuid.NullUUID
	CancelledAt               *time.Time
	CancelledBy               uuid.NullUUID
	CancelledReason           string
	CorrectedAt               *time.Time
	CorrectedBy               uuid.NullUUID
	CorrectsPrescriptionID    uuid.NullUUID
	CorrectionReason          string
	CorrectedByPrescriptionID uuid.NullUUID
	CorrectsDispensedOriginal bool
	CarriedForwardFrom        uuid.NullUUID
	CreatedEventID            uuid.UUID
	LastEventID               uuid.UUID
	LastGlobalSeq             int64
	UpdatedAt                 time.Time
}

// One line of a prescription, with the price as it was on the day it was written (CP80).
type ReadPrescriptionItem struct {
	ID                     uuid.UUID
	PrescriptionID         uuid.UUID
	FacilityID             uuid.UUID
	LineNo                 int32
	ProductID              uuid.NullUUID
	ProductLabel           string
	GenericName            string
	Strength               string
	FormCode               string
	Dose                   string
	DailyDose              pgtype.Numeric
	DoseUnit               string
	Frequency              string
	DurationDays           *int32
	Route                  string
	Quantity               pgtype.Numeric
	InstructionsEn         string
	InstructionsBn         string
	PricePoisha            *int64
	PriceID                uuid.NullUUID
	PriceEffectiveFrom     *time.Time
	PriceVerification      *string
	PriceCapturedAt        *time.Time
	CarriedForwardFromItem uuid.NullUUID
	RecordedAt             time.Time
	RecordedBy             uuid.UUID
	ModifiedAt             *time.Time
	ModifiedBy             uuid.NullUUID
	RemovedAt              *time.Time
	RemovedBy              uuid.NullUUID
	RemovedReason          string
	EventID                uuid.UUID
	GlobalSeq              int64
}

// Events a projection could not apply. The projection stays degraded until each is resolved (CP25).
type ReadProjectionDeadLetter struct {
	ID         int64
	Projection string
	GlobalSeq  int64
	EventID    uuid.UUID
	EventType  string
	Error      string
	Attempts   int32
	FailedAt   time.Time
	ResolvedAt *time.Time
	Resolution *string
}

// One row per projection: version, mode, how far it has got, and whether it is healthy (CP25).
type ReadProjectionState struct {
	Name       string
	Version    int32
	Mode       string
	Checkpoint int64
	Status     string
	AppliedAt  *time.Time
	UpdatedAt  time.Time
	RebuiltAt  *time.Time
}

// Per-station, per-day activity for the traffic board. Asynchronous projection (CP25).
type ReadStationActivity struct {
	FacilityID uuid.UUID
	ClinicDay  time.Time
	Station    string
	Events     int64
	LastSeq    int64
	UpdatedAt  time.Time
}

type ReadStationActivityVisit struct {
	FacilityID uuid.UUID
	ClinicDay  time.Time
	Station    string
	VisitID    uuid.UUID
}

// The current value of each measurement on a visit, with its attribution. Synchronous projection (CP25).
type ReadVisitVital struct {
	VisitID      uuid.UUID
	Code         string
	FacilityID   uuid.UUID
	PatientID    uuid.NullUUID
	Value        pgtype.Numeric
	Unit         string
	Value2       pgtype.Numeric
	TakenAt      time.Time
	RecordedAt   time.Time
	ActorUserID  uuid.UUID
	ActorRole    string
	ActorStation *string
	EventID      uuid.UUID
	GlobalSeq    int64
	Corrected    bool
}

// The consenting subjects, and the only thing dthcms_research may read. Consent is enforced by privilege (CP36).
type ResearchCohort struct {
	ResearchID         string
	FacilityCode       string
	EnrolledMonth      time.Time
	BirthYear          int16
	Sex                string
	EducationLevel     *string
	OccupationCategory *string
	IncomeBand         *string
	HouseholdSize      *int16
	ResidenceType      *string
	MedicinePayer      *string
	CreatedAt          time.Time
}

// The anonymised subject a researcher queries. Carries no identifier and no join path to core (CP28, §12).
type ResearchResearchSubject struct {
	// Opaque, from a cryptographic random source. Not derivable from the clinical id, and carrying no ordering.
	ResearchID         string
	FacilityCode       string
	EnrolledMonth      time.Time
	BirthYear          int16
	Sex                string
	EducationLevel     *string
	OccupationCategory *string
	IncomeBand         *string
	HouseholdSize      *int16
	ResidenceType      *string
	MedicinePayer      *string
	CreatedAt          time.Time
	// Opt-in, never assumed. False until a RESEARCH consent is granted, false again on revocation (CP36, D-02).
	ResearchConsent bool
}
