// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: observation.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const observationByID = `-- name: ObservationByID :one
SELECT id, facility_id, patient_id, visit_id, encounter_id, code, category, value_type, value_num, unit, entered_num, entered_unit, value_text, value_bool, value_code, value_json, effective_at, recorded_at, source, status, replaced_by, recorded_by, recorded_role, station_code, device_id, event_id, global_seq, note, formula, formula_version, inputs FROM read.observation WHERE id = $1 AND facility_id = $2
`

type ObservationByIDParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

func (q *Queries) ObservationByID(ctx context.Context, arg ObservationByIDParams) (ReadObservation, error) {
	row := q.db.QueryRow(ctx, observationByID, arg.ID, arg.FacilityID)
	var i ReadObservation
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.PatientID,
		&i.VisitID,
		&i.EncounterID,
		&i.Code,
		&i.Category,
		&i.ValueType,
		&i.ValueNum,
		&i.Unit,
		&i.EnteredNum,
		&i.EnteredUnit,
		&i.ValueText,
		&i.ValueBool,
		&i.ValueCode,
		&i.ValueJson,
		&i.EffectiveAt,
		&i.RecordedAt,
		&i.Source,
		&i.Status,
		&i.ReplacedBy,
		&i.RecordedBy,
		&i.RecordedRole,
		&i.StationCode,
		&i.DeviceID,
		&i.EventID,
		&i.GlobalSeq,
		&i.Note,
		&i.Formula,
		&i.FormulaVersion,
		&i.Inputs,
	)
	return i, err
}

const observationCodeByCode = `-- name: ObservationCodeByCode :one
SELECT c.code, c.category, c.value_type, c.dimension, c.loinc,
       c.display_en, c.display_bn, c.min_canonical, c.max_canonical, c.write_permission,
       c.retired_at,
       -- COALESCE, because a unitless code has no canonical unit and sqlc types this
       -- column from the cast: without it the driver is handed a NULL it cannot scan into
       -- a string, and every read of the registry is a 500.
       COALESCE((SELECT u.code FROM core.unit u
                  WHERE u.dimension = c.dimension AND u.is_canonical), '')::text AS canonical_unit
  FROM core.observation_code c
 WHERE c.code = $1
`

type ObservationCodeByCodeRow struct {
	Code            string
	Category        string
	ValueType       string
	Dimension       *string
	Loinc           string
	DisplayEn       string
	DisplayBn       string
	MinCanonical    pgtype.Numeric
	MaxCanonical    pgtype.Numeric
	WritePermission string
	RetiredAt       *time.Time
	CanonicalUnit   string
}

func (q *Queries) ObservationCodeByCode(ctx context.Context, code string) (ObservationCodeByCodeRow, error) {
	row := q.db.QueryRow(ctx, observationCodeByCode, code)
	var i ObservationCodeByCodeRow
	err := row.Scan(
		&i.Code,
		&i.Category,
		&i.ValueType,
		&i.Dimension,
		&i.Loinc,
		&i.DisplayEn,
		&i.DisplayBn,
		&i.MinCanonical,
		&i.MaxCanonical,
		&i.WritePermission,
		&i.RetiredAt,
		&i.CanonicalUnit,
	)
	return i, err
}

const observationCodes = `-- name: ObservationCodes :many

SELECT c.code, c.category, c.value_type, c.dimension, c.loinc,
       c.display_en, c.display_bn, c.min_canonical, c.max_canonical, c.write_permission,
       -- COALESCE, because a unitless code has no canonical unit and sqlc types this
       -- column from the cast: without it the driver is handed a NULL it cannot scan into
       -- a string, and every read of the registry is a 500.
       COALESCE((SELECT u.code FROM core.unit u
                  WHERE u.dimension = c.dimension AND u.is_canonical), '')::text AS canonical_unit
  FROM core.observation_code c
 WHERE c.retired_at IS NULL
 ORDER BY c.category, c.code
`

type ObservationCodesRow struct {
	Code            string
	Category        string
	ValueType       string
	Dimension       *string
	Loinc           string
	DisplayEn       string
	DisplayBn       string
	MinCanonical    pgtype.Numeric
	MaxCanonical    pgtype.Numeric
	WritePermission string
	CanonicalUnit   string
}

// Observations and the registry that gives them meaning (CP42).
// The whole registry, with each code's canonical unit. One query rather than three, because
// a station app fetches this once on start-up and then validates every entry against it,
// offline, for the rest of the clinic session.
func (q *Queries) ObservationCodes(ctx context.Context) ([]ObservationCodesRow, error) {
	rows, err := q.db.Query(ctx, observationCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationCodesRow{}
	for rows.Next() {
		var i ObservationCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.Category,
			&i.ValueType,
			&i.Dimension,
			&i.Loinc,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.MinCanonical,
			&i.MaxCanonical,
			&i.WritePermission,
			&i.CanonicalUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationHistoryForCode = `-- name: ObservationHistoryForCode :many
SELECT id, facility_id, patient_id, visit_id, encounter_id, code, category, value_type, value_num, unit, entered_num, entered_unit, value_text, value_bool, value_code, value_json, effective_at, recorded_at, source, status, replaced_by, recorded_by, recorded_role, station_code, device_id, event_id, global_seq, note, formula, formula_version, inputs FROM read.observation
 WHERE patient_id = $1 AND facility_id = $2 AND code = $3
 ORDER BY effective_at DESC, recorded_at DESC
 LIMIT $4
`

type ObservationHistoryForCodeParams struct {
	PatientID  uuid.UUID
	FacilityID uuid.UUID
	Code       string
	Limit      int32
}

// Every value ever recorded for one code on one patient, the replaced ones included. This is
// what a trend line reads, and what somebody asking "what did it say before" reads.
func (q *Queries) ObservationHistoryForCode(ctx context.Context, arg ObservationHistoryForCodeParams) ([]ReadObservation, error) {
	rows, err := q.db.Query(ctx, observationHistoryForCode,
		arg.PatientID,
		arg.FacilityID,
		arg.Code,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadObservation{}
	for rows.Next() {
		var i ReadObservation
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.PatientID,
			&i.VisitID,
			&i.EncounterID,
			&i.Code,
			&i.Category,
			&i.ValueType,
			&i.ValueNum,
			&i.Unit,
			&i.EnteredNum,
			&i.EnteredUnit,
			&i.ValueText,
			&i.ValueBool,
			&i.ValueCode,
			&i.ValueJson,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.Source,
			&i.Status,
			&i.ReplacedBy,
			&i.RecordedBy,
			&i.RecordedRole,
			&i.StationCode,
			&i.DeviceID,
			&i.EventID,
			&i.GlobalSeq,
			&i.Note,
			&i.Formula,
			&i.FormulaVersion,
			&i.Inputs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsForPatient = `-- name: ObservationsForPatient :many
SELECT id, facility_id, patient_id, visit_id, encounter_id, code, category, value_type, value_num, unit, entered_num, entered_unit, value_text, value_bool, value_code, value_json, effective_at, recorded_at, source, status, replaced_by, recorded_by, recorded_role, station_code, device_id, event_id, global_seq, note, formula, formula_version, inputs FROM read.observation
 WHERE patient_id = $1 AND facility_id = $2 AND status = 'ACTIVE'
   AND ($3::text = '' OR category = $3::text)
 ORDER BY effective_at DESC, code
 LIMIT $4
`

type ObservationsForPatientParams struct {
	PatientID  uuid.UUID
	FacilityID uuid.UUID
	Column3    string
	Limit      int32
}

// The current value of everything, newest first. Corrected and superseded rows are history,
// and history is read through ObservationHistoryForCode.
func (q *Queries) ObservationsForPatient(ctx context.Context, arg ObservationsForPatientParams) ([]ReadObservation, error) {
	rows, err := q.db.Query(ctx, observationsForPatient,
		arg.PatientID,
		arg.FacilityID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadObservation{}
	for rows.Next() {
		var i ReadObservation
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.PatientID,
			&i.VisitID,
			&i.EncounterID,
			&i.Code,
			&i.Category,
			&i.ValueType,
			&i.ValueNum,
			&i.Unit,
			&i.EnteredNum,
			&i.EnteredUnit,
			&i.ValueText,
			&i.ValueBool,
			&i.ValueCode,
			&i.ValueJson,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.Source,
			&i.Status,
			&i.ReplacedBy,
			&i.RecordedBy,
			&i.RecordedRole,
			&i.StationCode,
			&i.DeviceID,
			&i.EventID,
			&i.GlobalSeq,
			&i.Note,
			&i.Formula,
			&i.FormulaVersion,
			&i.Inputs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsForVisit = `-- name: ObservationsForVisit :many
SELECT id, facility_id, patient_id, visit_id, encounter_id, code, category, value_type, value_num, unit, entered_num, entered_unit, value_text, value_bool, value_code, value_json, effective_at, recorded_at, source, status, replaced_by, recorded_by, recorded_role, station_code, device_id, event_id, global_seq, note, formula, formula_version, inputs FROM read.observation
 WHERE visit_id = $1 AND facility_id = $2 AND status = 'ACTIVE'
 ORDER BY effective_at, code
`

type ObservationsForVisitParams struct {
	VisitID    uuid.NullUUID
	FacilityID uuid.UUID
}

func (q *Queries) ObservationsForVisit(ctx context.Context, arg ObservationsForVisitParams) ([]ReadObservation, error) {
	rows, err := q.db.Query(ctx, observationsForVisit, arg.VisitID, arg.FacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadObservation{}
	for rows.Next() {
		var i ReadObservation
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.PatientID,
			&i.VisitID,
			&i.EncounterID,
			&i.Code,
			&i.Category,
			&i.ValueType,
			&i.ValueNum,
			&i.Unit,
			&i.EnteredNum,
			&i.EnteredUnit,
			&i.ValueText,
			&i.ValueBool,
			&i.ValueCode,
			&i.ValueJson,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.Source,
			&i.Status,
			&i.ReplacedBy,
			&i.RecordedBy,
			&i.RecordedRole,
			&i.StationCode,
			&i.DeviceID,
			&i.EventID,
			&i.GlobalSeq,
			&i.Note,
			&i.Formula,
			&i.FormulaVersion,
			&i.Inputs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitByCode = `-- name: UnitByCode :one
SELECT code, dimension, is_canonical, factor, "offset", display_en, display_bn, decimals FROM core.unit WHERE code = $1
`

func (q *Queries) UnitByCode(ctx context.Context, code string) (CoreUnit, error) {
	row := q.db.QueryRow(ctx, unitByCode, code)
	var i CoreUnit
	err := row.Scan(
		&i.Code,
		&i.Dimension,
		&i.IsCanonical,
		&i.Factor,
		&i.Offset,
		&i.DisplayEn,
		&i.DisplayBn,
		&i.Decimals,
	)
	return i, err
}

const units = `-- name: Units :many
SELECT code, dimension, is_canonical, factor, "offset", display_en, display_bn, decimals FROM core.unit ORDER BY dimension, is_canonical DESC, code
`

func (q *Queries) Units(ctx context.Context) ([]CoreUnit, error) {
	rows, err := q.db.Query(ctx, units)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUnit{}
	for rows.Next() {
		var i CoreUnit
		if err := rows.Scan(
			&i.Code,
			&i.Dimension,
			&i.IsCanonical,
			&i.Factor,
			&i.Offset,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.Decimals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
