// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: offline.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const batchReceipt = `-- name: BatchReceipt :one
SELECT id, device_id, user_id, facility_id, received_at, closed_at, client_clock, skew_ms,
       events, accepted, duplicated, rejected, quarantined, blocked
  FROM ops.sync_batch
 WHERE id = $1
`

type BatchReceiptRow struct {
	ID          uuid.UUID
	DeviceID    uuid.UUID
	UserID      uuid.UUID
	FacilityID  uuid.UUID
	ReceivedAt  time.Time
	ClosedAt    *time.Time
	ClientClock *time.Time
	SkewMs      *int64
	Events      int32
	Accepted    int32
	Duplicated  int32
	Rejected    int32
	Quarantined int32
	Blocked     int32
}

// What happened to a batch, for a client that lost the response.
//
// The case this exists for is not a duplicate submission — the ledger absorbs those. It is the
// client that sent fifty events, the server processed them, and the answer was lost on the way
// back. Without this the client can only resend and hope, or drop and hope.
func (q *Queries) BatchReceipt(ctx context.Context, id uuid.UUID) (BatchReceiptRow, error) {
	row := q.db.QueryRow(ctx, batchReceipt, id)
	var i BatchReceiptRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.FacilityID,
		&i.ReceivedAt,
		&i.ClosedAt,
		&i.ClientClock,
		&i.SkewMs,
		&i.Events,
		&i.Accepted,
		&i.Duplicated,
		&i.Rejected,
		&i.Quarantined,
		&i.Blocked,
	)
	return i, err
}

const closeBatch = `-- name: CloseBatch :exec
UPDATE ops.sync_batch
   SET closed_at = $1, events = $2, accepted = $3,
       duplicated = $4, rejected = $5,
       quarantined = $6, blocked = $7
 WHERE id = $8
`

type CloseBatchParams struct {
	Now         *time.Time
	Events      int32
	Accepted    int32
	Duplicated  int32
	Rejected    int32
	Quarantined int32
	Blocked     int32
	ID          uuid.UUID
}

func (q *Queries) CloseBatch(ctx context.Context, arg CloseBatchParams) error {
	_, err := q.db.Exec(ctx, closeBatch,
		arg.Now,
		arg.Events,
		arg.Accepted,
		arg.Duplicated,
		arg.Rejected,
		arg.Quarantined,
		arg.Blocked,
		arg.ID,
	)
	return err
}

const deviceForSync = `-- name: DeviceForSync :one

SELECT d.id, d.facility_id, d.status, d.name, coalesce(d.status_reason, '') AS status_reason
  FROM core.device d
 WHERE d.id = $1
`

type DeviceForSyncRow struct {
	ID           uuid.UUID
	FacilityID   uuid.UUID
	Status       string
	Name         string
	StatusReason string
}

// The offline sync protocol (CP65).
// Who is sending, and whether they may. The status decides between accepting and quarantining, so
// it is read once per batch rather than per event — a device does not get revoked halfway through
// fifty blood pressures, and reading it fifty times would only make the answer inconsistent.
func (q *Queries) DeviceForSync(ctx context.Context, id uuid.UUID) (DeviceForSyncRow, error) {
	row := q.db.QueryRow(ctx, deviceForSync, id)
	var i DeviceForSyncRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Status,
		&i.Name,
		&i.StatusReason,
	)
	return i, err
}

const discardHeldEvent = `-- name: DiscardHeldEvent :one
UPDATE ops.sync_quarantine
   SET status = 'DISCARDED', resolved_at = $1, resolved_by = $2,
       resolution_note = $3
 WHERE id = $4 AND facility_id = $5 AND status = 'HELD'
RETURNING id, status
`

type DiscardHeldEventParams struct {
	Now        *time.Time
	ResolvedBy uuid.NullUUID
	Note       string
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type DiscardHeldEventRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) DiscardHeldEvent(ctx context.Context, arg DiscardHeldEventParams) (DiscardHeldEventRow, error) {
	row := q.db.QueryRow(ctx, discardHeldEvent,
		arg.Now,
		arg.ResolvedBy,
		arg.Note,
		arg.ID,
		arg.FacilityID,
	)
	var i DiscardHeldEventRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const eventsSince = `-- name: EventsSince :many
SELECT e.event_id, e.global_seq, e.aggregate_type, e.aggregate_id, e.patient_id, e.visit_id,
       e.event_type, e.event_version, e.occurred_at, e.recorded_at, e.payload,
       e.actor_user_id, e.actor_role, e.actor_station, e.facility_id, e.source
  FROM ledger.event e
 WHERE e.global_seq > $1
   AND e.facility_id = $2
   AND e.event_type = ANY($3::text[])
 ORDER BY e.global_seq
 LIMIT $4
`

type EventsSinceParams struct {
	Since      int64
	FacilityID uuid.UUID
	EventTypes []string
	RowLimit   int32
}

type EventsSinceRow struct {
	EventID       uuid.UUID
	GlobalSeq     int64
	AggregateType string
	AggregateID   uuid.UUID
	PatientID     uuid.NullUUID
	VisitID       uuid.NullUUID
	EventType     string
	EventVersion  int16
	OccurredAt    time.Time
	RecordedAt    time.Time
	Payload       []byte
	ActorUserID   uuid.UUID
	ActorRole     string
	ActorStation  *string
	FacilityID    uuid.UUID
	Source        string
}

// The incremental pull, scoped to the facility and to the event types the caller may read.
//
// **Fail closed**: the type list is passed in by the service from a declared map, so an event type
// nobody has decided about is not pullable at all. The alternative — everything except a denylist
// — means a type added next month is on every phone in the clinic before anybody notices.
//
// The payload comes with it: a station that has pulled an observation needs to render it offline,
// and a reference to a value it cannot read is not synchronisation.
func (q *Queries) EventsSince(ctx context.Context, arg EventsSinceParams) ([]EventsSinceRow, error) {
	rows, err := q.db.Query(ctx, eventsSince,
		arg.Since,
		arg.FacilityID,
		arg.EventTypes,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsSinceRow{}
	for rows.Next() {
		var i EventsSinceRow
		if err := rows.Scan(
			&i.EventID,
			&i.GlobalSeq,
			&i.AggregateType,
			&i.AggregateID,
			&i.PatientID,
			&i.VisitID,
			&i.EventType,
			&i.EventVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Payload,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorStation,
			&i.FacilityID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldEvent = `-- name: HeldEvent :one
SELECT q.id, q.batch_id, q.event_id, q.device_id, q.user_id, q.facility_id,
       q.reason_code, q.reason, q.envelope, q.event_type, q.occurred_at, q.patient_id,
       q.held_at, q.status, q.resolved_at, q.resolved_by, q.resolution_note,
       q.released_event_id,
       coalesce(d.name, '')          AS device_name,
       coalesce(u.employee_code, '') AS operator_code,
       coalesce(u.name_en, '')       AS operator_name_en,
       coalesce(u.name_bn, '')       AS operator_name_bn
  FROM ops.sync_quarantine q
  LEFT JOIN core.device d   ON d.id = q.device_id
  LEFT JOIN core.app_user u ON u.id = q.user_id
 WHERE q.id = $1 AND q.facility_id = $2
`

type HeldEventParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type HeldEventRow struct {
	ID              uuid.UUID
	BatchID         uuid.UUID
	EventID         uuid.UUID
	DeviceID        uuid.UUID
	UserID          uuid.UUID
	FacilityID      uuid.UUID
	ReasonCode      string
	Reason          string
	Envelope        []byte
	EventType       string
	OccurredAt      time.Time
	PatientID       uuid.NullUUID
	HeldAt          time.Time
	Status          string
	ResolvedAt      *time.Time
	ResolvedBy      uuid.NullUUID
	ResolutionNote  string
	ReleasedEventID uuid.NullUUID
	DeviceName      string
	OperatorCode    string
	OperatorNameEn  string
	OperatorNameBn  string
}

// One held event **with its envelope**. Separate from the list on purpose: the list is a triage
// view and needs no clinical content, and this one is the read that shows a blood pressure to a
// person deciding whether it belongs in a record.
func (q *Queries) HeldEvent(ctx context.Context, arg HeldEventParams) (HeldEventRow, error) {
	row := q.db.QueryRow(ctx, heldEvent, arg.ID, arg.FacilityID)
	var i HeldEventRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EventID,
		&i.DeviceID,
		&i.UserID,
		&i.FacilityID,
		&i.ReasonCode,
		&i.Reason,
		&i.Envelope,
		&i.EventType,
		&i.OccurredAt,
		&i.PatientID,
		&i.HeldAt,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ReleasedEventID,
		&i.DeviceName,
		&i.OperatorCode,
		&i.OperatorNameEn,
		&i.OperatorNameBn,
	)
	return i, err
}

const heldEvents = `-- name: HeldEvents :many
SELECT q.id, q.batch_id, q.event_id, q.device_id, q.user_id, q.facility_id,
       q.reason_code, q.reason, q.event_type, q.occurred_at, q.patient_id,
       q.held_at, q.status, q.resolved_at, q.resolved_by, q.resolution_note,
       q.released_event_id,
       coalesce(d.name, '')          AS device_name,
       coalesce(u.employee_code, '') AS operator_code,
       coalesce(u.name_en, '')       AS operator_name_en,
       coalesce(u.name_bn, '')       AS operator_name_bn
  FROM ops.sync_quarantine q
  LEFT JOIN core.device d   ON d.id = q.device_id
  LEFT JOIN core.app_user u ON u.id = q.user_id
 WHERE q.facility_id = $1
   AND ($2::text IS NULL OR q.status = $2::text)
   AND ($3::uuid IS NULL OR q.device_id = $3::uuid)
 ORDER BY q.held_at DESC
 LIMIT $4
`

type HeldEventsParams struct {
	FacilityID uuid.UUID
	Status     *string
	DeviceID   uuid.NullUUID
	RowLimit   int32
}

type HeldEventsRow struct {
	ID              uuid.UUID
	BatchID         uuid.UUID
	EventID         uuid.UUID
	DeviceID        uuid.UUID
	UserID          uuid.UUID
	FacilityID      uuid.UUID
	ReasonCode      string
	Reason          string
	EventType       string
	OccurredAt      time.Time
	PatientID       uuid.NullUUID
	HeldAt          time.Time
	Status          string
	ResolvedAt      *time.Time
	ResolvedBy      uuid.NullUUID
	ResolutionNote  string
	ReleasedEventID uuid.NullUUID
	DeviceName      string
	OperatorCode    string
	OperatorNameEn  string
	OperatorNameBn  string
}

// The triage list. Denormalised columns so a supervisor sees "eleven blood pressures and two
// weights" rather than eleven identifiers, without opening a single envelope — the envelope holds
// clinical values, and a list view should not need to.
func (q *Queries) HeldEvents(ctx context.Context, arg HeldEventsParams) ([]HeldEventsRow, error) {
	rows, err := q.db.Query(ctx, heldEvents,
		arg.FacilityID,
		arg.Status,
		arg.DeviceID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeldEventsRow{}
	for rows.Next() {
		var i HeldEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.EventID,
			&i.DeviceID,
			&i.UserID,
			&i.FacilityID,
			&i.ReasonCode,
			&i.Reason,
			&i.EventType,
			&i.OccurredAt,
			&i.PatientID,
			&i.HeldAt,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.ReleasedEventID,
			&i.DeviceName,
			&i.OperatorCode,
			&i.OperatorNameEn,
			&i.OperatorNameBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestGlobalSeq = `-- name: LatestGlobalSeq :one
SELECT coalesce(max(global_seq), 0)::bigint AS latest FROM ledger.event
`

// Where the ledger is now, so a client knows whether its page was the last one without asking for
// an empty one.
func (q *Queries) LatestGlobalSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, latestGlobalSeq)
	var latest int64
	err := row.Scan(&latest)
	return latest, err
}

const notePull = `-- name: NotePull :exec
INSERT INTO ops.device_sync_state (device_id, last_pulled_seq, last_pulled_at)
VALUES ($1, $2, $3)
ON CONFLICT (device_id) DO UPDATE SET
  -- Never moves backwards. A client that replays an old cursor is asking for old events, which is
  -- fine; recording that as its position would make the *next* pull re-send everything since.
  last_pulled_seq = greatest(ops.device_sync_state.last_pulled_seq, EXCLUDED.last_pulled_seq),
  last_pulled_at = EXCLUDED.last_pulled_at
`

type NotePullParams struct {
	DeviceID uuid.UUID
	Seq      int64
	Now      *time.Time
}

func (q *Queries) NotePull(ctx context.Context, arg NotePullParams) error {
	_, err := q.db.Exec(ctx, notePull, arg.DeviceID, arg.Seq, arg.Now)
	return err
}

const notePush = `-- name: NotePush :exec
INSERT INTO ops.device_sync_state
  (device_id, last_pushed_at, last_skew_ms, pushed_total, quarantined_total)
VALUES ($1, $2, $3,
        $4, $5)
ON CONFLICT (device_id) DO UPDATE SET
  last_pushed_at = EXCLUDED.last_pushed_at,
  last_skew_ms = EXCLUDED.last_skew_ms,
  pushed_total = ops.device_sync_state.pushed_total + EXCLUDED.pushed_total,
  quarantined_total = ops.device_sync_state.quarantined_total + EXCLUDED.quarantined_total
`

type NotePushParams struct {
	DeviceID    uuid.UUID
	Now         *time.Time
	SkewMs      *int64
	Pushed      int64
	Quarantined int64
}

func (q *Queries) NotePush(ctx context.Context, arg NotePushParams) error {
	_, err := q.db.Exec(ctx, notePush,
		arg.DeviceID,
		arg.Now,
		arg.SkewMs,
		arg.Pushed,
		arg.Quarantined,
	)
	return err
}

const quarantine = `-- name: Quarantine :one
INSERT INTO ops.sync_quarantine
  (id, batch_id, event_id, device_id, user_id, facility_id,
   reason_code, reason, envelope, event_type, occurred_at, patient_id, held_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT DO NOTHING
RETURNING id
`

type QuarantineParams struct {
	ID         uuid.UUID
	BatchID    uuid.UUID
	EventID    uuid.UUID
	DeviceID   uuid.UUID
	UserID     uuid.UUID
	FacilityID uuid.UUID
	ReasonCode string
	Reason     string
	Envelope   []byte
	EventType  string
	OccurredAt time.Time
	PatientID  uuid.NullUUID
	HeldAt     time.Time
}

func (q *Queries) Quarantine(ctx context.Context, arg QuarantineParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, quarantine,
		arg.ID,
		arg.BatchID,
		arg.EventID,
		arg.DeviceID,
		arg.UserID,
		arg.FacilityID,
		arg.ReasonCode,
		arg.Reason,
		arg.Envelope,
		arg.EventType,
		arg.OccurredAt,
		arg.PatientID,
		arg.HeldAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const quarantineLoad = `-- name: QuarantineLoad :one
SELECT count(*)::bigint AS held, ops.quarantine_cap()::integer AS cap
  FROM ops.sync_quarantine
 WHERE device_id = $1 AND status = 'HELD'
`

type QuarantineLoadRow struct {
	Held int64
	Cap  int32
}

// How much of this device's quarantine allowance is spent, and what the allowance is.
//
// Both in one row, from one place, because the cap belongs to the database (00050) and a constant
// in Go beside it would be a second number that agrees until somebody changes one. Read once per
// batch for the same reason the device's status is: it cannot meaningfully change halfway through
// fifty blood pressures, and reading it fifty times would only make the answer inconsistent.
//
// `status = 'HELD'` and not every row this device ever had held: the allowance is cleared by a
// person working through the triage list, which is the right thing to tie it to — the resource
// actually being protected is somebody's attention.
func (q *Queries) QuarantineLoad(ctx context.Context, deviceID uuid.UUID) (QuarantineLoadRow, error) {
	row := q.db.QueryRow(ctx, quarantineLoad, deviceID)
	var i QuarantineLoadRow
	err := row.Scan(&i.Held, &i.Cap)
	return i, err
}

const recordBatch = `-- name: RecordBatch :one
INSERT INTO ops.sync_batch
  (id, device_id, user_id, facility_id, received_at, client_clock, skew_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, received_at
`

type RecordBatchParams struct {
	ID          uuid.UUID
	DeviceID    uuid.UUID
	UserID      uuid.UUID
	FacilityID  uuid.UUID
	ReceivedAt  time.Time
	ClientClock *time.Time
	SkewMs      *int64
}

type RecordBatchRow struct {
	ID         uuid.UUID
	ReceivedAt time.Time
}

// Opened with nothing counted yet, and closed below once every event has an answer.
//
// Two reasons for the split, and the second is what made it necessary rather than tidy. A
// quarantined event points at its batch, so the batch must exist before the first one is held. And
// a crash halfway through leaves a receipt saying nothing was processed — honest, and what a client
// should re-send against, where a missing receipt would leave it unable to tell a batch that was
// never seen from one that was half done.
func (q *Queries) RecordBatch(ctx context.Context, arg RecordBatchParams) (RecordBatchRow, error) {
	row := q.db.QueryRow(ctx, recordBatch,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.FacilityID,
		arg.ReceivedAt,
		arg.ClientClock,
		arg.SkewMs,
	)
	var i RecordBatchRow
	err := row.Scan(&i.ID, &i.ReceivedAt)
	return i, err
}

const recordResult = `-- name: RecordResult :exec
INSERT INTO ops.sync_result (batch_id, event_id, outcome, reason_code, reason, global_seq)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (batch_id, event_id) DO NOTHING
`

type RecordResultParams struct {
	BatchID    uuid.UUID
	EventID    uuid.UUID
	Outcome    string
	ReasonCode string
	Reason     string
	GlobalSeq  *int64
}

func (q *Queries) RecordResult(ctx context.Context, arg RecordResultParams) error {
	_, err := q.db.Exec(ctx, recordResult,
		arg.BatchID,
		arg.EventID,
		arg.Outcome,
		arg.ReasonCode,
		arg.Reason,
		arg.GlobalSeq,
	)
	return err
}

const referenceVersions = `-- name: ReferenceVersions :many
SELECT 'observation_code' AS catalogue,
       count(*)::bigint   AS rows,
       md5(coalesce(string_agg(code || ':' || value_type || ':' ||
                               coalesce(dimension, ''), ',' ORDER BY code), ''))::text AS fingerprint
  FROM core.observation_code WHERE retired_at IS NULL
UNION ALL
SELECT 'food', count(*)::bigint,
       md5(coalesce(string_agg(code || ':' || name_en, ',' ORDER BY code), ''))::text
  FROM core.food WHERE retired_at IS NULL
UNION ALL
SELECT 'exercise', count(*)::bigint,
       md5(coalesce(string_agg(code || ':' || name_en, ',' ORDER BY code), ''))::text
  FROM core.exercise WHERE retired_at IS NULL
UNION ALL
SELECT 'contraindication', count(*)::bigint,
       md5(coalesce(string_agg(code || ':' || name_en, ',' ORDER BY code), ''))::text
  FROM core.contraindication WHERE retired_at IS NULL
UNION ALL
SELECT 'instrument', count(*)::bigint,
       md5(coalesce(string_agg(code || ':' || name_en, ',' ORDER BY code), ''))::text
  FROM core.instrument WHERE retired_at IS NULL
UNION ALL
SELECT 'counseling_template', count(*)::bigint,
       md5(coalesce(string_agg(t.code || ':' || v.version::text, ',' ORDER BY t.code), ''))::text
  FROM core.counseling_template t
  JOIN core.counseling_template_version v
    ON v.template_id = t.id AND v.published_at IS NOT NULL
ORDER BY catalogue
`

type ReferenceVersionsRow struct {
	Catalogue   string
	Rows        int64
	Fingerprint string
}

// What each reference catalogue looks like now, so a phone holding it for a morning can tell in
// one small request whether any of it has moved.
//
// A count and a fingerprint rather than a timestamp, because several of these tables have no
// updated_at and adding one to each would be five migrations to answer a question a hash already
// answers. The fingerprint changes when any row does; it does not say which.
func (q *Queries) ReferenceVersions(ctx context.Context) ([]ReferenceVersionsRow, error) {
	rows, err := q.db.Query(ctx, referenceVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferenceVersionsRow{}
	for rows.Next() {
		var i ReferenceVersionsRow
		if err := rows.Scan(&i.Catalogue, &i.Rows, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseHeldEvent = `-- name: ReleaseHeldEvent :one
UPDATE ops.sync_quarantine
   SET status = 'RELEASED', resolved_at = $1, resolved_by = $2,
       resolution_note = $3, released_event_id = $4
 WHERE id = $5 AND facility_id = $6 AND status = 'HELD'
RETURNING id, status, released_event_id
`

type ReleaseHeldEventParams struct {
	Now             *time.Time
	ResolvedBy      uuid.NullUUID
	Note            string
	ReleasedEventID uuid.NullUUID
	ID              uuid.UUID
	FacilityID      uuid.UUID
}

type ReleaseHeldEventRow struct {
	ID              uuid.UUID
	Status          string
	ReleasedEventID uuid.NullUUID
}

// Marked released only once the append has actually happened, and in the same transaction as it.
// The other order would let "released" be a status somebody set while the append failed, and the
// measurement would be marked recovered and not be there — worse than never releasing it, because
// now nobody is looking. Invariant 95 checks the whole table for the same reason.
func (q *Queries) ReleaseHeldEvent(ctx context.Context, arg ReleaseHeldEventParams) (ReleaseHeldEventRow, error) {
	row := q.db.QueryRow(ctx, releaseHeldEvent,
		arg.Now,
		arg.ResolvedBy,
		arg.Note,
		arg.ReleasedEventID,
		arg.ID,
		arg.FacilityID,
	)
	var i ReleaseHeldEventRow
	err := row.Scan(&i.ID, &i.Status, &i.ReleasedEventID)
	return i, err
}

const resultsFor = `-- name: ResultsFor :many
SELECT batch_id, event_id, outcome, reason_code, reason, global_seq
  FROM ops.sync_result
 WHERE batch_id = $1
 ORDER BY event_id
`

func (q *Queries) ResultsFor(ctx context.Context, batchID uuid.UUID) ([]OpsSyncResult, error) {
	rows, err := q.db.Query(ctx, resultsFor, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsSyncResult{}
	for rows.Next() {
		var i OpsSyncResult
		if err := rows.Scan(
			&i.BatchID,
			&i.EventID,
			&i.Outcome,
			&i.ReasonCode,
			&i.Reason,
			&i.GlobalSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncState = `-- name: SyncState :one
SELECT device_id, last_pulled_seq, last_pulled_at, last_pushed_at, last_skew_ms,
       pushed_total, quarantined_total
  FROM ops.device_sync_state
 WHERE device_id = $1
`

func (q *Queries) SyncState(ctx context.Context, deviceID uuid.UUID) (OpsDeviceSyncState, error) {
	row := q.db.QueryRow(ctx, syncState, deviceID)
	var i OpsDeviceSyncState
	err := row.Scan(
		&i.DeviceID,
		&i.LastPulledSeq,
		&i.LastPulledAt,
		&i.LastPushedAt,
		&i.LastSkewMs,
		&i.PushedTotal,
		&i.QuarantinedTotal,
	)
	return i, err
}
