// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projection.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceCheckpoint = `-- name: AdvanceCheckpoint :exec
UPDATE read.projection_state
   SET checkpoint = GREATEST(checkpoint, $2),
       applied_at = GREATEST(COALESCE(applied_at, '-infinity'::timestamptz), $3),
       updated_at = now()
 WHERE name = $1
`

type AdvanceCheckpointParams struct {
	Name       string
	Checkpoint int64
	AppliedAt  *time.Time
}

// GREATEST rather than assignment: a runner that re-applied a batch after a crash must not
// move its checkpoint backwards.
func (q *Queries) AdvanceCheckpoint(ctx context.Context, arg AdvanceCheckpointParams) error {
	_, err := q.db.Exec(ctx, advanceCheckpoint, arg.Name, arg.Checkpoint, arg.AppliedAt)
	return err
}

const allProjectionState = `-- name: AllProjectionState :many
SELECT name, version, mode, checkpoint, status, applied_at, updated_at, rebuilt_at FROM read.projection_state ORDER BY name
`

func (q *Queries) AllProjectionState(ctx context.Context) ([]ReadProjectionState, error) {
	rows, err := q.db.Query(ctx, allProjectionState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadProjectionState{}
	for rows.Next() {
		var i ReadProjectionState
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Mode,
			&i.Checkpoint,
			&i.Status,
			&i.AppliedAt,
			&i.UpdatedAt,
			&i.RebuiltAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const beginRebuild = `-- name: BeginRebuild :exec
UPDATE read.projection_state
   SET status = 'rebuilding', checkpoint = 0, applied_at = NULL, version = $2, updated_at = now()
 WHERE name = $1
`

type BeginRebuildParams struct {
	Name    string
	Version int32
}

func (q *Queries) BeginRebuild(ctx context.Context, arg BeginRebuildParams) error {
	_, err := q.db.Exec(ctx, beginRebuild, arg.Name, arg.Version)
	return err
}

const clearDeadLetters = `-- name: ClearDeadLetters :exec
DELETE FROM read.projection_dead_letter WHERE projection = $1
`

// A rebuild starts from nothing, so the failures of the previous derivation are history.
func (q *Queries) ClearDeadLetters(ctx context.Context, projection string) error {
	_, err := q.db.Exec(ctx, clearDeadLetters, projection)
	return err
}

const countOpenDeadLetters = `-- name: CountOpenDeadLetters :one
SELECT count(*) FROM read.projection_dead_letter WHERE projection = $1 AND resolved_at IS NULL
`

func (q *Queries) CountOpenDeadLetters(ctx context.Context, projection string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDeadLetters, projection)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishRebuild = `-- name: FinishRebuild :exec
UPDATE read.projection_state
   SET status = $2, checkpoint = $3, applied_at = $4, rebuilt_at = now(), updated_at = now()
 WHERE name = $1
`

type FinishRebuildParams struct {
	Name       string
	Status     string
	Checkpoint int64
	AppliedAt  *time.Time
}

func (q *Queries) FinishRebuild(ctx context.Context, arg FinishRebuildParams) error {
	_, err := q.db.Exec(ctx, finishRebuild,
		arg.Name,
		arg.Status,
		arg.Checkpoint,
		arg.AppliedAt,
	)
	return err
}

const ledgerHead = `-- name: LedgerHead :one
SELECT COALESCE(max(global_seq), 0)::bigint FROM ledger.event_key
`

// The highest global sequence in the ledger, for the lag metric. Zero when empty.
func (q *Queries) LedgerHead(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, ledgerHead)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const openDeadLetters = `-- name: OpenDeadLetters :many
SELECT id, projection, global_seq, event_id, event_type, error, attempts, failed_at, resolved_at, resolution FROM read.projection_dead_letter
 WHERE projection = $1 AND resolved_at IS NULL
 ORDER BY global_seq
`

func (q *Queries) OpenDeadLetters(ctx context.Context, projection string) ([]ReadProjectionDeadLetter, error) {
	rows, err := q.db.Query(ctx, openDeadLetters, projection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadProjectionDeadLetter{}
	for rows.Next() {
		var i ReadProjectionDeadLetter
		if err := rows.Scan(
			&i.ID,
			&i.Projection,
			&i.GlobalSeq,
			&i.EventID,
			&i.EventType,
			&i.Error,
			&i.Attempts,
			&i.FailedAt,
			&i.ResolvedAt,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionState = `-- name: ProjectionState :one
SELECT name, version, mode, checkpoint, status, applied_at, updated_at, rebuilt_at FROM read.projection_state WHERE name = $1
`

func (q *Queries) ProjectionState(ctx context.Context, name string) (ReadProjectionState, error) {
	row := q.db.QueryRow(ctx, projectionState, name)
	var i ReadProjectionState
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Mode,
		&i.Checkpoint,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.RebuiltAt,
	)
	return i, err
}

const recordDeadLetter = `-- name: RecordDeadLetter :exec
INSERT INTO read.projection_dead_letter (projection, global_seq, event_id, event_type, error, attempts)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (projection, global_seq) DO UPDATE
   SET error = EXCLUDED.error, attempts = read.projection_dead_letter.attempts + 1,
       failed_at = now(), resolved_at = NULL, resolution = NULL
`

type RecordDeadLetterParams struct {
	Projection string
	GlobalSeq  int64
	EventID    uuid.UUID
	EventType  string
	Error      string
	Attempts   int32
}

func (q *Queries) RecordDeadLetter(ctx context.Context, arg RecordDeadLetterParams) error {
	_, err := q.db.Exec(ctx, recordDeadLetter,
		arg.Projection,
		arg.GlobalSeq,
		arg.EventID,
		arg.EventType,
		arg.Error,
		arg.Attempts,
	)
	return err
}

const registerProjection = `-- name: RegisterProjection :one

INSERT INTO read.projection_state (name, version, mode)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET mode = EXCLUDED.mode, updated_at = now()
RETURNING name, version, mode, checkpoint, status, applied_at, updated_at, rebuilt_at
`

type RegisterProjectionParams struct {
	Name    string
	Version int32
	Mode    string
}

// The projection register and its dead-letter queue (CP25).
// Insert the projection's row, or return the one already there. The version is not
// overwritten here: a version that differs from the code's is exactly what the runner has
// to notice, and silently updating it would erase the signal.
func (q *Queries) RegisterProjection(ctx context.Context, arg RegisterProjectionParams) (ReadProjectionState, error) {
	row := q.db.QueryRow(ctx, registerProjection, arg.Name, arg.Version, arg.Mode)
	var i ReadProjectionState
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Mode,
		&i.Checkpoint,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.RebuiltAt,
	)
	return i, err
}

const resolveDeadLetter = `-- name: ResolveDeadLetter :exec
UPDATE read.projection_dead_letter
   SET resolved_at = now(), resolution = $2
 WHERE id = $1 AND resolved_at IS NULL
`

type ResolveDeadLetterParams struct {
	ID         int64
	Resolution *string
}

func (q *Queries) ResolveDeadLetter(ctx context.Context, arg ResolveDeadLetterParams) error {
	_, err := q.db.Exec(ctx, resolveDeadLetter, arg.ID, arg.Resolution)
	return err
}

const setProjectionStatus = `-- name: SetProjectionStatus :exec
UPDATE read.projection_state SET status = $2, updated_at = now() WHERE name = $1
`

type SetProjectionStatusParams struct {
	Name   string
	Status string
}

func (q *Queries) SetProjectionStatus(ctx context.Context, arg SetProjectionStatusParams) error {
	_, err := q.db.Exec(ctx, setProjectionStatus, arg.Name, arg.Status)
	return err
}
