// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quality.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachQualityFlagAudit = `-- name: AttachQualityFlagAudit :exec
UPDATE core.quality_flag SET audit_seq = $2 WHERE id = $1
`

type AttachQualityFlagAuditParams struct {
	ID       uuid.UUID
	AuditSeq *int64
}

func (q *Queries) AttachQualityFlagAudit(ctx context.Context, arg AttachQualityFlagAuditParams) error {
	_, err := q.db.Exec(ctx, attachQualityFlagAudit, arg.ID, arg.AuditSeq)
	return err
}

const correctionsByCode = `-- name: CorrectionsByCode :many
SELECT r.code,
       coalesce(c.display_en, r.code) AS display_en,
       coalesce(c.display_bn, r.code) AS display_bn,
       count(*)::bigint AS corrections
  FROM read.correction_request r
  LEFT JOIN core.observation_code c ON c.code = r.code
 WHERE r.facility_id = $1
   AND r.assigned_to = $2
   AND r.requested_at >= $3
   AND r.requested_at <  $4
 GROUP BY r.code, c.display_en, c.display_bn
 ORDER BY corrections DESC, r.code
`

type CorrectionsByCodeParams struct {
	FacilityID    uuid.UUID
	AssignedTo    uuid.UUID
	RequestedAt   time.Time
	RequestedAt_2 time.Time
}

type CorrectionsByCodeRow struct {
	Code        string
	DisplayEn   string
	DisplayBn   string
	Corrections int64
}

// Which measurement keeps going wrong. Usually the instrument rather than the person, which is
// why the threshold row carries that sentence as its suggested action.
//
// The display pair comes from the registry, because every other coded value in this system pairs
// with words a reader can understand and `BODY_WEIGHT` in front of a Bangla-reading operator is
// not a design. Ordered by count here, and only here: this is the query the pattern detector
// reads, and it wants the busiest measurement first.
func (q *Queries) CorrectionsByCode(ctx context.Context, arg CorrectionsByCodeParams) ([]CorrectionsByCodeRow, error) {
	rows, err := q.db.Query(ctx, correctionsByCode,
		arg.FacilityID,
		arg.AssignedTo,
		arg.RequestedAt,
		arg.RequestedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionsByCodeRow{}
	for rows.Next() {
		var i CorrectionsByCodeRow
		if err := rows.Scan(
			&i.Code,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.Corrections,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctionsByHour = `-- name: CorrectionsByHour :many
SELECT extract(hour FROM (o.recorded_at AT TIME ZONE $1::text))::int AS hour,
       count(*)::bigint AS corrections
  FROM read.correction_request r
  JOIN read.observation o ON o.id = r.observation_id
 WHERE r.facility_id = $2
   AND r.assigned_to = $3
   AND r.requested_at >= $4
   AND r.requested_at <  $5
 GROUP BY 1
 ORDER BY 1
`

type CorrectionsByHourParams struct {
	Zone       string
	FacilityID uuid.UUID
	AssignedTo uuid.UUID
	FromAt     time.Time
	ToAt       time.Time
}

type CorrectionsByHourRow struct {
	Hour        int32
	Corrections int64
}

// The time-of-day pattern §4.3 names. The hour is the hour the **value was recorded**, not the
// hour it was flagged: a physician reviewing yesterday's file at nine in the morning would
// otherwise make every operator look like a morning problem.
func (q *Queries) CorrectionsByHour(ctx context.Context, arg CorrectionsByHourParams) ([]CorrectionsByHourRow, error) {
	rows, err := q.db.Query(ctx, correctionsByHour,
		arg.Zone,
		arg.FacilityID,
		arg.AssignedTo,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionsByHourRow{}
	for rows.Next() {
		var i CorrectionsByHourRow
		if err := rows.Scan(&i.Hour, &i.Corrections); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctionsByReason = `-- name: CorrectionsByReason :many
SELECT r.reason_code,
       coalesce(n.display_en, r.reason_code) AS display_en,
       coalesce(n.display_bn, r.reason_code) AS display_bn,
       coalesce(n.is_transcription, false)   AS is_transcription,
       count(*)::bigint AS corrections
  FROM read.correction_request r
  LEFT JOIN core.correction_reason n ON n.code = r.reason_code
 WHERE r.facility_id = $1
   AND r.assigned_to = $2
   AND r.requested_at >= $3
   AND r.requested_at <  $4
 GROUP BY r.reason_code, n.display_en, n.display_bn, n.is_transcription
 -- Ordered by code, not by count. A size-ranked list of the ways one person's values were
 -- questioned, handed to that person, reads as a leaderboard however carefully it is labelled —
 -- and the client that wants the biggest first can sort. A stable order also means a screen does
 -- not reshuffle under somebody while they are reading it.
 ORDER BY r.reason_code
`

type CorrectionsByReasonParams struct {
	FacilityID    uuid.UUID
	AssignedTo    uuid.UUID
	RequestedAt   time.Time
	RequestedAt_2 time.Time
}

type CorrectionsByReasonRow struct {
	ReasonCode      string
	DisplayEn       string
	DisplayBn       string
	IsTranscription bool
	Corrections     int64
}

// Criterion 1's "by category". Ordered by count so the shape of somebody's month is the first
// thing read, and the reason display comes from the vocabulary so both languages are available.
func (q *Queries) CorrectionsByReason(ctx context.Context, arg CorrectionsByReasonParams) ([]CorrectionsByReasonRow, error) {
	rows, err := q.db.Query(ctx, correctionsByReason,
		arg.FacilityID,
		arg.AssignedTo,
		arg.RequestedAt,
		arg.RequestedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionsByReasonRow{}
	for rows.Next() {
		var i CorrectionsByReasonRow
		if err := rows.Scan(
			&i.ReasonCode,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.IsTranscription,
			&i.Corrections,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctionsReceived = `-- name: CorrectionsReceived :one
SELECT count(*)::bigint AS total,
       count(*) FILTER (WHERE r.status = 'APPLIED')::bigint    AS upheld,
       count(*) FILTER (WHERE r.status = 'OVERRIDDEN')::bigint AS overridden,
       count(*) FILTER (WHERE r.status = 'REJECTED')::bigint   AS rejected,
       count(*) FILTER (WHERE r.status = 'OPEN')::bigint       AS open
  FROM read.correction_request r
 WHERE r.facility_id = $1
   AND r.assigned_to = $2
   AND r.requested_at >= $3
   AND r.requested_at <  $4
`

type CorrectionsReceivedParams struct {
	FacilityID    uuid.UUID
	AssignedTo    uuid.UUID
	RequestedAt   time.Time
	RequestedAt_2 time.Time
}

type CorrectionsReceivedRow struct {
	Total      int64
	Upheld     int64
	Overridden int64
	Rejected   int64
	Open       int64
}

// The numerator: values this operator typed that somebody asked to have corrected. Rejected
// requests are counted too, deliberately — see the note in the service. Both are reported.
//
// `upheld` and `overridden` are counted apart. CP62 made a supervisor's fix a different event
// specifically so that an operator's record would not read it as though they had put it right
// themselves; folding the two together here would throw that distinction away at the one place it
// was created for, and tell somebody "you put three values right" about values they never touched.
func (q *Queries) CorrectionsReceived(ctx context.Context, arg CorrectionsReceivedParams) (CorrectionsReceivedRow, error) {
	row := q.db.QueryRow(ctx, correctionsReceived,
		arg.FacilityID,
		arg.AssignedTo,
		arg.RequestedAt,
		arg.RequestedAt_2,
	)
	var i CorrectionsReceivedRow
	err := row.Scan(
		&i.Total,
		&i.Upheld,
		&i.Overridden,
		&i.Rejected,
		&i.Open,
	)
	return i, err
}

const entriesByCode = `-- name: EntriesByCode :many
SELECT o.code,
       count(*)::bigint AS entries
  FROM read.observation o
 WHERE o.facility_id = $1
   AND o.recorded_by = $2
   AND o.recorded_at >= $3
   AND o.recorded_at <  $4
   AND o.category <> 'DERIVED'
 GROUP BY o.code
`

type EntriesByCodeParams struct {
	FacilityID   uuid.UUID
	RecordedBy   uuid.UUID
	RecordedAt   time.Time
	RecordedAt_2 time.Time
}

type EntriesByCodeRow struct {
	Code    string
	Entries int64
}

// The same, per measurement. Three corrections on a weight is a different fact when the operator
// weighed four hundred people and when they weighed nine.
func (q *Queries) EntriesByCode(ctx context.Context, arg EntriesByCodeParams) ([]EntriesByCodeRow, error) {
	rows, err := q.db.Query(ctx, entriesByCode,
		arg.FacilityID,
		arg.RecordedBy,
		arg.RecordedAt,
		arg.RecordedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntriesByCodeRow{}
	for rows.Next() {
		var i EntriesByCodeRow
		if err := rows.Scan(&i.Code, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByHour = `-- name: EntriesByHour :many
SELECT extract(hour FROM (o.recorded_at AT TIME ZONE $1::text))::int AS hour,
       count(*)::bigint AS entries
  FROM read.observation o
 WHERE o.facility_id = $2
   AND o.recorded_by = $3
   AND o.recorded_at >= $4
   AND o.recorded_at <  $5
   AND o.category <> 'DERIVED'
 GROUP BY 1
 ORDER BY 1
`

type EntriesByHourParams struct {
	Zone       string
	FacilityID uuid.UUID
	RecordedBy uuid.UUID
	FromAt     time.Time
	ToAt       time.Time
}

type EntriesByHourRow struct {
	Hour    int32
	Entries int64
}

// The denominator the hour breakdown was missing, and it is not a nicety.
//
// "Three corrections at four in the afternoon" answers nothing on its own: an operator who works
// only the late shift will always cluster late, and the end-of-shift threshold would flag them
// for the rota. Against "how many values did you enter at four in the afternoon" it becomes a
// question somebody can answer.
func (q *Queries) EntriesByHour(ctx context.Context, arg EntriesByHourParams) ([]EntriesByHourRow, error) {
	rows, err := q.db.Query(ctx, entriesByHour,
		arg.Zone,
		arg.FacilityID,
		arg.RecordedBy,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntriesByHourRow{}
	for rows.Next() {
		var i EntriesByHourRow
		if err := rows.Scan(&i.Hour, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesRecorded = `-- name: EntriesRecorded :one

SELECT count(*)::bigint AS entries
  FROM read.observation
 WHERE facility_id = $1
   AND recorded_by = $2
   AND recorded_at >= $3
   AND recorded_at <  $4
   -- Derived values are computed by the server, not typed by anybody, so counting them would
   -- inflate the denominator of whoever pressed the button.
   AND category <> 'DERIVED'
`

type EntriesRecordedParams struct {
	FacilityID   uuid.UUID
	RecordedBy   uuid.UUID
	RecordedAt   time.Time
	RecordedAt_2 time.Time
}

// The operator quality record (CP63).
//
// Every count here is taken at read time. There is no aggregation table and no nightly job — see
// ADR-0029 for why, and note that the queries are shaped so a materialised view could replace
// them without the API changing.
//
// **Nothing in this file selects a patient id or a clinical value.** A quality record is about
// an operator; a supervisor reading a patient's values through their staff's error history would
// be reading clinical data through a side door. `core.assert_no_quality_record_names_a_patient`
// enforces that on what is stored; this file is where it has to be true on what is read.
// The denominator. A correction count without it is the number that makes this feature feel
// punitive: three corrections out of four hundred entries and out of forty are different facts.
func (q *Queries) EntriesRecorded(ctx context.Context, arg EntriesRecordedParams) (int64, error) {
	row := q.db.QueryRow(ctx, entriesRecorded,
		arg.FacilityID,
		arg.RecordedBy,
		arg.RecordedAt,
		arg.RecordedAt_2,
	)
	var entries int64
	err := row.Scan(&entries)
	return entries, err
}

const openQualityFlagFor = `-- name: OpenQualityFlagFor :one
SELECT id, facility_id, operator_id, threshold_code, raised_at, window_from, window_to, observed_count, entries_count, evidence, status, resolved_at, resolved_by, resolution, audit_seq FROM core.quality_flag
 WHERE operator_id = $1 AND threshold_code = $2 AND status = 'OPEN'
`

type OpenQualityFlagForParams struct {
	OperatorID    uuid.UUID
	ThresholdCode string
}

func (q *Queries) OpenQualityFlagFor(ctx context.Context, arg OpenQualityFlagForParams) (CoreQualityFlag, error) {
	row := q.db.QueryRow(ctx, openQualityFlagFor, arg.OperatorID, arg.ThresholdCode)
	var i CoreQualityFlag
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.OperatorID,
		&i.ThresholdCode,
		&i.RaisedAt,
		&i.WindowFrom,
		&i.WindowTo,
		&i.ObservedCount,
		&i.EntriesCount,
		&i.Evidence,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.AuditSeq,
	)
	return i, err
}

const operatorsWithCorrections = `-- name: OperatorsWithCorrections :many
WITH entries AS (
  SELECT o.recorded_by AS operator_id, count(*)::bigint AS entries
    FROM read.observation o
   WHERE o.facility_id = $3
     AND o.recorded_at >= $4
     AND o.recorded_at <  $5
     AND o.category <> 'DERIVED'
   GROUP BY o.recorded_by
),
corrections AS (
  SELECT r.assigned_to AS operator_id,
         count(*)::bigint AS corrections,
         count(*) FILTER (WHERE r.status = 'APPLIED')::bigint    AS upheld,
         count(*) FILTER (WHERE r.status = 'OVERRIDDEN')::bigint AS overridden,
         count(*) FILTER (WHERE r.status = 'REJECTED')::bigint   AS rejected,
         count(*) FILTER (WHERE r.status = 'OPEN')::bigint       AS still_open
    FROM read.correction_request r
   WHERE r.facility_id = $3
     AND r.requested_at >= $4
     AND r.requested_at <  $5
   GROUP BY r.assigned_to
)
SELECT coalesce(c.operator_id, e.operator_id) AS operator_id,
       coalesce(u.employee_code, '') AS employee_code,
       coalesce(u.name_en, '')       AS name_en,
       coalesce(u.name_bn, '')       AS name_bn,
       coalesce(u.status, '')        AS status,
       coalesce(e.entries, 0)::bigint     AS entries,
       coalesce(c.corrections, 0)::bigint AS corrections,
       coalesce(c.upheld, 0)::bigint      AS upheld,
       coalesce(c.overridden, 0)::bigint  AS overridden,
       coalesce(c.rejected, 0)::bigint    AS rejected,
       coalesce(c.still_open, 0)::bigint  AS still_open
  FROM corrections c
  FULL OUTER JOIN entries e ON e.operator_id = c.operator_id
  LEFT JOIN core.app_user u ON u.id = coalesce(c.operator_id, e.operator_id)
 WHERE ($1::boolean OR c.operator_id IS NOT NULL)
 ORDER BY u.employee_code, coalesce(c.operator_id, e.operator_id)
 LIMIT $2
`

type OperatorsWithCorrectionsParams struct {
	IncludeAll bool
	RowLimit   int32
	FacilityID uuid.UUID
	FromAt     time.Time
	ToAt       time.Time
}

type OperatorsWithCorrectionsRow struct {
	OperatorID   uuid.UUID
	EmployeeCode string
	NameEn       string
	NameBn       string
	Status       string
	Entries      int64
	Corrections  int64
	Upheld       int64
	Overridden   int64
	Rejected     int64
	StillOpen    int64
}

// The supervisor's list.
//
// **One query, and it carries the denominator.** The first version counted corrections here and
// then asked `EntriesRecorded` once per operator in a Go loop, which was both an N+1 on the
// supervisor's landing screen and — worse — the reason the list's rate and the record's rate were
// computed from different numerators. Two screens showing a different figure for the same person
// and window is how a supervisor concludes the system is broken.
//
// **`include_all` decides whether this is a roster or a list of people with corrections.** With it
// false the list is structurally "everybody who was corrected", and no amount of denominators
// printed beside the counts undoes what a list like that reads as. With it true, everybody who
// recorded anything in the window is on it — including the people with four hundred entries and
// nothing corrected, who are the rows that make the list a roster rather than an accusation.
//
// Deactivated staff are included either way, for CP61's reason: much of what a review asks about
// is somebody who has since left, and a list of current staff would render a blank for them.
func (q *Queries) OperatorsWithCorrections(ctx context.Context, arg OperatorsWithCorrectionsParams) ([]OperatorsWithCorrectionsRow, error) {
	rows, err := q.db.Query(ctx, operatorsWithCorrections,
		arg.IncludeAll,
		arg.RowLimit,
		arg.FacilityID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorsWithCorrectionsRow{}
	for rows.Next() {
		var i OperatorsWithCorrectionsRow
		if err := rows.Scan(
			&i.OperatorID,
			&i.EmployeeCode,
			&i.NameEn,
			&i.NameBn,
			&i.Status,
			&i.Entries,
			&i.Corrections,
			&i.Upheld,
			&i.Overridden,
			&i.Rejected,
			&i.StillOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qualityFlagByID = `-- name: QualityFlagByID :one
SELECT f.id, f.facility_id, f.operator_id, f.threshold_code, f.raised_at, f.window_from, f.window_to, f.observed_count, f.entries_count, f.evidence, f.status, f.resolved_at, f.resolved_by, f.resolution, f.audit_seq,
       coalesce(u.employee_code, '') AS operator_code,
       coalesce(u.name_en, '')       AS operator_name_en,
       coalesce(u.name_bn, '')       AS operator_name_bn,
       coalesce(t.display_en, '')    AS threshold_en,
       coalesce(t.display_bn, '')    AS threshold_bn,
       coalesce(t.action_en, '')     AS action_en,
       coalesce(t.action_bn, '')     AS action_bn,
       t.approved_at                 AS threshold_approved_at,
       -- The resolver's names, joined like the operator's. Two people on one row named two
       -- different ways — one with a name and one with a uuid — is the kind of asymmetry that
       -- ends with a uuid on a screen.
       coalesce(v.employee_code, '') AS resolved_by_code,
       coalesce(v.name_en, '')       AS resolved_by_name_en,
       coalesce(v.name_bn, '')       AS resolved_by_name_bn
  FROM core.quality_flag f
  LEFT JOIN core.app_user u ON u.id = f.operator_id
  LEFT JOIN core.quality_threshold t ON t.code = f.threshold_code
  LEFT JOIN core.app_user v ON v.id = f.resolved_by
 WHERE f.id = $1 AND f.facility_id = $2
`

type QualityFlagByIDParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type QualityFlagByIDRow struct {
	ID                  uuid.UUID
	FacilityID          uuid.UUID
	OperatorID          uuid.UUID
	ThresholdCode       string
	RaisedAt            time.Time
	WindowFrom          time.Time
	WindowTo            time.Time
	ObservedCount       int32
	EntriesCount        int32
	Evidence            []byte
	Status              string
	ResolvedAt          *time.Time
	ResolvedBy          uuid.NullUUID
	Resolution          string
	AuditSeq            *int64
	OperatorCode        string
	OperatorNameEn      string
	OperatorNameBn      string
	ThresholdEn         string
	ThresholdBn         string
	ActionEn            string
	ActionBn            string
	ThresholdApprovedAt *time.Time
	ResolvedByCode      string
	ResolvedByNameEn    string
	ResolvedByNameBn    string
}

func (q *Queries) QualityFlagByID(ctx context.Context, arg QualityFlagByIDParams) (QualityFlagByIDRow, error) {
	row := q.db.QueryRow(ctx, qualityFlagByID, arg.ID, arg.FacilityID)
	var i QualityFlagByIDRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.OperatorID,
		&i.ThresholdCode,
		&i.RaisedAt,
		&i.WindowFrom,
		&i.WindowTo,
		&i.ObservedCount,
		&i.EntriesCount,
		&i.Evidence,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.AuditSeq,
		&i.OperatorCode,
		&i.OperatorNameEn,
		&i.OperatorNameBn,
		&i.ThresholdEn,
		&i.ThresholdBn,
		&i.ActionEn,
		&i.ActionBn,
		&i.ThresholdApprovedAt,
		&i.ResolvedByCode,
		&i.ResolvedByNameEn,
		&i.ResolvedByNameBn,
	)
	return i, err
}

const qualityFlags = `-- name: QualityFlags :many
SELECT f.id, f.facility_id, f.operator_id, f.threshold_code, f.raised_at, f.window_from, f.window_to, f.observed_count, f.entries_count, f.evidence, f.status, f.resolved_at, f.resolved_by, f.resolution, f.audit_seq,
       coalesce(u.employee_code, '') AS operator_code,
       coalesce(u.name_en, '')       AS operator_name_en,
       coalesce(u.name_bn, '')       AS operator_name_bn,
       coalesce(t.display_en, '')    AS threshold_en,
       coalesce(t.display_bn, '')    AS threshold_bn,
       coalesce(t.action_en, '')     AS action_en,
       coalesce(t.action_bn, '')     AS action_bn,
       t.approved_at                 AS threshold_approved_at,
       -- The resolver's names, joined like the operator's. Two people on one row named two
       -- different ways — one with a name and one with a uuid — is the kind of asymmetry that
       -- ends with a uuid on a screen.
       coalesce(v.employee_code, '') AS resolved_by_code,
       coalesce(v.name_en, '')       AS resolved_by_name_en,
       coalesce(v.name_bn, '')       AS resolved_by_name_bn
  FROM core.quality_flag f
  LEFT JOIN core.app_user u ON u.id = f.operator_id
  LEFT JOIN core.quality_threshold t ON t.code = f.threshold_code
  LEFT JOIN core.app_user v ON v.id = f.resolved_by
 WHERE f.facility_id = $1
   AND ($2::uuid IS NULL OR f.operator_id = $2::uuid)
   AND (NOT $3::boolean OR f.status = 'OPEN')
   -- The window the caller is looking at, and **an open flag is never outside it**.
   --
   -- Three bugs were one bug. The queue filtered on ` + "`" + `raised_at` + "`" + ` while the record did not filter
   -- at all, so at a seven-day window a supervisor saw a flag on somebody's record that was
   -- missing from the queue on the same screen, and a roster row saying "two waiting" beside a
   -- queue showing none. And a flag raised forty days ago but dismissed yesterday vanished from
   -- the answered view, which is the one view whose entire subject is what was decided recently.
   --
   -- The rule that makes all three coherent: "what is still waiting" is not a question about a
   -- date range. A window scopes what *happened* in it — raised or answered — and never hides
   -- something nobody has answered yet.
   AND ($4::timestamptz IS NULL
        OR f.status = 'OPEN'
        OR f.raised_at >= $4::timestamptz
        OR f.resolved_at >= $4::timestamptz)
 ORDER BY f.raised_at DESC
 LIMIT $5
`

type QualityFlagsParams struct {
	FacilityID uuid.UUID
	OperatorID uuid.NullUUID
	OpenOnly   bool
	Since      *time.Time
	RowLimit   int32
}

type QualityFlagsRow struct {
	ID                  uuid.UUID
	FacilityID          uuid.UUID
	OperatorID          uuid.UUID
	ThresholdCode       string
	RaisedAt            time.Time
	WindowFrom          time.Time
	WindowTo            time.Time
	ObservedCount       int32
	EntriesCount        int32
	Evidence            []byte
	Status              string
	ResolvedAt          *time.Time
	ResolvedBy          uuid.NullUUID
	Resolution          string
	AuditSeq            *int64
	OperatorCode        string
	OperatorNameEn      string
	OperatorNameBn      string
	ThresholdEn         string
	ThresholdBn         string
	ActionEn            string
	ActionBn            string
	ThresholdApprovedAt *time.Time
	ResolvedByCode      string
	ResolvedByNameEn    string
	ResolvedByNameBn    string
}

func (q *Queries) QualityFlags(ctx context.Context, arg QualityFlagsParams) ([]QualityFlagsRow, error) {
	rows, err := q.db.Query(ctx, qualityFlags,
		arg.FacilityID,
		arg.OperatorID,
		arg.OpenOnly,
		arg.Since,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityFlagsRow{}
	for rows.Next() {
		var i QualityFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.OperatorID,
			&i.ThresholdCode,
			&i.RaisedAt,
			&i.WindowFrom,
			&i.WindowTo,
			&i.ObservedCount,
			&i.EntriesCount,
			&i.Evidence,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Resolution,
			&i.AuditSeq,
			&i.OperatorCode,
			&i.OperatorNameEn,
			&i.OperatorNameBn,
			&i.ThresholdEn,
			&i.ThresholdBn,
			&i.ActionEn,
			&i.ActionBn,
			&i.ThresholdApprovedAt,
			&i.ResolvedByCode,
			&i.ResolvedByNameEn,
			&i.ResolvedByNameBn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qualityThresholds = `-- name: QualityThresholds :many
SELECT code, pattern, window_days, min_count, min_entries, after_hour,
       display_en, display_bn, action_en, action_bn, approved_at, ordering
  FROM core.quality_threshold
 WHERE active
 ORDER BY ordering, code
`

type QualityThresholdsRow struct {
	Code       string
	Pattern    string
	WindowDays int32
	MinCount   int32
	MinEntries int32
	AfterHour  *int32
	DisplayEn  string
	DisplayBn  string
	ActionEn   string
	ActionBn   string
	ApprovedAt *time.Time
	Ordering   int32
}

func (q *Queries) QualityThresholds(ctx context.Context) ([]QualityThresholdsRow, error) {
	rows, err := q.db.Query(ctx, qualityThresholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityThresholdsRow{}
	for rows.Next() {
		var i QualityThresholdsRow
		if err := rows.Scan(
			&i.Code,
			&i.Pattern,
			&i.WindowDays,
			&i.MinCount,
			&i.MinEntries,
			&i.AfterHour,
			&i.DisplayEn,
			&i.DisplayBn,
			&i.ActionEn,
			&i.ActionBn,
			&i.ApprovedAt,
			&i.Ordering,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseQualityFlag = `-- name: RaiseQualityFlag :one
INSERT INTO core.quality_flag
  (facility_id, operator_id, threshold_code, raised_at, window_from, window_to,
   observed_count, entries_count, evidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT DO NOTHING
RETURNING id, facility_id, operator_id, threshold_code, raised_at, window_from, window_to, observed_count, entries_count, evidence, status, resolved_at, resolved_by, resolution, audit_seq
`

type RaiseQualityFlagParams struct {
	FacilityID    uuid.UUID
	OperatorID    uuid.UUID
	ThresholdCode string
	RaisedAt      time.Time
	WindowFrom    time.Time
	WindowTo      time.Time
	ObservedCount int32
	EntriesCount  int32
	Evidence      []byte
}

func (q *Queries) RaiseQualityFlag(ctx context.Context, arg RaiseQualityFlagParams) (CoreQualityFlag, error) {
	row := q.db.QueryRow(ctx, raiseQualityFlag,
		arg.FacilityID,
		arg.OperatorID,
		arg.ThresholdCode,
		arg.RaisedAt,
		arg.WindowFrom,
		arg.WindowTo,
		arg.ObservedCount,
		arg.EntriesCount,
		arg.Evidence,
	)
	var i CoreQualityFlag
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.OperatorID,
		&i.ThresholdCode,
		&i.RaisedAt,
		&i.WindowFrom,
		&i.WindowTo,
		&i.ObservedCount,
		&i.EntriesCount,
		&i.Evidence,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.AuditSeq,
	)
	return i, err
}

const resolveQualityFlag = `-- name: ResolveQualityFlag :one
UPDATE core.quality_flag
   SET status      = $1,
       resolved_at = $2,
       resolved_by = $3,
       resolution  = $4
 WHERE id = $5
   AND facility_id = $6
   AND status = 'OPEN'
RETURNING id, facility_id, operator_id, threshold_code, raised_at, window_from, window_to, observed_count, entries_count, evidence, status, resolved_at, resolved_by, resolution, audit_seq
`

type ResolveQualityFlagParams struct {
	Status     string
	ResolvedAt *time.Time
	ResolvedBy uuid.NullUUID
	Resolution string
	ID         uuid.UUID
	FacilityID uuid.UUID
}

func (q *Queries) ResolveQualityFlag(ctx context.Context, arg ResolveQualityFlagParams) (CoreQualityFlag, error) {
	row := q.db.QueryRow(ctx, resolveQualityFlag,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.Resolution,
		arg.ID,
		arg.FacilityID,
	)
	var i CoreQualityFlag
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.OperatorID,
		&i.ThresholdCode,
		&i.RaisedAt,
		&i.WindowFrom,
		&i.WindowTo,
		&i.ObservedCount,
		&i.EntriesCount,
		&i.Evidence,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.AuditSeq,
	)
	return i, err
}

const staffMember = `-- name: StaffMember :one
SELECT id, employee_code, name_en, name_bn, status
  FROM core.app_user
 WHERE id = $1 AND facility_id = $2
`

type StaffMemberParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type StaffMemberRow struct {
	ID           uuid.UUID
	EmployeeCode string
	NameEn       string
	NameBn       string
	Status       string
}

// Who a record is about. The record carried only a uuid, so a supervisor opening somebody's month
// got a heading with no name in it unless that person happened to have an open flag.
func (q *Queries) StaffMember(ctx context.Context, arg StaffMemberParams) (StaffMemberRow, error) {
	row := q.db.QueryRow(ctx, staffMember, arg.ID, arg.FacilityID)
	var i StaffMemberRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.NameEn,
		&i.NameBn,
		&i.Status,
	)
	return i, err
}

const supportingCorrections = `-- name: SupportingCorrections :many
SELECT r.id AS request_id,
       r.reason_code,
       coalesce(n.display_en, r.reason_code) AS reason_en,
       coalesce(n.display_bn, r.reason_code) AS reason_bn,
       r.code,
       coalesce(c.display_en, r.code) AS code_en,
       coalesce(c.display_bn, r.code) AS code_bn,
       r.requested_at,
       r.status,
       extract(hour FROM (o.recorded_at AT TIME ZONE $1::text))::int AS recorded_hour
  FROM read.correction_request r
  JOIN read.observation o ON o.id = r.observation_id
  LEFT JOIN core.correction_reason n ON n.code = r.reason_code
  LEFT JOIN core.observation_code c ON c.code = r.code
 WHERE r.facility_id = $2
   AND r.assigned_to = $3
   AND r.requested_at >= $4
   AND r.requested_at <  $5
   AND (NOT $6::boolean OR coalesce(n.is_transcription, false))
   AND ($7::text IS NULL OR r.code = $7::text)
   AND ($8::int IS NULL
        OR extract(hour FROM (o.recorded_at AT TIME ZONE $1::text)) >= $8::int)
 ORDER BY r.requested_at DESC
 LIMIT $9
`

type SupportingCorrectionsParams struct {
	Zone              string
	FacilityID        uuid.UUID
	AssignedTo        uuid.UUID
	FromAt            time.Time
	ToAt              time.Time
	TranscriptionOnly bool
	OnlyCode          *string
	AfterHour         *int32
	RowLimit          int32
}

type SupportingCorrectionsRow struct {
	RequestID    uuid.UUID
	ReasonCode   string
	ReasonEn     string
	ReasonBn     string
	Code         string
	CodeEn       string
	CodeBn       string
	RequestedAt  time.Time
	Status       string
	RecordedHour int32
}

// What a flag is raised on, and all a supervisor is shown before they say anything to anybody:
// the request, the reason, the measurement code, the hour. **No patient id and no value.**
//
// The display pairs are joined rather than left to the client. This is the screen a supervisor
// reads *before speaking to somebody*, and `TRANSCRIPTION` / `BODY_HEIGHT` is not a sentence
// anybody should have to translate in their head first — least of all when the registries that
// would resolve them sit behind `observation.read.values`, which the administrator holds a
// quality permission without.
func (q *Queries) SupportingCorrections(ctx context.Context, arg SupportingCorrectionsParams) ([]SupportingCorrectionsRow, error) {
	rows, err := q.db.Query(ctx, supportingCorrections,
		arg.Zone,
		arg.FacilityID,
		arg.AssignedTo,
		arg.FromAt,
		arg.ToAt,
		arg.TranscriptionOnly,
		arg.OnlyCode,
		arg.AfterHour,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportingCorrectionsRow{}
	for rows.Next() {
		var i SupportingCorrectionsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.ReasonCode,
			&i.ReasonEn,
			&i.ReasonBn,
			&i.Code,
			&i.CodeEn,
			&i.CodeBn,
			&i.RequestedAt,
			&i.Status,
			&i.RecordedHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
