// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AbandonVisit(ctx context.Context, arg AbandonVisitParams) (CoreVisit, error)
	AcknowledgeAdminAlert(ctx context.Context, arg AcknowledgeAdminAlertParams) (CoreAdminAlert, error)
	AcknowledgeBreakGlass(ctx context.Context, arg AcknowledgeBreakGlassParams) (CoreBreakGlassAccess, error)
	// ActivateDevice moves a device to active on enrolment, in the same statement that records
	// what it said about itself. A pending device becomes active; an active or suspended one
	// being re-enrolled (reinstalled app, new key) stays or becomes active and keeps its
	// original enrolled_at. A revoked or lost device cannot be brought back this way — that is
	// what terminal means — and the WHERE returns no row for it.
	//
	ActivateDevice(ctx context.Context, arg ActivateDeviceParams) (CoreDevice, error)
	ActiveBreakGlass(ctx context.Context, arg ActiveBreakGlassParams) ([]CoreBreakGlassAccess, error)
	// Consent (CP36). The application reads templates and never writes them: publishing legal
	// wording is an administrative act, not something a request handler does.
	ActiveConsentTemplate(ctx context.Context, arg ActiveConsentTemplateParams) (ActiveConsentTemplateRow, error)
	ActiveConsentTemplates(ctx context.Context, language string) ([]ActiveConsentTemplatesRow, error)
	// GREATEST rather than assignment: a runner that re-applied a batch after a crash must not
	// move its checkpoint backwards.
	AdvanceCheckpoint(ctx context.Context, arg AdvanceCheckpointParams) error
	// The clinical event ledger (CP23). Append and read; the schema forbids anything else.
	// The last link of one aggregate's chain. Called under the aggregate's advisory lock.
	AggregateHead(ctx context.Context, arg AggregateHeadParams) (AggregateHeadRow, error)
	// Every aggregate with at least one event, for the verifier's walk. Paged by the pair.
	Aggregates(ctx context.Context, arg AggregatesParams) ([]AggregatesRow, error)
	AlertByID(ctx context.Context, arg AlertByIDParams) (AlertByIDRow, error)
	// Open alerts whose current step has been standing longer than the next step's window.
	//
	// The whole sweep in one statement, and deliberately so: the alternative is the worker
	// reading every open alert and doing the arithmetic in Go, which is the same arithmetic in
	// a second place, running against a clock that is not the database's.
	AlertsDueForEscalation(ctx context.Context, arg AlertsDueForEscalationParams) ([]AlertsDueForEscalationRow, error)
	// Every alert raised by one recorded value. Normally one; more than one when a value was
	// entered, corrected and entered again.
	AlertsForObservation(ctx context.Context, arg AlertsForObservationParams) ([]AlertsForObservationRow, error)
	// One patient's alert history, acknowledged ones included. What a physician reads before
	// deciding whether today's reading is the first of its kind.
	AlertsForPatient(ctx context.Context, arg AlertsForPatientParams) ([]AlertsForPatientRow, error)
	AllProjectionState(ctx context.Context) ([]ReadProjectionState, error)
	// What this patient reacts to. Withdrawn ones are absent: an allergy somebody took back is in
	// the ledger, and a header that showed it would be a warning nobody can act on.
	//
	// The substance's words are joined from the catalogue rather than copied onto the row, so a
	// corrected term reads correctly on every allergy coded with it. `is_emergency` comes with the
	// reaction because a header has to be able to lead with the ones that stop a heart.
	AllergiesForPatient(ctx context.Context, patientID uuid.UUID) ([]AllergiesForPatientRow, error)
	AllergyAssertionByID(ctx context.Context, id uuid.UUID) (AllergyAssertionByIDRow, error)
	AllergyByID(ctx context.Context, id uuid.UUID) (AllergyByIDRow, error)
	// Everything ever said about this patient's allergies, withdrawn entries included, newest
	// first. The plan asks for "allergy change history", and the reason it needs one is that an
	// allergy that was recorded and then taken back is a clinical event: somebody believed it,
	// and somebody else disagreed, and both are worth reading before prescribing.
	AllergyHistoryForPatient(ctx context.Context, patientID uuid.UUID) ([]AllergyHistoryForPatientRow, error)
	// The allergy hard stop (CP54).
	// The reaction vocabulary. Short on purpose: a list nobody can hold in their head is one
	// people pick the first item from. `is_emergency` is stored rather than inferred from the
	// severity somebody ticked — anaphylaxis is severe whatever the operator chose.
	AllergyReactions(ctx context.Context) ([]CoreAllergyReaction, error)
	// One function, one answer. The gate on the queue calls the same one, so "does this patient
	// have allergy status" cannot be answered two ways.
	AllergyStatus(ctx context.Context, pPatient uuid.UUID) (string, error)
	AnchorForDay(ctx context.Context, day time.Time) (LedgerChainAnchor, error)
	Anchors(ctx context.Context) ([]LedgerChainAnchor, error)
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (LedgerAuditEvent, error)
	AppendEvent(ctx context.Context, arg AppendEventParams) (LedgerEvent, error)
	// Rows that landed in the safety-net partition: zero unless somebody forgot the monthly
	// partitions. The verifier reports it.
	AuditDefaultPartitionCount(ctx context.Context) (int64, error)
	AuditEventCount(ctx context.Context) (int64, error)
	// The verifier walks the chain forwards in slices.
	AuditEventsFrom(ctx context.Context, arg AuditEventsFromParams) ([]LedgerAuditEvent, error)
	// The viewer's query: newest first, filtered by whatever the person narrowed to. A NULL
	// filter means "any". `before` is the seq cursor for the next page.
	AuditEventsPage(ctx context.Context, arg AuditEventsPageParams) ([]LedgerAuditEvent, error)
	// The audit chain (CP22). Append and read; the schema forbids anything else.
	// The last link, for the recorder to chain onto. Called under the advisory lock.
	AuditHead(ctx context.Context) (AuditHeadRow, error)
	BeginRebuild(ctx context.Context, arg BeginRebuildParams) error
	// Second-factor queries (CP17).
	//
	// Seeds arrive and leave this file sealed; codes and tokens arrive as digests. Nothing here
	// accepts a plaintext seed, code or token.
	// ---------------------------------------------------------------------------
	// TOTP seeds
	// ---------------------------------------------------------------------------
	// Starting or restarting an enrolment replaces the row wholesale: a new seed, unconfirmed,
	// no replay state, no disablement. A confirmed seed is never overwritten by this — the
	// service checks first — but the statement is written so that even a mistaken call cannot
	// turn a confirmed factor into an unconfirmed one.
	//
	BeginTotpEnrolment(ctx context.Context, arg BeginTotpEnrolmentParams) (CoreUserTotp, error)
	// Everyone still in the building, in the order the board draws them.
	//
	// `position` before `station_code` so a station's column appears where the journey puts it:
	// registration on the left, follow-up booking on the right, which is the order staff walk.
	BoardRows(ctx context.Context, arg BoardRowsParams) ([]CoreBoardRow, error)
	// The Clinic Traffic Control board (CP40).
	//
	// Every read here goes through `core.board_row`, never through `core.queue_entry` joined to
	// `core.visit`. The view is an allowlist of columns safe to project onto a wall in a public
	// waiting area, and `core.assert_the_board_shows_nothing_clinical()` fails the deployment if
	// it ever grows. Querying the base tables here would route around both.
	BoardSetting(ctx context.Context, facilityID uuid.UUID) (CoreBoardSetting, error)
	BreakGlassByID(ctx context.Context, id uuid.UUID) (CoreBreakGlassAccess, error)
	// What a person currently holds through the glass: the clinical checkpoints ask this.
	BreakGlassForUser(ctx context.Context, arg BreakGlassForUserParams) ([]CoreBreakGlassAccess, error)
	CallNextAtStation(ctx context.Context, arg CallNextAtStationParams) (CoreQueueEntry, error)
	ChangeDeviceStatus(ctx context.Context, arg ChangeDeviceStatusParams) (CoreDevice, error)
	// Idempotency records (CP24). Claimed before the handler runs, completed after it.
	// Insert the claim, or return nothing if the key is already held. ON CONFLICT DO NOTHING
	// rather than a SELECT-then-INSERT: two concurrent retries of one request must not both
	// believe they are the first.
	ClaimIdempotency(ctx context.Context, arg ClaimIdempotencyParams) (OpsIdempotencyRecord, error)
	// A rebuild starts from nothing, so the failures of the previous derivation are history.
	ClearDeadLetters(ctx context.Context, projection string) error
	CloseVisit(ctx context.Context, arg CloseVisitParams) (CoreVisit, error)
	// Coded diagnoses and complaints (CP52).
	// Which terminologies exist, and what may be done with each. The licence note is part of the
	// answer: the next person to add a system will be tempted to add SNOMED, and this is where
	// they find out that they cannot yet (D-24).
	CodeSystems(ctx context.Context) ([]CodeSystemsRow, error)
	CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) error
	ConfirmTotp(ctx context.Context, arg ConfirmTotpParams) (int64, error)
	ConsentTemplateVersion(ctx context.Context, arg ConsentTemplateVersionParams) (ConsentTemplateVersionRow, error)
	ConsumeDeviceEnrolment(ctx context.Context, arg ConsumeDeviceEnrolmentParams) (int64, error)
	ConsumeShortToken(ctx context.Context, arg ConsumeShortTokenParams) (int64, error)
	// The write side of a demographic correction (CP35). Every field is supplied — the caller
	// has already merged what changed with what did not — so this cannot half-apply.
	CorrectPatient(ctx context.Context, arg CorrectPatientParams) error
	CountLiveRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOpenDeadLetters(ctx context.Context, projection string) (int64, error)
	// The today's-patients fast path (CP31). Every station uses it dozens of times an hour, and
	// it must never become a scan of the register.
	CountTodaysPatients(ctx context.Context, arg CountTodaysPatientsParams) (int64, error)
	// Device queries (CP18).
	//
	// Nothing here deletes. A device is revoked, a key retired, a code consumed.
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (CoreDevice, error)
	// --- enrolment codes ---
	CreateDeviceEnrolment(ctx context.Context, arg CreateDeviceEnrolmentParams) (CoreDeviceEnrolment, error)
	// The id is supplied rather than defaulted, because a rotation has to name the successor
	// in the predecessor's replaced_by column in the same transaction that inserts it.
	//
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CoreRefreshToken, error)
	// Session queries.
	//
	// Every one of these works in digests. No statement in this file accepts or returns a token,
	// because a token exists exactly twice: in the response that issues it, and in the
	// Authorization header that presents it.
	CreateSession(ctx context.Context, arg CreateSessionParams) (CoreSession, error)
	// ---------------------------------------------------------------------------
	// Short-lived tokens
	// ---------------------------------------------------------------------------
	CreateShortToken(ctx context.Context, arg CreateShortTokenParams) (CoreShortToken, error)
	// Identity queries.
	//
	// Scoped to what CP15 owns: creating staff, moving them through their lifecycle, granting
	// and revoking roles, and resolving what a user may do. Authentication (CP16), session
	// handling (CP16) and enforcement (CP19/CP20) each add their own queries in their own
	// checkpoint, beside this file.
	CreateUser(ctx context.Context, arg CreateUserParams) (CoreAppUser, error)
	// CredentialsByCode is the login lookup.
	//
	// Named separately from GetUserByEmployeeCode, which is identical today, because the two
	// have different futures: this one is allowed to read password_hash and the other is not.
	// Keeping them apart from the start means the day somebody narrows the ordinary lookup to
	// exclude the secret columns, there is already a query for the one caller that needs them.
	//
	CredentialsByCode(ctx context.Context, arg CredentialsByCodeParams) (CoreAppUser, error)
	// The rule that applies to one patient and one code, resolved by the database.
	CriticalValueRuleFor(ctx context.Context, arg CriticalValueRuleForParams) (CoreCriticalValueRule, error)
	// Critical values and their escalation (CP50).
	// Every rule, for a station app to evaluate locally so the alarm sounds in the operator's
	// hand at the instant they type, not after a round trip they may not have signal for.
	//
	// **Ordered most specific first, in exactly the order core.critical_value_for resolves.**
	// The same trick as the plausibility rules and the reference ranges: the client's rule is
	// "the first entry whose predicate matches", and it never ranks anything itself. A phone
	// that ranked them could sound an alarm the server did not raise — or, far worse, stay
	// quiet when the server did.
	CriticalValueRules(ctx context.Context) ([]CoreCriticalValueRule, error)
	CurrentPatientPhoto(ctx context.Context, arg CurrentPatientPhotoParams) (CorePatientPhoto, error)
	// What a correction to a field invalidates (CP35). Read from the register rather than
	// from a list in the code, so a checkpoint that adds a derived value adds a row and the
	// correction path picks it up without being edited.
	DerivedDependencies(ctx context.Context, fields []string) ([]DerivedDependenciesRow, error)
	DeviceByID(ctx context.Context, id uuid.UUID) (CoreDevice, error)
	DeviceEnrolmentByDigest(ctx context.Context, codeDigest []byte) (CoreDeviceEnrolment, error)
	DeviceEventsForDevice(ctx context.Context, arg DeviceEventsForDeviceParams) ([]CoreDeviceEvent, error)
	DevicesForFacility(ctx context.Context, facilityID uuid.UUID) ([]CoreDevice, error)
	DisableTotp(ctx context.Context, arg DisableTotpParams) (int64, error)
	EncounterByID(ctx context.Context, arg EncounterByIDParams) (CoreEncounter, error)
	EncountersForVisit(ctx context.Context, arg EncountersForVisitParams) ([]CoreEncounter, error)
	EndBreakGlass(ctx context.Context, arg EndBreakGlassParams) (CoreBreakGlassAccess, error)
	// The station queue (CP39).
	EnterQueue(ctx context.Context, arg EnterQueueParams) (CoreQueueEntry, error)
	// The chain, in order. Read by the worker on every sweep rather than cached: an escalation
	// window edited at nine o'clock should apply to the alert raised at nine-oh-one.
	EscalationChain(ctx context.Context) ([]CoreEscalationStep, error)
	EventByID(ctx context.Context, eventID uuid.UUID) (LedgerEvent, error)
	EventCount(ctx context.Context) (int64, error)
	EventDefaultPartitionCount(ctx context.Context) (int64, error)
	EventKeyByID(ctx context.Context, eventID uuid.UUID) (LedgerEventKey, error)
	// Replay order: the aggregate's own sequence.
	EventsForAggregate(ctx context.Context, arg EventsForAggregateParams) ([]LedgerEvent, error)
	EventsForPatient(ctx context.Context, arg EventsForPatientParams) ([]LedgerEvent, error)
	// Projection order (§7.8): global sequence.
	EventsFromGlobal(ctx context.Context, arg EventsFromGlobalParams) ([]LedgerEvent, error)
	// ExpirePendingEnrolments consumes every open code for a device, so that issuing a new one
	// leaves exactly one that works.
	//
	ExpirePendingEnrolments(ctx context.Context, arg ExpirePendingEnrolmentsParams) (int64, error)
	FacilityCode(ctx context.Context, id uuid.UUID) (string, error)
	// Who a family history is about, with the degree. First-degree family history is a risk
	// factor with a number attached; second-degree is context, and a query that had to enumerate
	// which is which would be a clinical rule living in a WHERE clause somebody copies wrong.
	FamilyRelations(ctx context.Context) ([]CoreFamilyRelation, error)
	FinishEncounter(ctx context.Context, arg FinishEncounterParams) (CoreEncounter, error)
	FinishRebuild(ctx context.Context, arg FinishRebuildParams) error
	GetFacilityByCode(ctx context.Context, code string) (CoreFacility, error)
	// Facility lookups.
	//
	// Facilities are platform-level reference data: every module needs a facility_id, and
	// rendering any clinical timestamp needs the facility's timezone. They are read
	// constantly and written almost never, which is why the queries live here rather than
	// in a domain module that would own them exclusively.
	GetFacilityByID(ctx context.Context, id uuid.UUID) (CoreFacility, error)
	GetRole(ctx context.Context, id uuid.UUID) (CoreRole, error)
	GetRoleByCode(ctx context.Context, code string) (CoreRole, error)
	GetUser(ctx context.Context, id uuid.UUID) (CoreAppUser, error)
	GetUserByEmployeeCode(ctx context.Context, arg GetUserByEmployeeCodeParams) (CoreAppUser, error)
	GrantHistoryForUser(ctx context.Context, userID uuid.UUID) ([]GrantHistoryForUserRow, error)
	GrantRole(ctx context.Context, arg GrantRoleParams) (CoreUserRole, error)
	// The protocol for one indicator, oldest band first, with each standard's identity so a
	// chart can label where the reference changes rather than pretending one curve runs the
	// whole way (D-21).
	GrowthBands(ctx context.Context, indicator string) ([]GrowthBandsRow, error)
	// One table: an indicator, a sex and a standard, in age order.
	GrowthLMS(ctx context.Context, arg GrowthLMSParams) ([]GrowthLMSRow, error)
	// Paediatric growth reference (CP47, D-21).
	// Which standard covers this age for this indicator. D-21's protocol, read as data — so
	// changing it is an UPDATE rather than a release, which is what the decision promised.
	GrowthStandardForAge(ctx context.Context, arg GrowthStandardForAgeParams) (string, error)
	// Stored with every computed percentile, so a value from 2026 stays interpretable if the
	// reference data is ever replaced.
	GrowthStandardVersion(ctx context.Context, code string) (string, error)
	// The day's events in global order, for the anchor. Bounded by recorded_at so the query
	// prunes to the month's partition.
	HashesForDay(ctx context.Context, arg HashesForDayParams) ([]HashesForDayRow, error)
	// Everything currently believed about this patient, in the order station 4 asks it.
	//
	// Removed items are absent: an item somebody removed is one somebody said should not have
	// been recorded, and it belongs in the ledger rather than on the screen. RESOLVED items are
	// present, because "she had this and no longer does" is a clinical fact and a list that hid
	// it would make every follow-up look like a first visit.
	//
	// The concept's displays are joined rather than copied onto the item. A catalogue title that
	// was corrected — a spelling, a better Bangla term — should read correctly on every item
	// coded with it, and a copy would leave the old words on every row recorded before the fix.
	// What is *not* joined is `said`: that is what the patient told this officer on this day, and
	// it is the item's own.
	HistoryForPatient(ctx context.Context, patientID uuid.UUID) ([]HistoryForPatientRow, error)
	HistoryItem(ctx context.Context, id uuid.UUID) (HistoryItemRow, error)
	HistoryKind(ctx context.Context, kind string) (CoreHistoryKind, error)
	// Medical history (CP53).
	// The six kinds and what each one needs. Reference data a station app fetches once and then
	// renders the right fields from — which is what stops a screen asking for a family relation on
	// a complaint, or forgetting to ask for one on a family history.
	HistoryKinds(ctx context.Context) ([]CoreHistoryKind, error)
	IdempotencyRecord(ctx context.Context, arg IdempotencyRecordParams) (OpsIdempotencyRecord, error)
	IdentifiersForPatient(ctx context.Context, patientID uuid.UUID) ([]CorePatientIdentifier, error)
	InsertAnchor(ctx context.Context, arg InsertAnchorParams) (LedgerChainAnchor, error)
	// --- events ---
	InsertDeviceEvent(ctx context.Context, arg InsertDeviceEventParams) error
	// --- keys ---
	InsertDeviceKey(ctx context.Context, arg InsertDeviceKeyParams) (CoreDeviceKey, error)
	InsertEventKey(ctx context.Context, arg InsertEventKeyParams) error
	InsertPatient(ctx context.Context, arg InsertPatientParams) (CorePatient, error)
	InsertPatientIdentifier(ctx context.Context, arg InsertPatientIdentifierParams) (CorePatientIdentifier, error)
	InsertPatientMerge(ctx context.Context, arg InsertPatientMergeParams) error
	InsertPatientPhoto(ctx context.Context, arg InsertPatientPhotoParams) (CorePatientPhoto, error)
	// ---------------------------------------------------------------------------
	// Recovery codes
	// ---------------------------------------------------------------------------
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	InsertResearchSubject(ctx context.Context, arg InsertResearchSubjectParams) error
	// ---------------------------------------------------------------------------
	// Security events
	// ---------------------------------------------------------------------------
	InsertSecurityEvent(ctx context.Context, arg InsertSecurityEventParams) error
	LatestAnchorBefore(ctx context.Context, day time.Time) (LedgerChainAnchor, error)
	LeaveQueue(ctx context.Context, arg LeaveQueueParams) (CoreQueueEntry, error)
	// The highest global sequence in the ledger, for the lag metric. Zero when empty.
	LedgerHead(ctx context.Context) (int64, error)
	LinkBreakGlassAudit(ctx context.Context, arg LinkBreakGlassAuditParams) error
	// The application may INSERT here and may not SELECT (migration 00016). Going from a
	// research finding back to a person is a governed act, not a query a handler can make.
	LinkResearchSubject(ctx context.Context, arg LinkResearchSubjectParams) error
	ListActiveFacilities(ctx context.Context) ([]CoreFacility, error)
	ListPermissions(ctx context.Context) ([]CorePermission, error)
	ListRoles(ctx context.Context) ([]CoreRole, error)
	ListStations(ctx context.Context, facilityID uuid.UUID) ([]CoreStation, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]CoreAppUser, error)
	// The current assertion, if there is one. At most one is live at a time — a new one supersedes
	// the old in the same statement that writes it.
	LiveAssertionForPatient(ctx context.Context, patientID uuid.UUID) (LiveAssertionForPatientRow, error)
	LiveDeviceKey(ctx context.Context, deviceID uuid.UUID) (CoreDeviceKey, error)
	MarkPatientMerged(ctx context.Context, arg MarkPatientMergedParams) error
	// MarkRefreshUsed and RekeySession are the two halves of a rotation.
	//
	// They are separate statements and must be run in one transaction. The intermediate states
	// are both wrong: marking used without inserting the successor locks the user out, and
	// inserting without marking leaves two live tokens in a lineage whose entire purpose is that
	// there is exactly one. The store method that calls them owns the transaction.
	//
	MarkRefreshUsed(ctx context.Context, arg MarkRefreshUsedParams) error
	// The blocking query for the probabilistic pass: everyone this registration could plausibly
	// be, narrowed cheaply so that scoring runs over a handful of rows rather than the register.
	//
	// Four blocks, unioned: the same phonetic key, a similar phonetic key, a similar name in
	// either script, and the same birth date. Each is index-backed. The scoring in Go then
	// decides; this only has to not miss.
	MatchCandidates(ctx context.Context, arg MatchCandidatesParams) ([]MatchCandidatesRow, error)
	MergesForSurvivor(ctx context.Context, survivorID uuid.UUID) ([]CorePatientMerge, error)
	// Patients (CP28). The registration path and the reads it needs.
	NextClinicalID(ctx context.Context, arg NextClinicalIDParams) (string, error)
	NextVisitCode(ctx context.Context, arg NextVisitCodeParams) (string, error)
	// The plan's own mitigation for the risk it names: operators asserting NKA reflexively to
	// clear the gate. It is a query rather than a project because the index is there.
	//
	// Not a judgement. A registration officer whose patients genuinely have no allergies will sit
	// near the top, and so will one who taps the button without asking — which is exactly why this
	// belongs in front of a QA officer rather than in an automatic rule.
	NoKnownAllergyRateByOperator(ctx context.Context, arg NoKnownAllergyRateByOperatorParams) ([]NoKnownAllergyRateByOperatorRow, error)
	// Every vocabulary, in clinical order. Whole rather than per code: the examination screen
	// needs eleven of these the moment the patient sits down, and eleven round trips on a clinic
	// connection is the difference between a two-minute examination and a five-minute one.
	ObservationAnswers(ctx context.Context) ([]CoreObservationAnswer, error)
	ObservationByID(ctx context.Context, arg ObservationByIDParams) (ReadObservation, error)
	ObservationCodeByCode(ctx context.Context, code string) (ObservationCodeByCodeRow, error)
	// Observations and the registry that gives them meaning (CP42).
	// The whole registry, with each code's canonical unit. One query rather than three, because
	// a station app fetches this once on start-up and then validates every entry against it,
	// offline, for the rest of the clinic session.
	ObservationCodes(ctx context.Context) ([]ObservationCodesRow, error)
	// Every value ever recorded for one code on one patient, the replaced ones included. This is
	// what a trend line reads, and what somebody asking "what did it say before" reads.
	ObservationHistoryForCode(ctx context.Context, arg ObservationHistoryForCodeParams) ([]ReadObservation, error)
	// The current value of everything, newest first. Corrected and superseded rows are history,
	// and history is read through ObservationHistoryForCode.
	//
	// The tie-break is the ledger's own sequence, not the code. Two values of the same code can
	// share an effective time — a re-measurement in the same minute, a whole station form saved
	// at once — and a caller that takes "the first row for this code" as the current value would
	// otherwise get an arbitrary one of them. A BMI derived from the wrong one of two heights is
	// a plausible-looking wrong number, which is the worst kind (CP45).
	ObservationsForPatient(ctx context.Context, arg ObservationsForPatientParams) ([]ReadObservation, error)
	ObservationsForVisit(ctx context.Context, arg ObservationsForVisitParams) ([]ReadObservation, error)
	OpenAdminAlerts(ctx context.Context, arg OpenAdminAlertsParams) ([]CoreAdminAlert, error)
	// The consultant's priority surface: everything unacknowledged in this facility, newest
	// first. Small by construction — an alert list long enough to need paging is a clinic in
	// trouble, and the answer to that is not pagination.
	//
	// The display names are joined rather than left to the client. An alert is a message, and a
	// message that says "SPO2 88" makes whoever reads it look the code up; one that says "Oxygen
	// saturation" does not. The registry is the only place those names live (CP42), so this is a
	// join rather than a copy.
	OpenAlerts(ctx context.Context, arg OpenAlertsParams) ([]OpenAlertsRow, error)
	OpenBreakGlass(ctx context.Context, arg OpenBreakGlassParams) (CoreBreakGlassAccess, error)
	OpenDeadLetters(ctx context.Context, projection string) ([]ReadProjectionDeadLetter, error)
	OpenEncounterAtStation(ctx context.Context, arg OpenEncounterAtStationParams) (CoreEncounter, error)
	// Visits and encounters (CP38).
	OpenVisit(ctx context.Context, arg OpenVisitParams) (CoreVisit, error)
	OpenVisitForPatient(ctx context.Context, arg OpenVisitForPatientParams) (CoreVisit, error)
	PatientByClinicalID(ctx context.Context, clinicalID string) (CorePatient, error)
	PatientByID(ctx context.Context, arg PatientByIDParams) (CorePatient, error)
	// The duplicate check with a number in hand. The unique constraint is what actually
	// prevents the duplicate; this is what lets the desk be told about it politely first.
	PatientByIdentifierDigest(ctx context.Context, arg PatientByIdentifierDigestParams) (CorePatient, error)
	// The second deterministic duplicate rule (CP30). A household shares a telephone; a
	// household does not share a telephone *and* an exact date of birth.
	PatientByPhoneAndBirthDate(ctx context.Context, arg PatientByPhoneAndBirthDateParams) (CorePatient, error)
	PatientConsent(ctx context.Context, arg PatientConsentParams) (PatientConsentRow, error)
	PatientConsentHistory(ctx context.Context, arg PatientConsentHistoryParams) ([]PatientConsentHistoryRow, error)
	PatientConsents(ctx context.Context, arg PatientConsentsParams) ([]PatientConsentsRow, error)
	PatientCorrections(ctx context.Context, arg PatientCorrectionsParams) ([]ReadPatientCorrection, error)
	PatientPhotoHistory(ctx context.Context, arg PatientPhotoHistoryParams) ([]CorePatientPhoto, error)
	// The patient timeline (CP37, §8).
	//
	// The permission filter is in SQL, not in Go. A post-filter is how a count comes back larger
	// than the rows returned, and how a paging cursor skips what it hid.
	PatientTimeline(ctx context.Context, arg PatientTimelineParams) ([]PatientTimelineRow, error)
	PatientTimelineCount(ctx context.Context, arg PatientTimelineCountParams) (int64, error)
	// The exact-handle route (CP31). A clinical id, whole or as the six digits somebody reads
	// off a card. Two index lookups, no trigram work: an exact handle is not a guess, and
	// making it pay for fuzzy name matching spends most of the search budget on the one route
	// that should be instant.
	PatientsByClinicalID(ctx context.Context, arg PatientsByClinicalIDParams) ([]PatientsByClinicalIDRow, error)
	// The fuzzy route. Trigram indexes on both name columns and on the phonetic key, ranked by
	// the best of them.
	//
	// `bangla` and `latin` say which scripts the term is written in, decided in Go. Without
	// them a Latin search still pays to compute `similarity(name_bn, 'Rahim')` for every
	// matching row — a comparison that can never be above zero — and at fifty thousand patients
	// that is a measurable share of the search budget (CP31).
	PatientsByName(ctx context.Context, arg PatientsByNameParams) ([]PatientsByNameRow, error)
	PatientsByPhone(ctx context.Context, arg PatientsByPhoneParams) ([]PatientsByPhoneRow, error)
	PermissionsForRole(ctx context.Context, code string) ([]CorePermission, error)
	// PermissionsForUser resolves the union across every live role [R-02].
	//
	// Two conditions carry weight here. `ur.revoked_at IS NULL` means a revoked role stops
	// granting immediately rather than at the next session refresh. `u.status = 'active'`
	// means suspending an account takes effect at once, without walking its grants — which is
	// what makes suspension usable in the minute it is needed.
	//
	PermissionsForUser(ctx context.Context, id uuid.UUID) ([]string, error)
	// The most specific rule for one patient and one code. Resolved by the database so that the
	// client's copy of the resolution rule and the server's cannot disagree about which rule
	// applies — which would show an operator one band and refuse them with another.
	PlausibilityRuleFor(ctx context.Context, arg PlausibilityRuleForParams) (CorePlausibilityRule, error)
	// Every rule, for the station app to evaluate locally. Whole rather than per code, for the
	// same reason the registry is: a tablet fetches it once and warns offline for the rest of
	// the clinic session.
	//
	// **Ordered most specific first, in exactly the order core.plausibility_for resolves.** That
	// is the whole trick: the client's rule is "the first one in this list whose predicate
	// matches", which cannot drift from the server's resolution because the server computed the
	// order. A client reimplementing the specificity ranking is a client that one day shows an
	// operator one band and is refused by another.
	PlausibilityRules(ctx context.Context) ([]CorePlausibilityRule, error)
	ProjectionState(ctx context.Context, name string) (ReadProjectionState, error)
	PurgeExpiredIdempotency(ctx context.Context, cutoff time.Time) (int32, error)
	QueueEntryByID(ctx context.Context, arg QueueEntryByIDParams) (CoreQueueEntry, error)
	QueueForVisit(ctx context.Context, arg QueueForVisitParams) ([]CoreQueueEntry, error)
	RaiseAdminAlert(ctx context.Context, arg RaiseAdminAlertParams) (CoreAdminAlert, error)
	ReadPatientByClinicalID(ctx context.Context, arg ReadPatientByClinicalIDParams) (ReadPatient, error)
	ReadPatientByID(ctx context.Context, arg ReadPatientByIDParams) (ReadPatient, error)
	RecentFailuresForClient(ctx context.Context, arg RecentFailuresForClientParams) (int64, error)
	// RecentFailuresForCode counts against what was typed, not against a user.
	//
	// The code may name nobody. Counting only real accounts would answer "does this person work
	// here" by how quickly the server refuses.
	//
	RecentFailuresForCode(ctx context.Context, arg RecentFailuresForCodeParams) (int64, error)
	RecordDeadLetter(ctx context.Context, arg RecordDeadLetterParams) error
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RecordShortTokenFailure(ctx context.Context, id uuid.UUID) (int32, error)
	// The replay guard and the re-seal, in one statement. The step only moves forward; a row
	// whose step has already passed the one offered is left alone and the caller sees zero rows,
	// which is the refusal.
	//
	RecordTotpUse(ctx context.Context, arg RecordTotpUseParams) (int64, error)
	RecoveryCodeByDigest(ctx context.Context, codeDigest []byte) (CoreRecoveryCode, error)
	// Every normal range, for a station app to flag against locally. Ordered most specific
	// first, in exactly the order core.reference_range_for resolves — so the client takes the
	// first match and never ranks anything itself (the same rule as the plausibility rules).
	ReferenceRanges(ctx context.Context) ([]CoreReferenceRange, error)
	RefreshTokenByDigest(ctx context.Context, tokenDigest []byte) (CoreRefreshToken, error)
	// The projection register and its dead-letter queue (CP25).
	// Insert the projection's row, or return the one already there. The version is not
	// overwritten here: a version that differs from the code's is exactly what the runner has
	// to notice, and silently updating it would erase the signal.
	RegisterProjection(ctx context.Context, arg RegisterProjectionParams) (ReadProjectionState, error)
	RekeySession(ctx context.Context, arg RekeySessionParams) error
	// A handler that failed leaves no claim behind: the client may retry, and a claim nobody
	// completed would refuse them until it expired.
	ReleaseIdempotency(ctx context.Context, arg ReleaseIdempotencyParams) error
	ReopenVisit(ctx context.Context, arg ReopenVisitParams) (CoreVisit, error)
	RerouteQueueEntry(ctx context.Context, arg RerouteQueueEntryParams) (CoreQueueEntry, error)
	ResolveDeadLetter(ctx context.Context, arg ResolveDeadLetterParams) error
	RetireDeviceKeys(ctx context.Context, arg RetireDeviceKeysParams) (int64, error)
	RetirePatientPhoto(ctx context.Context, arg RetirePatientPhotoParams) error
	RevokeRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	// Reuse detection calls both of these, in one transaction.
	//
	// Two plain statements rather than one CTE that updates two tables: the CTE is cleverer and
	// the store has to hold a transaction either way, so the cleverness buys nothing and costs
	// the next person a minute working out what it does.
	//
	// Revoking the tokens alone would not be enough. The access tokens already issued under
	// that family keep working until they expire, which is up to their full lifetime after the
	// theft was detected — so the sessions go too.
	RevokeRefreshFamilyTokens(ctx context.Context, arg RevokeRefreshFamilyTokensParams) (int64, error)
	RevokeRefreshForSession(ctx context.Context, arg RevokeRefreshForSessionParams) error
	// RevokeRole ends a grant without deleting it, so "who could sign on the 14th of March"
	// stays answerable.
	//
	RevokeRole(ctx context.Context, arg RevokeRoleParams) (CoreUserRole, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	// RevokeSessionsForDevice ends every live session on a device the moment it is revoked, so
	// that revocation is effective on the next request rather than at the next refresh.
	//
	RevokeSessionsForDevice(ctx context.Context, arg RevokeSessionsForDeviceParams) (int64, error)
	RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) (int64, error)
	RevokeSessionsInFamily(ctx context.Context, arg RevokeSessionsInFamilyParams) (int64, error)
	RolesForUser(ctx context.Context, userID uuid.UUID) ([]CoreRole, error)
	// One statement, one ranking, one place to explain why a result came first.
	//
	// The tiers, in the order a clinician expects:
	//
	//   1. the code itself, typed. "E11" should be the first thing "E11" finds.
	//   2. a favourite whose words start with what was typed. The clinic's twenty, first.
	//   3. any title or synonym whose words start with it.
	//   4. anything the trigram index thinks is close, for a misspelling.
	//
	// `word` matches at the start of any word rather than only the whole string, because a
	// clinician typing "dia" means diabetes — and a plain prefix would answer "Diabetic
	// polyneuropathy" and not "Type 2 diabetes mellitus", which is the diagnosis this clinic
	// makes more often than any other.
	//
	// The tier is returned with the row. "Why is that third" is the question every search gets
	// asked, and a ranking nobody can inspect is a ranking nobody can tune.
	SearchTerminology(ctx context.Context, arg SearchTerminologyParams) ([]SearchTerminologyRow, error)
	SecurityEventsForUser(ctx context.Context, arg SecurityEventsForUserParams) ([]CoreSecurityEvent, error)
	SessionByID(ctx context.Context, id uuid.UUID) (CoreSession, error)
	// SessionByToken is the authentication path.
	//
	// One equality lookup on a unique index, run on every authenticated request. It is not
	// filtered on revoked_at or expires_at here deliberately: the caller decides, and a row that
	// comes back revoked is a different thing from no row at all when something has to be logged.
	//
	SessionByToken(ctx context.Context, tokenDigest []byte) (CoreSession, error)
	// --- sessions ---
	SessionsForDevice(ctx context.Context, arg SessionsForDeviceParams) ([]CoreSession, error)
	// Unrevoked, not yet expired by the *service's* clock: Sessions.Sessions filters on it.
	// The database's now() is deliberately not consulted here — the service owns time, and a
	// query that quietly used a second clock was the kind of thing that fails at 09:16 on the
	// day a fixed test clock said 09:00.
	SessionsForUser(ctx context.Context, userID uuid.UUID) ([]CoreSession, error)
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error
	SetProjectionStatus(ctx context.Context, arg SetProjectionStatusParams) error
	// SetStationStaffed turns a station on or off for the queue. A station nobody works must
	// not receive patients (§5.2).
	//
	SetStationStaffed(ctx context.Context, arg SetStationStaffedParams) (CoreStation, error)
	// SetUserStatus moves a user through the lifecycle.
	//
	// The transition itself is checked by core.assert_user_status_transition, so an illegal
	// move raises rather than silently writing. The application checks first (auth.Lifecycle)
	// so the caller gets a 422 naming the transition rather than a 500 naming a trigger; the
	// database check is what makes that guarantee true for every other writer.
	//
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (CoreAppUser, error)
	ShortTokenByDigest(ctx context.Context, tokenDigest []byte) (CoreShortToken, error)
	StartEncounter(ctx context.Context, arg StartEncounterParams) (CoreEncounter, error)
	StartQueueService(ctx context.Context, arg StartQueueServiceParams) (CoreQueueEntry, error)
	// What the traffic board reads: one row per station, with the numbers a supervisor acts on.
	StationBoard(ctx context.Context, arg StationBoardParams) ([]StationBoardRow, error)
	StationCodes(ctx context.Context, facilityID uuid.UUID) ([]string, error)
	// How many are waiting at one station right now. The board's realtime delta carries this so
	// a screen can redraw one column without a round trip; a count is not clinical.
	StationDepth(ctx context.Context, arg StationDepthParams) (int64, error)
	StationQueue(ctx context.Context, arg StationQueueParams) ([]CoreQueueEntry, error)
	StationSequence(ctx context.Context, arg StationSequenceParams) ([]StationSequenceRow, error)
	SurvivingPatient(ctx context.Context, pPatient uuid.UUID) (uuid.UUID, error)
	TerminologyConcept(ctx context.Context, arg TerminologyConceptParams) (CoreTerminologyConcept, error)
	// The clinic's own list, in the order it was ranked. Criterion 1 — twenty diagnoses in three
	// keystrokes — is reached by knowing which twenty, not by a cleverer search.
	TerminologyFavourites(ctx context.Context, arg TerminologyFavouritesParams) ([]CoreTerminologyConcept, error)
	// Where a concept maps in another system. Empty until D-24 answers whether SNOMED may be used
	// here; the query exists so that the day it does, nothing above this line changes.
	TerminologyMappings(ctx context.Context, arg TerminologyMappingsParams) ([]CoreTerminologyMap, error)
	TodaysPatients(ctx context.Context, arg TodaysPatientsParams) ([]TodaysPatientsRow, error)
	TotpByUser(ctx context.Context, userID uuid.UUID) (CoreUserTotp, error)
	// TouchDevice records the request just verified: when, and what version of the app made
	// it. The version travels with every signed request so the admin screen is current
	// without an update endpoint.
	//
	TouchDevice(ctx context.Context, arg TouchDeviceParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	// How much of the history has no code, by kind.
	//
	// Criterion 1 says complaints and comorbidities are coded rather than free text, and the
	// escape hatch for a concept the catalogue lacks is what keeps that rule from being one people
	// work around. This is the number that keeps the hatch honest: it is the list of concepts
	// somebody should add, and if it grows the catalogue is wrong rather than the officers.
	UncodedHistoryCount(ctx context.Context, facilityID uuid.UUID) ([]UncodedHistoryCountRow, error)
	UnitByCode(ctx context.Context, code string) (CoreUnit, error)
	Units(ctx context.Context) ([]CoreUnit, error)
	// Spending is conditional on the row still being live, so two concurrent presentations of
	// one code cannot both succeed: the second UPDATE finds used_at set and touches nothing.
	//
	UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error)
	VisitByID(ctx context.Context, arg VisitByIDParams) (CoreVisit, error)
	VisitsForPatient(ctx context.Context, arg VisitsForPatientParams) ([]CoreVisit, error)
	VisitsOnDay(ctx context.Context, arg VisitsOnDayParams) ([]CoreVisit, error)
}

var _ Querier = (*Queries)(nil)
