// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: synthesis.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const currentSynthesis = `-- name: CurrentSynthesis :one
SELECT id, facility_id, visit_id, patient_id, generation, state, trigger,
       context, material_sha256, output, ai_interaction_id, prompt_version, model_version,
       job_id, requested_at, requested_by, started_at, finished_at,
       sla_deadline, met_sla, failure_kind, failure_detail,
       grounding_state, grounding_findings, superseded_at
  FROM core.ai_synthesis
 WHERE visit_id = $1 AND facility_id = $2
 ORDER BY generation DESC
 LIMIT 1
`

type CurrentSynthesisParams struct {
	VisitID    uuid.UUID
	FacilityID uuid.UUID
}

type CurrentSynthesisRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	VisitID           uuid.UUID
	PatientID         uuid.UUID
	Generation        int32
	State             string
	Trigger           string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	JobID             uuid.NullUUID
	RequestedAt       time.Time
	RequestedBy       uuid.NullUUID
	StartedAt         *time.Time
	FinishedAt        *time.Time
	SlaDeadline       *time.Time
	MetSla            *bool
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	SupersededAt      *time.Time
}

// The newest run for a visit. What the physician's screen reads, and what the re-run check
// compares its freshly assembled hash against.
func (q *Queries) CurrentSynthesis(ctx context.Context, arg CurrentSynthesisParams) (CurrentSynthesisRow, error) {
	row := q.db.QueryRow(ctx, currentSynthesis, arg.VisitID, arg.FacilityID)
	var i CurrentSynthesisRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.VisitID,
		&i.PatientID,
		&i.Generation,
		&i.State,
		&i.Trigger,
		&i.Context,
		&i.MaterialSha256,
		&i.Output,
		&i.AiInteractionID,
		&i.PromptVersion,
		&i.ModelVersion,
		&i.JobID,
		&i.RequestedAt,
		&i.RequestedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SlaDeadline,
		&i.MetSla,
		&i.FailureKind,
		&i.FailureDetail,
		&i.GroundingState,
		&i.GroundingFindings,
		&i.SupersededAt,
	)
	return i, err
}

const finishSynthesis = `-- name: FinishSynthesis :one
UPDATE core.ai_synthesis
   SET state = $1,
       context = $2,
       material_sha256 = $3,
       output = $4,
       ai_interaction_id = $5,
       prompt_version = $6,
       model_version = $7,
       finished_at = $8,
       met_sla = CASE WHEN sla_deadline IS NULL THEN NULL
                      ELSE $8 <= sla_deadline END,
       failure_kind = $9,
       failure_detail = $10,
       -- CP72. Written in the same statement as the state, which is what makes
       -- ` + "`" + `ai_synthesis_ready_is_grounded` + "`" + ` a guarantee rather than a race: there is no moment at
       -- which a row is READY and its verdict has not yet arrived.
       grounding_state = $11,
       grounding_findings = $12
 WHERE id = $13 AND state IN ('PENDING', 'RUNNING')
RETURNING id, facility_id, visit_id, patient_id, generation, state, trigger,
          context, material_sha256, output, ai_interaction_id, prompt_version, model_version,
          job_id, requested_at, requested_by, started_at, finished_at,
          sla_deadline, met_sla, failure_kind, failure_detail,
          grounding_state, grounding_findings, superseded_at
`

type FinishSynthesisParams struct {
	State             string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	FinishedAt        *time.Time
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	ID                uuid.UUID
}

type FinishSynthesisRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	VisitID           uuid.UUID
	PatientID         uuid.UUID
	Generation        int32
	State             string
	Trigger           string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	JobID             uuid.NullUUID
	RequestedAt       time.Time
	RequestedBy       uuid.NullUUID
	StartedAt         *time.Time
	FinishedAt        *time.Time
	SlaDeadline       *time.Time
	MetSla            *bool
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	SupersededAt      *time.Time
}

// The terminal write: READY, FAILED or UNCHANGED, with everything the row has to be able to
// account for afterwards. `met_sla` is computed here against the deadline the queue stamped, so
// that §7.1's five minutes is measured from one clock rather than from whichever process was
// asked.
func (q *Queries) FinishSynthesis(ctx context.Context, arg FinishSynthesisParams) (FinishSynthesisRow, error) {
	row := q.db.QueryRow(ctx, finishSynthesis,
		arg.State,
		arg.Context,
		arg.MaterialSha256,
		arg.Output,
		arg.AiInteractionID,
		arg.PromptVersion,
		arg.ModelVersion,
		arg.FinishedAt,
		arg.FailureKind,
		arg.FailureDetail,
		arg.GroundingState,
		arg.GroundingFindings,
		arg.ID,
	)
	var i FinishSynthesisRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.VisitID,
		&i.PatientID,
		&i.Generation,
		&i.State,
		&i.Trigger,
		&i.Context,
		&i.MaterialSha256,
		&i.Output,
		&i.AiInteractionID,
		&i.PromptVersion,
		&i.ModelVersion,
		&i.JobID,
		&i.RequestedAt,
		&i.RequestedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SlaDeadline,
		&i.MetSla,
		&i.FailureKind,
		&i.FailureDetail,
		&i.GroundingState,
		&i.GroundingFindings,
		&i.SupersededAt,
	)
	return i, err
}

const insertSynthesis = `-- name: InsertSynthesis :one

INSERT INTO core.ai_synthesis (
  id, facility_id, visit_id, patient_id, generation, state, trigger,
  context, material_sha256, job_id, requested_at, requested_by, sla_deadline
) VALUES (
  $1, $2, $3, $4,
  -- The generation is computed here rather than passed in. Two stations finishing in the same
  -- second both read "there are two runs" and both write a third; the unique index on
  -- (visit_id, generation) turns that into one winner and one refusal, which is the outcome the
  -- caller can handle. A number chosen in Go from a prior SELECT could not be.
  (SELECT coalesce(max(generation), 0) + 1 FROM core.ai_synthesis WHERE visit_id = $3),
  $5, $6, $7, $8,
  $9, $10, $11, $12
)
RETURNING id, facility_id, visit_id, patient_id, generation, state, trigger,
          context, material_sha256, output, ai_interaction_id, prompt_version, model_version,
          job_id, requested_at, requested_by, started_at, finished_at,
          sla_deadline, met_sla, failure_kind, failure_detail,
          grounding_state, grounding_findings, superseded_at
`

type InsertSynthesisParams struct {
	ID             uuid.UUID
	FacilityID     uuid.UUID
	VisitID        uuid.UUID
	PatientID      uuid.UUID
	State          string
	Trigger        string
	Context        []byte
	MaterialSha256 string
	JobID          uuid.NullUUID
	RequestedAt    time.Time
	RequestedBy    uuid.NullUUID
	SlaDeadline    *time.Time
}

type InsertSynthesisRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	VisitID           uuid.UUID
	PatientID         uuid.UUID
	Generation        int32
	State             string
	Trigger           string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	JobID             uuid.NullUUID
	RequestedAt       time.Time
	RequestedBy       uuid.NullUUID
	StartedAt         *time.Time
	FinishedAt        *time.Time
	SlaDeadline       *time.Time
	MetSla            *bool
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	SupersededAt      *time.Time
}

// The pre-consultation synthesis (CP71, §7.1).
//
// # The query that is deliberately absent
//
// There is no `DELETE`. A summary a physician was shown is evidence of what they were shown, and a
// re-run replaces nothing: it inserts the next generation and stamps the previous one superseded.
// The application's grant holds no DELETE on this table either, so this is a rule rather than a
// habit — the same shape as the interaction log it sits beside.
// Creates a run. Called inside the transaction that decided the work was needed, beside the
// `EnqueueTx` that queues it: a run recorded without its job, or a job without its run, would be
// exactly the split-brain the queue's whole design exists to avoid.
func (q *Queries) InsertSynthesis(ctx context.Context, arg InsertSynthesisParams) (InsertSynthesisRow, error) {
	row := q.db.QueryRow(ctx, insertSynthesis,
		arg.ID,
		arg.FacilityID,
		arg.VisitID,
		arg.PatientID,
		arg.State,
		arg.Trigger,
		arg.Context,
		arg.MaterialSha256,
		arg.JobID,
		arg.RequestedAt,
		arg.RequestedBy,
		arg.SlaDeadline,
	)
	var i InsertSynthesisRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.VisitID,
		&i.PatientID,
		&i.Generation,
		&i.State,
		&i.Trigger,
		&i.Context,
		&i.MaterialSha256,
		&i.Output,
		&i.AiInteractionID,
		&i.PromptVersion,
		&i.ModelVersion,
		&i.JobID,
		&i.RequestedAt,
		&i.RequestedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SlaDeadline,
		&i.MetSla,
		&i.FailureKind,
		&i.FailureDetail,
		&i.GroundingState,
		&i.GroundingFindings,
		&i.SupersededAt,
	)
	return i, err
}

const startSynthesis = `-- name: StartSynthesis :one
UPDATE core.ai_synthesis
   SET state = 'RUNNING', started_at = $1
 WHERE id = $2 AND state = 'PENDING'
RETURNING id, facility_id, visit_id, patient_id, generation, state, trigger,
          context, material_sha256, output, ai_interaction_id, prompt_version, model_version,
          job_id, requested_at, requested_by, started_at, finished_at,
          sla_deadline, met_sla, failure_kind, failure_detail,
          grounding_state, grounding_findings, superseded_at
`

type StartSynthesisParams struct {
	StartedAt *time.Time
	ID        uuid.UUID
}

type StartSynthesisRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	VisitID           uuid.UUID
	PatientID         uuid.UUID
	Generation        int32
	State             string
	Trigger           string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	JobID             uuid.NullUUID
	RequestedAt       time.Time
	RequestedBy       uuid.NullUUID
	StartedAt         *time.Time
	FinishedAt        *time.Time
	SlaDeadline       *time.Time
	MetSla            *bool
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	SupersededAt      *time.Time
}

// A worker has picked the run up. The `state = 'PENDING'` guard is what makes at-least-once
// delivery safe here: a lease that expired and returned the job to the queue must not restart a
// run another worker is already inside, and the second claim gets no row rather than a race.
func (q *Queries) StartSynthesis(ctx context.Context, arg StartSynthesisParams) (StartSynthesisRow, error) {
	row := q.db.QueryRow(ctx, startSynthesis, arg.StartedAt, arg.ID)
	var i StartSynthesisRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.VisitID,
		&i.PatientID,
		&i.Generation,
		&i.State,
		&i.Trigger,
		&i.Context,
		&i.MaterialSha256,
		&i.Output,
		&i.AiInteractionID,
		&i.PromptVersion,
		&i.ModelVersion,
		&i.JobID,
		&i.RequestedAt,
		&i.RequestedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SlaDeadline,
		&i.MetSla,
		&i.FailureKind,
		&i.FailureDetail,
		&i.GroundingState,
		&i.GroundingFindings,
		&i.SupersededAt,
	)
	return i, err
}

const supersedeEarlierSyntheses = `-- name: SupersedeEarlierSyntheses :exec
UPDATE core.ai_synthesis
   SET superseded_at = $1
 WHERE visit_id = $2 AND generation < $3 AND superseded_at IS NULL
`

type SupersedeEarlierSynthesesParams struct {
	At         *time.Time
	VisitID    uuid.UUID
	Generation int32
}

// Stamps every earlier run for this visit as superseded. Run when a new one becomes READY, so the
// history reads as a sequence rather than as a set of competing summaries.
func (q *Queries) SupersedeEarlierSyntheses(ctx context.Context, arg SupersedeEarlierSynthesesParams) error {
	_, err := q.db.Exec(ctx, supersedeEarlierSyntheses, arg.At, arg.VisitID, arg.Generation)
	return err
}

const synthesisByID = `-- name: SynthesisByID :one
SELECT id, facility_id, visit_id, patient_id, generation, state, trigger,
       context, material_sha256, output, ai_interaction_id, prompt_version, model_version,
       job_id, requested_at, requested_by, started_at, finished_at,
       sla_deadline, met_sla, failure_kind, failure_detail,
       grounding_state, grounding_findings, superseded_at
  FROM core.ai_synthesis
 WHERE id = $1 AND facility_id = $2
`

type SynthesisByIDParams struct {
	ID         uuid.UUID
	FacilityID uuid.UUID
}

type SynthesisByIDRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	VisitID           uuid.UUID
	PatientID         uuid.UUID
	Generation        int32
	State             string
	Trigger           string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	JobID             uuid.NullUUID
	RequestedAt       time.Time
	RequestedBy       uuid.NullUUID
	StartedAt         *time.Time
	FinishedAt        *time.Time
	SlaDeadline       *time.Time
	MetSla            *bool
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	SupersededAt      *time.Time
}

func (q *Queries) SynthesisByID(ctx context.Context, arg SynthesisByIDParams) (SynthesisByIDRow, error) {
	row := q.db.QueryRow(ctx, synthesisByID, arg.ID, arg.FacilityID)
	var i SynthesisByIDRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.VisitID,
		&i.PatientID,
		&i.Generation,
		&i.State,
		&i.Trigger,
		&i.Context,
		&i.MaterialSha256,
		&i.Output,
		&i.AiInteractionID,
		&i.PromptVersion,
		&i.ModelVersion,
		&i.JobID,
		&i.RequestedAt,
		&i.RequestedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SlaDeadline,
		&i.MetSla,
		&i.FailureKind,
		&i.FailureDetail,
		&i.GroundingState,
		&i.GroundingFindings,
		&i.SupersededAt,
	)
	return i, err
}

const synthesisHistory = `-- name: SynthesisHistory :many
SELECT id, facility_id, visit_id, patient_id, generation, state, trigger,
       context, material_sha256, output, ai_interaction_id, prompt_version, model_version,
       job_id, requested_at, requested_by, started_at, finished_at,
       sla_deadline, met_sla, failure_kind, failure_detail,
       grounding_state, grounding_findings, superseded_at
  FROM core.ai_synthesis
 WHERE visit_id = $1 AND facility_id = $2
 ORDER BY generation DESC
`

type SynthesisHistoryParams struct {
	VisitID    uuid.UUID
	FacilityID uuid.UUID
}

type SynthesisHistoryRow struct {
	ID                uuid.UUID
	FacilityID        uuid.UUID
	VisitID           uuid.UUID
	PatientID         uuid.UUID
	Generation        int32
	State             string
	Trigger           string
	Context           []byte
	MaterialSha256    string
	Output            []byte
	AiInteractionID   uuid.NullUUID
	PromptVersion     *string
	ModelVersion      *string
	JobID             uuid.NullUUID
	RequestedAt       time.Time
	RequestedBy       uuid.NullUUID
	StartedAt         *time.Time
	FinishedAt        *time.Time
	SlaDeadline       *time.Time
	MetSla            *bool
	FailureKind       *string
	FailureDetail     string
	GroundingState    string
	GroundingFindings int32
	SupersededAt      *time.Time
}

// Every run for a visit, newest first. The audit view: what was on the screen at each point of the
// consultation, and why the earlier one was replaced.
func (q *Queries) SynthesisHistory(ctx context.Context, arg SynthesisHistoryParams) ([]SynthesisHistoryRow, error) {
	rows, err := q.db.Query(ctx, synthesisHistory, arg.VisitID, arg.FacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SynthesisHistoryRow{}
	for rows.Next() {
		var i SynthesisHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.VisitID,
			&i.PatientID,
			&i.Generation,
			&i.State,
			&i.Trigger,
			&i.Context,
			&i.MaterialSha256,
			&i.Output,
			&i.AiInteractionID,
			&i.PromptVersion,
			&i.ModelVersion,
			&i.JobID,
			&i.RequestedAt,
			&i.RequestedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SlaDeadline,
			&i.MetSla,
			&i.FailureKind,
			&i.FailureDetail,
			&i.GroundingState,
			&i.GroundingFindings,
			&i.SupersededAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const synthesisSLA = `-- name: SynthesisSLA :one
SELECT count(*)::bigint AS finished,
       count(*) FILTER (WHERE met_sla)::bigint AS met,
       count(*) FILTER (WHERE state = 'FAILED')::bigint AS failed,
       count(*) FILTER (WHERE trigger = 'MANUAL')::bigint AS manual,
       coalesce(
         percentile_disc(0.95) WITHIN GROUP (
           ORDER BY extract(epoch FROM (finished_at - requested_at))), 0)::double precision
         AS p95_seconds
  FROM core.ai_synthesis
 WHERE facility_id = $1
   AND finished_at >= $2
   AND finished_at <= $3
`

type SynthesisSLAParams struct {
	FacilityID uuid.UUID
	Since      *time.Time
	Until      *time.Time
}

type SynthesisSLARow struct {
	Finished   int64
	Met        int64
	Failed     int64
	Manual     int64
	P95Seconds float64
}

// Acceptance criterion 1, as a number somebody can put on a screen: of the runs that finished in
// this window, how many made §7.1's deadline.
//
// `UNCHANGED` runs count. They are a completed promise — the physician's page was checked and was
// already current — and excluding them would let a clinic hit 95% by re-requesting summaries it
// knew were fresh.
func (q *Queries) SynthesisSLA(ctx context.Context, arg SynthesisSLAParams) (SynthesisSLARow, error) {
	row := q.db.QueryRow(ctx, synthesisSLA, arg.FacilityID, arg.Since, arg.Until)
	var i SynthesisSLARow
	err := row.Scan(
		&i.Finished,
		&i.Met,
		&i.Failed,
		&i.Manual,
		&i.P95Seconds,
	)
	return i, err
}
