import { issueCommand, readProjections, type Command, type Executor } from '@/lib/sync';
import type { LocalStore } from '@/lib/local-store';

import { toVitalsBatch, type PreviousVital, type Reading } from './form';

/**
 * Station 5, offline (CP64/CP66, §15.2).
 *
 * This is the worked example the other eleven stations follow, and it is here rather than in the
 * screen for the reason every station has followed since CP33: a decision inside a React Native
 * component is a decision nobody can test.
 *
 * # One builder, two destinations
 *
 * `toVitalsBatch` already decides what a set of readings means — which values were entered, that
 * two readings a minute apart are two facts rather than a correction, that the arm and cuff travel
 * with the blood pressure they describe. **That function is reused unchanged**, and each
 * observation it produces becomes one local command. So the shape the clinic receives cannot drift
 * from the shape the screen composes: there is one builder, and the offline path is a different
 * destination for its output rather than a second implementation of it.
 *
 * # What the client has to supply that the server used to
 *
 * Two things, and both belong to the fact rather than to the moment it arrived:
 *
 *   - **`observation_id`.** Generated by the server on the online path; generated here offline,
 *     because a measurement recorded on a tablet in a corridor needs an identity before anything
 *     has accepted it.
 *   - **`facility_id`.** From the session. The ledger requires it and the projection is scoped by
 *     it; a client that guessed would have every event refused with `INVALID_PAYLOAD` — which is
 *     surfaced rather than silent, but is still a morning of measurements nobody can use.
 *
 * Everything else the server assigns — `recorded_at`, the actor, the source — stays the server's,
 * because a client that could supply them could forge attribution.
 *
 * # `source` is what the station is, not how the value travelled
 *
 * `STATION` for a value an operator measured, whether it syncs in two seconds or tomorrow
 * morning. The ledger's `source` — the one that says a value arrived through a queue — is the
 * envelope's, and it is the server's to set.
 */

/** The event type every station's measurement is: one payload for all of them (CP42). */
export const OBSERVATION_EVENT = 'OBSERVATION_RECORDED';

export interface VitalsContext {
  facilityId: string;
  patientId: string;
  visitId?: string | null;
  /** The encounter, when the station is working inside one. */
  encounterId?: string | null;
}

export interface VitalsIds {
  /** A stable id per (reading, code), so a retry writes the same values. */
  perValue: (readingIndex: number, code: string) => string;
  /** When each reading was taken. */
  takenAt: (readingIndex: number) => string;
  /** The observation's own identity. Server-generated online; ours offline. */
  newObservationId: () => string;
}

/**
 * The readings as local commands, one per observation, in the order they were measured.
 *
 * The order matters: they share an aggregate (the patient), and the clinic applies a batch in the
 * order it arrives, so the sequence the operator worked in is the sequence the record holds.
 */
export function vitalsCommands(
  readings: readonly Reading[],
  ids: VitalsIds,
  context: VitalsContext,
): Command[] {
  const batch = toVitalsBatch(readings, {
    // The batch's own id is unused offline — there is no request to make idempotent, because
    // every event carries its own key — but `toVitalsBatch` asks for one and inventing a second
    // shape to avoid passing it would be the drift this function exists to prevent.
    batch: ids.newObservationId(),
    patient: context.patientId,
    perValue: ids.perValue,
    takenAt: ids.takenAt,
  });

  return batch.observations.map((observation) => {
    const payload: Record<string, unknown> = {
      observation_id: ids.newObservationId(),
      facility_id: context.facilityId,
      patient_id: context.patientId,
      code: observation.code,
      effective_at: observation.effective_at,
      source: 'STATION',
    };
    if (context.visitId) payload.visit_id = context.visitId;
    if (context.encounterId) payload.encounter_id = context.encounterId;
    // Exactly one value shape, which is what the ledger validates: a number with its unit, or a
    // code. `toVitalsBatch` has already decided which this is.
    if (observation.value !== undefined) {
      payload.value = observation.value;
      payload.unit = observation.unit;
    } else if (observation.value_code !== undefined) {
      payload.value_code = observation.value_code;
    }

    return {
      eventId: observation.event_id,
      aggregateType: 'PATIENT',
      aggregateId: context.patientId,
      patientId: context.patientId,
      visitId: context.visitId ?? null,
      eventType: OBSERVATION_EVENT,
      eventVersion: 1,
      // When the value was true. The envelope's own time is when it was written down, and the
      // two are different questions — a blood pressure taken at 09:05 and entered at 09:20.
      occurredAt: observation.effective_at,
      payload,
    };
  });
}

/**
 * Record a set of readings on this device.
 *
 * Returns the event ids, which the screen keeps: a save the operator was told had failed is
 * re-issued with the same ids and is one measurement, not two.
 *
 * There is no network call here and there is no online variant of this function. That is the
 * checkpoint: the station writes locally, the engine delivers, and the operator is told the truth
 * about which of those has happened.
 */
export async function recordVitals(
  store: LocalStore,
  readings: readonly Reading[],
  ids: VitalsIds,
  context: VitalsContext,
  deps: { now?: () => number } = {},
): Promise<string[]> {
  const commands = vitalsCommands(readings, ids, context);
  const written: string[] = [];
  for (const command of commands) {
    const issued = await issueCommand(store, command, deps);
    written.push(issued.eventId);
  }
  return written;
}

/**
 * What this patient's vitals were last time, from the local record.
 *
 * Shaped as the rows `previousVitals` and `previousVitalSourcesFrom` already read, so the screen's
 * comparison line and its "entered by" chip work identically whether the values came down from
 * the clinic this morning or were recorded on this tablet ten minutes ago.
 *
 * A value this device has not yet delivered carries no attribution, and that is deliberate: the
 * actor is assigned by the server from an unforgeable identity, so a row that named somebody
 * locally would be asserting what it cannot know. The screen draws those as pending.
 */
export async function previousVitalsLocally(
  store: Executor,
  patientId: string,
): Promise<PreviousVital[]> {
  const projections = await readProjections(store, patientId, 'observation');
  const rows: PreviousVital[] = [];
  for (const projection of projections) {
    const document = projection.document;
    const value = document.value;
    rows.push({
      code: String(document.code ?? ''),
      value: typeof value === 'number' ? value : null,
      ...(typeof document.recorded_by === 'string' ? { recorded_by: document.recorded_by } : {}),
      ...(typeof document.recorded_role === 'string'
        ? { recorded_role: document.recorded_role }
        : {}),
      ...(typeof document.recorded_at === 'string' ? { recorded_at: document.recorded_at } : {}),
      ...(typeof document.station_code === 'string' ? { station_code: document.station_code } : {}),
      ...(typeof document.source === 'string' ? { source: document.source } : {}),
      // The projection's own stamp, so the sort below is by when the value was true rather than
      // by when the clinic heard about it — the ordering a clinician means by "the last one".
      effective_at: projection.occurredAt,
    });
  }
  // Newest first, which is the order `previousVitals` and `previousVitalSourcesFrom` read: the
  // first sighting of a code is the current one.
  return rows.sort((a, b) => (b.effective_at ?? '').localeCompare(a.effective_at ?? ''));
}
