/**
 * Station 8's exercise assessment and plan (CP60, §3 step 8, §12.1).
 *
 * The public surface is the screen, the five calls, and the pure decisions the tests check. What
 * is deliberately **not** here, and must never be added:
 *
 *  - anything that returns the exercise library. There is no such route in the contract, and a
 *    helper here that assembled one from anywhere would put the excluded rows on the device —
 *    which is the single thing acceptance criterion 1 forbids;
 *  - anything that computes a weekly total. `minutes_per_week` is derived once on the server, per
 *    item and per plan, so a screen, a printed sheet and §12.1's research extract cannot each
 *    round it differently.
 */

export { ExerciseStation } from './ExerciseStation';
export {
  issuePlan,
  listContraindications,
  readExerciseRecord,
  readOptions,
  recordAssessment,
  troubleOf,
} from './api';
export {
  ADVICE,
  ATTEMPTS,
  CODE_CONTRAINDICATED,
  CODE_NO_ASSESSMENT,
  CODE_RETIRED,
  CODE_SUPERSEDED,
  CONDITION_ANSWERS,
  EXCLUSION_STATUSES,
  MINUTES_PER_SESSION,
  NUMBER_PROBLEMS,
  REVIEWS,
  STEPS,
  TARGET_PROBLEMS,
  TIMES_PER_WEEK,
  WALKS_ANSWERS,
  WALK_MINUTES,
  adviceFor,
  answerCondition,
  answerWalks,
  askedOf,
  assessmentReading,
  chooseExercise,
  conditionsOf,
  contraindicated,
  duplicated,
  emptyAssessment,
  emptyStage,
  exclusionReading,
  incomplete,
  isChosen,
  keepOffered,
  namesExercise,
  namesOf,
  noAssessment,
  noTargets,
  offerRows,
  planReading,
  questionRows,
  questionsMissing,
  readsAsFailure,
  refusedRow,
  reviewFor,
  serverSpoke,
  stepFor,
  retired,
  superseded,
  targetFor,
  targetProblem,
  targetProblems,
  toAssessmentBody,
  toPlanBody,
  troubleKey,
  typeJointPain,
  typeMinutes,
  typeTimes,
  typeWalkMinutes,
  unanswered,
  unapproved,
  walkMinutesProblem,
  wordingOf,
  type Advice,
  type Assessment,
  type AssessmentBody,
  type AssessmentDraft,
  type AssessmentReading,
  type Attempt,
  type Chosen,
  type ConditionAnswer,
  type Contraindication,
  type Exclusion,
  type ExclusionReading,
  type ExclusionReason,
  type ExclusionStatus,
  type Exercise,
  type Locale,
  type NumberProblem,
  type OfferRow,
  type Options,
  type Plan,
  type PlanBody,
  type PlanItem,
  type PlanReading,
  type PlanTarget,
  type QuestionRow,
  type Review,
  type SheetRow,
  type Stage,
  type Step,
  type TargetDraft,
  type TargetProblem,
  type Trouble,
  type WalksAnswer,
  type Wording,
} from './state';
