/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Is the process alive?
     * @description Answers one question: is this process running and able to serve HTTP?
     *
     *     It deliberately **never touches a dependency**. A failing database must not
     *     cause the orchestrator to kill and restart a perfectly healthy process — that
     *     turns one outage into two, and the restarted process fails exactly the same way.
     *     Dependency health is `/readyz`.
     */
    get: operations['getLiveness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Can it serve requests?
     * @description Checks every declared dependency in parallel and reports which one is unhappy.
     *
     *     Dependency failures are reported as a **status word, never as the underlying
     *     error text**: a connection error can contain a host, a user name or a password.
     *     The detail goes to the log, where it is access-controlled.
     *
     *     A critical dependency being unavailable makes the service unready (503). A
     *     non-critical one degrades it but still reports 200 — the blob store being down
     *     stops document upload, not the clinic.
     */
    get: operations['getReadiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * What exactly is running?
     * @description The build identity of the running binary: version, commit and build time.
     *
     *     This is the first question in any incident, and the one that is hardest to
     *     answer from outside. Values are injected at build time through `ldflags`; a
     *     development build reports `0.1.0-dev` with `unknown` for commit and build time,
     *     which is itself the answer to "is this a real build?"
     */
    get: operations['getVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Error
     * @description The one shape an error takes on the wire. Every non-2xx response is this
     *     envelope — there is no second error format anywhere in the API.
     */
    Error: {
      error: components['schemas']['ErrorBody'];
    };
    /**
     * ErrorBody
     * @example {
     *       "code": "VALIDATION_FAILED",
     *       "kind": "validation",
     *       "message": "Some values need correcting.",
     *       "message_bn": "কিছু তথ্য সংশোধন করতে হবে।",
     *       "fields": {
     *         "date_of_birth": "A date of birth cannot be in the future."
     *       },
     *       "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
     *     }
     */
    ErrorBody: {
      /**
       * @description Stable, machine-readable, and the **only** thing a client may branch on.
       *     Message text is written for humans and will be reworded; codes will not.
       * @example VALIDATION_FAILED
       * @example NOT_FOUND
       * @example RATE_LIMITED
       */
      code: string;
      kind: components['schemas']['ErrorKind'];
      /**
       * @description English, shown to the user. Never contains internal detail — no query text,
       *     no file path, and no indication of whether a resource the caller may not see
       *     happens to exist.
       */
      message: string;
      /**
       * @description Bangla, shown to the user. Always present, never a fallback to English:
       *     half the clinic's staff work in Bangla, and an error is exactly the moment
       *     a person needs their own language.
       */
      message_bn: string;
      /**
       * @description Per-field validation messages, keyed by field name. Present on
       *     `VALIDATION_FAILED`, absent otherwise.
       * @example {
       *       "date_of_birth": "A date of birth cannot be in the future."
       *     }
       */
      fields?: {
        [key: string]: string;
      };
      /**
       * @description The request's correlation ID, repeated in the body so it survives being
       *     screenshotted — which is how errors are actually reported from a clinic.
       */
      correlation_id?: string;
    };
    /**
     * ErrorKind
     * @description What sort of error this is, and therefore how the interface should respond.
     *
     *     The distinction is not cosmetic. A blocked safety rule needs an override path
     *     with a recorded reason; a database timeout needs a retry button. An interface
     *     that shows the same red box for both teaches staff to dismiss both.
     * @enum {string}
     */
    ErrorKind: 'validation' | 'auth' | 'not_found' | 'conflict' | 'clinical' | 'technical';
    /**
     * PageInfo
     * @description Cursor pagination. A list response is `{ "items": [...], "page": PageInfo }`.
     *
     *     Cursors rather than page numbers because clinical lists change underneath the
     *     person reading them. A queue gains a patient while an operator is on page two;
     *     with offset pagination that shifts every subsequent row, so the operator sees
     *     one patient twice and never sees another at all. A cursor is a position in the
     *     data, not a count of rows skipped, so an insertion above it changes nothing.
     *
     *     The cost is that there is no "jump to page 7" and no total count. Neither is
     *     something a station operator has ever needed; both are things a paging bug
     *     would happily provide.
     */
    PageInfo: {
      /** @description Pass as `cursor` to fetch the next page. `null` on the last page. */
      next_cursor?: string | null;
      /**
       * @description Whether another page exists. **The only reliable end-of-list signal** — a
       *     page shorter than `limit` does not mean the end.
       */
      has_more: boolean;
    };
    /** LivenessResponse */
    LivenessResponse: {
      /** @enum {string} */
      status: 'ok';
      /**
       * @description Which binary answered. One of api, worker, realtime, migrate.
       * @example api
       */
      service: string;
      /** @example 0.1.0-dev */
      version: string;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** @enum {string} */
      status: 'ok' | 'unready';
      /** @example api */
      service: string;
      /** @example 0.1.0-dev */
      version: string;
      /**
       * @description One entry per declared dependency. A status word only — never the underlying
       *     error, which may carry a host, a user name or a password.
       * @example {
       *       "postgres": "ok",
       *       "redis": "ok",
       *       "blobstore": "unavailable"
       *     }
       */
      checks?: {
        [key: string]: 'ok' | 'unavailable';
      };
    };
    /** VersionResponse */
    VersionResponse: {
      /** @example api */
      service: string;
      /** @example 0.1.0 */
      version: string;
      /** @description The git commit this binary was built from, or `unknown` locally. */
      commit: string;
      /** @description RFC 3339 build timestamp, or `unknown` locally. */
      build_time: string;
    };
  };
  responses: {
    /** @description The request could not be understood. `BAD_REQUEST`. */
    BadRequest: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "BAD_REQUEST",
         *         "kind": "validation",
         *         "message": "The request could not be understood.",
         *         "message_bn": "অনুরোধটি বোঝা যায়নি।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description No valid session. `UNAUTHENTICATED`. */
    Unauthenticated: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "UNAUTHENTICATED",
         *         "kind": "auth",
         *         "message": "Please sign in again.",
         *         "message_bn": "অনুগ্রহ করে আবার সাইন ইন করুন।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /**
     * @description The caller may not do this. `FORBIDDEN`.
     *
     *     Deliberately **identical whether the resource is missing or merely forbidden**.
     *     Telling a caller that a patient exists but is out of reach is itself a
     *     disclosure.
     */
    Forbidden: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "FORBIDDEN",
         *         "kind": "auth",
         *         "message": "You do not have permission to do that.",
         *         "message_bn": "এই কাজটি করার অনুমতি আপনার নেই।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description No such resource, or none the caller may see. `NOT_FOUND`. */
    NotFound: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "NOT_FOUND",
         *         "kind": "not_found",
         *         "message": "Not found.",
         *         "message_bn": "পাওয়া যায়নি।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /**
     * @description The request contradicts current state. `CONFLICT`.
     *
     *     Also returned when an `Idempotency-Key` is reused with a different body.
     */
    Conflict: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "CONFLICT",
         *         "kind": "conflict",
         *         "message": "This conflicts with a change someone else made.",
         *         "message_bn": "অন্য কেউ পরিবর্তন করায় দ্বন্দ্ব তৈরি হয়েছে।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description The request body exceeds the configured limit. `PAYLOAD_TOO_LARGE`. */
    PayloadTooLarge: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "PAYLOAD_TOO_LARGE",
         *         "kind": "validation",
         *         "message": "The request is too large.",
         *         "message_bn": "অনুরোধটি অনেক বড়।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /**
     * @description One or more values failed a rule. `VALIDATION_FAILED`, with `fields` naming
     *     each one.
     */
    ValidationFailed: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "VALIDATION_FAILED",
         *         "kind": "validation",
         *         "message": "Some values need correcting.",
         *         "message_bn": "কিছু তথ্য সংশোধন করতে হবে।",
         *         "fields": {
         *           "date_of_birth": "A date of birth cannot be in the future."
         *         },
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Too many requests. `RATE_LIMITED`. Implemented at CP49. */
    RateLimited: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        'Retry-After': components['headers']['RetryAfter'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "RATE_LIMITED",
         *         "kind": "validation",
         *         "message": "Too many requests. Please slow down.",
         *         "message_bn": "অনেক বেশি অনুরোধ। একটু ধীরে চেষ্টা করুন।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /**
     * @description The system failed. `INTERNAL`. The cause is logged against the correlation ID
     *     and never returned.
     */
    Internal: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "INTERNAL",
         *         "kind": "technical",
         *         "message": "Something went wrong. The team has been notified.",
         *         "message_bn": "কিছু একটা সমস্যা হয়েছে। বিষয়টি জানানো হয়েছে।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Temporarily unable to serve. `UNAVAILABLE`. Retryable. */
    Unavailable: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        'Retry-After': components['headers']['RetryAfter'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "UNAVAILABLE",
         *         "kind": "technical",
         *         "message": "The service is temporarily unavailable. Please try again.",
         *         "message_bn": "সেবাটি সাময়িকভাবে বন্ধ আছে। আবার চেষ্টা করুন।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description The request took too long. `TIMEOUT`. Retryable. */
    Timeout: {
      headers: {
        'X-Request-ID': components['headers']['XRequestID'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "TIMEOUT",
         *         "kind": "technical",
         *         "message": "The request took too long. Please try again.",
         *         "message_bn": "অনুরোধটি সম্পন্ন হতে বেশি সময় নিচ্ছে। আবার চেষ্টা করুন।",
         *         "correlation_id": "0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d"
         *       }
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    /**
     * @description Opaque cursor from the previous page's `page.next_cursor`. Omit for the first
     *     page. The value is not parseable by clients and its encoding is not part of the
     *     contract — treat it as a token to hand back.
     * @example eyJhZnRlciI6IjAxOThjNGUyIn0
     */
    Cursor: string;
    /**
     * @description Maximum items to return. The server may return fewer — never assume a short page
     *     means the end; `page.has_more` is the only reliable signal.
     */
    Limit: number;
    /**
     * @description Return only records changed at or after this instant. The standard filter for a
     *     station application catching up after a period offline.
     * @example 2026-08-24T06:00:00Z
     */
    UpdatedSince: string;
    /**
     * @description A client-generated UUIDv7 making a write safe to retry.
     *
     *     Required on **every** state-changing request. A clinic's connection drops
     *     mid-save routinely, and the station application queues writes offline and
     *     replays them on reconnect. Without this header, one recorded blood-pressure
     *     reading becomes two rows in an append-only ledger — which, the ledger being
     *     append-only, is not something anybody can quietly tidy up afterwards.
     *
     *     The server stores the outcome against the key and returns the **original
     *     response** for a repeat, rather than performing the work twice. The same key
     *     with a genuinely different body is a `409 CONFLICT`, not a silent overwrite.
     *
     *     Keys are generated by the client *before* the request is queued, which is what
     *     makes an offline replay safe: the identifier travels with the event rather than
     *     being assigned on arrival.
     * @example 0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d
     */
    IdempotencyKey: string;
    /**
     * @description A client-supplied correlation ID. Echoed back on the response. The server
     *     generates one when this is absent or longer than 64 characters.
     */
    RequestID: string;
  };
  requestBodies: never;
  headers: {
    /**
     * @description The correlation ID for this request, echoed on **every** response including
     *     errors. A station operator reporting a problem can read it down the phone, and
     *     it ties together every log line, span and background job belonging to the one
     *     interaction.
     *
     *     A client may supply its own on the way in (up to 64 characters); the server
     *     generates a UUIDv7 when it does not.
     * @example 0198c4e2-7f3a-7000-8c1d-2b4e6a8f0c3d
     */
    XRequestID: string;
    /**
     * @description Present when the endpoint is deprecated. Carries the RFC 9745 date after which
     *     it may stop working. The endpoint keeps functioning until the API version is
     *     retired — a station tablet running a three-week-old build must not break because
     *     a deprecation landed on the server.
     * @example @1793404800
     */
    Deprecation: string;
    /**
     * @description Seconds to wait before retrying. Present on 429 and, where known, 503.
     * @example 30
     */
    RetryAfter: number;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getLiveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The process is alive. */
      200: {
        headers: {
          'X-Request-ID': components['headers']['XRequestID'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LivenessResponse'];
        };
      };
    };
  };
  getReadiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready to serve. Every critical dependency answered. */
      200: {
        headers: {
          'X-Request-ID': components['headers']['XRequestID'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadinessResponse'];
        };
      };
      /**
       * @description Not ready. At least one **critical** dependency did not answer. The response
       *     body names which, so the on-call engineer does not have to guess.
       */
      503: {
        headers: {
          'X-Request-ID': components['headers']['XRequestID'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadinessResponse'];
        };
      };
    };
  };
  getVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Build information for this binary. */
      200: {
        headers: {
          'X-Request-ID': components['headers']['XRequestID'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionResponse'];
        };
      };
    };
  };
}
