package patient

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"errors"
	"fmt"
	"strings"
	"unicode"

	"github.com/AmlanWTK/DTHCMS/backend/internal/platform/secretbox"
)

// The two identifiers, and why they are shaped as they are (CP28, ADR-0020).
//
//	clinical_id   DTHC-FRD-2026-000137. Spoken at a desk, written on a card, typed by a
//	              person who is looking at the patient rather than the screen. Sequential
//	              within a facility and year, gapless, generated by the database.
//	research_id   RS-7K2MQ9XW4B6NPRTVYZ3H5DFGJ8. Opaque, from a cryptographic random
//	              source, carrying no ordering and no facility. §12 requires that a
//	              research finding cannot be traced back to a person by inspection, and an
//	              id derived from — or merely correlated with — the clinical id would make
//	              that untrue while looking fine.
//
// The two must not be derivable from each other. The test that holds this generates a
// thousand pairs and asserts that sorting by one produces no ordering in the other.

// ResearchIDPrefix marks the shape in a log or a spreadsheet, so that a research id pasted
// somewhere it does not belong is recognisable as one.
const ResearchIDPrefix = "RS-"

// crockford is Crockford's base32: no I, L, O or U, so a research id read aloud or
// transcribed from a printout does not turn into a different one. U is omitted to avoid
// accidental obscenities, which is Crockford's own reasoning and worth keeping.
const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

// researchIDBytes is 130 bits before encoding, which is 26 base32 characters. Well past
// any birthday concern, and short enough to fit in a spreadsheet column.
const researchIDBytes = 17

// NewResearchID returns an opaque subject identifier.
//
// crypto/rand, not a hash of anything the clinic knows. A research id derived from the
// patient id — even through a keyed hash — is one that becomes reversible the day the key
// leaks, and the whole point is that the research dataset survives that day.
func NewResearchID() (string, error) {
	raw := make([]byte, researchIDBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("patient: no random source for a research id: %w", err)
	}
	var out strings.Builder
	out.WriteString(ResearchIDPrefix)
	// 17 bytes = 136 bits; 26 characters carry 130. The last six bits are dropped, which
	// is fine: what matters is that every character is uniformly random.
	var acc uint64
	var bits uint
	for _, b := range raw {
		acc = acc<<8 | uint64(b)
		bits += 8
		for bits >= 5 && out.Len() < len(ResearchIDPrefix)+26 {
			bits -= 5
			out.WriteByte(crockford[(acc>>bits)&0x1F])
		}
	}
	for out.Len() < len(ResearchIDPrefix)+26 {
		out.WriteByte(crockford[0])
	}
	return out.String(), nil
}

// ValidResearchID reports whether a string has the shape the database will accept.
func ValidResearchID(id string) bool {
	if !strings.HasPrefix(id, ResearchIDPrefix) {
		return false
	}
	body := id[len(ResearchIDPrefix):]
	if len(body) != 26 {
		return false
	}
	for _, r := range body {
		if !strings.ContainsRune(crockford, r) {
			return false
		}
	}
	return true
}

// --- official numbers ---

// ErrNoPepper is returned when the identifier hasher has no key. A digest computed without
// one is a plain SHA-256 of a ten-digit number, which is reversible by anyone with a
// laptop and a weekend — so the absence is refused rather than defaulted.
var ErrNoPepper = errors.New("patient: no identifier pepper configured")

// IdentifierSealer turns a number into the three forms the database holds: a digest for
// matching, a sealed value for retrieval, and a mask for display. It never returns the
// number, and nothing here stores it.
type IdentifierSealer struct {
	// pepper is deployment-wide and lives with the other secrets (CP12). It is not per
	// patient: the digest has to match across patients for duplicate detection to work,
	// which is exactly what a per-row salt would prevent.
	pepper []byte
	ring   *secretbox.Ring
}

func NewIdentifierSealer(pepper []byte, ring *secretbox.Ring) (*IdentifierSealer, error) {
	if len(pepper) < 32 {
		return nil, fmt.Errorf("%w: at least 32 bytes are needed", ErrNoPepper)
	}
	if ring == nil {
		return nil, errors.New("patient: no key ring to seal identifiers with")
	}
	return &IdentifierSealer{pepper: pepper, ring: ring}, nil
}

// NormaliseIdentifier strips everything that is presentation rather than number.
//
// A national ID written as "1990 1234 5678" and as "1990-1234-5678" is one number, and a
// duplicate check that treats them as two is a duplicate check that does not work.
func NormaliseIdentifier(raw string) string {
	var out strings.Builder
	for _, r := range raw {
		if unicode.IsDigit(r) || unicode.IsLetter(r) {
			out.WriteRune(unicode.ToUpper(r))
		}
	}
	return out.String()
}

// Seal produces what the row holds.
func (s *IdentifierSealer) Seal(kind IdentifierKind, raw string) (Identifier, error) {
	normalised := NormaliseIdentifier(raw)
	if normalised == "" {
		return Identifier{}, fmt.Errorf("patient: an empty %s cannot be stored", kind)
	}

	mac := hmac.New(sha256.New, s.pepper)
	// The kind is in the digest: a passport number and a national ID that happen to share
	// digits are two identifiers, not a duplicate.
	mac.Write([]byte(kind))
	mac.Write([]byte{0})
	mac.Write([]byte(normalised))
	digest := mac.Sum(nil)

	// The kind travels as additional data, so a ciphertext cannot be moved from one row to
	// another and opened as a different kind of identifier.
	sealed, keyID, err := s.ring.Seal([]byte(normalised), []byte(kind))
	if err != nil {
		return Identifier{}, fmt.Errorf("patient: sealing the %s: %w", kind, err)
	}

	return Identifier{
		Kind: kind, Digest: digest, Sealed: sealed, KeyID: keyID,
		Masked: Mask(normalised),
	}, nil
}

// Open returns the number, for the one screen that may show it — behind a step-up, and
// with an audit entry that the caller writes.
func (s *IdentifierSealer) Open(id Identifier) (string, error) {
	plain, err := s.ring.Open(id.Sealed, id.KeyID, []byte(id.Kind))
	if err != nil {
		return "", fmt.Errorf("patient: opening the %s: %w", id.Kind, err)
	}
	return string(plain), nil
}

// Digest is the matching value on its own, for a duplicate check that has a number in hand
// and no row yet.
func (s *IdentifierSealer) Digest(kind IdentifierKind, raw string) []byte {
	mac := hmac.New(sha256.New, s.pepper)
	mac.Write([]byte(kind))
	mac.Write([]byte{0})
	mac.Write([]byte(NormaliseIdentifier(raw)))
	return mac.Sum(nil)
}

// Mask is what a screen shows without a step-up: the last four characters, and asterisks
// for the rest, grouped so the length is still legible.
//
// Four is the convention every bank in Bangladesh uses and the number a patient recognises
// as their own. Fewer would not identify; more would be most of a national ID on a screen
// anyone walking past can read.
func Mask(normalised string) string {
	const visible = 4
	if len(normalised) <= visible {
		return strings.Repeat("*", len(normalised))
	}
	hidden := strings.Repeat("*", len(normalised)-visible)
	tail := normalised[len(normalised)-visible:]
	// Grouped in fours, as the number would be written on the card.
	var out strings.Builder
	for i, r := range hidden {
		if i > 0 && i%4 == 0 {
			out.WriteByte(' ')
		}
		out.WriteRune(r)
	}
	if out.Len() > 0 {
		out.WriteByte(' ')
	}
	out.WriteString(tail)
	return out.String()
}
